(()=>{
'use strict';
const API='https://ball46-344-engine.mccarey-supon.workers.dev';
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=(s)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtTime=(ms)=>ms?new Date(ms).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const age=(ms)=>{if(!ms)return'—';const s=Math.max(0,Math.round((Date.now()-ms)/1000));return s<60?`${s}s`:s<3600?`${Math.round(s/60)}m`:`${Math.round(s/3600)}h`};
const n=(v,d='—')=>v===null||v===undefined||Number.isNaN(Number(v))?d:Number(v);
const pct=(v)=>v===null||v===undefined?'—':`${Number(v).toFixed(1)}%`;
const teamColor=(name)=>{let h=0;for(const c of String(name))h=(h*31+c.charCodeAt(0))>>>0;return `hsl(${h%360} 58% 48%)`;};
async function get(path){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(API+path,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t)}}
function activeNav(){const page=document.body.dataset.page;$$('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));}
async function health(){try{const h=await get('/health');const dot=$('#sysDot'),text=$('#sysText'),fresh=$('#freshness'),quota=$('#quota');dot.className='dot '+(h.status==='ONLINE'?'online':h.status==='STALE'?'stale':'error');text.textContent=h.status==='ONLINE'?'LIVE CORE':h.status;fresh&&(fresh.textContent=h.lastSuccessAgeSeconds==null?'—':`${h.lastSuccessAgeSeconds}s`);quota&&(quota.textContent=h.rate?.remaining==null?'—':`${h.rate.remaining}/${h.rate.limit??40}`);}catch{const d=$('#sysDot');d&&(d.className='dot error');const t=$('#sysText');t&&(t.textContent='CORE OFFLINE')}}
function shell(){activeNav();health();setInterval(health,20000);}
function bar(h,a){h=n(h,0);a=n(a,0);const total=Math.max(1,h+a),hp=h/total*100;return `<div class="bar"><i class="home" style="width:${hp}%"></i><i class="away" style="width:${100-hp}%"></i></div>`;}
function statRow(label,pair){return `<div class="stat-row"><b>${esc(n(pair?.home))}</b>${bar(pair?.home,pair?.away)}<b>${esc(n(pair?.away))}</b><span class="hidden">${esc(label)}</span></div>`;}
function marketText(f,key,label){const m=f.inlineOdds?.[key]?.inplay;if(m===null||m===undefined)return `<div class="market-chip"><small>${label}</small><b>NO LIVE</b></div>`;if(typeof m==='number')return `<div class="market-chip"><small>${label}</small><b>LINE ${m}</b></div>`;if(key==='1x2')return `<div class="market-chip"><small>${label}</small><b>${n(m.home)} · ${n(m.draw)} · ${n(m.away)}</b></div>`;return `<div class="market-chip"><small>${label}</small><b>${n(m.line)} · ${n(m.home??m.over)} / ${n(m.away??m.under)}</b></div>`;}
function eventHtml(e){const min=e?.minute??'';const type=String(e?.type??'event').replaceAll('_',' ');const side=e?.team??'';const detail=e?.player??e?.player_in??(e?.score?JSON.stringify(e.score):'');return `<div class="event"><b>${esc(min)}'</b><span>${esc(type.toUpperCase())}</span><em>${esc(side)} ${esc(detail)}</em></div>`;}
function bookHtml(b){const ah=b.ah,ou=b.ou,x=b.x;return `<div class="book-card"><strong>${esc(b.name)}</strong><div class="book-line">AH ${ah?`${n(ah.line)} · ${n(ah.home)}/${n(ah.away)}`:'—'}</div><div class="book-line">O/U ${ou?`${n(ou.line)} · ${n(ou.over)}/${n(ou.under)}`:'—'}</div><div class="book-line">1X2 ${x?`${n(x.home)}/${n(x.draw)}/${n(x.away)}`:'—'}</div></div>`;}
function detailHtml(f){const s=f.statistics;return `<div class="match-detail"><div class="detail-grid"><div class="detail-panel"><h4>LIVE STATISTICS · HOME / AWAY</h4>${s?`<small>SOT</small>${statRow('SOT',s.shotsOnTarget)}<small>SHOTS OFF</small>${statRow('SOFF',s.shotsOffTarget)}<small>CORNERS</small>${statRow('CORNER',f.corners)}<small>DANGEROUS ATTACKS</small>${statRow('DA',s.dangerousAttacks)}<small>ATTACKS</small>${statRow('ATT',s.attacks)}<small>POSSESSION</small>${statRow('POS',s.possession)}`:'<div class="empty">คู่นี้ไม่มี in-play statistics coverage</div>'}</div><div class="detail-panel"><h4>EVENT FLOW</h4><div class="event-list">${(f.events||[]).slice().reverse().slice(0,18).map(eventHtml).join('')||'<div class="empty">ยังไม่มี event</div>'}</div></div></div><div class="detail-panel" style="margin-top:12px"><div class="panel-head"><h3>FULL MARKET CACHE</h3><p data-odds-age>${f.fullOddsUpdatedAt?`cached ${age(f.fullOddsUpdatedAt)} ago`:'กำลังรอรอบ odds rotation'}</p></div><div class="odds-grid" data-books>${(f.fullOddsSummary||[]).map(bookHtml).join('')||'<div class="empty" style="grid-column:1/-1">ยังไม่มี bookmaker snapshot</div>'}</div><div class="cache-note"><b>Viewer click → 5USD upstream request = 0</b> · รายละเอียดนี้อ่านจาก Ball46 central cache เท่านั้น</div></div></div>`;}
function matchCard(f){const live=f.status==='in_play'||String(f.status).includes('play');return `<article class="match-card ${live?'live':''}" data-id="${esc(f.fixtureId)}"><div class="match-main" role="button" tabindex="0"><div class="clock"><b>${esc(f.statusCode??(f.minute?`${f.minute}'`:'LIVE'))}</b><small>${live?'LIVE':'MATCH'}</small></div><div class="teams"><div class="team"><i class="jersey" style="--jersey:${teamColor(f.home?.name)}"></i><span class="team-name">${esc(f.home?.name)}</span><strong class="team-score">${esc(n(f.goals?.home,0))}</strong></div><div class="team"><i class="jersey" style="--jersey:${teamColor(f.away?.name)}"></i><span class="team-name">${esc(f.away?.name)}</span><strong class="team-score">${esc(n(f.goals?.away,0))}</strong></div></div><div class="market-snap">${marketText(f,'asian_handicap','AH')}${marketText(f,'goal_line','O/U')}</div><button class="expand-btn" aria-label="เปิดรายละเอียด">⌄</button></div>${detailHtml(f)}</article>`;}
function groupMatches(fixtures,query=''){const q=query.trim().toLowerCase();const filtered=fixtures.filter(f=>!q||`${f.home?.name} ${f.away?.name} ${f.league?.name}`.toLowerCase().includes(q));const groups=new Map();for(const f of filtered){const k=f.league?.name||'Other';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f);}return [...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0]));}
async function hydrateMatch(card,id){try{const x=await get(`/api/match?id=${encodeURIComponent(id)}`);if(!x?.odds)return;const books=x.odds.summary||[];const wrap=$('[data-books]',card),label=$('[data-odds-age]',card);if(wrap)wrap.innerHTML=books.map(bookHtml).join('')||'<div class="empty" style="grid-column:1/-1">ยังไม่มี full odds</div>';if(label)label.textContent=`cached ${age(x.odds.updatedAt)} ago · ${x.odds.bookmakers?.length??0} books`;}catch{}}
function bindCards(){ $$('.match-card').forEach(card=>{const main=$('.match-main',card),toggle=()=>{const on=card.classList.toggle('expanded');if(on&&!card.dataset.hydrated){card.dataset.hydrated='1';hydrateMatch(card,card.dataset.id);}};main.addEventListener('click',toggle);main.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}});}); }
async function initLive(){let all=[];const root=$('#liveRoot'),search=$('#matchSearch'),count=$('#liveCount'),obs=$('#observedAt');const render=()=>{const groups=groupMatches(all,search?.value||'');root.innerHTML=groups.map(([league,rows])=>`<section class="league"><header class="league-head"><b>${esc(league)}</b><span>${rows.length} LIVE</span></header>${rows.sort((a,b)=>(b.minute??0)-(a.minute??0)).map(matchCard).join('')}</section>`).join('')||'<div class="empty">ยังไม่มีการแข่งขันสดในขณะนี้</div>';bindCards();};const refresh=async()=>{try{const j=await get('/api/live');all=j.fixtures||[];count.textContent=all.length;obs.textContent=j.observedAt?fmtTime(j.observedAt):'—';render();}catch{root.innerHTML='<div class="empty">Live Core ยังไม่พร้อม · ระบบจะลองใหม่อัตโนมัติ</div>';}};search?.addEventListener('input',render);await refresh();setInterval(refresh,15000);}
function signalRow(s){return `<div class="signal"><div><div class="signal-market">${esc(s.market)}</div><span class="pill">${esc(s.side)}</span></div><div class="signal-match"><b>${esc(s.home?.name)} ${n(s.score?.home,0)}–${n(s.score?.away,0)} ${esc(s.away?.name)}</b><small>${esc(s.league?.name)} · ${esc(s.minute)}' · ${esc(s.reason)}</small></div><div class="signal-edge"><span class="pill green">EDGE ${n(s.edge)}%</span><span class="pill gold">CONF ${n(s.confidence)}%</span><span class="pill">${s.line==null?'1X2':`LINE ${s.line}`} @ ${n(s.odds)}</span></div><div class="signal-meta"><b class="result ${esc(s.result)}">${esc(s.result)}</b><small>${fmtTime(s.createdAt)}</small></div></div>`;}
async function initSignals(){const root=$('#signalRoot'),cand=$('#candidateRoot');const refresh=async()=>{try{const [s,l]=await Promise.all([get('/api/signals'),get('/api/live')]);const list=s.signals||[];root.innerHTML=list.map(signalRow).join('')||'<div class="empty">ยังไม่มี Signal · NO SIGNAL ถือเป็นผลลัพธ์ที่ถูกต้องเมื่อ Edge ไม่พอ</div>';const cs=l.candidates||[];cand.innerHTML=cs.slice(0,20).map(c=>`<div class="signal"><div><div class="signal-market">WATCH</div><span class="pill">${esc(c.market)}</span></div><div class="signal-match"><b>${esc(c.home?.name)} vs ${esc(c.away?.name)}</b><small>${esc(c.minute)}' · ${esc(c.reason)}</small></div><div class="signal-edge"><span class="pill green">${n(c.probability?.edge*100).toFixed?Number(c.probability.edge*100).toFixed(1):'—'}% EDGE</span><span class="pill">${n(c.price?.odds)} ODDS</span></div><div></div></div>`).join('')||'<div class="empty">ไม่มี candidate ที่ผ่านประตูคัดในรอบล่าสุด</div>';$('#sigTotal').textContent=s.summary?.total??0;$('#sigHit').textContent=s.summary?.hitRate==null?'—':`${s.summary.hitRate}%`;$('#sigUnits').textContent=s.summary?.units??0;$('#sigPending').textContent=s.summary?.pending??0;}catch{root.innerHTML='<div class="empty">Signal Core ยังไม่พร้อม</div>';}};await refresh();setInterval(refresh,20000);}
async function initStats(){const root=$('#statsRows');try{const j=await get('/api/statistics'),x=j.summary||{};$('#stResolved').textContent=x.resolved??0;$('#stHit').textContent=x.hitRate==null?'—':`${x.hitRate}%`;$('#stUnits').textContent=x.units??0;$('#stRoi').textContent=x.roi==null?'—':`${x.roi}%`;const markets=Object.entries(x.byMarket||{});$('#marketBreakdown').innerHTML=markets.map(([m,v])=>`<div class="kpi"><small>${esc(m)}</small><b class="${v.units>=0?'good':'bad'}">${v.hitRate??'—'}%</b><span class="pill">${v.wins}W · ${v.losses}L · ${v.pushes}P</span> <span class="pill">${v.units}u</span></div>`).join('')||'<div class="empty" style="grid-column:1/-1">รอผล Signal ที่ตัดสินแล้ว</div>';root.innerHTML=(j.signals||[]).map(s=>`<tr><td>${fmtTime(s.createdAt)}</td><td>${esc(s.market)}</td><td>${esc(s.home?.name)} vs ${esc(s.away?.name)}</td><td>${esc(s.minute)}'</td><td>${s.line??'—'} @ ${n(s.odds)}</td><td>${n(s.edge)}%</td><td class="result ${esc(s.result)}">${esc(s.result)}</td><td>${s.finalScore?`${n(s.finalScore.home)}-${n(s.finalScore.away)}`:'—'}</td></tr>`).join('')||'<tr><td colspan="8">ยังไม่มีประวัติ</td></tr>';}catch{root.innerHTML='<tr><td colspan="8">Statistics Core ยังไม่พร้อม</td></tr>';}}
let replay={rows:[],idx:0,timer:null,match:null};
function replayRender(){const r=replay.rows[replay.idx];if(!r)return;$('#replayMinute').textContent=r.minute==null?'—':`${r.minute}'`;$('#replayScore').textContent=`${n(r.goals?.home,0)} – ${n(r.goals?.away,0)}`;$('#replaySlider').value=replay.idx;$('#replaySlider').max=Math.max(0,replay.rows.length-1);const s=r.statistics;$('#replayStats').innerHTML=s?`<small>SOT</small>${statRow('SOT',s.shotsOnTarget)}<small>SHOTS OFF</small>${statRow('SOFF',s.shotsOffTarget)}<small>CORNERS</small>${statRow('CORNER',r.corners)}<small>DANGEROUS</small>${statRow('DA',s.dangerousAttacks)}<small>ATTACKS</small>${statRow('ATT',s.attacks)}`:'<div class="empty">No stats snapshot</div>';}
async function selectReplay(id,el){$$('.lab-item').forEach(x=>x.classList.toggle('active',x===el));const x=await get(`/api/match?id=${encodeURIComponent(id)}`);replay.rows=x.timeline||[];replay.idx=Math.max(0,replay.rows.length-1);replay.match=x.match;$('#replayTitle').textContent=x.match?`${x.match.home?.name} vs ${x.match.away?.name}`:`Fixture ${id}`;$('#replaySlider').disabled=!replay.rows.length;replayRender();}
async function initLab(){const s=await get('/api/signals');const items=s.signals||[];const list=$('#labList');list.innerHTML=items.map(x=>`<button class="lab-item" data-id="${esc(x.fixtureId)}"><b>${esc(x.market)} · ${esc(x.home?.name)} vs ${esc(x.away?.name)}</b><br><small>${esc(x.minute)}' · ${x.line??'1X2'} @ ${n(x.odds)} · ${esc(x.result)}</small></button>`).join('')||'<div class="empty">Match Lab จะเริ่มมี Replay เมื่อระบบบันทึก Signal</div>';$$('.lab-item',list).forEach(el=>el.addEventListener('click',()=>selectReplay(el.dataset.id,el)));$('#replaySlider').addEventListener('input',e=>{replay.idx=Number(e.target.value);replayRender();});$('#replayPlay').addEventListener('click',()=>{if(replay.timer){clearInterval(replay.timer);replay.timer=null;$('#replayPlay').textContent='▶ PLAY';return}$('#replayPlay').textContent='❚❚ PAUSE';if(replay.idx>=replay.rows.length-1)replay.idx=0;replay.timer=setInterval(()=>{if(replay.idx>=replay.rows.length-1){clearInterval(replay.timer);replay.timer=null;$('#replayPlay').textContent='▶ PLAY';return}replay.idx++;replayRender();},700);});if($('.lab-item',list))$('.lab-item',list).click();}
function predictionRow(p){return `<div class="signal"><div><div class="signal-market">BEST PICK</div><span class="pill">${esc(p.market)}</span></div><div class="signal-match"><b>${esc(p.side==='HOME'?p.home?.name:p.away?.name)} · ${esc(p.home?.name)} vs ${esc(p.away?.name)}</b><small>${esc(p.league?.name)} · ${p.kickoffAt?new Date(p.kickoffAt).toLocaleString('th-TH'):'—'} · ${esc(p.reason)}</small></div><div class="signal-edge"><span class="pill gold">ODDS ${n(p.odds)}</span><span class="pill green">EDGE ${n(p.edge)}%</span><span class="pill">CONF ${n(p.confidence)}%</span></div><div class="signal-meta"><b class="result ${esc(p.result)}">${esc(p.result)}</b><small>${p.finalScore?`${n(p.finalScore.home)}-${n(p.finalScore.away)}`:'QUALITY OVER QUANTITY'}</small></div></div>`;}
async function initPrediction(){const root=$('#predictionRoot');try{const j=await get('/api/predictions'),all=j.predictions||[];const pending=all.filter(x=>x.result==='PENDING'),resolved=all.filter(x=>x.result!=='PENDING');$('#todayPick').innerHTML=pending[0]?predictionRow(pending[0]):'<div class="empty"><b>NO PICK TODAY</b><br><small>ไม่มีคู่ผ่านเกณฑ์ Edge/ราคาในรอบล่าสุด ระบบไม่บังคับแจกบอล</small></div>';root.innerHTML=resolved.map(predictionRow).join('')||'<div class="empty">ยังไม่มีผล Prediction ที่จบแล้ว</div>';$('#predCount').textContent=all.length;$('#predResolved').textContent=resolved.length;const w=resolved.filter(x=>x.result==='WIN').length,l=resolved.filter(x=>x.result==='LOSS').length;$('#predHit').textContent=w+l?`${(w/(w+l)*100).toFixed(1)}%`:'—';}catch{root.innerHTML='<div class="empty">Prediction Core ยังไม่พร้อม</div>';}}
async function boot(){shell();const p=document.body.dataset.page;try{if(p==='live')await initLive();if(p==='signals')await initSignals();if(p==='statistics')await initStats();if(p==='lab')await initLab();if(p==='prediction')await initPrediction();}catch(e){console.error(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
