const DEFAULT_WORKER='https://nomadtips3-car31-goaloo.mccarey-supon.workers.dev';
let runtime={workerUrl:DEFAULT_WORKER},page=1,lastTrend=[],lastPages=1,loading=false;const limit=25;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString('th-TH',{hour12:false});};
const line=v=>v===null||v===undefined||v===''?'—':`${Number(v)>=0?'+':''}${v}`;
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function setHealth(text,state='warn'){const el=$('historyHealth');if(!el)return;el.textContent=text;el.classList.remove('good','warn','red');el.classList.add(state);}
function normalizeSummary(data){const s=data?.summary||{};const win=num(s.win??s.correct),loss=num(s.loss??s.incorrect),draw=num(s.draw??s.push),pending=num(s.pending),total=num(s.total??data?.total),averageOdds=num(s.averageOdds),winRate=Number.isFinite(Number(s.winRate))?Number(s.winRate):(win+loss?win/(win+loss)*100:0);return{...s,total,pending,win,loss,draw,averageOdds,winRate,trend:Array.isArray(s.trend)?s.trend:[]};}
function summary(data){const s=normalizeSummary(data);lastTrend=s.trend;const items=[['TOTAL',s.total],['PENDING',s.pending],['WIN',s.win],['LOSS',s.loss],['DRAW',s.draw],['AVERAGE ODDS',s.averageOdds.toFixed(2)],['WIN RATE',`${s.winRate.toFixed(2)}%`]];return items.map(([k,v])=>`<article class="metric"><small>${k}</small><b>${v}</b></article>`).join('');}
function resultClass(v){v=String(v||'PENDING').toUpperCase();if(v==='CORRECT')v='WIN';if(v==='INCORRECT')v='LOSS';if(v==='PUSH')v='DRAW';return ['WIN','LOSS','DRAW','PENDING','VOID'].includes(v)?v.toLowerCase():'pending';}
function drawChart(){const canvas=$('resultChart');if(!canvas)return;const box=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1),w=Math.max(320,Math.round(box.width||320)),h=260;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.height=`${h}px`;const c=canvas.getContext('2d');if(!c)return;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const pad={l:38,r:16,t:18,b:30},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b,data=lastTrend.length?lastTrend:[{index:0,win:0,loss:0,draw:0}],max=Math.max(1,...data.flatMap(x=>[num(x.win),num(x.loss),num(x.draw)]));c.font='10px system-ui';c.fillStyle='#929aa2';c.strokeStyle='#30363d';c.lineWidth=1;for(let i=0;i<=4;i++){const y=pad.t+ph*i/4,val=Math.round(max*(1-i/4));c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(String(val),5,y+3);}const xAt=i=>pad.l+(data.length<=1?0:(i/(data.length-1))*pw),yAt=v=>pad.t+ph-(num(v)/max)*ph;for(const [key,color] of [['win','#39d06f'],['loss','#ef5b63'],['draw','#929aa2']]){c.beginPath();data.forEach((p,i)=>{const x=xAt(i),y=yAt(p[key]);i?c.lineTo(x,y):c.moveTo(x,y);});c.strokeStyle=color;c.lineWidth=2.5;c.stroke();}c.fillStyle='#929aa2';c.fillText('1',pad.l,h-8);c.fillText(String(data.length),Math.max(pad.l,w-pad.r-20),h-8);}
function render(data){const s=normalizeSummary(data);$('historySummary').innerHTML=summary(data);$('historyUpdated').textContent=`Updated ${dt(data.generatedAt)} · ${num(data.total)} records`;const rows=Array.isArray(data.records)?data.records:[];$('historyBody').innerHTML=rows.length?rows.map((r,i)=>{let group=String(r.resultGroup||r.result||'PENDING').toUpperCase();if(group==='CORRECT')group='WIN';if(group==='INCORRECT')group='LOSS';if(group==='PUSH')group='DRAW';const detail=r.settlementResult&&String(r.settlementResult).toUpperCase()!==group?String(r.settlementResult).replaceAll('_',' '):'';return `<tr><td>${num(data.offset)+i+1}</td><td><b>${esc(r.selectionDate)}</b><br>${dt(r.selectedAt)}</td><td><b>${esc(r.league)}</b><br>${esc(r.home)} vs ${esc(r.away)}</td><td>${esc(r.selectedSide)}<br><span class="history-selected-team">${esc(r.selectedTeam||'—')}</span></td><td>${esc(r.entryMinute)}′<br>${esc(r.entryScore?.home)}-${esc(r.entryScore?.away)}</td><td><b>${esc(r.market)}</b><br>Line ${line(r.selectedLine??r.line)} · Odds ${esc(r.odds)}</td><td>${esc(r.momentum)}%<br>DA +${esc(r.evidence?.dangerous??0)} · Shots +${esc(r.evidence?.shots??0)} · SOT +${esc(r.evidence?.sot??0)} · C +${esc(r.evidence?.corners??0)}</td><td>${dt(r.kickoffUtc)}</td><td>${esc(r.ftStatus||r.status)}<br>${dt(r.settledAt)}</td><td>${r.finalScore?`${esc(r.finalScore.home)}-${esc(r.finalScore.away)}`:'—'}</td><td><span class="result ${resultClass(group)}">${esc(group)}</span>${detail?`<small class="settlement-detail">${esc(detail)}</small>`:''}</td></tr>`;}).join(''):'<tr><td colspan="11" class="empty-row">No confirmed signals have been recorded yet.</td></tr>';page=num(data.page,page);lastPages=Math.max(1,num(data.pages,1));$('pageInfo').textContent=`Page ${page} / ${lastPages} · 25 rows/page`;$('prevPage').disabled=loading||page<=1;$('nextPage').disabled=loading||page>=lastPages;setHealth('ONLINE','good');requestAnimationFrame(drawChart);}
function showError(error){setHealth('RETRYING','red');$('historyUpdated').textContent='Live data connection issue';$('historyBody').innerHTML=`<tr><td colspan="11" class="empty-row">Statistics are temporarily unavailable. Automatic retry is active. ${esc(error?.message||'')}</td></tr>`;$('prevPage').disabled=true;$('nextPage').disabled=true;}
async function fetchJson(url,timeoutMs=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function load(){if(loading)return;loading=true;$('prevPage').disabled=true;$('nextPage').disabled=true;try{const url=`${runtime.workerUrl||DEFAULT_WORKER}/history?page=${page}&limit=${limit}&t=${Date.now()}`;let data=await fetchJson(url);if(!data.ok)throw new Error(data.error||'History unavailable');const pages=Math.max(1,num(data.pages,1));if(page>pages){page=pages;data=await fetchJson(`${runtime.workerUrl||DEFAULT_WORKER}/history?page=${page}&limit=${limit}&t=${Date.now()}`);}render(data);}catch(error){showError(error);}finally{loading=false;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=lastPages;}}
$('prevPage').onclick=()=>{if(!loading&&page>1){page--;load();}};
$('nextPage').onclick=()=>{if(!loading&&page<lastPages){page++;load();}};
window.addEventListener('resize',()=>requestAnimationFrame(drawChart),{passive:true});
(async()=>{try{const cfg=await fetchJson(`./runtime.json?t=${Date.now()}`,5000);runtime={...runtime,...cfg};}catch{runtime.workerUrl=DEFAULT_WORKER;}await load();setInterval(load,30000);})();
