const $=id=>document.getElementById(id);
const DEFAULT_WORKER=location.origin;
let runtime={workerUrl:DEFAULT_WORKER,liveUrl:`${DEFAULT_WORKER}/live`,healthUrl:`${DEFAULT_WORKER}/health`,refreshSeconds:15},snapshots=[];
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const pair=v=>[num(v?.home),num(v?.away)];
const fmtMinute=m=>{const s=String(m?.status||'LIVE').toUpperCase();if(s==='FT'||s.includes('FINISH'))return'FT';if(s==='HT'||s.includes('HALF'))return'HT';return Number.isFinite(Number(m?.minute))?`${Math.round(Number(m.minute))}'`:'Live'};
const unwrapMatches=data=>Array.isArray(data)?data:Array.isArray(data?.matches)?data.matches:Array.isArray(data?.data)?data.data:[];
const workerBase=()=>String(runtime.workerUrl||runtime.liveUrl||DEFAULT_WORKER).replace(/\/live(?:\?.*)?$/,'');
async function json(url,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
async function loadRuntime(){try{runtime={...runtime,...await json(`./runtime.json?t=${Date.now()}`,5000)}}catch{}return runtime}
function pressure(row){const p=row?.engine?.pressure||row?.pressure;if(Number.isFinite(Number(p?.home))&&Number.isFinite(Number(p?.away)))return[Math.round(Number(p.home)),Math.round(Number(p.away))];return null}
function pressureTimeline(id,current){const points=[];for(const snap of snapshots){const row=(snap.matches||[]).find(x=>String(x.sourceMatchId??x.id)===String(id));if(!row||!Number.isFinite(Number(row.minute)))continue;const p=pressure(row);if(!p)continue;points.push([Number(row.minute),p[0],p[1]])}const byMinute=new Map(points.map(p=>[p[0],p])),rows=[...byMinute.values()].sort((a,b)=>a[0]-b[0]).slice(-45);if(!rows.length&&Number.isFinite(Number(current.minute)))rows.push([Number(current.minute),current.pressure[0],current.pressure[1]]);return rows}
function decision(row){const raw=String(row?.engine?.decision||row?.decision||row?.state||'WATCH').toUpperCase();if(raw.includes('SIGNAL'))return'SIGNAL';if(raw.includes('NEAR'))return'NEAR';return'WATCH'}
function signalInfo(row){const e=row.engine||{},market=e.market||row.market||'Live selection',selected=e.selectedTeam||e.pick||row.selectedTeam||'Monitoring';let odds=e.odds??e.lockedOdds??row.lockedOdds??row.oddsAtSignal;const detected=e.detectedMinute??e.entryMinute??row.detectedMinute??row.entryMinute??row.minute;let confidence=e.confidence??e.momentum??row.confidence??row.matchConfidence;if(Number(confidence)<=1&&Number(confidence)>0)confidence=Number(confidence)*100;return{market,selected,odds:Number.isFinite(Number(odds))?Number(odds):null,detected,confidence:Number.isFinite(Number(confidence))?Math.round(Number(confidence)):null,line:e.selectedLine??e.line??null}}
function normalize(row){const p=pressure(row)||[50,50],sig=signalInfo(row);return{id:String(row.sourceMatchId??row.id??`${row.home}-${row.away}-${row.minute}`),league:row.league||'Live match',home:row.home||'Home',away:row.away||'Away',score:pair(row.score),minute:row.minute,status:row.status||'LIVE',stats:{possession:pair(row.stats?.possession),attacks:pair(row.stats?.attacks),dangerous:pair(row.stats?.dangerous_attacks),shots:pair(row.stats?.shots),sot:pair(row.stats?.shots_on_target),corners:pair(row.stats?.corners),red:pair(row.stats?.red_cards)},events:Array.isArray(row.events)?row.events:[],pressure:p,state:decision(row),signal:sig,freshness:num(row.sourceFreshnessSeconds,0),collectedAt:row.collectedAt||new Date().toISOString()}}
let matches=[],selectedId=null,liveRefreshing=false,liveTimer=null;
function setFeed(ok,text){const el=document.querySelector('.feed-state');if(el)el.classList.toggle('offline',!ok);if($('feedState'))$('feedState').textContent=text}
function liveCounts(){if(!$('liveCount'))return;$('liveCount').textContent=matches.length;$('watchCount').textContent=matches.filter(m=>m.state!=='SIGNAL').length;$('signalCount').textContent=matches.filter(m=>m.state==='SIGNAL').length;const f=matches.length?Math.max(...matches.map(m=>m.freshness)):null;$('freshness').textContent=f===null?'—':`${f.toFixed?f.toFixed(1):f}s`}
function candidate(m){const s=m.signal,odds=s.odds?s.odds.toFixed(2):'—';return`<button class="signal-item ${m.id===selectedId?'active':''}" data-id="${esc(m.id)}"><div class="signal-top"><span class="minute">${fmtMinute(m)}</span><span class="state-pill ${m.state.toLowerCase()}">${m.state==='SIGNAL'?'Signal':m.state==='NEAR'?'Near signal':'Watch'}</span></div><div class="teams-line"><span>${esc(m.home)}</span><b>${m.score[0]}–${m.score[1]}</b><span>${esc(m.away)}</span></div><div class="pick-line">${esc(s.selected)}</div><div class="signal-bottom"><span>${esc(s.market)} · Odds <strong>${odds}</strong></span><span>Detected ${esc(s.detected)}'</span></div></button>`}
function renderSignalList(){liveCounts();const list=$('signalList');if(!list)return;if(!matches.length){list.innerHTML='<div class="soft-card empty-state"><p>No live records are ready in this scan.</p></div>';return}const order={SIGNAL:0,NEAR:1,WATCH:2},rows=[...matches].sort((a,b)=>order[a.state]-order[b.state]||num(b.minute)-num(a.minute));list.innerHTML=rows.map(candidate).join('');list.querySelectorAll('.signal-item').forEach(btn=>btn.onclick=()=>selectMatch(btn.dataset.id,true))}
function statRow(label,v){const total=Math.max(1,num(v[0])+num(v[1])),left=Math.round(num(v[0])/total*100);return`<div class="stat-row"><div class="stat-values"><b>${esc(v[0])}</b><span>${esc(label)}</span><b>${esc(v[1])}</b></div><div class="stat-bar"><i style="width:${left}%"></i><i style="width:${100-left}%"></i></div></div>`}
function drawMomentum(m){const svg=$('momentumChart');if(!svg)return;const data=pressureTimeline(m.id,m),w=800,h=220,p=28;if(data.length<2){const yH=h-p-num(data[0]?.[1]??m.pressure[0])*(h-p*2)/100,yA=h-p-num(data[0]?.[2]??m.pressure[1])*(h-p*2)/100;svg.innerHTML=`<line x1="${p}" y1="${h/2}" x2="${w-p}" y2="${h/2}" stroke="rgba(255,255,255,.07)"/><circle cx="${w/2}" cy="${yH}" r="5" fill="#f3c623"/><circle cx="${w/2}" cy="${yA}" r="5" fill="#7b838c"/><text x="${w/2}" y="${h-12}" text-anchor="middle" fill="#969da6" font-size="12">Awaiting engine pressure snapshots</text>`;return}const minX=Math.min(...data.map(d=>d[0])),maxX=Math.max(...data.map(d=>d[0])),range=Math.max(1,maxX-minX),x=v=>p+(v-minX)*(w-p*2)/range,y=v=>h-p-num(v)*(h-p*2)/100,path=k=>data.map((d,i)=>`${i?'L':'M'} ${x(d[0]).toFixed(1)} ${y(d[k]).toFixed(1)}`).join(' ');let grid='';for(let i=0;i<=4;i++){const yy=p+i*(h-p*2)/4;grid+=`<line x1="${p}" y1="${yy}" x2="${w-p}" y2="${yy}" stroke="rgba(255,255,255,.07)"/>`}svg.innerHTML=`${grid}<path d="${path(1)}" fill="none" stroke="#f3c623" stroke-width="3"/><path d="${path(2)}" fill="none" stroke="#7b838c" stroke-width="2.4"/>`}
function renderMatch(m){$('emptyState').hidden=true;$('matchContent').hidden=false;$('leagueName').textContent=m.league;$('matchClock').textContent=fmtMinute(m);$('homeName').textContent=m.home;$('awayName').textContent=m.away;$('scoreText').textContent=`${m.score[0]}–${m.score[1]}`;$('matchStatus').textContent=String(m.status).replaceAll('_',' ');const s=m.signal,st=$('decisionState');st.textContent=m.state==='SIGNAL'?'Signal active':m.state==='NEAR'?'Near signal':'Watch';st.className=`state-pill ${m.state.toLowerCase()}`;$('pickValue').textContent=s.selected;$('lockedOdds').textContent=s.odds?s.odds.toFixed(2):'—';$('confidence').textContent=s.confidence!==null?`${s.confidence}%`:'—';$('detectedMinute').textContent=s.detected!==null?`${s.detected}'`:'—';if($('marketName'))$('marketName').textContent=s.market||'Live';if($('signalLine'))$('signalLine').textContent=s.line===null?'—':`${Number(s.line)>0?'+':''}${s.line}`;$('statsRows').innerHTML=[['Possession %',m.stats.possession],['Attacks',m.stats.attacks],['Dangerous attacks',m.stats.dangerous],['Shots',m.stats.shots],['Shots on target',m.stats.sot],['Corners',m.stats.corners],['Red cards',m.stats.red]].map(([l,v])=>statRow(l,v)).join('');drawMomentum(m)}
function selectMatch(id,openMobile=false){selectedId=String(id);renderSignalList();const m=matches.find(x=>x.id===selectedId)||matches[0];if(m)renderMatch(m);if(openMobile&&window.matchMedia('(max-width:1023px)').matches)$('liveLayout')?.classList.add('match-open')}
async function refreshLive(){if(liveRefreshing)return;liveRefreshing=true;try{const base=workerBase(),[live,snap]=await Promise.all([json(`${runtime.liveUrl}${runtime.liveUrl.includes('?')?'&':'?'}t=${Date.now()}`),json(`${base}/snapshots?t=${Date.now()}`).catch(()=>({snapshots:[]}))]);snapshots=Array.isArray(snap?.snapshots)?snap.snapshots:[];const rows=unwrapMatches(live).filter(row=>{const s=String(row?.status||'').toUpperCase();return s!=='FT'&&!s.includes('FINISH')&&s!=='NS'&&s!=='SCHEDULED'});matches=rows.map(normalize);if(selectedId&&!matches.some(m=>m.id===selectedId))selectedId=null;if(!selectedId&&matches.length)selectedId=matches.find(m=>m.state==='SIGNAL')?.id||matches[0].id;renderSignalList();if(selectedId)renderMatch(matches.find(m=>m.id===selectedId));if($('lastUpdated'))$('lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;setFeed(true,'Online')}catch(e){setFeed(false,'Reconnecting');if($('lastUpdated'))$('lastUpdated').textContent='Live feed connection issue';console.warn(e)}finally{liveRefreshing=false}}
function scheduleLive(){clearTimeout(liveTimer);liveTimer=setTimeout(async()=>{await refreshLive();scheduleLive()},Math.max(10,num(runtime.refreshSeconds,15))*1000)}
async function initLive(){await loadRuntime();if($('mobileBack'))$('mobileBack').onclick=()=>$('liveLayout').classList.remove('match-open');await refreshLive();scheduleLive();document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLive()});window.addEventListener('online',refreshLive)}
function initAlerts(){setFeed(true,'Ready')}
const page=document.body.dataset.page;if(page==='live')initLive();if(page==='alerts')initAlerts();
