const $=(id)=>document.getElementById(id);
const page=document.body.dataset.page;
const DEFAULT_WORKER='https://nomadtips3-car31-goaloo.mccarey-supon.workers.dev';
let runtime={liveUrl:`${DEFAULT_WORKER}/live`,healthUrl:`${DEFAULT_WORKER}/health`,refreshSeconds:15};
const esc=(v)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const pair=(v)=>[num(v?.home),num(v?.away)];
const fmtMinute=(m)=>{const s=String(m?.status||'LIVE').toUpperCase();if(s==='FT'||s.includes('FINISH'))return'FT';if(s==='HT'||s.includes('HALF'))return'HT';return Number.isFinite(Number(m?.minute))?`${Math.round(Number(m.minute))}'`:'Live';};
const unwrapMatches=(data)=>Array.isArray(data)?data:Array.isArray(data?.matches)?data.matches:Array.isArray(data?.data)?data.data:[];
async function json(url,timeout=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function loadRuntime(){try{runtime={...runtime,...await json(`./runtime.json?t=${Date.now()}`,5000)};}catch{}return runtime;}

function pressure(row){const s=row.stats||{},h=num(s.attacks?.home)*.16+num(s.dangerous_attacks?.home)*.32+num(s.shots?.home)*.18+num(s.shots_on_target?.home)*.22+num(s.corners?.home)*.12,a=num(s.attacks?.away)*.16+num(s.dangerous_attacks?.away)*.32+num(s.shots?.away)*.18+num(s.shots_on_target?.away)*.22+num(s.corners?.away)*.12,t=Math.max(.01,h+a);return[Math.round(h/t*100),Math.round(a/t*100)];}
function decision(row){const raw=String(row?.engine?.decision||row?.decision||row?.state||'WATCH').toUpperCase();if(raw.includes('SIGNAL'))return'SIGNAL';if(raw.includes('NEAR'))return'NEAR';return'WATCH';}
function signalInfo(row){const e=row.engine||{},market=e.market||e.selectedMarket||row.market||'Live selection';const selected=e.selectedTeam||e.pick||e.selection||row.selectedTeam||row.pick||'Monitoring';let odds=e.odds??e.lockedOdds??row.lockedOdds??row.oddsAtSignal; if(!Number.isFinite(Number(odds))){const one=row.odds?.oneXtwo;odds=one?.home??one?.away??null;}const detected=e.detectedMinute??e.entryMinute??row.detectedMinute??row.entryMinute??row.minute;let confidence=e.confidence??row.confidence??row.matchConfidence;if(Number(confidence)<=1&&Number(confidence)>0)confidence=Number(confidence)*100;return{market,selected,odds:Number.isFinite(Number(odds))?Number(odds):null,detected,confidence:Number.isFinite(Number(confidence))?Math.round(Number(confidence)):null,engine:e.engine||e.version||'CAR 3.1'};}
function normalize(row){const p=pressure(row),sig=signalInfo(row);return{id:String(row.sourceMatchId??row.id??crypto.randomUUID()),league:row.league||'Live match',home:row.home||'Home',away:row.away||'Away',score:pair(row.score),minute:row.minute,status:row.status||'LIVE',stats:{possession:pair(row.stats?.possession),attacks:pair(row.stats?.attacks),dangerous:pair(row.stats?.dangerous_attacks),shots:pair(row.stats?.shots),sot:pair(row.stats?.shots_on_target),corners:pair(row.stats?.corners),red:pair(row.stats?.red_cards)},events:Array.isArray(row.events)?row.events:[],pressure:p,state:decision(row),signal:sig,freshness:num(row.sourceFreshnessSeconds,0),collectedAt:row.collectedAt||new Date().toISOString()};}

let matches=[],selectedId=null;
function setFeed(ok,text){const el=document.querySelector('.feed-state');if(el)el.classList.toggle('offline',!ok);if($('feedState'))$('feedState').textContent=text;}
function liveCounts(){if(!$('liveCount'))return;$('liveCount').textContent=matches.length;$('watchCount').textContent=matches.filter(m=>m.state!=='SIGNAL').length;$('signalCount').textContent=matches.filter(m=>m.state==='SIGNAL').length;const f=matches.length?Math.min(...matches.map(m=>m.freshness)):null;$('freshness').textContent=f===null?'—':`${f}s`;}
function candidate(m){const sig=m.signal,odds=sig.odds?sig.odds.toFixed(2):'—';return`<button class="signal-item ${m.id===selectedId?'active':''}" data-id="${esc(m.id)}"><div class="signal-top"><span class="minute">${fmtMinute(m)}</span><span class="state-pill ${m.state.toLowerCase()}">${m.state==='SIGNAL'?'Signal':m.state==='NEAR'?'Near signal':'Watch'}</span></div><div class="teams-line"><span>${esc(m.home)}</span><b>${m.score[0]}–${m.score[1]}</b><span>${esc(m.away)}</span></div><div class="pick-line">${esc(sig.selected)}</div><div class="signal-bottom"><span>${esc(sig.market)} · Odds <strong>${odds}</strong></span><span>Detected ${esc(sig.detected)}'</span></div></button>`;}
function renderSignalList(){liveCounts();const list=$('signalList');if(!list)return;if(!matches.length){list.innerHTML='<div class="soft-card empty-state"><p>No live records are ready in this scan.</p></div>';return;}const ordered=[...matches].sort((a,b)=>({SIGNAL:0,NEAR:1,WATCH:2}[a.state]-{SIGNAL:0,NEAR:1,WATCH:2}[b.state]||num(b.minute)-num(a.minute));list.innerHTML=ordered.map(candidate).join('');list.querySelectorAll('.signal-item').forEach(btn=>btn.onclick=()=>selectMatch(btn.dataset.id,true));}
function latestEvent(m){if(!m.events.length)return null;return [...m.events].sort((a,b)=>num(b.minute)-num(a.minute))[0];}
function eventZone(event,m){const type=String(event?.type||event?.event||'').toLowerCase(),team=String(event?.team||'').toLowerCase(),home=team&&team.includes(String(m.home).toLowerCase()),side=home?'home':'away';let x=side==='home'?68:32,y=50;if(type.includes('danger'))x=side==='home'?84:16;if(type.includes('attack'))x=side==='home'?72:28;if(type.includes('corner')){x=side==='home'?94:6;y=type.includes('left')?12:88;}if(type.includes('goal kick'))x=side==='home'?12:88;if(type.includes('goal'))x=side==='home'?94:6;if(type.includes('card')||type.includes('sub')){x=50;y=50;}return{x,y,side,label:event?`${event.minute??m.minute}' · ${event.type||event.event||'Live event'}`:'Live data'};}
function moveBall(m){const event=latestEvent(m),z=eventZone(event,m),ball=$('ball'),glow=$('zoneGlow');if(ball){ball.style.left=`${z.x}%`;ball.style.top=`${z.y}%`;}if(glow){glow.style.transform=`translateX(${z.side==='home'?'115%':'0'})`;glow.style.opacity=event?'.58':'.28';}if($('pitchEvent'))$('pitchEvent').textContent=z.label;}
function statRow(label,v){const total=Math.max(1,num(v[0])+num(v[1])),left=Math.round(num(v[0])/total*100);return`<div class="stat-row"><div class="stat-values"><b>${esc(v[0])}</b><span>${esc(label)}</span><b>${esc(v[1])}</b></div><div class="stat-bar"><i style="width:${left}%"></i><i style="width:${100-left}%"></i></div></div>`;}
function drawMomentum(m){const svg=$('momentumChart');if(!svg)return;const home=m.pressure[0],away=m.pressure[1],points=18,w=800,h=220,pad=24,make=(base,phase)=>Array.from({length:points},(_,i)=>Math.max(4,Math.min(96,base+Math.sin(i*.72+phase)*7+Math.cos(i*.31+phase)*4))),a=make(home,.4),b=make(away,2.1),path=(arr)=>arr.map((v,i)=>`${i?'L':'M'} ${(pad+i*(w-pad*2)/(points-1)).toFixed(1)} ${(h-pad-v*(h-pad*2)/100).toFixed(1)}`).join(' ');let grid='';for(let i=0;i<=4;i++){const y=pad+i*(h-pad*2)/4;grid+=`<line x1="${pad}" y1="${y}" x2="${w-pad}" y2="${y}" stroke="rgba(255,255,255,.07)"/>`;}svg.innerHTML=`${grid}<path d="${path(a)}" fill="none" stroke="#f3c623" stroke-width="3" vector-effect="non-scaling-stroke"/><path d="${path(b)}" fill="none" stroke="#7b838c" stroke-width="2.4" vector-effect="non-scaling-stroke"/>`;}
function renderMatch(m){$('emptyState').hidden=true;$('matchContent').hidden=false;$('leagueName').textContent=m.league;$('matchClock').textContent=fmtMinute(m);$('homeName').textContent=m.home;$('awayName').textContent=m.away;$('scoreText').textContent=`${m.score[0]}–${m.score[1]}`;$('matchStatus').textContent=String(m.status).replaceAll('_',' ');const s=m.signal,st=$('decisionState');st.textContent=m.state==='SIGNAL'?'Signal active':m.state==='NEAR'?'Near signal':'Watch';st.className=`state-pill ${m.state.toLowerCase()}`;$('pickValue').textContent=s.selected;$('lockedOdds').textContent=s.odds?s.odds.toFixed(2):'—';$('confidence').textContent=s.confidence!==null?`${s.confidence}%`:'—';$('detectedMinute').textContent=s.detected!==null?`${s.detected}'`:'—';$('engineName').textContent=s.engine;$('statsRows').innerHTML=[['Possession %',m.stats.possession],['Attacks',m.stats.attacks],['Dangerous attacks',m.stats.dangerous],['Shots',m.stats.shots],['Shots on target',m.stats.sot],['Corners',m.stats.corners],['Red cards',m.stats.red]].map(([l,v])=>statRow(l,v)).join('');const events=[...m.events].sort((a,b)=>num(b.minute)-num(a.minute)).slice(0,20);$('eventCount').textContent=`${events.length} events`;$('eventList').innerHTML=events.length?events.map(e=>`<div class="event"><time>${esc(e.minute??'—')}'</time><span>${esc(e.type||e.event||'Event')}</span><small>${esc(e.team||'')}</small></div>`).join(''):'<div class="event"><time>—</time><span>Waiting for event feed</span><small>Goaloo</small></div>';moveBall(m);drawMomentum(m);}
function selectMatch(id,openMobile=false){selectedId=String(id);renderSignalList();const m=matches.find(x=>x.id===selectedId)||matches[0];if(m)renderMatch(m);if(openMobile&&window.matchMedia('(max-width:1023px)').matches)$('liveLayout')?.classList.add('match-open');}
async function refreshLive(){try{const data=await json(`${runtime.liveUrl}${runtime.liveUrl.includes('?')?'&':'?'}t=${Date.now()}`),rows=unwrapMatches(data);matches=rows.map(normalize);if(selectedId&&!matches.some(m=>m.id===selectedId))selectedId=null;if(!selectedId&&matches.length)selectedId=matches.find(m=>m.state==='SIGNAL')?.id||matches[0].id;renderSignalList();if(selectedId)renderMatch(matches.find(m=>m.id===selectedId));if($('lastUpdated'))$('lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;setFeed(true,'Online');}catch(err){setFeed(false,'Retrying');if($('lastUpdated'))$('lastUpdated').textContent='Live feed connection issue';console.warn('CAR 3.5 live refresh failed',err);}}
async function initLive(){await loadRuntime();$('mobileBack').onclick=()=>$('liveLayout').classList.remove('match-open');await refreshLive();setInterval(refreshLive,Math.max(10,num(runtime.refreshSeconds,15))*1000);}

let historyPage=1,historyPages=1,trend=[];
function drawHistory(){const svg=$('historyChart');if(!svg)return;const data=trend.length?trend:[{index:0,win:0,loss:0,draw:0}],w=800,h=240,p=28,max=Math.max(1,...data.flatMap(d=>[num(d.win),num(d.loss),num(d.draw)])),x=i=>p+(data.length<=1?0:i*(w-p*2)/(data.length-1)),y=v=>h-p-num(v)*(h-p*2)/max,path=k=>data.map((d,i)=>`${i?'L':'M'} ${x(i).toFixed(1)} ${y(d[k]).toFixed(1)}`).join(' ');let grid='';for(let i=0;i<=4;i++){const yy=p+i*(h-p*2)/4;grid+=`<line x1="${p}" y1="${yy}" x2="${w-p}" y2="${yy}" stroke="rgba(255,255,255,.07)"/>`;}svg.innerHTML=`${grid}<path d="${path('win')}" fill="none" stroke="#33d17a" stroke-width="3"/><path d="${path('loss')}" fill="none" stroke="#ff5c5c" stroke-width="3"/><path d="${path('draw')}" fill="none" stroke="#8b929b" stroke-width="2.5"/>`;}
function resultName(r){let v=String(r.resultGroup||r.result||'PENDING').toUpperCase();if(v==='CORRECT')v='WIN';if(v==='INCORRECT')v='LOSS';if(v==='PUSH')v='DRAW';return v;}
function renderHistory(data){const s=data.summary||{},win=num(s.win??s.correct),loss=num(s.loss??s.incorrect),draw=num(s.draw??s.push),avg=num(s.averageOdds),rate=Number.isFinite(Number(s.winRate))?num(s.winRate):(win+loss?win/(win+loss)*100:0);$('statWin').textContent=win;$('statLoss').textContent=loss;$('statDraw').textContent=draw;$('statRate').textContent=`${rate.toFixed(2)}%`;$('statOdds').textContent=avg.toFixed(2);trend=Array.isArray(s.trend)?s.trend:[];const rows=Array.isArray(data.records)?data.records:[];$('historyBody').innerHTML=rows.length?rows.map(r=>{const result=resultName(r),cls=`result-${result.toLowerCase()}`;return`<tr><td>${esc(r.selectionDate||'—')}</td><td>${esc(r.home||'—')} vs ${esc(r.away||'—')}</td><td>${esc(r.selectedTeam||r.selectedSide||'—')}</td><td>${esc(r.market||'—')}</td><td>${esc(r.odds??'—')}</td><td>${esc(r.entryMinute??'—')}'</td><td class="${cls}">${esc(result)}</td></tr>`;}).join(''):'<tr><td colspan="7">No settled signals yet.</td></tr>';historyPage=num(data.page,historyPage);historyPages=Math.max(1,num(data.pages,1));$('pageInfo').textContent=`Page ${historyPage} / ${historyPages} · 25 rows/page`;$('prevPage').disabled=historyPage<=1;$('nextPage').disabled=historyPage>=historyPages;requestAnimationFrame(drawHistory);setFeed(true,'Online');}
async function refreshHistory(){try{const worker=(runtime.liveUrl||'').replace(/\/live(?:\?.*)?$/,'')||DEFAULT_WORKER,data=await json(`${worker}/history?page=${historyPage}&limit=25&t=${Date.now()}`);if(data.ok===false)throw new Error(data.error||'History unavailable');renderHistory(data);}catch(err){setFeed(false,'Retrying');$('historyBody').innerHTML='<tr><td colspan="7">Statistics are temporarily unavailable. Automatic retry is active.</td></tr>';}}
async function initStatistics(){await loadRuntime();$('prevPage').onclick=()=>{if(historyPage>1){historyPage--;refreshHistory();}};$('nextPage').onclick=()=>{if(historyPage<historyPages){historyPage++;refreshHistory();}};await refreshHistory();setInterval(refreshHistory,30000);}

function initAlerts(){setFeed(true,'Plans ready');document.querySelectorAll('[data-integration]').forEach(btn=>btn.addEventListener('click',(e)=>{e.preventDefault();const type=btn.dataset.integration;if(type==='stripe')alert('Stripe checkout is intentionally not activated in this scaffold until the production price/webhook and LINE entitlement endpoint are connected.');else alert('Custom live engine is a manual pre-order. Owner provisioning will be enabled when the production payment flow is connected.');}));}

if(page==='live')initLive();if(page==='statistics')initStatistics();if(page==='alerts')initAlerts();
