const $=id=>document.getElementById(id),DEFAULT_WORKER=location.origin;
let runtime={workerUrl:DEFAULT_WORKER,liveUrl:`${DEFAULT_WORKER}/live`,refreshSeconds:15},historyPage=1,historyPages=1,historyRange='ALL',trend=[],historyRefreshing=false;
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,workerBase=()=>String(runtime.workerUrl||runtime.liveUrl||DEFAULT_WORKER).replace(/\/live(?:\?.*)?$/,'');
async function json(url,timeout=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(t)}}
async function loadRuntime(){try{runtime={...runtime,...await json(`./runtime.json?t=${Date.now()}`,5000)}}catch{}}
function setFeed(ok,text){const s=document.querySelector('.feed-state');if(s)s.classList.toggle('offline',!ok);if($('feedState'))$('feedState').textContent=text}
function settlementName(r){return String(r?.result||r?.resultGroup||'PENDING').toUpperCase().replaceAll('_',' ')}
function resultClass(r){const v=settlementName(r);if(v.includes('WIN'))return'result-win';if(v.includes('LOSS'))return'result-loss';if(v==='PUSH'||v==='DRAW')return'result-draw';return''}
function fmtDateTime(r){if(r?.selectedAt){const d=new Date(r.selectedAt);if(Number.isFinite(d.getTime()))return d.toLocaleString([],{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}return r?.selectionDate||'—'}
function fmtScore(s){const h=Number(s?.home),a=Number(s?.away);return Number.isFinite(h)&&Number.isFinite(a)?`${h}–${a}`:'—'}
function fmtMarket(r){const m=String(r?.market||'—').toUpperCase();return m==='OU'?'O/U':m}function fmtPick(r){return String(r?.market||'').toUpperCase()==='OU'?String(r?.ouDirection||'—').toUpperCase():r?.selectedTeam||r?.selectedSide||'—'}
function fmtLine(r){const m=String(r?.market||'').toUpperCase();if(m==='WIN')return'—';const v=r?.selectedLine??r?.line;if(!Number.isFinite(Number(v)))return'—';const n=Number(v);return m==='AH'?`${n>0?'+':''}${Number.isInteger(n)?n.toFixed(1):String(n)}`:String(n)}
const fmtOdds=r=>Number.isFinite(Number(r?.odds))?Number(r.odds).toFixed(2):'—',fmtMomentum=r=>Number.isFinite(Number(r?.momentum))?`${Math.round(Number(r.momentum))}%`:'—';
function drawHistory(){const svg=$('historyChart');if(!svg)return;const data=trend.length?trend:[{index:0,date:'',win:0,loss:0,draw:0}],w=800,h=240,left=34,right=16,top=18,bottom=27,max=Math.max(1,...data.flatMap(r=>[num(r.win),num(r.loss),num(r.draw)])),innerW=w-left-right,innerH=h-top-bottom,x=i=>left+(data.length<=1?innerW/2:i*innerW/(data.length-1)),y=v=>top+innerH-num(v)*innerH/max,path=k=>data.map((r,i)=>`${i?'L':'M'} ${x(i).toFixed(2)} ${y(r[k]).toFixed(2)}`).join(' ');let grid='';for(let i=0;i<=4;i++){const yy=top+i*innerH/4;grid+=`<line x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}" stroke="rgba(255,255,255,.055)"/>`}svg.innerHTML=`${grid}<path d="${path('win')}" fill="none" stroke="#33d17a" stroke-width="1.55"/><path d="${path('loss')}" fill="none" stroke="#ff5c5c" stroke-width="1.45"/><path d="${path('draw')}" fill="none" stroke="#8b929b" stroke-width="1.25"/><text x="${left}" y="${h-7}" fill="#757c84" font-size="10">${esc(data[0]?.date||'')}</text><text x="${w-right}" y="${h-7}" text-anchor="end" fill="#757c84" font-size="10">${esc(data.at(-1)?.date||'')}</text>`}
function renderHistory(data){const s=data.summary||{},win=num(s.win??s.wins),loss=num(s.loss??s.losses),draw=num(s.draw??s.draws),avg=num(s.averageOdds),rate=Number.isFinite(Number(s.winRate))?num(s.winRate):(win+loss+draw?win/(win+loss+draw)*100:0);$('statWin').textContent=win;$('statLoss').textContent=loss;$('statDraw').textContent=draw;$('statRate').textContent=`${rate.toFixed(2)}%`;$('statOdds').textContent=avg.toFixed(2);if($('statUnits'))$('statUnits').textContent=`${num(s.netUnits)>0?'+':''}${num(s.netUnits).toFixed(2)}u`;trend=Array.isArray(s.trend)?s.trend:[];const records=Array.isArray(data.records)?data.records:[];$('historyBody').innerHTML=records.length?records.map(r=>`<tr><td>${esc(fmtDateTime(r))}</td><td class="league-cell">${esc(r.league||'—')}</td><td class="match-cell">${esc(r.home||'—')} vs ${esc(r.away||'—')}</td><td>${esc(r.entryMinute??'—')}${r.entryMinute!==null&&r.entryMinute!==undefined?"'":''}</td><td><span class="score-pill">${esc(fmtScore(r.entryScore))}</span></td><td>${esc(fmtMarket(r))}</td><td>${esc(fmtPick(r))}</td><td class="line-cell">${esc(fmtLine(r))}</td><td class="odds-cell">${esc(fmtOdds(r))}</td><td>${esc(fmtMomentum(r))}</td><td><span class="score-pill">${esc(fmtScore(r.finalScore))}</span></td><td class="${resultClass(r)}">${esc(settlementName(r))}</td></tr>`).join(''):'<tr><td colspan="12">No records are available in this range.</td></tr>';historyPage=num(data.page,historyPage);historyPages=Math.max(1,num(data.pages,1));$('pageInfo').textContent=`Page ${historyPage} / ${historyPages} · 25 rows/page`;$('prevPage').disabled=historyPage<=1;$('nextPage').disabled=historyPage>=historyPages;if($('historyMeta'))$('historyMeta').textContent=`${historyRange} · ${num(data.total)} records · ${data.historyStorage==='CAR35_SQLITE_HISTORY_V2'?'CAR 3.5 SQLite archive':'CAR 3.5 history'}`;requestAnimationFrame(drawHistory);setFeed(true,'Online')}
async function refreshHistory(){if(historyRefreshing)return;historyRefreshing=true;try{const data=await json(`${workerBase()}/history?page=${historyPage}&limit=25&range=${encodeURIComponent(historyRange)}&t=${Date.now()}`);if(data.ok===false)throw new Error(data.error||'History unavailable');renderHistory(data)}catch(e){setFeed(false,'Reconnecting');$('historyBody').innerHTML='<tr><td colspan="12">Statistics are temporarily unavailable.</td></tr>';console.warn(e)}finally{historyRefreshing=false}}
async function init(){await loadRuntime();$('prevPage').onclick=()=>{if(historyPage>1){historyPage--;refreshHistory()}};$('nextPage').onclick=()=>{if(historyPage<historyPages){historyPage++;refreshHistory()}};document.querySelectorAll('#historyRanges [data-range]').forEach(b=>b.addEventListener('click',()=>{historyRange=b.dataset.range||'ALL';historyPage=1;document.querySelectorAll('#historyRanges [data-range]').forEach(x=>x.classList.toggle('active',x===b));refreshHistory()}));await refreshHistory();setInterval(refreshHistory,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshHistory()});window.addEventListener('online',refreshHistory)}
init();
