(()=>{
'use strict';
if(window.__CAR35_STATS_BOOTED__)return;window.__CAR35_STATS_BOOTED__=true;
const $=id=>document.getElementById(id),ORIGIN=location.origin;
let page=1,pages=1,range='ALL',trend=[],refreshing=false;
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function json(url,timeout=6000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function setFeed(ok,text){const s=document.querySelector('.feed-state');if(s)s.classList.toggle('offline',!ok);const f=$('feedState');if(f)f.textContent=text}
function settlementName(r){const v=String(r?.result||r?.resultGroup||'').toUpperCase().replaceAll(' ','_');if(['WIN','W','CORRECT','FULL_WIN','HALF_WIN'].includes(v))return'WIN';if(['LOSS','L','INCORRECT','FULL_LOSS','HALF_LOSS'].includes(v))return'LOSS';if(['DRAW','D','PUSH'].includes(v))return'DRAW';return'—'}
function bucket(r){const v=settlementName(r);return v==='WIN'?'win':v==='LOSS'?'loss':v==='DRAW'?'draw':null}
function fmtDateTime(r){if(r?.selectedAt){const d=new Date(r.selectedAt);if(Number.isFinite(d.getTime()))return d.toLocaleString([],{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}return r?.selectionDate||'—'}
function fmtScore(s){const h=Number(s?.home),a=Number(s?.away);return Number.isFinite(h)&&Number.isFinite(a)?`${h}–${a}`:'—'}
function fmtMarket(r){const m=String(r?.market||'—').toUpperCase();return m==='OU'?'O/U':m}
function fmtPick(r){return String(r?.market||'').toUpperCase()==='OU'?String(r?.ouDirection||'—').toUpperCase():r?.selectedTeam||r?.selectedSide||'—'}
function fmtLine(r){const m=String(r?.market||'').toUpperCase();if(m==='WIN')return'—';const v=r?.selectedLine??r?.line;if(!Number.isFinite(Number(v)))return'—';const n=Number(v);return m==='AH'?`${n>0?'+':''}${Number.isInteger(n)?n.toFixed(1):String(n)}`:String(n)}
function fmtBookmaker(r){const explicit=String(r?.bookmaker??r?.bookmakerName??r?.oddsBookmaker??'').trim();if(explicit)return explicit;const id=Number(r?.bookmakerCompanyId);if(id===8)return'Bet365';if(id===50)return'1xBet';return'—'}
function fmtOdds(r){return `${Number.isFinite(Number(r?.odds))?Number(r.odds).toFixed(2):'—'} · ${fmtBookmaker(r)}`}
function fmtMomentum(r){return Number.isFinite(Number(r?.momentum))?`${Math.round(Number(r.momentum))}%`:'—'}
function drawHistory(){const svg=$('historyChart');if(!svg)return;if(!trend.length){svg.innerHTML='<text x="400" y="120" text-anchor="middle" fill="#969da6" font-size="13">No settled result data for this chart yet</text>';return}const data=trend,w=800,h=240,left=34,right=16,top=18,bottom=27,max=Math.max(1,...data.flatMap(r=>[num(r.win),num(r.loss),num(r.draw)])),innerW=w-left-right,innerH=h-top-bottom,x=i=>left+(data.length<=1?innerW/2:i*innerW/(data.length-1)),y=v=>top+innerH-num(v)*innerH/max,path=k=>data.map((r,i)=>`${i?'L':'M'} ${x(i).toFixed(2)} ${y(r[k]).toFixed(2)}`).join(' ');let grid='';for(let i=0;i<=4;i++){const yy=top+i*innerH/4;grid+=`<line x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}" stroke="rgba(255,255,255,.055)"/>`}const last=data.at(-1),lx=x(data.length-1);svg.innerHTML=`${grid}<path d="${path('win')}" fill="none" stroke="#33d17a" stroke-width="2.2"/><path d="${path('loss')}" fill="none" stroke="#ff5c5c" stroke-width="2.1"/><path d="${path('draw')}" fill="none" stroke="#8b929b" stroke-width="1.8"/><circle cx="${lx}" cy="${y(last.win)}" r="3.4" fill="#33d17a"/><circle cx="${lx}" cy="${y(last.loss)}" r="3.4" fill="#ff5c5c"/><circle cx="${lx}" cy="${y(last.draw)}" r="3" fill="#8b929b"/>`}
function render(data){const s=data.summary||{},win=num(s.win??s.wins),loss=num(s.loss??s.losses),draw=num(s.draw??s.draws),settled=win+loss+draw,rate=Number.isFinite(Number(s.winRate))?num(s.winRate):(settled?win/settled*100:0),avg=num(s.averageOdds),records=Array.isArray(data.records)?data.records:[];if($('statWin'))$('statWin').textContent=win;if($('statLoss'))$('statLoss').textContent=loss;if($('statDraw'))$('statDraw').textContent=draw;if($('statRate'))$('statRate').textContent=`${rate.toFixed(2)}%`;if($('statOdds'))$('statOdds').textContent=avg.toFixed(2);if($('statUnits'))$('statUnits').textContent=`${num(s.netUnits)>0?'+':''}${num(s.netUnits).toFixed(2)}u`;trend=Array.isArray(s.trend)?s.trend:[];const body=$('historyBody');if(body)body.innerHTML=records.length?records.map(r=>`<tr><td>${esc(fmtDateTime(r))}</td><td class="league-cell">${esc(r.league||'—')}</td><td class="match-cell">${esc(r.home||'—')} vs ${esc(r.away||'—')}</td><td>${esc(r.entryMinute??'—')}${r.entryMinute!==null&&r.entryMinute!==undefined?"'":''}</td><td><span class="score-pill">${esc(fmtScore(r.entryScore))}</span></td><td>${esc(fmtMarket(r))}</td><td>${esc(fmtPick(r))}</td><td class="line-cell">${esc(fmtLine(r))}</td><td class="odds-cell">${esc(fmtOdds(r))}</td><td>${esc(fmtMomentum(r))}</td><td><span class="score-pill">${esc(fmtScore(r.finalScore))}</span></td><td class="result-${bucket(r)||''}">${esc(settlementName(r))}</td></tr>`).join(''):'<tr><td colspan="12">No records are available in this range.</td></tr>';page=Math.max(1,num(data.page,page));pages=Math.max(1,num(data.pages,1));if($('pageInfo'))$('pageInfo').textContent=`Page ${page} / ${pages} · 25 rows/page`;if($('prevPage'))$('prevPage').disabled=page<=1;if($('nextPage'))$('nextPage').disabled=page>=pages;if($('historyMeta'))$('historyMeta').textContent=`${range} · ${num(data.total)} records`;requestAnimationFrame(drawHistory);setFeed(true,'Online')}
async function refresh(){if(refreshing)return;refreshing=true;setFeed(false,'Connecting');try{const data=await json(`${ORIGIN}/history?page=${page}&limit=25&range=${encodeURIComponent(range)}&t=${Date.now()}`);if(data?.ok===false)throw new Error(data.error||'History unavailable');render(data||{})}catch(e){const body=$('historyBody');if(body)body.innerHTML='<tr><td colspan="12">Statistics are temporarily unavailable.</td></tr>';const svg=$('historyChart');if(svg)svg.innerHTML='<text x="400" y="120" text-anchor="middle" fill="#ff5c5c" font-size="13">Statistics feed unavailable</text>';if($('historyMeta'))$('historyMeta').textContent='Archive unavailable';setFeed(false,'Reconnecting');console.warn('CAR 3.5 statistics:',e)}finally{refreshing=false}}
function init(){const prev=$('prevPage'),next=$('nextPage');if(prev)prev.onclick=()=>{if(page>1){page--;refresh()}};if(next)next.onclick=()=>{if(page<pages){page++;refresh()}};document.querySelectorAll('#historyRanges [data-range]').forEach(b=>b.addEventListener('click',()=>{range=b.dataset.range||'ALL';page=1;document.querySelectorAll('#historyRanges [data-range]').forEach(x=>x.classList.toggle('active',x===b));refresh()}));refresh();setInterval(refresh,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('online',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
