const WORKER='https://nomadtips3-car33-live.mccarey-supon.workers.dev';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let live={matches:[],candidates:[],activeSignals:[]},selectedId=null,selectedSignal=false,anchors=new Map(),config=null,seen=new Set();
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const odds=v=>n(v)===null?'—':n(v).toFixed(2),line=v=>n(v)===null?'—':`${n(v)>0?'+':''}${Number.isInteger(n(v))?n(v).toFixed(1):n(v)}`;
function recordById(id){return live.activeSignals.find(x=>String(x.id)===String(id));}function matchById(id){return live.matches.find(x=>String(x.id)===String(id));}function candidateById(id){return live.candidates.find(x=>String(x.id)===String(id));}
function lockText(r){if(!r)return'—';if(r.market==='AH')return `${r.selectedTeam} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;if(r.market==='OU')return `${r.ouDirection} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;return `${r.selectedTeam} · WIN @ ${odds(r.lockedOdds)}`;}
function currentMarket(r,m){if(!r||!m)return'—';const away=r.selectedSide==='AWAY';if(r.market==='AH'){const raw=n(m.odds?.asianHandicap?.line),l=raw===null?null:(away?-raw:raw),o=m.odds?.asianHandicap?.[away?'away':'home'];return `${r.selectedTeam} ${line(l)} @ ${odds(o)}`;}if(r.market==='OU'){const d=r.ouDirection==='UNDER'?'under':'over';return `${r.ouDirection} ${line(m.odds?.overUnder?.line)} @ ${odds(m.odds?.overUnder?.[d])}`;}return `${r.selectedTeam} · WIN @ ${odds(m.odds?.oneXtwo?.[away?'away':'home'])}`;}
function orientedScore(r,m){if(!m)return'—';if(!r)return`${m.score.home}–${m.score.away}`;return r.selectedSide==='AWAY'?`${m.score.away}–${m.score.home}`:`${m.score.home}–${m.score.away}`;}
function entryScore(r){if(!r?.entryScore)return'—';return r.selectedSide==='AWAY'?`${r.entryScore.away}–${r.entryScore.home}`:`${r.entryScore.home}–${r.entryScore.away}`;}
function anchorSnapshot(m){if(n(m.elapsedSeconds)===null)return;const old=anchors.get(String(m.id));if(!old||old.sourceClock!==m.sourceClock)anchors.set(String(m.id),{elapsed:n(m.elapsedSeconds),perf:performance.now(),sourceClock:m.sourceClock,status:m.status});}
function clockText(id){const m=matchById(id);if(!m)return'—';if(m.status==='FT')return'FT';if(m.status==='HT')return'HT';const a=anchors.get(String(id));if(!a)return m.minute===null?'LIVE':`${m.minute}'`;const sec=Math.max(0,a.elapsed+(performance.now()-a.perf)/1000),whole=Math.floor(sec);return`${Math.floor(whole/60)}:${String(whole%60).padStart(2,'0')}`;}
function signalClock(r){const s=n(r?.signalElapsedSeconds);if(s===null)return`${r?.entryMinute??'—'}'`;return`${Math.floor(s/60)}:${String(Math.floor(s)%60).padStart(2,'0')}`;}
function updateClocks(){document.querySelectorAll('[data-clock]').forEach(el=>el.textContent=clockText(el.dataset.clock));}
function reasonChips(r){if(!r)return'';const e=r.evidence||{};return[[`Momentum`,`${Math.round(n(r.momentum)||0)}%`],[`Dangerous`,`${n(e.dangerous)>=0?'+':''}${n(e.dangerous)??'—'}`],[`SOT`,`${n(e.sot)>=0?'+':''}${n(e.sot)??'—'}`],[`Shots`,`${n(e.shots)>=0?'+':''}${n(e.shots)??'—'}`],[`Corners`,`${n(e.corners)>=0?'+':''}${n(e.corners)??'—'}`]].map(([k,v])=>`<span class="chip">${k} <strong>${v}</strong></span>`).join('');}
function renderScorebar(){const bar=$('#scorebar'),signals=[...live.activeSignals].sort((a,b)=>Date.parse(b.selectedAt)-Date.parse(a.selectedAt));$('#activeCount').textContent=`${signals.length} ACTIVE`;if(!signals.length){bar.innerHTML='<div class="empty">Waiting for confirmed signals…</div>';return;}bar.innerHTML=signals.map(r=>{const m=matchById(r.id),isNew=!seen.has(String(r.id))&&Date.now()-Date.parse(r.selectedAt)<60000;return`<button class="scorecard ${String(r.id)===String(selectedId)&&selectedSignal?'active':''} ${isNew?'new':''}" data-signal="${esc(r.id)}"><div class="score-top"><small>⚡ SIGNAL ${esc(signalClock(r))}</small><b>LIVE <span data-clock="${esc(r.id)}">${esc(clockText(r.id))}</span></b></div><strong class="pick">${esc(lockText(r))}</strong><div class="score-bottom"><span>ENTRY ${esc(entryScore(r))}</span><span>NOW ${esc(orientedScore(r,m))}</span></div></button>`;}).join('');bar.querySelectorAll('[data-signal]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.signal;selectedSignal=true;seen.add(String(selectedId));render();});}
function renderCandidates(){const box=$('#candidates');$('#liveCount').textContent=live.matches.length;box.innerHTML=live.matches.map(m=>{const c=candidateById(m.id),r=recordById(m.id),decision=r?'CONFIRMED':c?.decision||'WATCH';return`<button class="candidate ${String(m.id)===String(selectedId)&&!selectedSignal?'active':''}" data-match="${esc(m.id)}"><small>${esc(m.league)} · <span data-clock="${esc(m.id)}">${esc(clockText(m.id))}</span></small><strong>${esc(m.home)} ${esc(m.score.home)}–${esc(m.score.away)} ${esc(m.away)}</strong><div class="row"><span>${esc(decision)}</span><span>${c?.momentum??'—'}%</span></div></button>`;}).join('')||'<div class="empty">No live matches.</div>';box.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>{selectedId=b.dataset.match;selectedSignal=false;render();});}
function renderSummary(){const box=$('#summary'),r=selectedSignal?recordById(selectedId):null,m=matchById(selectedId);if(!r){box.className='signal-summary monitoring';box.innerHTML='<div class="status"><span class="dot"></span><b>MONITORING</b><small>No confirmed signal selected.</small></div>';return;}box.className='signal-summary';box.innerHTML=`<div class="status"><span class="dot"></span><b>CONFIRMED SIGNAL</b><small>Detection data locked · live match continues</small></div><div class="signal-grid"><div class="cell primary"><small>SELECTION</small><b>${esc(lockText(r))}</b></div><div class="cell signal"><small>DETECTED / ENTRY</small><b>${esc(signalClock(r))} · ${esc(entryScore(r))}</b></div><div class="cell live"><small>LIVE NOW</small><b><span data-clock="${esc(r.id)}">${esc(clockText(r.id))}</span> · ${esc(orientedScore(r,m))}</b></div><div class="cell"><small>CURRENT MARKET</small><b>${esc(currentMarket(r,m))}</b></div></div><div class="chips">${reasonChips(r)}</div>`;}
function renderMatch(){const m=matchById(selectedId);if(!m){$('#match').innerHTML='<div class="empty">Select a live match.</div>';$('#stats').innerHTML='';$('#events').innerHTML='';return;}const r=selectedSignal?recordById(selectedId):null,sel=r?.selectedSide;$('#match').innerHTML=`<div class="match-card"><div class="team ${sel==='HOME'?'selected':''}"><small>HOME</small><b>${esc(m.home)}</b></div><div class="score"><b>${esc(m.score.home)}–${esc(m.score.away)}</b><span data-clock="${esc(m.id)}">${esc(clockText(m.id))}</span></div><div class="team ${sel==='AWAY'?'selected':''}"><small>AWAY</small><b>${esc(m.away)}</b></div></div>`;const keys=[['Possession','possession'],['Attacks','attacks'],['Dangerous','dangerous_attacks'],['Shots','shots'],['Shots on Target','shots_on_target'],['Corners','corners']];$('#stats').innerHTML='<div class="section-label">LIVE STATS</div><div class="stats">'+keys.map(([label,key])=>`<div class="stat"><small>${label}</small><div class="split"><b>${m.stats?.[key]?.home??'—'}</b><b>${m.stats?.[key]?.away??'—'}</b></div></div>`).join('')+'</div>';$('#events').innerHTML='<div class="section-label">RECENT EVENTS</div><div class="events">'+(m.events||[]).slice(0,8).map(e=>`<div class="event"><span>${esc(e.minute??'—')}' · ${esc(e.type)}</span><span>${esc(e.team)}</span></div>`).join('')+'</div>';}
function render(){renderScorebar();renderCandidates();renderSummary();renderMatch();updateClocks();}
async function refresh(){try{const [l,c]=await Promise.all([fetch(`${WORKER}/live?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),config?Promise.resolve({config}):fetch(`${WORKER}/config`,{cache:'no-store'}).then(r=>r.json())]);live=l;config=c.config||config;live.matches.forEach(anchorSnapshot);if(selectedId&&!matchById(selectedId))selectedId=null;if(!selectedId&&live.activeSignals.length){selectedId=live.activeSignals[0].id;selectedSignal=true;}else if(!selectedId&&live.matches.length){selectedId=live.matches[0].id;selectedSignal=false;}render();}catch(e){console.error(e);}}
$('#prev').onclick=()=>$('#scorebar').scrollBy({left:-520,behavior:'smooth'});$('#next').onclick=()=>$('#scorebar').scrollBy({left:520,behavior:'smooth'});$('#scorebar').addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();$('#scorebar').scrollLeft+=e.deltaY;}},{passive:false});
setInterval(updateClocks,250);setInterval(refresh,5000);refresh();
