const WORKER='https://nomadtips3-car33-live.mccarey-supon.workers.dev',$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=v=>Number.isFinite(Number(v))?Number(v):null;let page=1,total=0,limit=25;
const odds=v=>n(v)===null?'—':n(v).toFixed(2),line=v=>n(v)===null?'—':`${n(v)>0?'+':''}${Number.isInteger(n(v))?n(v).toFixed(1):n(v)}`;
function pick(r){if(r.market==='AH')return`${r.selectedTeam} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;if(r.market==='OU')return`${r.ouDirection} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;return`${r.selectedTeam} · WIN @ ${odds(r.lockedOdds)}`;}
function signalTime(r){const s=n(r.signalElapsedSeconds);return s===null?`${r.entryMinute??'—'}'`:`${Math.floor(s/60)}:${String(Math.floor(s)%60).padStart(2,'0')}`;}
function entry(r){return r.selectedSide==='AWAY'?`${r.entryScore?.away??'—'}–${r.entryScore?.home??'—'}`:`${r.entryScore?.home??'—'}–${r.entryScore?.away??'—'}`;}
function final(r){return r.finalScore?`${r.finalScore.home}–${r.finalScore.away}`:(r.result==='PENDING'?'LIVE / AWAITING FT':'—');}
function dt(v){if(!v)return'—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():'—';}
function evidence(r){const e=r.evidence||{};return`Danger ${signed(e.dangerous)} · Shots ${signed(e.shots)} · SOT ${signed(e.sot)} · Corners ${signed(e.corners)}`;}
function signed(v){const x=n(v);return x===null?'—':`${x>=0?'+':''}${x}`;}
function gates(r){const g=r.gates||{},items=Object.entries(g);if(!items.length)return'—';return items.map(([k,v])=>`<span class="${v?'gate-pass':'gate-wait'}">${esc(k)} ${v?'PASS':'WAIT'}</span>`).join(' · ');}
function marketMeta(r){const raw=n(r.rawLine),sel=n(r.selectedLine);return`${esc(r.market||'—')} · selected ${esc(line(sel))} · raw ${esc(line(raw))} · odds ${esc(odds(r.lockedOdds))} · ${esc(r.linePerspective||'—')}`;}
function detailRow(r){const pending=r.result==='PENDING';return`<tr class="record-detail"><td colspan="9"><div class="detail-grid"><div class="detail-cell"><small>STATUS</small><b class="${pending?'pending-note':''}">${esc(r.result||'PENDING')} · ${esc(r.resultDetail||'PENDING')}</b></div><div class="detail-cell"><small>SELECTED SIDE</small><b>${esc(r.selectedSide||'—')} · ${esc(r.selectedTeam||'—')}</b></div><div class="detail-cell"><small>SIGNAL CLOCK</small><b>${esc(signalTime(r))} · source ${esc(r.sourceClockAtSignal||'—')}</b></div><div class="detail-cell"><small>ENTRY SCORE</small><b>${esc(entry(r))}</b></div><div class="detail-cell"><small>MOMENTUM</small><b>${n(r.momentum)===null?'—':`${Math.round(n(r.momentum))}%`}</b></div><div class="detail-cell detail-wide"><small>MARKET SNAPSHOT</small><b>${marketMeta(r)}</b></div><div class="detail-cell detail-wide"><small>ATTACK EVIDENCE AT SIGNAL</small><b>${esc(evidence(r))}</b></div><div class="detail-cell detail-wide"><small>GATES AT SIGNAL</small><b>${gates(r)}</b></div><div class="detail-cell"><small>SNAPSHOT ID</small><b>${esc(r.snapshotId||'—')}</b></div><div class="detail-cell"><small>DETECTED AT</small><b>${esc(dt(r.selectedAt))}</b></div><div class="detail-cell"><small>SETTLED AT</small><b>${pending?'<span class="pending-note">PENDING</span>':esc(dt(r.settledAt))}</b></div></div></td></tr>`;}
function mainRow(r){const pending=r.result==='PENDING';return`<tr class="record-main ${pending?'pending-row':''}"><td><span class="status-pill ${esc(r.result||'PENDING')}">${esc(r.result||'PENDING')}</span><div class="signal-meta">${esc(r.resultDetail||'PENDING')}</div></td><td><strong>${esc(pick(r))}</strong><div class="signal-meta">SIGNAL ${esc(signalTime(r))}</div></td><td>${esc(r.home)} vs ${esc(r.away)}<div class="signal-meta">${esc(r.league||'—')}</div></td><td>${esc(entry(r))}<div class="signal-meta">${esc(r.selectedSide||'—')} selected</div></td><td>${esc(r.market||'—')}<div class="signal-meta">Line ${esc(line(r.selectedLine))} · @ ${esc(odds(r.lockedOdds))}</div></td><td>${n(r.momentum)===null?'—':`${Math.round(n(r.momentum))}%`}<div class="signal-meta">${esc(evidence(r))}</div></td><td>${esc(final(r))}</td><td>${esc(dt(r.selectedAt))}</td><td>${pending?'<span class="pending-note">PENDING · LIVE</span>':esc(dt(r.settledAt))}</td></tr>`;}
async function load(){const data=await fetch(`${WORKER}/history?page=${page}&limit=${limit}&t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json());total=data.total||0;const s=data.summary||{};$('#summary').innerHTML=[['TOTAL',s.total],['WIN',s.win],['LOSS',s.loss],['DRAW',s.draw],['PENDING',s.pending],['WIN RATE',s.winRate==null?'—':`${s.winRate.toFixed(1)}%`]].map(([k,v])=>`<div class="metric"><small>${k}</small><b>${v??0}</b></div>`).join('');const rows=(data.records||[]);$('#rows').innerHTML=rows.map(r=>mainRow(r)+detailRow(r)).join('')||'<tr><td colspan="9">No records.</td></tr>';$('#page').textContent=`PAGE ${page} / ${Math.max(1,Math.ceil(total/limit))}`;}
$('#prev').onclick=()=>{if(page>1){page--;load();}};$('#next').onclick=()=>{if(page*limit<total){page++;load();}};load();setInterval(load,10000);
