const WORKER='https://nomadtips3-car33-live.mccarey-supon.workers.dev';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;};
let page=1,limit=25,total=0,busy=false;
const odds=v=>n(v)===null?'—':n(v).toFixed(2);
const line=v=>n(v)===null?'—':`${n(v)>0?'+':''}${Number.isInteger(n(v))?n(v).toFixed(1):n(v)}`;
function signalText(r){if(r.market==='AH')return`${r.selectedTeam} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;if(r.market==='OU')return`${r.ouDirection||'OVER'} ${line(r.selectedLine)} @ ${odds(r.lockedOdds)}`;return`${r.selectedTeam} · WIN @ ${odds(r.lockedOdds)}`;}
function signalTime(r){const s=n(r.signalElapsedSeconds);return s===null?`${r.entryMinute??'—'}'`:`${Math.floor(s/60)}:${String(Math.floor(s)%60).padStart(2,'0')}`;}
function entryScore(r){if(!r.entryScore)return'—';return r.selectedSide==='AWAY'?`${r.entryScore.away??'—'}–${r.entryScore.home??'—'}`:`${r.entryScore.home??'—'}–${r.entryScore.away??'—'}`;}
function finalScore(r){return r.finalScore?`${r.finalScore.home??'—'}–${r.finalScore.away??'—'}`:(r.result==='PENDING'?'LIVE / AWAITING FT':'—');}
function dt(v){if(!v)return'—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():'—';}
function signed(v){const x=n(v);return x===null?'—':`${x>=0?'+':''}${x}`;}
function evidence(r){const e=r.evidence||{};return`Danger ${signed(e.dangerous)} · Shots ${signed(e.shots)} · SOT ${signed(e.sot)} · Corners ${signed(e.corners)}`;}
function gateHtml(r){const items=Object.entries(r.gates||{});return items.length?items.map(([k,v])=>`<span class="${v?'gate-pass':'gate-wait'}">${esc(k)} ${v?'PASS':'WAIT'}</span>`).join(' · '):'—';}
function mainRow(r){const status=String(r.result||'PENDING').toUpperCase(),pending=status==='PENDING';return`<tr class="record-main ${pending?'pending-row':''}"><td><span class="status-pill ${esc(status)}">${esc(status)}</span><div class="signal-meta">${esc(r.resultDetail||status)}</div></td><td><strong>${esc(signalText(r))}</strong><div class="signal-meta">SIGNAL ${esc(signalTime(r))}</div></td><td>${esc(r.home||'—')} vs ${esc(r.away||'—')}<div class="signal-meta">${esc(r.league||'—')}</div></td><td>${esc(entryScore(r))}<div class="signal-meta">${esc(r.selectedSide||'—')} selected</div></td><td>${esc(r.market||'—')}<div class="signal-meta">Line ${esc(line(r.selectedLine))} · @ ${esc(odds(r.lockedOdds))}</div></td><td>${n(r.momentum)===null?'—':`${Math.round(n(r.momentum))}%`}<div class="signal-meta">${esc(evidence(r))}</div></td><td>${esc(finalScore(r))}</td><td>${esc(dt(r.selectedAt))}</td><td>${pending?'<span class="pending-note">PENDING · LIVE</span>':esc(dt(r.settledAt))}</td></tr>`;}
function detailRow(r){const pending=String(r.result||'PENDING').toUpperCase()==='PENDING';return`<tr class="record-detail"><td colspan="9"><div class="detail-grid"><div class="detail-cell"><small>STATUS</small><b class="${pending?'pending-note':''}">${esc(r.result||'PENDING')} · ${esc(r.resultDetail||'PENDING')}</b></div><div class="detail-cell"><small>SELECTED TEAM / SIDE</small><b>${esc(r.selectedTeam||'—')} · ${esc(r.selectedSide||'—')}</b></div><div class="detail-cell"><small>SIGNAL CLOCK</small><b>${esc(signalTime(r))}</b></div><div class="detail-cell"><small>SOURCE CLOCK AT SIGNAL</small><b>${esc(r.sourceClockAtSignal||'—')}</b></div><div class="detail-cell"><small>ENTRY SCORE</small><b>${esc(entryScore(r))}</b></div><div class="detail-cell"><small>MOMENTUM</small><b>${n(r.momentum)===null?'—':`${Math.round(n(r.momentum))}%`}</b></div><div class="detail-cell"><small>MARKET SNAPSHOT</small><b>${esc(r.market||'—')} · selected ${esc(line(r.selectedLine))} · raw ${esc(line(r.rawLine))} · odds ${esc(odds(r.lockedOdds))} · ${esc(r.linePerspective||'—')}</b></div><div class="detail-cell"><small>SNAPSHOT ID</small><b>${esc(r.snapshotId||'—')}</b></div><div class="detail-cell detail-wide"><small>ATTACK EVIDENCE AT SIGNAL</small><b>${esc(evidence(r))}</b></div><div class="detail-cell detail-wide"><small>GATES AT SIGNAL</small><b>${gateHtml(r)}</b></div><div class="detail-cell"><small>DETECTED AT</small><b>${esc(dt(r.selectedAt))}</b></div><div class="detail-cell"><small>SETTLED AT</small><b>${pending?'<span class="pending-note">PENDING</span>':esc(dt(r.settledAt))}</b></div></div></td></tr>`;}
function renderSummary(s={}){const settled=(n(s.win)||0)+(n(s.loss)||0)+(n(s.draw)||0),cards=[['TOTAL',s.total??0,''],['SETTLED',settled,''],['PENDING',s.pending??0,'pending'],['WIN',s.win??0,'win'],['LOSS',s.loss??0,'loss'],['DRAW',s.draw??0,''],['WIN RATE',s.winRate==null?'—':`${Number(s.winRate).toFixed(1)}%`,'rate'],['AVG ODDS',s.averageOdds==null?'—':Number(s.averageOdds).toFixed(2),'odds']];$('#summary').innerHTML=cards.map(([k,v,c])=>`<div class="stats-metric ${c}"><small>${k}</small><b>${v}</b></div>`).join('');}
function renderDistribution(s={}){const values=[['WIN',n(s.win)||0,'win'],['LOSS',n(s.loss)||0,'loss'],['DRAW',n(s.draw)||0,'draw'],['PENDING',n(s.pending)||0,'pending']],max=Math.max(1,...values.map(x=>x[1]));$('#distribution').innerHTML=values.map(([k,v,c])=>`<div class="dist-row ${c}"><span>${k}</span><div class="dist-track"><i style="width:${Math.max(v?4:0,v/max*100)}%"></i></div><b>${v}</b></div>`).join('');$('#distLabel').textContent=`${s.total??0} TOTAL`;}
function renderCurve(records=[]){const settled=records.filter(r=>r.result!=='PENDING').slice().reverse();if(!settled.length){$('#curve').innerHTML='<div class="stats-message">No settled records yet.</div>';return;}let score=0;const vals=[0];for(const r of settled){if(r.result==='WIN')score+=1;else if(r.result==='LOSS')score-=1;vals.push(score);}const w=760,h=150,p=14,min=Math.min(0,...vals),max=Math.max(0,...vals),range=Math.max(1,max-min),x=i=>p+(w-p*2)*(i/Math.max(1,vals.length-1)),y=v=>h-p-(h-p*2)*((v-min)/range),pts=vals.map((v,i)=>`${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' '),zero=y(0).toFixed(1);$('#curve').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="curve-grid"><line x1="${p}" y1="37" x2="${w-p}" y2="37"/><line x1="${p}" y1="75" x2="${w-p}" y2="75"/><line x1="${p}" y1="112" x2="${w-p}" y2="112"/></g><line class="curve-zero" x1="${p}" y1="${zero}" x2="${w-p}" y2="${zero}"/><polyline class="curve-line" points="${pts}"/></svg>`;}
function showMessage(text='',error=false){const box=$('#message');box.innerHTML=text?`<div class="stats-message ${error?'error':''}">${esc(text)}</div>`:'';}
async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();if(!p||!Array.isArray(p.records)||!p.summary)throw new Error('Invalid history payload');return p;}
async function load(){if(busy)return;busy=true;try{showMessage();const [data,recent]=await Promise.all([getJson(`${WORKER}/api/history?page=${page}&limit=${limit}&t=${Date.now()}`),getJson(`${WORKER}/api/history?page=1&limit=100&t=${Date.now()}`)]);total=data.total||0;renderSummary(data.summary);renderDistribution(data.summary);renderCurve(recent.records||[]);const rows=data.records||[];$('#rows').innerHTML=rows.map(r=>mainRow(r)+detailRow(r)).join('');if(!rows.length){$('#rows').innerHTML='<tr><td colspan="9"><div class="stats-message">No signal records yet. Confirmed signals will appear here immediately, including PENDING.</div></td></tr>';}$('#page').textContent=`PAGE ${page} / ${Math.max(1,Math.ceil(total/limit))}`;$('#prev').disabled=page<=1;$('#next').disabled=page*limit>=total;}catch(e){console.error(e);renderSummary({});renderDistribution({});$('#curve').innerHTML='<div class="stats-message error">Performance data unavailable.</div>';$('#rows').innerHTML='<tr><td colspan="9"><div class="stats-message error">Statistics could not load from the history API.</div></td></tr>';showMessage(`STATISTICS DATA ERROR · ${e.message}`,true);}finally{busy=false;}}
$('#prev').onclick=()=>{if(page>1){page--;load();}};$('#next').onclick=()=>{if(page*limit<total){page++;load();}};load();setInterval(load,10000);
