const VERSION='nomad343-5usd-hub-v4-status-safe';
const API_BASE='https://api.5dollarfootballapi.com/v1';
const REFRESH_MS=120_000;
const STALE_MS=180_000;
const TIMEOUT_MS=15_000;
const TODAY_PAGE_SIZE=50;
const LIVE_PAGE_SIZE=50;
const TODAY_MAX_PAGES=4;
const LIVE_MAX_PAGES=1;
const MAX_PROVIDER_REQUESTS_PER_REFRESH=5;
const CHUNK_BYTES=72_000;
const encoder=new TextEncoder();
const now=()=>Date.now();
const finite=v=>v===null||v===undefined||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))?null:Number(v);
const text=v=>v===null||v===undefined?null:String(v);

const ALLOWED_ORIGINS=new Set(['https://www.nomadtips3.com','https://nomadtips3.com','https://mccareysupon-png.github.io','http://localhost:8787','http://127.0.0.1:8787']);
function headers(request){const origin=request.headers.get('origin')||'';const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type',vary:'Origin'});h.set('access-control-allow-origin',ALLOWED_ORIGINS.has(origin)?origin:'https://www.nomadtips3.com');return h}
function json(request,body,status=200){return new Response(status===204?null:JSON.stringify(body),{status,headers:headers(request)})}
function pair(v){if(!v||typeof v!=='object')return null;const home=finite(v.home),away=finite(v.away);return home===null&&away===null?null:{home,away}}
function score(v){if(!v||typeof v!=='object')return null;return {home:finite(v.home),away:finite(v.away),halfHome:finite(v.half_home??v.halfHome),halfAway:finite(v.half_away??v.halfAway)}}
function cards(v){if(!v||typeof v!=='object')return null;const side=x=>x&&typeof x==='object'?{yellow:finite(x.yellow),red:finite(x.red)}:null;return {home:side(v.home),away:side(v.away)}}
function team(f,side){const r=f?.teams?.[side]??f?.[`${side}_team`]??f?.[side]??{};return {id:text(r?.id??f?.[`${side}_id`]??null),name:text(r?.name??f?.[`${side}_name`]??null)}}
function league(f){const r=f?.league??f?.competition??{};return {id:text(r?.id??f?.league_id??f?.competition_id??null),name:text(r?.name??f?.league_name??f?.competition_name??null),country:text(r?.country?.name??r?.country??f?.country??null)}}
function statistics(r){if(!r||typeof r!=='object')return null;const out={attacks:pair(r.attacks),dangerousAttacks:pair(r.dangerous_attacks??r.dangerousAttacks),shotsOnTarget:pair(r.shots_on_target??r.shotsOnTarget),shotsOffTarget:pair(r.shots_off_target??r.shotsOffTarget),possession:pair(r.possession)};if(!Object.values(out).some(Boolean))return null;const h=r.first_half??r.half;out.half=h&&typeof h==='object'?{attacks:pair(h.attacks),dangerousAttacks:pair(h.dangerous_attacks??h.dangerousAttacks),shotsOnTarget:pair(h.shots_on_target??h.shotsOnTarget),shotsOffTarget:pair(h.shots_off_target??h.shotsOffTarget),possession:pair(h.possession)}:null;return out}
function fixtureId(f){return text(f?.id??f?.fixture_id??f?.fixture?.id??null)}
function kickoffUtc(f){return text(f?.kickoff_utc??f?.kickoffUtc??f?.start_time??f?.kickoff??f?.date??null)}
function boardState(status,statusCode){const s=`${status||''} ${statusCode||''}`.toLowerCase();if(/unknown/.test(s))return'unknown';if(/finished|full_time|full time|\bft\b|ended|\bfull\b/.test(s))return'finished';if(/in_play|in play|live|half/.test(s)||/^\d+$/.test(String(statusCode||'')))return'live';return'scheduled'}
function normalize(f){const id=fixtureId(f),status=text(f?.status?.name??f?.status??null),statusReason=text(f?.status_reason??f?.status?.reason??null),statusCode=text(f?.status_code??f?.status?.code??f?.status?.short??null),minute=finite(f?.minute??f?.elapsed??f?.status?.minute??f?.status?.elapsed??statusCode),kickoff=kickoffUtc(f);return {fixtureId:id,league:league(f),home:team(f,'home'),away:team(f,'away'),kickoffUtc:kickoff,kickoffAt:kickoff&&Number.isFinite(Date.parse(kickoff))?Date.parse(kickoff):finite(f?.kickoff_ts??f?.start_time)?finite(f?.kickoff_ts??f?.start_time)*1000:null,status,statusReason,statusCode,boardState:boardState(status,statusCode),minute,goals:score(f?.goals??f?.score),corners:score(f?.corners),cards:cards(f?.cards),statistics:statistics(f?.statistics??f?.stats??null),events:Array.isArray(f?.events)?f.events:null,providerOdds:f?.odds??f?.bookmakers??f?.markets??f?.bet365??null}}
function extract(payload){if(Array.isArray(payload?.data))return payload.data;if(Array.isArray(payload?.data?.data))return payload.data.data;if(Array.isArray(payload?.fixtures))return payload.fixtures;return []}
function pageInfo(payload){const p=payload?.pagination??payload?.meta?.pagination??payload?.meta??{};const raw=p?.has_more??p?.hasMore??payload?.has_more??payload?.hasMore??false;return {hasMore:raw===true||raw===1||raw==='1'||raw==='true'}}
async function fetchJson(url,key){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),TIMEOUT_MS);try{const r=await fetch(url,{cache:'no-store',signal:ac.signal,headers:{accept:'application/json',authorization:`Bearer ${key}`}});const raw=await r.text();let j=null;try{j=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(`provider:HTTP_${r.status}`);if(!j||typeof j!=='object')throw new Error('provider:INVALID_JSON');return j}catch(e){if(e?.name==='AbortError')throw new Error('provider:TIMEOUT');throw e}finally{clearTimeout(timer)}}
async function fetchPages(env,query,perPage,maxPages){if(!env.FIVEDOLLAR_API_KEY)throw new Error('provider:FIVEDOLLAR_API_KEY_MISSING');const rows=[];let page=1,hasMore=false;do{const join=query?`&${query}`:'';const j=await fetchJson(`${API_BASE}/fixtures?per_page=${perPage}&page=${page}${join}`,env.FIVEDOLLAR_API_KEY);rows.push(...extract(j));hasMore=pageInfo(j).hasMore;page+=1}while(hasMore&&page<=maxPages);return {rows,requests:page-1,guardHit:hasMore&&page>maxPages}}
function bangkokWindow(ms=now()){const shift=7*3600_000,d=new Date(ms+shift);const start=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-shift;return {startMs:start,endMs:start+86_400_000,start:Math.floor(start/1000),end:Math.floor((start+86_400_000)/1000)}}
async function fetchProvider(env){const w=bangkokWindow();const include='odds,events,stats';const today=await fetchPages(env,`start_time=${w.start}&end_time=${w.end}&status=all&include=${include}`,TODAY_PAGE_SIZE,TODAY_MAX_PAGES);const live=await fetchPages(env,`status=live&include=${include}`,LIVE_PAGE_SIZE,LIVE_MAX_PAGES);const requests=today.requests+live.requests;if(requests>MAX_PROVIDER_REQUESTS_PER_REFRESH)throw new Error(`provider:REQUEST_BUDGET_${requests}`);return {today,live,window:w,include,requestBudget:MAX_PROVIDER_REQUESTS_PER_REFRESH}}
function merge(base,extra){if(!base)return extra;if(!extra)return base;return {...base,...extra,league:{...(base.league||{}),...(extra.league||{})},home:{...(base.home||{}),...(extra.home||{})},away:{...(base.away||{}),...(extra.away||{})},kickoffUtc:extra.kickoffUtc??base.kickoffUtc,kickoffAt:extra.kickoffAt??base.kickoffAt,goals:extra.goals??base.goals,corners:extra.corners??base.corners,cards:extra.cards??base.cards,statistics:extra.statistics??base.statistics,events:extra.events??base.events,providerOdds:extra.providerOdds??base.providerOdds}}
function chunks(rows){const out=[];let cur=[];for(const row of rows){const next=[...cur,row];if(cur.length&&encoder.encode(JSON.stringify(next)).byteLength>CHUNK_BYTES){out.push(cur);cur=[row]}else cur=next}if(cur.length||!out.length)out.push(cur);return out}

export class FiveUsdHub{
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.refreshPromise=null}
  async meta(){return await this.ctx.storage.get('meta')||null}
  async state(){return await this.ctx.storage.get('state')||{lastAttemptAt:null,lastSuccessAt:null,lastError:null}}
  async readRows(meta){if(!meta)return[];const out=[];for(let i=0;i<Number(meta.chunkCount||0);i++){const raw=await this.ctx.storage.get(`snapshot:${meta.snapshotId}:${i}`);if(!raw)continue;try{const rows=JSON.parse(raw);if(Array.isArray(rows))out.push(...rows)}catch{}}return out}
  async refreshIfDue(){const m=await this.meta();if(m?.fetchedAt&&now()-m.fetchedAt<REFRESH_MS)return m;if(this.refreshPromise)return this.refreshPromise;this.refreshPromise=this.refresh().finally(()=>{this.refreshPromise=null});return this.refreshPromise}
  async refresh(){const attempt=now(),oldMeta=await this.meta(),oldRows=await this.readRows(oldMeta),oldState=await this.state();await this.ctx.storage.put('state',{...oldState,lastAttemptAt:attempt});try{const p=await fetchProvider(this.env);const map=new Map();for(const raw of p.today.rows){const n=normalize(raw);if(n.fixtureId)map.set(n.fixtureId,n)}for(const old of oldRows){if(map.has(old.fixtureId))map.set(old.fixtureId,merge(old,map.get(old.fixtureId)))}for(const raw of p.live.rows){const n=normalize(raw);if(n.fixtureId)map.set(n.fixtureId,merge(map.get(n.fixtureId),n))}const rows=[...map.values()].sort((a,b)=>(a.kickoffAt??0)-(b.kickoffAt??0));const dataChunks=chunks(rows),snapshotId=attempt.toString(36);for(let i=0;i<dataChunks.length;i++)await this.ctx.storage.put(`snapshot:${snapshotId}:${i}`,JSON.stringify(dataChunks[i]));const counts={scheduled:rows.filter(x=>x.boardState==='scheduled').length,live:rows.filter(x=>x.boardState==='live').length,finished:rows.filter(x=>x.boardState==='finished').length,unknown:rows.filter(x=>x.boardState==='unknown').length};const meta={version:VERSION,fetchedAt:now(),snapshotId,chunkCount:dataChunks.length,fixtureCount:rows.length,counts,providerRequestCount:p.today.requests+p.live.requests,providerRequestBudget:p.requestBudget,todayRequests:p.today.requests,liveRequests:p.live.requests,guardHit:Boolean(p.today.guardHit||p.live.guardHit),include:p.include,todayWindow:{start:p.window.start,end:p.window.end,timeZone:'Asia/Bangkok'}};await this.ctx.storage.put('meta',meta);await this.ctx.storage.put('state',{lastAttemptAt:attempt,lastSuccessAt:meta.fetchedAt,lastError:null});if(oldMeta?.snapshotId&&oldMeta.snapshotId!==snapshotId){for(let i=0;i<Number(oldMeta.chunkCount||0);i++)await this.ctx.storage.delete(`snapshot:${oldMeta.snapshotId}:${i}`)}return meta}catch(e){await this.ctx.storage.put('state',{...oldState,lastAttemptAt:attempt,lastError:String(e?.message||e)});if(oldMeta)return oldMeta;throw e}}
  async snapshot(){let m=await this.meta();if(!m||!m.fetchedAt||now()-m.fetchedAt>=REFRESH_MS){try{m=await this.refreshIfDue()}catch{}}m=await this.meta();const s=await this.state();if(!m)return {ok:false,version:VERSION,error:s.lastError||'NO_SNAPSHOT'};const rows=await this.readRows(m),ageMs=Math.max(0,now()-m.fetchedAt);return {ok:true,version:VERSION,provider:'5DollarFootballAPI',fetchedAt:m.fetchedAt,ageMs,stale:ageMs>STALE_MS,fixtureCount:rows.length,counts:m.counts,providerRequestCount:m.providerRequestCount,providerRequestBudget:m.providerRequestBudget,todayRequests:m.todayRequests,liveRequests:m.liveRequests,guardHit:m.guardHit,include:m.include,todayWindow:m.todayWindow,lastAttemptAt:s.lastAttemptAt,lastSuccessAt:s.lastSuccessAt,lastError:s.lastError,fixtures:rows}}
  async health(){const m=await this.meta(),s=await this.state(),ageMs=m?.fetchedAt?Math.max(0,now()-m.fetchedAt):null;return {ok:Boolean(m),component:'5USD_HUB',version:VERSION,fixtureCount:m?.fixtureCount??0,counts:m?.counts??{scheduled:0,live:0,finished:0,unknown:0},fetchedAt:m?.fetchedAt??null,ageMs,stale:ageMs===null||ageMs>STALE_MS,refreshMs:REFRESH_MS,providerRequestCount:m?.providerRequestCount??0,providerRequestBudget:m?.providerRequestBudget??MAX_PROVIDER_REQUESTS_PER_REFRESH,include:m?.include??null,lastError:s.lastError}}
  async fetch(request){const u=new URL(request.url);if(u.pathname==='/_internal/refresh'&&request.method==='POST'){try{await this.refreshIfDue();return new Response(JSON.stringify(await this.health()),{headers:{'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:String(e?.message||e)}),{status:502,headers:{'content-type':'application/json'}})}}if(u.pathname==='/snapshot')return new Response(JSON.stringify(await this.snapshot()),{headers:{'content-type':'application/json'}});if(u.pathname==='/health')return new Response(JSON.stringify(await this.health()),{headers:{'content-type':'application/json'}});return new Response('Not found',{status:404})}
}
function stub(env){return env.HUB.get(env.HUB.idFromName('global'))}
export default{async fetch(request,env){if(request.method==='OPTIONS')return json(request,null,204);const u=new URL(request.url),s=stub(env);if(request.method==='GET'&&u.pathname==='/snapshot'){const r=await s.fetch('https://hub.internal/snapshot');return json(request,await r.json(),r.status)}if(request.method==='GET'&&(u.pathname==='/health'||u.pathname==='/status')){const r=await s.fetch('https://hub.internal/health');return json(request,await r.json(),r.status)}return json(request,{ok:false,version:VERSION,error:'NOT_FOUND'},404)},async scheduled(_event,env,ctx){ctx.waitUntil(stub(env).fetch('https://hub.internal/_internal/refresh',{method:'POST'}))}}