const VERSION='nomad343-5usd-hub-v7-live-core-500';
const API_BASE='https://api.5dollarfootballapi.com/v1';
const SCHEDULE_REFRESH_MS=120_000;
const STALE_MS=180_000;
const TIMEOUT_MS=15_000;
const TODAY_PAGE_SIZE=50;
const LIVE_PAGE_SIZE=500;
const TODAY_MAX_PAGES=4;
const LIVE_MAX_PAGES=1;
const SCHEDULE_MAX_REQUESTS=5;
const LIVE_CORE_REQUESTS=1;
const ACCOUNT_LIMIT_PER_MINUTE=40;
const ALLOWED_INTERVALS_SEC=[120,60,30,15,6,3,2];
const OWNER_TOKEN_SHA256='2e865593c9988c1f6dd0e620ba96bd14cf607555c0f273f68e192e9accad6e9b';
const INTERNAL_CONTROL_MARKER='preview-binding-v1';
const CHUNK_BYTES=72_000;
const LEDGER_RETENTION_MS=10*60_000;
const encoder=new TextEncoder();
const now=()=>Date.now();
const finite=v=>v===null||v===undefined||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))?null:Number(v);
const text=v=>v===null||v===undefined?null:String(v);
const round1=v=>Math.round(Number(v||0)*10)/10;

const ALLOWED_ORIGINS=new Set(['https://www.nomadtips3.com','https://nomadtips3.com','https://mccareysupon-png.github.io','http://localhost:8787','http://127.0.0.1:8787']);
function headers(request){const origin=request.headers.get('origin')||'';const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-nomad-owner-token',vary:'Origin'});h.set('access-control-allow-origin',ALLOWED_ORIGINS.has(origin)?origin:'https://www.nomadtips3.com');return h}
function json(request,body,status=200){return new Response(status===204?null:JSON.stringify(body),{status,headers:headers(request)})}
async function sha256Hex(value){const data=encoder.encode(String(value||'')),hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function ownerAuthorized(request){const token=request.headers.get('x-nomad-owner-token')||'';if(!token)return false;return (await sha256Hex(token))===OWNER_TOKEN_SHA256}
function internalControlAuthorized(request){const u=new URL(request.url);return u.hostname==='hub.internal'&&request.headers.get('x-nomad-internal-control')===INTERNAL_CONTROL_MARKER}
function pair(v){if(!v||typeof v!=='object')return null;const home=finite(v.home),away=finite(v.away);return home===null&&away===null?null:{home,away}}
function score(v){if(!v||typeof v!=='object')return null;return {home:finite(v.home),away:finite(v.away),halfHome:finite(v.half_home??v.halfHome),halfAway:finite(v.half_away??v.halfAway)}}
function cards(v){if(!v||typeof v!=='object')return null;const side=x=>x&&typeof x==='object'?{yellow:finite(x.yellow),red:finite(x.red)}:null;return {home:side(v.home),away:side(v.away)}}
function team(f,side){const r=f?.teams?.[side]??f?.[`${side}_team`]??f?.[side]??{};return {id:text(r?.id??f?.[`${side}_id`]??null),name:text(r?.name??f?.[`${side}_name`]??null)}}
function league(f){const r=f?.league??f?.competition??{};return {id:text(r?.id??f?.league_id??f?.competition_id??null),name:text(r?.name??f?.league_name??f?.competition_name??null),country:text(r?.country?.name??r?.country??f?.country??null)}}
function statistics(r){if(!r||typeof r!=='object')return null;const out={attacks:pair(r.attacks),dangerousAttacks:pair(r.dangerous_attacks??r.dangerousAttacks),shotsOnTarget:pair(r.shots_on_target??r.shotsOnTarget),shotsOffTarget:pair(r.shots_off_target??r.shotsOffTarget),possession:pair(r.possession)};if(!Object.values(out).some(Boolean))return null;const h=r.first_half??r.half;out.half=h&&typeof h==='object'?{attacks:pair(h.attacks),dangerousAttacks:pair(h.dangerous_attacks??h.dangerousAttacks),shotsOnTarget:pair(h.shots_on_target??h.shotsOnTarget),shotsOffTarget:pair(h.shots_off_target??h.shotsOffTarget),possession:pair(h.possession)}:null;return out}
function fixtureId(f){return text(f?.id??f?.fixture_id??f?.fixture?.id??null)}
function kickoffUtc(f){return text(f?.kickoff_utc??f?.kickoffUtc??f?.start_time??f?.kickoff??f?.date??null)}
function plainObject(v){return Boolean(v)&&typeof v==='object'&&!Array.isArray(v)}
function deepKeep(base,extra){if(extra===null||extra===undefined)return base;if(base===null||base===undefined)return extra;if(Array.isArray(base)||Array.isArray(extra))return Array.isArray(extra)&&extra.length?extra:base;if(plainObject(base)&&plainObject(extra)){const out={...base};for(const [k,v] of Object.entries(extra))out[k]=deepKeep(out[k],v);return out}return extra}
function bookmakerKey(v,i=0){return String(v?.id??v?.slug??v?.name??v?.bookmaker?.id??v?.bookmaker?.slug??v?.bookmaker?.name??`#${i}`).toLowerCase().replace(/[\s_-]/g,'')}
function mergeBookmakers(base,extra){const out=Array.isArray(base)?base.map(x=>plainObject(x)?{...x}:x):[];const pos=new Map(out.map((x,i)=>[bookmakerKey(x,i),i]));for(const [i,row] of (Array.isArray(extra)?extra:[]).entries()){const key=bookmakerKey(row,i),at=pos.get(key);if(at===undefined){pos.set(key,out.length);out.push(row)}else out[at]=deepKeep(out[at],row)}return out}
function providerOddsRaw(f){const out={};if(f?.bookmakers!==undefined&&f?.bookmakers!==null)out.bookmakers=f.bookmakers;if(f?.bet365!==undefined&&f?.bet365!==null)out.bet365=f.bet365;if(f?.markets!==undefined&&f?.markets!==null)out.markets=f.markets;if(f?.odds!==undefined&&f?.odds!==null)out.odds=f.odds;return Object.keys(out).length?out:null}
function mergeProviderOdds(base,extra){if(!base)return extra;if(!extra)return base;const out={...base};for(const [k,v] of Object.entries(extra)){if(v===null||v===undefined)continue;out[k]=k==='bookmakers'&&Array.isArray(v)?mergeBookmakers(out[k],v):deepKeep(out[k],v)}return out}
function boardState(status,statusCode){const s=`${status||''} ${statusCode||''}`.toLowerCase();if(/unknown/.test(s))return'unknown';if(/finished|full_time|full time|\bft\b|ended|\bfull\b/.test(s))return'finished';if(/in_play|in play|live|half/.test(s)||/^\d+$/.test(String(statusCode||'')))return'live';return'scheduled'}
function normalize(f){const id=fixtureId(f),status=text(f?.status?.name??f?.status??null),statusReason=text(f?.status_reason??f?.status?.reason??null),statusCode=text(f?.status_code??f?.status?.code??f?.status?.short??null),minute=finite(f?.minute??f?.elapsed??f?.status?.minute??f?.status?.elapsed??statusCode),kickoff=kickoffUtc(f);return {fixtureId:id,league:league(f),home:team(f,'home'),away:team(f,'away'),kickoffUtc:kickoff,kickoffAt:kickoff&&Number.isFinite(Date.parse(kickoff))?Date.parse(kickoff):finite(f?.kickoff_ts??f?.start_time)?finite(f?.kickoff_ts??f?.start_time)*1000:null,status,statusReason,statusCode,boardState:boardState(status,statusCode),minute,goals:score(f?.goals??f?.score),corners:score(f?.corners),cards:cards(f?.cards),statistics:statistics(f?.statistics??f?.stats??null),events:Array.isArray(f?.events)?f.events:null,providerOdds:providerOddsRaw(f),providerOddsUpdatedAt:providerOddsRaw(f)?now():null}}
function extract(payload){if(Array.isArray(payload?.data))return payload.data;if(Array.isArray(payload?.data?.data))return payload.data.data;if(Array.isArray(payload?.fixtures))return payload.fixtures;return []}
function pageInfo(payload){const p=payload?.pagination??payload?.meta?.pagination??payload?.meta??{};const raw=p?.has_more??p?.hasMore??payload?.has_more??payload?.hasMore??false;return {hasMore:raw===true||raw===1||raw==='1'||raw==='true'}}
function providerRate(response,startedAt){const limit=finite(response.headers.get('x-ratelimit-limit')??response.headers.get('x-ratelimit-requests-limit'));const remaining=finite(response.headers.get('x-ratelimit-remaining')??response.headers.get('x-ratelimit-requests-remaining'));const reset=finite(response.headers.get('x-ratelimit-reset'));const retryAfterSec=finite(response.headers.get('retry-after'));return {limit,remaining,reset,retryAfterSec,observedAt:now(),status:response.status,durationMs:Math.max(0,now()-startedAt),headerAvailable:limit!==null||remaining!==null||reset!==null}}
async function fetchJson(url,key){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),TIMEOUT_MS),startedAt=now();try{const r=await fetch(url,{cache:'no-store',signal:ac.signal,headers:{accept:'application/json',authorization:`Bearer ${key}`}});const rate=providerRate(r,startedAt),raw=await r.text();let j=null;try{j=JSON.parse(raw)}catch{}if(!r.ok){const e=new Error(`provider:HTTP_${r.status}`);e.status=r.status;e.retryAfter=rate.retryAfterSec;e.rate=rate;throw e}if(!j||typeof j!=='object'){const e=new Error('provider:INVALID_JSON');e.status=r.status;e.rate=rate;throw e}return {json:j,rate}}catch(e){if(e?.name==='AbortError'){const x=new Error('provider:TIMEOUT');x.status=0;throw x}throw e}finally{clearTimeout(timer)}}
async function fetchPages(env,query,perPage,maxPages,onRequest,kind){if(!env.FIVEDOLLAR_API_KEY)throw new Error('provider:FIVEDOLLAR_API_KEY_MISSING');const rows=[];let page=1,hasMore=false,lastRate=null;do{if(onRequest)await onRequest(kind);const join=query?`&${query}`:'';const out=await fetchJson(`${API_BASE}/fixtures?per_page=${perPage}&page=${page}${join}`,env.FIVEDOLLAR_API_KEY);lastRate=out.rate;rows.push(...extract(out.json));hasMore=pageInfo(out.json).hasMore;page+=1}while(hasMore&&page<=maxPages);return {rows,requests:page-1,guardHit:hasMore&&page>maxPages,lastRate}}
function bangkokWindow(ms=now()){const shift=7*3600_000,d=new Date(ms+shift);const start=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-shift;return {startMs:start,endMs:start+86_400_000,start:Math.floor(start/1000),end:Math.floor((start+86_400_000)/1000)}}
async function fetchFullProvider(env,onRequest){const w=bangkokWindow(),include='odds,events,stats';const today=await fetchPages(env,`start_time=${w.start}&end_time=${w.end}&status=all&include=${include}`,TODAY_PAGE_SIZE,TODAY_MAX_PAGES,onRequest,'FULL_SCHEDULE_TODAY');const live=await fetchPages(env,`status=live&include=${include}`,LIVE_PAGE_SIZE,LIVE_MAX_PAGES,onRequest,'FULL_SCHEDULE_LIVE');const requests=today.requests+live.requests;if(requests>SCHEDULE_MAX_REQUESTS)throw new Error(`provider:REQUEST_BUDGET_${requests}`);return {today,live,window:w,include,requests,rate:live.lastRate??today.lastRate??null}}
async function fetchLiveProvider(env,onRequest){const include='odds,events,stats';const live=await fetchPages(env,`status=live&include=${include}`,LIVE_PAGE_SIZE,LIVE_MAX_PAGES,onRequest,'LIVE_CORE');if(live.requests>LIVE_CORE_REQUESTS)throw new Error(`provider:LIVE_CORE_BUDGET_${live.requests}`);return {live,include,requests:live.requests,rate:live.lastRate??null}}
function merge(base,extra){if(!base)return extra;if(!extra)return base;return {...base,...extra,league:{...(base.league||{}),...(extra.league||{})},home:{...(base.home||{}),...(extra.home||{})},away:{...(base.away||{}),...(extra.away||{})},kickoffUtc:extra.kickoffUtc??base.kickoffUtc,kickoffAt:extra.kickoffAt??base.kickoffAt,goals:extra.goals??base.goals,corners:extra.corners??base.corners,cards:extra.cards??base.cards,statistics:extra.statistics??base.statistics,events:extra.events??base.events,providerOdds:mergeProviderOdds(base.providerOdds,extra.providerOdds),providerOddsUpdatedAt:extra.providerOdds?(extra.providerOddsUpdatedAt??now()):base.providerOddsUpdatedAt}}
function chunks(rows){const out=[];let cur=[];for(const row of rows){const next=[...cur,row];if(cur.length&&encoder.encode(JSON.stringify(next)).byteLength>CHUNK_BYTES){out.push(cur);cur=[row]}else cur=next}if(cur.length||!out.length)out.push(cur);return out}
function usedInWindow(rate){const limit=finite(rate?.limit),remaining=finite(rate?.remaining);return limit!==null&&remaining!==null?Math.max(0,limit-remaining):null}
function scheduleAverageRpm(){return round1(SCHEDULE_MAX_REQUESTS*(60/(SCHEDULE_REFRESH_MS/1000)))}
function liveCoreRpm(intervalSec){return Number(intervalSec)<120?round1(LIVE_CORE_REQUESTS*(60/Number(intervalSec))):0}
function projectedTotalRpm(intervalSec){return round1(scheduleAverageRpm()+liveCoreRpm(intervalSec))}
function projectedPeakRpm(intervalSec){return Number(intervalSec)<120?round1(SCHEDULE_MAX_REQUESTS+liveCoreRpm(intervalSec)):SCHEDULE_MAX_REQUESTS}
function riskZone(rpm){return rpm<=20?'GREEN':rpm<=28?'YELLOW':rpm<=34?'RED':'PROTECT'}
function modeView(sec){const live=liveCoreRpm(sec),schedule=scheduleAverageRpm(),total=projectedTotalRpm(sec),peak=projectedPeakRpm(sec);return {intervalSec:sec,liveRequestsPerMinute:live,scheduleAverageRequestsPerMinute:schedule,projectedTotalRequestsPerMinute:total,projectedPeakMinuteRequests:peak,riskZone:riskZone(total),allowed:peak<ACCOUNT_LIMIT_PER_MINUTE}}

export class FiveUsdHub{
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.refreshPromise=null;this.livePromise=null}
  async meta(){return await this.ctx.storage.get('meta')||null}
  async state(){return await this.ctx.storage.get('state')||{lastAttemptAt:null,lastSuccessAt:null,lastScheduleAttemptAt:null,lastScheduleSuccessAt:null,lastLiveAttemptAt:null,lastLiveSuccessAt:null,lastError:null,lastRateLimitAt:null,retryAfterSec:null,providerRate:null}}
  async ledger(){const rows=await this.ctx.storage.get('requestLedger');return Array.isArray(rows)?rows:[]}
  async recordRequest(kind){const t=now(),rows=(await this.ledger()).filter(x=>finite(x?.at)!==null&&t-Number(x.at)<=LEDGER_RETENTION_MS);rows.push({at:t,kind:String(kind||'UNKNOWN'),count:1});await this.ctx.storage.put('requestLedger',rows)}
  async ledgerView(rate){const t=now(),rows=(await this.ledger()).filter(x=>finite(x?.at)!==null&&t-Number(x.at)<=LEDGER_RETENTION_MS);const reset=finite(rate?.reset),resetMs=reset===null?null:reset*1000;const windowStart=resetMs!==null&&Math.abs(resetMs-t)<120_000?resetMs-60_000:t-60_000;const inWindow=rows.filter(x=>Number(x.at)>=windowStart&&Number(x.at)<=t);const breakdown={};for(const x of inWindow)breakdown[x.kind]=(breakdown[x.kind]||0)+Number(x.count||1);const localKnownUsed=inWindow.reduce((sum,x)=>sum+Number(x.count||1),0);return {windowStartAt:windowStart,windowResetAt:resetMs,localKnownUsed,breakdown,recent:rows.slice(-60)}}
  async control(){const c=await this.ctx.storage.get('control')||{};const intervalSec=ALLOWED_INTERVALS_SEC.includes(Number(c.intervalSec))?Number(c.intervalSec):120;return {enabled:c.enabled!==false,intervalSec,updatedAt:c.updatedAt??null}}
  async controlView(){const c=await this.control(),mode=modeView(c.intervalSec);return {ok:true,version:VERSION,enabled:c.enabled,intervalSec:c.intervalSec,refreshMs:c.intervalSec*1000,allowedIntervalsSec:ALLOWED_INTERVALS_SEC,modes:ALLOWED_INTERVALS_SEC.map(modeView),livePageSize:LIVE_PAGE_SIZE,liveRequestsPerCycle:LIVE_CORE_REQUESTS,scheduleIntervalSec:SCHEDULE_REFRESH_MS/1000,scheduleMaxRequestsPerCycle:SCHEDULE_MAX_REQUESTS,projectedLiveRequestsPerMinute:mode.liveRequestsPerMinute,projectedScheduleAverageRequestsPerMinute:mode.scheduleAverageRequestsPerMinute,projectedTotalRequestsPerMinute:mode.projectedTotalRequestsPerMinute,projectedPeakMinuteRequests:mode.projectedPeakMinuteRequests,projectedKnownRequestsPerMinute:mode.projectedTotalRequestsPerMinute,accountLimitPerMinute:ACCOUNT_LIMIT_PER_MINUTE,riskZone:mode.riskZone,safe:mode.allowed,updatedAt:c.updatedAt}}
  async scheduleNext(c){if(!c?.enabled||Number(c.intervalSec)>=120){try{await this.ctx.storage.deleteAlarm()}catch{}return}const s=await this.state();let delay=Math.max(2000,Number(c.intervalSec)*1000);const retry=finite(s.retryAfterSec),last429=finite(s.lastRateLimitAt);if(retry!==null&&last429!==null&&now()-last429<Math.max(60_000,retry*1000))delay=Math.max(delay,retry*1000);await this.ctx.storage.setAlarm(now()+delay)}
  async setControl(payload){const current=await this.control(),intervalSec=ALLOWED_INTERVALS_SEC.includes(Number(payload?.intervalSec))?Number(payload.intervalSec):current.intervalSec,enabled=payload?.enabled===undefined?current.enabled:Boolean(payload.enabled),mode=modeView(intervalSec);if(enabled&&!mode.allowed)return {ok:false,error:'UNSAFE_PROJECTED_LOAD',message:`${intervalSec}s can reach ${mode.projectedPeakMinuteRequests} req/min, at/above Ultra ${ACCOUNT_LIMIT_PER_MINUTE}/min`,...mode,accountLimitPerMinute:ACCOUNT_LIMIT_PER_MINUTE};const next={enabled,intervalSec,updatedAt:now()};await this.ctx.storage.put('control',next);await this.scheduleNext(next);return await this.controlView()}
  async readRows(meta){if(!meta)return[];const out=[];for(let i=0;i<Number(meta.chunkCount||0);i++){const raw=await this.ctx.storage.get(`snapshot:${meta.snapshotId}:${i}`);if(!raw)continue;try{const rows=JSON.parse(raw);if(Array.isArray(rows))out.push(...rows)}catch{}}return out}
  async writeSnapshot(rows,oldMeta,patch){const savedAt=now(),dataChunks=chunks(rows),snapshotId=savedAt.toString(36);for(let i=0;i<dataChunks.length;i++)await this.ctx.storage.put(`snapshot:${snapshotId}:${i}`,JSON.stringify(dataChunks[i]));const counts={scheduled:rows.filter(x=>x.boardState==='scheduled').length,live:rows.filter(x=>x.boardState==='live').length,finished:rows.filter(x=>x.boardState==='finished').length,unknown:rows.filter(x=>x.boardState==='unknown').length};const meta={...(oldMeta||{}),version:VERSION,fetchedAt:savedAt,snapshotId,chunkCount:dataChunks.length,fixtureCount:rows.length,counts,...patch};await this.ctx.storage.put('meta',meta);if(oldMeta?.snapshotId&&oldMeta.snapshotId!==snapshotId){for(let i=0;i<Number(oldMeta.chunkCount||0);i++)await this.ctx.storage.delete(`snapshot:${oldMeta.snapshotId}:${i}`)}return meta}
  async markSuccess(patch,rate){const s=await this.state();await this.ctx.storage.put('state',{...s,...patch,lastAttemptAt:patch.lastAttemptAt??s.lastAttemptAt,lastSuccessAt:patch.lastSuccessAt??s.lastSuccessAt,lastError:null,retryAfterSec:null,providerRate:rate??s.providerRate??null})}
  async markError(e,attempt,kind){const s=await this.state(),status=Number(e?.status||0),retryAfter=finite(e?.retryAfter??e?.rate?.retryAfterSec);await this.ctx.storage.put('state',{...s,lastAttemptAt:attempt,lastError:String(e?.message||e),lastRateLimitAt:status===429?attempt:s.lastRateLimitAt??null,retryAfterSec:status===429?(retryAfter??10):s.retryAfterSec??null,providerRate:e?.rate??s.providerRate??null,[kind==='LIVE_CORE'?'lastLiveAttemptAt':'lastScheduleAttemptAt']:attempt})}
  async refreshFull(){if(this.refreshPromise)return this.refreshPromise;this.refreshPromise=(async()=>{const attempt=now(),oldMeta=await this.meta(),oldRows=await this.readRows(oldMeta);try{const p=await fetchFullProvider(this.env,k=>this.recordRequest(k));const map=new Map();for(const raw of p.today.rows){const n=normalize(raw);if(n.fixtureId)map.set(n.fixtureId,n)}for(const old of oldRows){if(map.has(old.fixtureId))map.set(old.fixtureId,merge(old,map.get(old.fixtureId)))}for(const raw of p.live.rows){const n=normalize(raw);if(n.fixtureId)map.set(n.fixtureId,merge(map.get(n.fixtureId),n))}const rows=[...map.values()].sort((a,b)=>(a.kickoffAt??0)-(b.kickoffAt??0));const completed=now(),meta=await this.writeSnapshot(rows,oldMeta,{scheduleFetchedAt:completed,liveFetchedAt:completed,lastCycleType:'FULL_SCHEDULE',providerRequestCount:p.requests,providerRequestBudget:SCHEDULE_MAX_REQUESTS,todayRequests:p.today.requests,liveRequests:p.live.requests,guardHit:Boolean(p.today.guardHit||p.live.guardHit),include:p.include,todayWindow:{start:p.window.start,end:p.window.end,timeZone:'Asia/Bangkok'}});await this.markSuccess({lastAttemptAt:attempt,lastSuccessAt:completed,lastScheduleAttemptAt:attempt,lastScheduleSuccessAt:completed,lastLiveSuccessAt:completed},p.rate);return meta}catch(e){await this.markError(e,attempt,'FULL_SCHEDULE');if(oldMeta)return oldMeta;throw e}})().finally(()=>{this.refreshPromise=null});return this.refreshPromise}
  async refreshLive(){if(this.livePromise)return this.livePromise;this.livePromise=(async()=>{const attempt=now(),oldMeta=await this.meta();if(!oldMeta)return await this.refreshFull();const oldRows=await this.readRows(oldMeta);try{const p=await fetchLiveProvider(this.env,k=>this.recordRequest(k)),map=new Map(oldRows.map(x=>[String(x.fixtureId),x]));for(const raw of p.live.rows){const n=normalize(raw);if(n.fixtureId)map.set(String(n.fixtureId),merge(map.get(String(n.fixtureId)),n))}const rows=[...map.values()].sort((a,b)=>(a.kickoffAt??0)-(b.kickoffAt??0));const completed=now(),meta=await this.writeSnapshot(rows,oldMeta,{liveFetchedAt:completed,lastCycleType:'LIVE_CORE',providerRequestCount:p.requests,providerRequestBudget:LIVE_CORE_REQUESTS,liveRequests:p.live.requests,guardHit:Boolean(p.live.guardHit),include:p.include});await this.markSuccess({lastAttemptAt:attempt,lastSuccessAt:completed,lastLiveAttemptAt:attempt,lastLiveSuccessAt:completed},p.rate);return meta}catch(e){await this.markError(e,attempt,'LIVE_CORE');return oldMeta}})().finally(()=>{this.livePromise=null});return this.livePromise}
  async refreshFullIfDue(force=false){const m=await this.meta(),last=finite(m?.scheduleFetchedAt??m?.fetchedAt);if(!force&&last!==null&&now()-last<SCHEDULE_REFRESH_MS-500)return m;return await this.refreshFull()}
  async refreshLiveIfDue(){const c=await this.control(),m=await this.meta();if(!c.enabled||c.intervalSec>=120)return m;if(!m)return await this.refreshFull();const last=finite(m?.liveFetchedAt??m?.fetchedAt);if(last!==null&&now()-last<Math.max(1000,c.intervalSec*1000-250))return m;return await this.refreshLive()}
  async snapshot(){const c=await this.control(),m=await this.meta(),s=await this.state();if(!m)return {ok:false,version:VERSION,error:s.lastError||'NO_SNAPSHOT',control:await this.controlView()};const rows=await this.readRows(m),ageMs=Math.max(0,now()-Number(m.fetchedAt||0)),scheduleAgeMs=m.scheduleFetchedAt?Math.max(0,now()-Number(m.scheduleFetchedAt)):null,liveAgeMs=m.liveFetchedAt?Math.max(0,now()-Number(m.liveFetchedAt)):ageMs,rate=s.providerRate??null,ledger=await this.ledgerView(rate),providerUsed=usedInWindow(rate),unknown=providerUsed===null?null:Math.max(0,providerUsed-ledger.localKnownUsed);return {ok:true,version:VERSION,provider:'5DollarFootballAPI',fetchedAt:m.fetchedAt,ageMs,scheduleAgeMs,liveAgeMs,stale:ageMs>Math.max(STALE_MS,c.intervalSec*3000),fixtureCount:rows.length,counts:m.counts,lastCycleType:m.lastCycleType,providerRequestCount:m.providerRequestCount,providerRequestBudget:m.providerRequestBudget,todayRequests:m.todayRequests,liveRequests:m.liveRequests,guardHit:m.guardHit,include:m.include,todayWindow:m.todayWindow,lastAttemptAt:s.lastAttemptAt,lastSuccessAt:s.lastSuccessAt,lastScheduleAttemptAt:s.lastScheduleAttemptAt,lastScheduleSuccessAt:s.lastScheduleSuccessAt,lastLiveAttemptAt:s.lastLiveAttemptAt,lastLiveSuccessAt:s.lastLiveSuccessAt,lastError:s.lastError,lastRateLimitAt:s.lastRateLimitAt??null,retryAfterSec:s.retryAfterSec??null,providerRate:rate,providerUsedInWindow:providerUsed,localKnownUsedInWindow:ledger.localKnownUsed,unexplainedUsedInWindow:unknown,requestBreakdown:ledger.breakdown,estimatedKnownRequestsPerMinute:projectedTotalRpm(c.intervalSec),control:await this.controlView(),fixtures:rows}}
  async health(){const c=await this.control(),m=await this.meta(),s=await this.state(),rate=s.providerRate??null,observedAt=finite(rate?.observedAt),providerLimit=finite(rate?.limit),providerRemaining=finite(rate?.remaining),providerUsed=usedInWindow(rate),ledger=await this.ledgerView(rate),unknown=providerUsed===null?null:Math.max(0,providerUsed-ledger.localKnownUsed),ageMs=m?.fetchedAt?Math.max(0,now()-m.fetchedAt):null,scheduleAgeMs=m?.scheduleFetchedAt?Math.max(0,now()-m.scheduleFetchedAt):null,liveAgeMs=m?.liveFetchedAt?Math.max(0,now()-m.liveFetchedAt):ageMs;return {ok:Boolean(m),component:'5USD_HUB',version:VERSION,architecture:'LIVE_CORE_1_CALL_PER_CYCLE',livePageSize:LIVE_PAGE_SIZE,fixtureCount:m?.fixtureCount??0,counts:m?.counts??{scheduled:0,live:0,finished:0,unknown:0},fetchedAt:m?.fetchedAt??null,ageMs,scheduleAgeMs,liveAgeMs,stale:ageMs===null||ageMs>Math.max(STALE_MS,c.intervalSec*3000),refreshMs:c.intervalSec*1000,lastCycleType:m?.lastCycleType??null,providerRequestCount:m?.providerRequestCount??0,providerRequestBudget:m?.providerRequestBudget??0,estimatedKnownRequestsPerMinute:projectedTotalRpm(c.intervalSec),projectedLiveRequestsPerMinute:liveCoreRpm(c.intervalSec),projectedScheduleAverageRequestsPerMinute:scheduleAverageRpm(),projectedPeakMinuteRequests:projectedPeakRpm(c.intervalSec),accountLimitPerMinute:providerLimit??ACCOUNT_LIMIT_PER_MINUTE,providerRateLimit:providerLimit,providerRateRemaining:providerRemaining,providerRateReset:finite(rate?.reset),providerRateObservedAt:observedAt,providerRateAgeMs:observedAt===null?null:Math.max(0,now()-observedAt),providerRateStatus:finite(rate?.status),providerLatencyMs:finite(rate?.durationMs),providerHeadersAvailable:Boolean(rate?.headerAvailable),providerUsedInWindow:providerUsed,localKnownUsedInWindow:ledger.localKnownUsed,unexplainedUsedInWindow:unknown,requestBreakdown:ledger.breakdown,include:m?.include??null,lastAttemptAt:s.lastAttemptAt??null,lastSuccessAt:s.lastSuccessAt??null,lastScheduleAttemptAt:s.lastScheduleAttemptAt??null,lastScheduleSuccessAt:s.lastScheduleSuccessAt??null,lastLiveAttemptAt:s.lastLiveAttemptAt??null,lastLiveSuccessAt:s.lastLiveSuccessAt??null,lastError:s.lastError,lastRateLimitAt:s.lastRateLimitAt??null,retryAfterSec:s.retryAfterSec??null,control:await this.controlView()}}
  async alarm(){const c=await this.control();if(!c.enabled||c.intervalSec>=120)return;try{await this.refreshLiveIfDue()}finally{await this.scheduleNext(await this.control())}}
  async fetch(request){const u=new URL(request.url);if((u.pathname==='/_internal/full-refresh'||u.pathname==='/_internal/refresh')&&request.method==='POST'){try{await this.refreshFullIfDue(true);await this.scheduleNext(await this.control());return new Response(JSON.stringify(await this.health()),{headers:{'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({ok:false,error:String(e?.message||e)}),{status:502,headers:{'content-type':'application/json'}})}}if(u.pathname==='/snapshot')return new Response(JSON.stringify(await this.snapshot()),{headers:{'content-type':'application/json'}});if(u.pathname==='/health')return new Response(JSON.stringify(await this.health()),{headers:{'content-type':'application/json'}});if(u.pathname==='/control'&&request.method==='GET')return new Response(JSON.stringify(await this.controlView()),{headers:{'content-type':'application/json'}});if(u.pathname==='/control'&&request.method==='POST'){let body={};try{body=await request.json()}catch{return new Response(JSON.stringify({ok:false,error:'INVALID_JSON'}),{status:400,headers:{'content-type':'application/json'}})}const out=await this.setControl(body);return new Response(JSON.stringify(out),{status:out.ok===false?409:200,headers:{'content-type':'application/json'}})}return new Response('Not found',{status:404})}
}
function stub(env){return env.HUB.get(env.HUB.idFromName('global'))}
export default{async fetch(request,env){if(request.method==='OPTIONS')return json(request,null,204);const u=new URL(request.url),s=stub(env);if(request.method==='GET'&&u.pathname==='/snapshot'){const r=await s.fetch('https://hub.internal/snapshot');return json(request,await r.json(),r.status)}if(request.method==='GET'&&(u.pathname==='/health'||u.pathname==='/status')){const r=await s.fetch('https://hub.internal/health');return json(request,await r.json(),r.status)}if(request.method==='GET'&&u.pathname==='/control'){const r=await s.fetch('https://hub.internal/control');return json(request,await r.json(),r.status)}if(request.method==='POST'&&u.pathname==='/control'){if(!internalControlAuthorized(request)&&!(await ownerAuthorized(request)))return json(request,{ok:false,error:'OWNER_TOKEN_REQUIRED'},401);const body=await request.text();const r=await s.fetch('https://hub.internal/control',{method:'POST',headers:{'content-type':'application/json'},body});return json(request,await r.json(),r.status)}return json(request,{ok:false,version:VERSION,error:'NOT_FOUND'},404)},async scheduled(_event,env,ctx){ctx.waitUntil(stub(env).fetch('https://hub.internal/_internal/full-refresh',{method:'POST'}))}}