const fs=require('fs');
const path=require('path');
const {chromium}=require('playwright');
const OUT='/tmp/b46-topcard-post-browser'; fs.mkdirSync(OUT,{recursive:true});
async function inspect(browser,viewport,name){
 const ctx=await browser.newContext({viewport,serviceWorkers:'block'}); const page=await ctx.newPage(); const errs=[]; page.on('pageerror',e=>errs.push(String(e)));
 await page.goto('https://www.ball46.com/?topcardactual='+Date.now(),{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForSelector('[data-workspace-scorebar-slot]',{state:'attached',timeout:30000});
 if(viewport.width>760) await page.waitForFunction(()=>document.querySelectorAll('[data-scorebar-details="1"]').length>0,null,{timeout:30000});
 const state=await page.evaluate(()=>{const slot=document.querySelector('[data-workspace-scorebar-slot]'),grid=slot?.querySelector('.workspace-scorebar-grid'),cards=[...(slot?.querySelectorAll('.workspace-scorebar-cell')||[])],pop=cards.filter(c=>!c.classList.contains('placeholder')),r=e=>e?e.getBoundingClientRect():null,c=e=>e?getComputedStyle(e):null;return{display:slot?c(slot).display:null,slotH:r(slot)?.height??null,gridH:r(grid)?.height??null,count:cards.length,details:slot?.querySelectorAll('[data-scorebar-details="1"]').length||0,cards:pop.map(x=>{const cr=r(x),dr=r(x.querySelector('.workspace-scorebar-details')),mr=r(x.querySelector('.workspace-scorebar-meta'));return{text:x.innerText.replace(/\n+/g,' | '),h:cr.height,scrollH:x.scrollHeight,bottom:cr.bottom,detailBottom:dr?.bottom??null,metaOffset:(mr?.top??0)-cr.top}})}});
 if(viewport.width>760){if(state.count!==10)throw Error(name+': count '+state.count);if(state.details<1)throw Error(name+': details missing');if(Math.abs(state.slotH-120)>1.5||Math.abs(state.gridH-118)>1.5)throw Error(name+': geometry '+JSON.stringify(state));for(const x of state.cards){if(Math.abs(x.h-118)>1.5||x.scrollH>x.h+1.5||(x.detailBottom!==null&&x.detailBottom>x.bottom+.75)||x.metaOffset<3||x.metaOffset>9)throw Error(name+': card bad '+JSON.stringify(x));}}else if(state.display!=='none')throw Error(name+': mobile scorebar changed');
 await page.screenshot({path:path.join(OUT,name+'.png'),fullPage:false}); return {ctx,page,state,errs};
}
(async()=>{const b=await chromium.launch({headless:true});const report={at:new Date().toISOString(),production:true,views:{}};try{const d=await inspect(b,{width:1440,height:900},'desktop-1440');report.views.desktop=d.state;const before=await d.page.locator('[data-workspace-scorebar-slot]').innerHTML();await d.page.locator('[data-stat-market="all"]').click();await d.page.waitForSelector('[data-workspace-panel="statistics"]:not([hidden])',{timeout:10000});const st=await d.page.locator('[data-workspace-scorebar-slot]').innerHTML();if(!st.includes('data-scorebar-details="1"'))throw Error('statistics lost details');report.sharedAcrossStatistics=before===st;await d.page.screenshot({path:path.join(OUT,'desktop-statistics-1440.png'),fullPage:false});await d.page.locator('[data-workspace-view="signal"]').click();await d.page.waitForTimeout(300);const sg=await d.page.locator('[data-workspace-scorebar-slot]').innerHTML();if(!sg.includes('data-scorebar-details="1"'))throw Error('signal lost details');report.sharedAcrossSignal=before===sg;await d.page.screenshot({path:path.join(OUT,'desktop-signal-1440.png'),fullPage:false});await d.ctx.close();const t=await inspect(b,{width:1000,height:850},'tablet-1000');report.views.tablet=t.state;await t.ctx.close();const m=await inspect(b,{width:390,height:844},'mobile-390');report.views.mobile=m.state;await m.ctx.close();fs.writeFileSync(path.join(OUT,'report.json'),JSON.stringify(report,null,2));console.log('POST_BROWSER_PASS',JSON.stringify(report));}finally{await b.close();}})().catch(e=>{fs.writeFileSync(path.join(OUT,'error.txt'),String(e.stack||e));console.error(e.stack||e);process.exit(1)});
