from pathlib import Path

html_path=Path('nomad-live-343/statistics.html')
js_path=Path('nomad-live-343/statistics-next.js')
html=html_path.read_text()
js=js_path.read_text()

# Presentation-only stylesheet.
needle='<link rel="stylesheet" href="content-rails-343.css?v=343-content-rails-v1">'
insert=needle+'\n<link rel="stylesheet" href="statistics-performance.css?v=343-stat-market-ceo-v1">'
if 'statistics-performance.css?v=343-stat-market-ceo-v1' not in html:
    if needle not in html: raise SystemExit('STAT_CSS_INSERT_POINT_MISSING')
    html=html.replace(needle,insert,1)

# CEO performance section before market cards.
market_section='  <section class="next-market-strip" data-next-stat-markets></section>'
ceo_section='''  <section class="ceo-performance-shell" data-ceo-performance>
    <article class="ceo-performance-card">
      <div class="ceo-performance-head">
        <div><span class="ceo-kicker">SPECIAL STRATEGY</span><h2>CEO · ADD K PERFORMANCE</h2><p>Settled results generated by the CEO strategy only.</p></div>
        <span class="ceo-sample-badge" data-ceo-sample>Building sample</span>
      </div>
      <div class="ceo-performance-body" data-ceo-performance-body><div class="next-empty">Waiting for settled CEO results…</div></div>
    </article>
  </section>

  <div class="market-performance-title"><div><span>MARKET PERFORMANCE</span><h2>Accuracy by Market</h2></div><small>W/L includes half outcomes · Push excluded from Win Rate</small></div>
  <section class="market-performance-grid" data-next-stat-markets></section>'''
if 'CEO · ADD K PERFORMANCE' not in html:
    if market_section not in html: raise SystemExit('MARKET_SECTION_MISSING')
    html=html.replace(market_section,ceo_section,1)

html=html.replace('statistics-next.js?v=343-next-production-v2-team-flow','statistics-next.js?v=343-stat-market-ceo-v1')
html_path.write_text(html)

old="""function avgOdds(rows){const vals=rows.map(r=>num(r?.odds)).filter(v=>v!==null&&v>1);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}\nfunction renderMarkets(j){const el=document.querySelector('[data-next-stat-markets]');if(!el)return;const defs=j?.markets||{},counts=j?.byMarket||{};el.innerHTML=Object.entries(defs).map(([k,d])=>`<div class=\"next-market-item\"><span>${esc(d?.label||k)}</span><strong>${esc(counts[k]||0)}</strong><small>${esc(d?.provider||'Bet365')} · ${esc(d?.period||'FT')}</small></div>`).join('')}"""
new="""function avgOdds(rows){const vals=rows.map(r=>num(r?.odds)).filter(v=>v!==null&&v>1);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}\nfunction outcomeSummary(rows){\n  const settled=(Array.isArray(rows)?rows:[]).filter(r=>String(r?.status||'SETTLED').toUpperCase()==='SETTLED');\n  const n=x=>settled.filter(r=>String(r?.result||'').toUpperCase()===x).length;\n  const win=n('WIN'),halfWin=n('HALF_WIN'),loss=n('LOSS'),halfLoss=n('HALF_LOSS'),push=n('PUSH');\n  const decision=win+halfWin+loss+halfLoss;\n  const winRate=decision?((win+.5*halfWin)/decision)*100:null;\n  const profit=settled.reduce((sum,r)=>{const o=num(r?.odds),x=String(r?.result||'').toUpperCase();if(o===null||o<=1)return sum;if(x==='WIN')return sum+(o-1);if(x==='HALF_WIN')return sum+(o-1)/2;if(x==='LOSS')return sum-1;if(x==='HALF_LOSS')return sum-.5;return sum},0);\n  const roi=settled.length?profit/settled.length*100:null;\n  return {settled:settled.length,win,halfWin,loss,halfLoss,push,w:win+halfWin,l:loss+halfLoss,winRate,avgOdds:avgOdds(settled),profit,roi};\n}\nconst pct=v=>v===null||v===undefined?'—':`${v.toFixed(1)}%`;\nconst oddsFmt=v=>v===null||v===undefined?'—':v.toFixed(2);\nconst roiFmt=v=>v===null||v===undefined?'—':`${v>=0?'+':''}${v.toFixed(1)}%`;\nfunction resultBar(m){const total=m.w+m.l+m.push;if(!total)return'<div class=\"market-result-bar empty\"></div>';const w=m.w/total*100,l=m.l/total*100,p=m.push/total*100;return`<div class=\"market-result-bar\" aria-label=\"Win ${w.toFixed(0)} percent, loss ${l.toFixed(0)} percent, push ${p.toFixed(0)} percent\"><i class=\"w\" style=\"width:${w}%\"></i><i class=\"l\" style=\"width:${l}%\"></i><i class=\"p\" style=\"width:${p}%\"></i></div>`}\nfunction marketCard(key,d,rows){const m=outcomeSummary(rows),has=m.settled>0,half=m.halfWin||m.halfLoss?`<small class=\"market-half\">HW ${m.halfWin} · HL ${m.halfLoss}</small>`:'';return`<article class=\"market-performance-card${has?'':' empty'}\"><div class=\"market-performance-head\"><div><span>${esc(d?.period||'FT')}</span><h3>${esc(d?.label||key)}</h3></div><strong>${has?pct(m.winRate):'—'}</strong></div><div class=\"market-wlp\"><span class=\"win\"><b>${m.w}</b> W</span><span class=\"loss\"><b>${m.l}</b> L</span><span class=\"push\"><b>${m.push}</b> P</span></div>${resultBar(m)}<div class=\"market-meta\"><span><small>Settled</small><b>${m.settled}</b></span><span><small>Avg Odds</small><b>${oddsFmt(m.avgOdds)}</b></span><span><small>ROI</small><b class=\"${(m.roi??0)>=0?'positive':'negative'}\">${roiFmt(m.roi)}</b></span></div>${half}${has?'':'<small class=\"market-no-data\">No settled data yet</small>'}</article>`}\nfunction renderMarkets(j){const el=document.querySelector('[data-next-stat-markets]');if(!el)return;const defs=j?.markets||{},rows=Array.isArray(j?.rows)?j.rows:[];el.innerHTML=Object.entries(defs).map(([k,d])=>marketCard(k,d,rows.filter(r=>r?.market===k))).join('')}\nfunction renderCEO(j){const body=document.querySelector('[data-ceo-performance-body]'),badge=document.querySelector('[data-ceo-sample]');if(!body)return;const all=Array.isArray(j?.rows)?j.rows:[],rows=all.filter(r=>String(r?.strategy||'OWNER').toUpperCase()==='CEO'),m=outcomeSummary(rows);if(badge)badge.textContent=m.settled>=100?'Established sample':m.settled>=30?'Growing sample':'Building sample';const versions=[...new Set(rows.map(r=>r?.strategyVersion).filter(Boolean))];const byMarket=new Map();for(const r of rows){const key=r?.market||'unknown';if(!byMarket.has(key))byMarket.set(key,[]);byMarket.get(key).push(r)}const breakdown=[...byMarket.entries()].map(([key,rs])=>{const x=outcomeSummary(rs);return`<span class=\"ceo-market-chip\"><b>${esc(rs[0]?.marketLabel||key)}</b><em>${pct(x.winRate)}</em><small>${x.w}W ${x.l}L ${x.push}P · ${x.settled}</small></span>`}).join('');body.innerHTML=`<div class=\"ceo-scoreline\"><div><small>WIN RATE</small><strong>${pct(m.winRate)}</strong></div><div class=\"ceo-wlp\"><span class=\"win\"><b>${m.w}</b> WIN</span><span class=\"loss\"><b>${m.l}</b> LOSS</span><span class=\"push\"><b>${m.push}</b> PUSH</span></div></div>${resultBar(m)}<div class=\"ceo-metrics\"><span><small>SETTLED</small><b>${m.settled}</b></span><span><small>AVG ODDS</small><b>${oddsFmt(m.avgOdds)}</b></span><span><small>ROI / YIELD</small><b class=\"${(m.roi??0)>=0?'positive':'negative'}\">${roiFmt(m.roi)}</b></span><span><small>PROFIT</small><b class=\"${m.profit>=0?'positive':'negative'}\">${m.profit>=0?'+':''}${m.profit.toFixed(2)}u</b></span><span><small>VERSION</small><b>${esc(versions.join(' · ')||'v1.0')}</b></span></div><div class=\"ceo-market-breakdown\">${breakdown||'<span class=\"ceo-no-data\">CEO results will appear here after settlement.</span>'}</div><p class=\"ceo-footnote\">Transparent settled record · 1 unit per signal for ROI calculation · Half Win/Loss weighted by settlement result.</p>`}"""
if old not in js: raise SystemExit('STAT_RENDER_BLOCK_MISSING')
js=js.replace(old,new,1)

old_call="set('[data-next-avg-odds]',avg===null?'—':avg.toFixed(2));renderMarkets(j);const body=document.querySelector('[data-next-stat-body]');"
new_call="set('[data-next-avg-odds]',avg===null?'—':avg.toFixed(2));renderCEO(j);renderMarkets(j);const body=document.querySelector('[data-next-stat-body]');"
if old_call not in js: raise SystemExit('STAT_RENDER_CALL_MISSING')
js=js.replace(old_call,new_call,1)
js_path.write_text(js)
print('STAT_MARKET_CEO_PATCH_PASS')
