from pathlib import Path

P=Path('workers/nomadtips3-engine-343/src/index.js')
s=P.read_text()

def once(old,new,label):
    global s
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 match, got {n}')
    s=s.replace(old,new,1)

once("const VERSION='nomad343-engine-v5-settlement-tail';","const VERSION='nomad343-engine-v6-targeted-settlement-recovery';",'version')
once("const MAX_ODDS_FIXTURES_PER_SCAN=4;","const MAX_ODDS_FIXTURES_PER_SCAN=4;\nconst MAX_SETTLEMENT_RECOVERY_PER_SCAN=2;\nconst SETTLEMENT_RECOVERY_MIN_AGE_MS=3*60*60_000;\nconst SETTLEMENT_RECOVERY_RETRY_MS=30*60_000;",'recovery constants')
once("function periodCompleteForSignal(s,f){const def=MARKET_RULES[s?.market];if(!def)return false;return def.period==='HT'?isHalfComplete(f):isFinished(f)}","const LEGACY_SETTLEMENT_MARKETS=Object.freeze({oneXtwo:'ft_1x2',ah:'ft_ah',over:'ft_over',under:'ft_under'});\nfunction settlementMarketKey(key){return MARKET_RULES[key]?key:(LEGACY_SETTLEMENT_MARKETS[key]||key)}\nfunction periodCompleteForSignal(s,f){const def=MARKET_RULES[settlementMarketKey(s?.market)];if(!def)return false;return def.period==='HT'?isHalfComplete(f):isFinished(f)}",'legacy settlement map')
needle="async function fetchRefereeOdds(fixtureId,env){\n  if(!env.FIVEDOLLAR_API_KEY)throw new Error('FIVEDOLLAR_API_KEY_MISSING');"
insert="function recoveryScore(v){return v&&typeof v==='object'?{home:num(v.home),away:num(v.away),halfHome:num(v.half_home??v.halfHome),halfAway:num(v.half_away??v.halfAway)}:{home:null,away:null,halfHome:null,halfAway:null}}\nfunction recoveryCards(v){const side=x=>x&&typeof x==='object'?{yellow:num(x.yellow),red:num(x.red)}:null;return {home:side(v?.home),away:side(v?.away)}}\nfunction recoveryBoardState(status,statusCode){const x=`${status||''} ${statusCode||''}`.toLowerCase();if(/unknown|postpon|cancel|canceled|abandon|suspend/.test(x))return'unknown';if(/finished|full_time|full time|\\bft\\b|ended|\\bfull\\b|after extra|\\baet\\b|penalties|\\bpen\\b/.test(x))return'finished';if(/in_play|in play|live|half|first|second|\\b1h\\b|\\b2h\\b/.test(x)||/^\\d+$/.test(String(statusCode||'')))return'live';return'scheduled'}\nfunction normalizeRecoveryFixture(payload,fallbackId){const f=payload?.data?.id!==undefined?payload.data:(payload?.data?.data??payload?.fixture??payload?.data??payload),status=String(f?.status?.name??f?.status??''),statusCode=String(f?.status_code??f?.status?.code??f?.status?.short??''),fixtureId=String(f?.id??f?.fixture_id??f?.fixture?.id??fallbackId);return {fixtureId,status,statusCode,statusReason:f?.status_reason??f?.status?.reason??null,boardState:recoveryBoardState(status,statusCode),minute:num(f?.minute??f?.elapsed??f?.status?.minute??f?.status?.elapsed),goals:recoveryScore(f?.goals??f?.score),corners:recoveryScore(f?.corners),cards:recoveryCards(f?.cards)}}\nasync function fetchSettlementRecoveryFixture(fixtureId,env){if(!env.FIVEDOLLAR_API_KEY)throw new Error('FIVEDOLLAR_API_KEY_MISSING');const r=await fetch(`${API_BASE}/fixtures/${encodeURIComponent(fixtureId)}`,{cache:'no-store',headers:{accept:'application/json',authorization:`Bearer ${env.FIVEDOLLAR_API_KEY}`}});const raw=await r.text();let j=null;try{j=JSON.parse(raw)}catch{}if(!r.ok){const e=new Error(`5USD_FIXTURE_HTTP_${r.status}`);e.status=r.status;e.retryAfter=num(r.headers.get('retry-after'));throw e}if(!j||typeof j!=='object')throw new Error('5USD_FIXTURE_SHAPE');return normalizeRecoveryFixture(j,fixtureId)}\nconst sleep=ms=>new Promise(r=>setTimeout(r,ms));\n\nasync function fetchRefereeOdds(fixtureId,env){\n  if(!env.FIVEDOLLAR_API_KEY)throw new Error('FIVEDOLLAR_API_KEY_MISSING');"
once(needle,insert,'recovery fetch helper')
once("      const fixtureMap=new Map();for(const f of hub.fixtures||[])fixtureMap.set(String(f.fixtureId),f);for(const f of hub.settlements||[])fixtureMap.set(String(f.fixtureId),f);\n      for(const f of hub.fixtures||[]){","      const fixtureMap=new Map();for(const f of hub.fixtures||[])fixtureMap.set(String(f.fixtureId),f);for(const f of hub.settlements||[])fixtureMap.set(String(f.fixtureId),f);\n      const recoveryState=await this.ctx.storage.get('settlementRecovery')||{},missingById=new Map();for(const sig of signals){if(!['PENDING','UNRESOLVED'].includes(sig.status))continue;const id=String(sig.fixtureId||'');if(!id||fixtureMap.has(id)||!MARKET_RULES[settlementMarketKey(sig.market)])continue;const created=Number(sig.createdAt||0);if(!created||startedAt-created<SETTLEMENT_RECOVERY_MIN_AGE_MS)continue;const cur=missingById.get(id)||{fixtureId:id,newestCreatedAt:0,oldestCreatedAt:created};cur.newestCreatedAt=Math.max(cur.newestCreatedAt,created);cur.oldestCreatedAt=Math.min(cur.oldestCreatedAt,created);missingById.set(id,cur)}const recoveryCandidates=[...missingById.values()].filter(x=>startedAt-Number(recoveryState[x.fixtureId]?.lastAttemptAt||0)>=SETTLEMENT_RECOVERY_RETRY_MS).sort((a,b)=>b.newestCreatedAt-a.newestCreatedAt),recoverySelected=recoveryCandidates.slice(0,MAX_SETTLEMENT_RECOVERY_PER_SCAN);let settlementRecoveryRequests=0,settlementRecoveryRecovered=0,settlementRecoveryErrors=[];for(let i=0;i<recoverySelected.length;i++){const item=recoverySelected[i],id=item.fixtureId;try{settlementRecoveryRequests++;const f=await fetchSettlementRecoveryFixture(id,this.env);recoveryState[id]={lastAttemptAt:now(),state:f.boardState,status:f.status,statusCode:f.statusCode};if(isFinished(f)||isUnknown(f)){fixtureMap.set(id,f);settlementRecoveryRecovered++;recoveryState[id].recoveredAt=now()}}catch(e){recoveryState[id]={lastAttemptAt:now(),state:'ERROR',error:String(e?.message||e)};settlementRecoveryErrors.push({fixtureId:id,error:String(e?.message||e)});if(i+1<recoverySelected.length)await sleep(800)}}const recoveryEntries=Object.entries(recoveryState).sort((a,b)=>Number(b[1]?.lastAttemptAt||0)-Number(a[1]?.lastAttemptAt||0)).slice(0,500);await this.ctx.storage.put('settlementRecovery',Object.fromEntries(recoveryEntries));\n      for(const f of hub.fixtures||[]){",'recovery integration')
once("        const result=settleMarketSignal(s,f);","        const settleKey=settlementMarketKey(s.market),result=settleMarketSignal(settleKey===s.market?s:{...s,market:settleKey},f);",'legacy settle call')
once("referee:{bookmakersRequested:REFEREE_BOOKS.length,canonicalBookmakers:REFEREE_BOOKS.map(x=>x.name),maxFixturesPerScan:MAX_ODDS_FIXTURES_PER_SCAN,requests:refereeRequests,queued:Math.max(0,fixtureCandidates.length-selected.length),errors:refereeErrors}","referee:{bookmakersRequested:REFEREE_BOOKS.length,canonicalBookmakers:REFEREE_BOOKS.map(x=>x.name),maxFixturesPerScan:MAX_ODDS_FIXTURES_PER_SCAN,requests:refereeRequests,queued:Math.max(0,fixtureCandidates.length-selected.length),errors:refereeErrors},settlementRecovery:{maxPerScan:MAX_SETTLEMENT_RECOVERY_PER_SCAN,minAgeMs:SETTLEMENT_RECOVERY_MIN_AGE_MS,retryMs:SETTLEMENT_RECOVERY_RETRY_MS,requests:settlementRecoveryRequests,recovered:settlementRecoveryRecovered,queued:Math.max(0,recoveryCandidates.length-recoverySelected.length),errors:settlementRecoveryErrors}",'recovery telemetry')
P.write_text(s)
print('patched 3.43 targeted settlement recovery: 2 missing fixtures/scan, 3h threshold, 30m retry')
