from pathlib import Path
import re

html_path = Path('nomad-live-343/statistics.html')
js_path = Path('nomad-live-343/statistics-next.js')
html = html_path.read_text()
js = js_path.read_text()

REV = '343-stat-market-ceo-page50-v2'
CSS_REV = '343-stat-market-ceo-page50-v2'

# Keep the patch presentation-only. The existing Statistics and Signal fetches are reused;
# no Odds / Full Market endpoint is introduced here.

# Cache-bust and identify the exact Statistics revision so an older wrapper cannot silently
# keep serving the previous UI after deployment.
html = re.sub(
    r'<meta name="ball46-page-revision" content="[^"]+">',
    f'<meta name="ball46-page-revision" content="{REV}">',
    html,
    count=1,
)

css_link = f'<link rel="stylesheet" href="statistics-performance.css?v={CSS_REV}">'
if 'statistics-performance.css?v=' in html:
    html = re.sub(
        r'<link rel="stylesheet" href="statistics-performance\.css\?v=[^"]+">',
        css_link,
        html,
        count=1,
    )
else:
    needle = '<link rel="stylesheet" href="content-rails-343.css?v=343-content-rails-v1">'
    if needle not in html:
        raise SystemExit('STAT_CSS_INSERT_POINT_MISSING')
    html = html.replace(needle, needle + '\n' + css_link, 1)

# Ensure the CEO performance card exists. If Production is already on a CEO-capable build,
# leave that structure intact; otherwise upgrade the old market strip in place.
ceo_shell = '''  <section class="ceo-performance-shell" data-ceo-performance>
    <article class="ceo-performance-card">
      <div class="ceo-performance-head">
        <div><span class="ceo-kicker">SPECIAL STRATEGY</span><h2>CEO · ADD K PERFORMANCE</h2><p>Settled results generated by the CEO strategy only.</p></div>
        <span class="ceo-sample-badge" data-ceo-sample>Building sample</span>
      </div>
      <div class="ceo-performance-body" data-ceo-performance-body><div class="next-empty">Waiting for settled CEO results…</div></div>
    </article>
  </section>'''
market_grid = '  <section class="market-performance-grid" data-next-stat-markets></section>'
market_title = '''  <div class="market-performance-title"><div><span>MARKET PERFORMANCE</span><h2>Accuracy by Market</h2></div><small>W/L includes half outcomes · Push excluded from Win Rate</small></div>'''
old_market = '  <section class="next-market-strip" data-next-stat-markets></section>'

if 'CEO · ADD K PERFORMANCE' not in html:
    if old_market in html:
        html = html.replace(old_market, ceo_shell + '\n\n' + market_title + '\n' + market_grid, 1)
    elif market_grid in html:
        html = html.replace(market_grid, ceo_shell + '\n\n' + market_grid, 1)
    else:
        raise SystemExit('MARKET_SECTION_MISSING')

# Force the browser to load the matching JS revision.
if 'statistics-next.js?v=' in html:
    html = re.sub(
        r'statistics-next\.js\?v=[^"\']+',
        f'statistics-next.js?v={REV}',
        html,
        count=1,
    )
else:
    raise SystemExit('STAT_JS_SCRIPT_MISSING')

html_path.write_text(html)

# Add the page-size state once. This does not add any network request.
if 'const HISTORY_PAGE_SIZE=50;' not in js:
    marker = 'const POLL=45000;'
    if marker not in js:
        raise SystemExit('STAT_POLL_MARKER_MISSING')
    js = js.replace(
        marker,
        marker + '\nconst HISTORY_PAGE_SIZE=50;\nlet historyPage=1;\nlet lastHistoryRows=[];',
        1,
    )

# Replace the presentation helper block with the known-good CEO/market calculations plus
# client-side Results History pagination. This is intentionally independent of settlement logic.
start = js.find('function avgOdds(')
end = js.find('\nfunction renderStats(', start)
if start < 0 or end < 0:
    raise SystemExit('STAT_PRESENTATION_BLOCK_MISSING')

presentation = r'''function avgOdds(rows){const vals=rows.map(r=>num(r?.odds)).filter(v=>v!==null&&v>1);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function outcomeSummary(rows){
  const settled=(Array.isArray(rows)?rows:[]).filter(r=>String(r?.status||'SETTLED').toUpperCase()==='SETTLED');
  const n=x=>settled.filter(r=>String(r?.result||'').toUpperCase()===x).length;
  const win=n('WIN'),halfWin=n('HALF_WIN'),loss=n('LOSS'),halfLoss=n('HALF_LOSS'),push=n('PUSH');
  const decision=win+halfWin+loss+halfLoss;
  const winRate=decision?((win+.5*halfWin)/decision)*100:null;
  const profit=settled.reduce((sum,r)=>{const o=num(r?.odds),x=String(r?.result||'').toUpperCase();if(o===null||o<=1)return sum;if(x==='WIN')return sum+(o-1);if(x==='HALF_WIN')return sum+(o-1)/2;if(x==='LOSS')return sum-1;if(x==='HALF_LOSS')return sum-.5;return sum},0);
  const roi=settled.length?profit/settled.length*100:null;
  return {settled:settled.length,win,halfWin,loss,halfLoss,push,w:win+halfWin,l:loss+halfLoss,winRate,avgOdds:avgOdds(settled),profit,roi};
}
const pct=v=>v===null||v===undefined?'—':`${v.toFixed(1)}%`;
const oddsFmt=v=>v===null||v===undefined?'—':v.toFixed(2);
const roiFmt=v=>v===null||v===undefined?'—':`${v>=0?'+':''}${v.toFixed(1)}%`;
function resultBar(m){const total=m.w+m.l+m.push;if(!total)return'<div class="market-result-bar empty"></div>';const w=m.w/total*100,l=m.l/total*100,p=m.push/total*100;return`<div class="market-result-bar" aria-label="Win ${w.toFixed(0)} percent, loss ${l.toFixed(0)} percent, push ${p.toFixed(0)} percent"><i class="w" style="width:${w}%"></i><i class="l" style="width:${l}%"></i><i class="p" style="width:${p}%"></i></div>`}
function marketCard(key,d,rows){const m=outcomeSummary(rows),has=m.settled>0,half=m.halfWin||m.halfLoss?`<small class="market-half">HW ${m.halfWin} · HL ${m.halfLoss}</small>`:'';return`<article class="market-performance-card${has?'':' empty'}"><div class="market-performance-head"><div><span>${esc(d?.period||'FT')}</span><h3>${esc(d?.label||key)}</h3></div><strong>${has?pct(m.winRate):'—'}</strong></div><div class="market-wlp"><span class="win"><b>${m.w}</b> W</span><span class="loss"><b>${m.l}</b> L</span><span class="push"><b>${m.push}</b> P</span></div>${resultBar(m)}<div class="market-meta"><span><small>Settled</small><b>${m.settled}</b></span><span><small>Avg Odds</small><b>${oddsFmt(m.avgOdds)}</b></span><span><small>ROI</small><b class="${(m.roi??0)>=0?'positive':'negative'}">${roiFmt(m.roi)}</b></span></div>${half}${has?'':'<small class="market-no-data">No settled data yet</small>'}</article>`}
function renderMarkets(j){const el=document.querySelector('[data-next-stat-markets]');if(!el)return;const defs=j?.markets||{},rows=Array.isArray(j?.rows)?j.rows:[];el.innerHTML=Object.entries(defs).map(([k,d])=>marketCard(k,d,rows.filter(r=>r?.market===k))).join('')}
function renderCEO(j){const body=document.querySelector('[data-ceo-performance-body]'),badge=document.querySelector('[data-ceo-sample]');if(!body)return;const all=Array.isArray(j?.rows)?j.rows:[],rows=all.filter(r=>String(r?.strategy||'OWNER').toUpperCase()==='CEO'),m=outcomeSummary(rows);if(badge)badge.textContent=m.settled>=100?'Established sample':m.settled>=30?'Growing sample':'Building sample';const versions=[...new Set(rows.map(r=>r?.strategyVersion).filter(Boolean))];const byMarket=new Map();for(const r of rows){const key=r?.market||'unknown';if(!byMarket.has(key))byMarket.set(key,[]);byMarket.get(key).push(r)}const breakdown=[...byMarket.entries()].map(([key,rs])=>{const x=outcomeSummary(rs);return`<span class="ceo-market-chip"><b>${esc(rs[0]?.marketLabel||key)}</b><em>${pct(x.winRate)}</em><small>${x.w}W ${x.l}L ${x.push}P · ${x.settled}</small></span>`}).join('');body.innerHTML=`<div class="ceo-scoreline"><div><small>WIN RATE</small><strong>${pct(m.winRate)}</strong></div><div class="ceo-wlp"><span class="win"><b>${m.w}</b> WIN</span><span class="loss"><b>${m.l}</b> LOSS</span><span class="push"><b>${m.push}</b> PUSH</span></div></div>${resultBar(m)}<div class="ceo-metrics"><span><small>SETTLED</small><b>${m.settled}</b></span><span><small>AVG ODDS</small><b>${oddsFmt(m.avgOdds)}</b></span><span><small>ROI / YIELD</small><b class="${(m.roi??0)>=0?'positive':'negative'}">${roiFmt(m.roi)}</b></span><span><small>PROFIT</small><b class="${m.profit>=0?'positive':'negative'}">${m.profit>=0?'+':''}${m.profit.toFixed(2)}u</b></span><span><small>VERSION</small><b>${esc(versions.join(' · ')||'v1.0')}</b></span></div><div class="ceo-market-breakdown">${breakdown||'<span class="ceo-no-data">CEO results will appear here after settlement.</span>'}</div><p class="ceo-footnote">Transparent settled record · 1 unit per signal for ROI calculation · Half Win/Loss weighted by settlement result.</p>`}
function historyRow(s){const league=[s?.league?.country,s?.league?.name].filter(Boolean).join(' · '),m=s?.entryMinute??s?.minute;return`<tr><td>${esc(when(s?.createdAt))}</td><td><span class="match-primary">${esc(s?.home?.name||'—')} — ${esc(s?.away?.name||'—')}</span><span class="sub">${esc(league||'—')}</span></td><td>${esc(show(m))}${m==null?'':"'"}</td><td><span class="match-primary">${esc(s?.marketLabel||s?.market||'—')}</span><span class="sub">${esc(s?.period||'—')}</span></td><td>${esc(selection(s))}</td><td>${esc(lineText(s))}</td><td class="odds-readonly">${esc(show(s?.odds))}</td><td>${esc(s?.bookmaker||'Bet365')}</td><td>${esc(score(s?.entryScore??s?.scoreAt))}</td><td>${esc(score(s?.finalScore))}</td><td>${resultTag(s?.result)}</td></tr>`}
function historyPageTokens(totalPages,current){if(totalPages<=7)return Array.from({length:totalPages},(_,i)=>i+1);if(current<=4)return[1,2,3,4,5,'…',totalPages];if(current>=totalPages-3)return[1,'…',totalPages-4,totalPages-3,totalPages-2,totalPages-1,totalPages];return[1,'…',current-1,current,current+1,'…',totalPages]}
function ensureHistoryPagination(){let nav=document.querySelector('[data-next-stat-pagination]');if(nav)return nav;const wrap=document.querySelector('[data-next-stat-body]')?.closest('.next-table-wrap');if(!wrap)return null;nav=document.createElement('nav');nav.className='history-pagination';nav.setAttribute('data-next-stat-pagination','');nav.setAttribute('aria-label','Results History pages');wrap.insertAdjacentElement('afterend',nav);return nav}
function renderHistoryPagination(total,totalPages,from,to){const nav=ensureHistoryPagination();if(!nav)return;if(totalPages<=1){nav.hidden=true;nav.innerHTML='';return}nav.hidden=false;const tokenHtml=historyPageTokens(totalPages,historyPage).map(p=>p==='…'?'<span class="history-page-gap" aria-hidden="true">…</span>':`<button type="button" class="history-page-btn${p===historyPage?' active':''}" data-history-page="${p}"${p===historyPage?' aria-current="page"':''}>${p}</button>`).join('');nav.innerHTML=`<span class="history-page-summary">${from}–${to} / ${total}</span><div class="history-page-controls"><button type="button" class="history-page-btn nav" data-history-page="${historyPage-1}" ${historyPage<=1?'disabled':''} aria-label="Previous page">‹</button>${tokenHtml}<button type="button" class="history-page-btn nav" data-history-page="${historyPage+1}" ${historyPage>=totalPages?'disabled':''} aria-label="Next page">›</button></div>`;nav.querySelectorAll('button[data-history-page]').forEach(btn=>btn.addEventListener('click',()=>{const next=Number(btn.dataset.historyPage);if(!Number.isFinite(next)||next<1||next>totalPages||next===historyPage)return;historyPage=next;renderHistory(lastHistoryRows);document.querySelector('[data-next-stat-body]')?.closest('.next-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function renderHistory(rows){lastHistoryRows=Array.isArray(rows)?rows:[];const sorted=[...lastHistoryRows].sort((a,b)=>Number(b?.createdAt||0)-Number(a?.createdAt||0));const total=sorted.length,totalPages=Math.max(1,Math.ceil(total/HISTORY_PAGE_SIZE));historyPage=Math.min(Math.max(1,historyPage),totalPages);const start=(historyPage-1)*HISTORY_PAGE_SIZE,end=Math.min(start+HISTORY_PAGE_SIZE,total),pageRows=sorted.slice(start,end),body=document.querySelector('[data-next-stat-body]');if(body)body.innerHTML=pageRows.length?pageRows.map(historyRow).join(''):'<tr><td colspan="11"><div class="next-empty">No settled results yet.</div></td></tr>';renderHistoryPagination(total,totalPages,total?start+1:0,end)}'''

js = js[:start] + presentation + js[end:]

# Replace only the Results History presentation call. CEO and market cards continue to use all
# rows, while the table uses a sorted client-side 50-row slice.
rs = js.find('function renderStats(')
re_ = js.find('\nfunction groupSignals(', rs)
if rs < 0 or re_ < 0:
    raise SystemExit('STAT_RENDER_FUNCTION_MISSING')

render_stats = r'''function renderStats(j){const rows=Array.isArray(j?.rows)?j.rows:[],avg=avgOdds(rows);set('[data-next-total]',j?.total);set('[data-next-win]',j?.win);set('[data-next-loss]',j?.loss);set('[data-next-win-rate]',j?.winRate===null||j?.winRate===undefined?'—':`${j.winRate}%`);set('[data-next-avg-odds]',avg===null?'—':avg.toFixed(2));renderCEO(j);renderMarkets(j);renderHistory(rows);status('live',`Results online · ${esc(j?.settlementRevision||'current rules')}`)}'''
js = js[:rs] + render_stats + js[re_:]

js_path.write_text(js)
print('STAT_MARKET_CEO_PAGE50_PATCH_PASS')
