(()=>{
const FALLBACK='https://nomadtips3-car-livescore.mccarey-supon.workers.dev';let worker=FALLBACK,refresh=30,payload=null,filter='all',timer=null;const expanded=new Set();
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
function age(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return'Updated —';const s=Math.max(0,Math.floor((Date.now()-t)/1000));return s<5?'Updated just now':s<60?`Updated ${s}s ago`:`Updated ${Math.floor(s/60)}m ago`;}
function state(m){if(m.status==='FT')return'FT';if(m.status==='HT')return'HT';if(m.minute)return`${m.minute}'`;return m.statusText&&m.statusText.length<18?m.statusText:'LIVE';}
function metric(m,key,label,suffix=''){const h=num(m?.stats?.[key]?.home),a=num(m?.stats?.[key]?.away);if(h===null||a===null)return'';const max=key==='possession'?Math.max(1,h+a):Math.max(1,h,a);const hw=key==='possession'?h/max*100:h/max*100,aw=key==='possession'?a/max*100:a/max*100;return `<div class="stat"><div class="stat-head"><strong>${esc(h)}${suffix}</strong><span>${esc(label)}</span><strong>${esc(a)}${suffix}</strong></div><div class="tracks"><div class="track"><div class="fill" style="width:${Math.min(100,hw)}%"></div></div><div class="track"><div class="fill" style="width:${Math.min(100,aw)}%"></div></div></div></div>`;}
function details(m){const items=[metric(m,'possession','Possession','%'),metric(m,'attacks','Attacks'),metric(m,'dangerous_attacks','Dangerous attacks'),metric(m,'shots','Shots'),metric(m,'shots_on_target','On target'),metric(m,'corners','Corners')].filter(Boolean);return `<div class="details"><div class="detail-title"><strong>Match statistics</strong><span>${items.length?'Live comparison':'Statistics not available yet'}</span></div><div class="stats">${items.join('')||'<div class="empty">Waiting for detailed statistics.</div>'}</div>${m.sourceUrl?`<a class="source-link" href="${esc(m.sourceUrl)}" target="_blank" rel="noopener noreferrer">View source match page ↗</a>`:''}</div>`;}
function row(m){const id=String(m.id||''),open=expanded.has(id),live=m.status==='LIVE'||m.status==='HT';return `<article class="match ${open?'expanded':''}" data-id="${esc(id)}"><button class="match-toggle" type="button" aria-expanded="${open}"><div class="state ${live?'live':m.status==='HT'?'ht':'ft'}">${esc(state(m))}</div><div class="teams"><div class="team"><span>${esc(m.home||'Home')}</span></div><div class="team"><span>${esc(m.away||'Away')}</span></div></div><div class="score ${live?'live':''}">${esc(m?.score?.home??'—')}<br>${esc(m?.score?.away??'—')}</div><div class="chev">⌄</div></button>${details(m)}</article>`;}
function selected(){const all=Array.isArray(payload?.matches)?payload.matches:[];if(filter==='live')return all.filter(m=>m.status==='LIVE'||m.status==='HT');if(filter==='finished')return all.filter(m=>m.status==='FT');return all;}
function render(){const board=$('#board');if(!board)return;const matches=selected();if(!matches.length){board.innerHTML='<div class="empty">No matches are available for this filter right now.</div>';return;}const groups=new Map();for(const m of matches){const l=m.league||'Football';if(!groups.has(l))groups.set(l,[]);groups.get(l).push(m);}board.innerHTML=[...groups.entries()].map(([league,items])=>`<section class="league"><header class="league-head"><div class="league-name"><i class="league-mark"></i><strong>${esc(league)}</strong></div><small>${items.length} ${items.length===1?'match':'matches'}</small></header>${items.map(row).join('')}</section>`).join('');}
function summary(){const s=payload?.summary||{};$('#liveCount').textContent=s.live??'—';$('#matchCount').textContent=s.matches??'—';$('#leagueCount').textContent=s.leagues??'—';$('#fresh').textContent=age(payload?.generatedAt);}
function online(ok){document.body.classList.toggle('offline',!ok);$('#feedState').textContent=ok?'Live data':'Feed unavailable';}
async function load(){try{const r=await fetch(`${worker}/scores`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!data?.ok)throw new Error(data?.error||'Feed unavailable');payload=data;online(true);const n=$('#notice');if(data.summary?.capturedIds===0){n.hidden=false;n.textContent='No active match IDs were returned by the source in this cycle.';}else{n.hidden=true;n.textContent='';}summary();render();}catch(e){online(false);const n=$('#notice');n.hidden=false;n.textContent=`Live score feed is temporarily unavailable. ${e.message||e}`;if(!payload)$('#board').innerHTML='<div class="empty">Waiting for the live score service.</div>';}}
function bind(){$('#filters').addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render();});$('#board').addEventListener('click',e=>{const b=e.target.closest('.match-toggle');if(!b)return;const a=b.closest('.match');const id=String(a.dataset.id||'');if(expanded.has(id))expanded.delete(id);else expanded.add(id);a.classList.toggle('expanded',expanded.has(id));b.setAttribute('aria-expanded',expanded.has(id));});}
async function boot(){try{const r=await fetch('./runtime.json',{cache:'no-store'});const cfg=await r.json();worker=cfg.workerUrl||worker;refresh=Math.max(15,Number(cfg.refreshSeconds)||30);}catch{}bind();await load();timer=setInterval(load,refresh*1000);setInterval(()=>{if(payload)$('#fresh').textContent=age(payload.generatedAt)},1000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
