const $=id=>document.getElementById(id);
let filter='ALL';
let lastMatches=[];
let seconds=10;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
const fmtOdds=v=>Number.isFinite(Number(v))?Number(v).toFixed(2):'—';
const fmtTime=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v))}catch{return'—'}};
const score=m=>`${Number(m?.score?.home)||0} - ${Number(m?.score?.away)||0}`;
const minute=m=>Number.isFinite(Number(m?.minute))?`${Math.floor(Number(m.minute))}'`:'LIVE';
function renderMetrics(matches,generatedAt){$('liveCount').textContent=matches.length;$('watchCount').textContent=matches.filter(m=>m.engine?.decision==='WATCH').length;$('nearCount').textContent=matches.filter(m=>m.engine?.decision==='NEAR').length;$('signalCount').textContent=matches.filter(m=>m.engine?.decision==='SIGNAL').length;$('lastScan').textContent=fmtTime(generatedAt)}
function checkPills(checks={}){const labels={live:'LIVE',minute:'MINUTE',odds:'ODDS',goalGap:'GOAL GAP',fresh:'FRESH'};return Object.entries(labels).map(([key,label])=>{const ok=Boolean(checks[key]);return`<span class="check ${ok?'ok':'bad'}">${esc(label)} ${ok?'✓':'×'}</span>`}).join('')}
function card(m){const e=m.engine||{},d=String(e.decision||'WATCH').toUpperCase(),cls=d==='SIGNAL'?'signal':d==='NEAR'?'near':'',one=m.odds?.oneXtwo||{},ah=m.odds?.asianHandicap||{},ou=m.odds?.overUnder||{};return`<article class="match-card ${cls}"><div class="match-main"><div class="minute">${esc(minute(m))}<small>${esc(m.status||'LIVE')}</small></div><div class="teams"><div class="league">${esc(m.league||'Football')}</div><div class="fixture">${esc(m.home)} <span style="color:#707984">vs</span> ${esc(m.away)}</div></div><div class="score">${esc(score(m))}</div><div class="pick"><span>Selected</span><b>${esc(e.selectedTeam||'—')}</b></div><div class="odds"><span>Current odds</span><b>${esc(fmtOdds(e.odds))}</b></div><div class="status"><span class="pill ${d.toLowerCase()}">${esc(d)}</span></div></div><div class="details"><div class="detail"><span>1X2 Home</span><b>${esc(fmtOdds(one.home))}</b></div><div class="detail"><span>1X2 Draw</span><b>${esc(fmtOdds(one.draw))}</b></div><div class="detail"><span>1X2 Away</span><b>${esc(fmtOdds(one.away))}</b></div><div class="detail"><span>AH</span><b>${esc(ah.line??'—')} · ${esc(fmtOdds(ah.home))} / ${esc(fmtOdds(ah.away))}</b></div><div class="detail"><span>O/U</span><b>${esc(ou.line??'—')} · ${esc(fmtOdds(ou.over))} / ${esc(fmtOdds(ou.under))}</b></div></div><div class="checks">${checkPills(e.checks)}</div></article>`}
function renderList(){const rows=filter==='ALL'?[...lastMatches]:lastMatches.filter(m=>m.engine?.decision===filter);if(!rows.length){$('matchList').innerHTML=`<div class="empty">${lastMatches.length?'No matches in this filter.':'No live football rows available from the current 1xBet feed.'}</div>`;return}const rank={SIGNAL:0,NEAR:1,WATCH:2};rows.sort((a,b)=>(rank[a.engine?.decision]??9)-(rank[b.engine?.decision]??9)||(Number(b.minute)||0)-(Number(a.minute)||0));$('matchList').innerHTML=rows.map(card).join('')}
function setFeed(health,stale){const tag=$('feedTag'),label=$('feedLabel'),msg=$('feedMessage');tag.classList.remove('online','error');if(health?.online&&!stale){tag.classList.add('online');label.textContent=`1xBet online · ${health.events||0}`;msg.classList.remove('show');msg.textContent=''}else{tag.classList.add('error');label.textContent=stale?'Feed stale':'Feed unavailable';const attempt=(health?.attempts||[]).map(x=>`${x.host}: ${x.error}`).join(' · ');msg.textContent=`1xBet source is not returning usable live JSON to this Worker right now.${attempt?` ${attempt}`:''}`;msg.classList.add('show')}}
async function load(){try{const r=await fetch(`/live?t=${Date.now()}`,{cache:'no-store'}),data=await r.json();if(!r.ok||!data?.ok)throw new Error(data?.error||`HTTP ${r.status}`);lastMatches=Array.isArray(data.matches)?data.matches:[];renderMetrics(lastMatches,data.generatedAt);setFeed(data.sourceHealth,data.stale);renderList()}catch(error){$('feedTag').classList.add('error');$('feedLabel').textContent='Detector error';$('feedMessage').textContent=String(error?.message||error);$('feedMessage').classList.add('show');if(!lastMatches.length)$('matchList').innerHTML='<div class="empty">Detector could not load data.</div>'}finally{seconds=10}}
$('filterTabs').querySelectorAll('button').forEach(btn=>{btn.onclick=()=>{filter=btn.dataset.filter;$('filterTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===btn));renderList()}});
setInterval(()=>{seconds=Math.max(0,seconds-1);$('refreshNote').textContent=`Auto refresh ${seconds}s`;if(seconds===0)load()},1000);
load();
