const $=id=>document.getElementById(id);
let range='ALL',page=1,pages=1;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
const fmtOdds=v=>Number.isFinite(Number(v))?Number(v).toFixed(2):'—';
const fmtNum=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):(0).toFixed(d);
const dt=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat(undefined,{year:'2-digit',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return'—'}};
const sc=v=>v&&Number.isFinite(Number(v.home))&&Number.isFinite(Number(v.away))?`${v.home}-${v.away}`:'—';
function draw(trend=[]){const svg=$('historyChart');if(!trend.length){svg.innerHTML='<text x="450" y="112" text-anchor="middle" fill="#6f7882" font-size="12" font-family="Arial">No settled signals yet</text>';$('graphCaption').textContent='No settled signals yet';return}const w=900,h=220,pad=24,values=trend.map(x=>Number(x.netUnits)||0),min=Math.min(0,...values),max=Math.max(0,...values),span=Math.max(1,max-min),x=i=>pad+(i/(Math.max(1,trend.length-1)))*(w-pad*2),y=v=>h-pad-((v-min)/span)*(h-pad*2),pts=trend.map((r,i)=>`${x(i)},${y(Number(r.netUnits)||0)}`).join(' '),area=`${pad},${y(0)} ${pts} ${x(trend.length-1)},${y(0)}`,grids=[0,.25,.5,.75,1].map(t=>{const yy=pad+t*(h-pad*2);return`<line class="chart-grid" x1="${pad}" x2="${w-pad}" y1="${yy}" y2="${yy}"/>`}).join('');svg.innerHTML=`${grids}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${pts}"/>`;$('graphCaption').textContent=`${trend.length} settled day${trend.length===1?'':'s'} · latest ${fmtNum(values.at(-1),3)}u`}
function renderSummary(s={}){$('statWin').textContent=s.win||0;$('statLoss').textContent=s.loss||0;$('statDraw').textContent=s.draw||0;$('statRate').textContent=`${fmtNum(s.winRate,2)}%`;$('statPending').textContent=s.pending||0;$('statOdds').textContent=fmtNum(s.averageOdds,2);$('statUnits').textContent=`${fmtNum(s.netUnits,3)}u`;$('statRoi').textContent=`${fmtNum(s.roi,2)}%`;$('statSignals').textContent=s.signals||0;$('statSettled').textContent=s.settled||0;draw(s.trend||[])}
function resultClass(r){const g=String(r.resultGroup||'PENDING').toUpperCase();return['W','L','D'].includes(g)?g:'PENDING'}
function renderRows(rows=[]){if(!rows.length){$('historyBody').innerHTML='<tr><td colspan="12" style="text-align:center;color:#7f8994;padding:28px">No signal history in this range.</td></tr>';return}$('historyBody').innerHTML=rows.map(r=>`<tr><td>${esc(dt(r.selectedAt))}</td><td>${esc(r.league||'—')}</td><td>${esc(r.home)} vs ${esc(r.away)}</td><td>${esc(r.entryMinute??'—')}${r.entryMinute!=null?"'":''}</td><td>${esc(sc(r.entryScore))}</td><td>${esc(r.market||'WIN')}</td><td><b>${esc(r.selectedTeam||'—')}</b></td><td>${esc(r.line??'—')}</td><td><b>${esc(fmtOdds(r.odds))}</b></td><td>${esc(sc(r.finalScore))}</td><td><span class="result ${resultClass(r)}">${esc(r.result||'PENDING')}</span></td><td>${r.netUnits==null?'—':`${esc(fmtNum(r.netUnits,3))}u`}</td></tr>`).join('')}
async function load(){$('historyMeta').textContent='Loading history…';try{const r=await fetch(`/history?page=${page}&limit=25&range=${encodeURIComponent(range)}&t=${Date.now()}`,{cache:'no-store'}),data=await r.json();if(!r.ok||!data?.ok)throw new Error(data?.error||`HTTP ${r.status}`);pages=data.pages||1;page=Math.min(page,pages);renderSummary(data.summary||{});renderRows(data.records||[]);$('pageInfo').textContent=`Page ${page} / ${pages} · ${data.total||0} signals`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('historyMeta').textContent=`${range} · 25 rows/page · X1 SQLite history`;$('feedTag').classList.add('online');$('feedLabel').textContent='History ready'}catch(error){$('historyBody').innerHTML=`<tr><td colspan="12">${esc(String(error?.message||error))}</td></tr>`;$('feedTag').classList.add('error');$('feedLabel').textContent='History error';$('historyMeta').textContent='Unable to load'}}
$('rangeTabs').querySelectorAll('button').forEach(btn=>{btn.onclick=()=>{range=btn.dataset.range;page=1;$('rangeTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===btn));load()}});
$('prevPage').onclick=()=>{if(page>1){page--;load()}};
$('nextPage').onclick=()=>{if(page<pages){page++;load()}};
load();
