function serviceRequest(request,hostname,path){const u=new URL(request.url);u.protocol='https:';u.hostname=hostname;u.pathname=path;return new Request(u,request)}
const num=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
const copy=v=>v&&typeof v==='object'?JSON.parse(JSON.stringify(v)):v??null;
async function noStoreUiAsset(request,env){const r=await env.ASSETS.fetch(request),h=new Headers(r.headers),path=new URL(request.url).pathname;h.set('cache-control','no-store, no-cache, must-revalidate, max-age=0');h.set('pragma','no-cache');h.set('expires','0');h.set('x-nomad-ui-revision','343-full-market-one-request-v2');if(path.startsWith('/statistics'))h.set('x-nomad-stat-revision','343-stat-results-v7-live-mirror');if(path.startsWith('/signal'))h.set('x-nomad-signal-revision','343-signal-bettor-v4');if(path==='/index.html'||path.startsWith('/expanded-match-343')||path.startsWith('/full-market-bookmaker-343'))h.set('x-nomad-live-revision','343-full-market-one-request-v2');return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
function fixtureIsLive(f){const raw=String(f?.boardState??f?.status??f?.statusCode??'').toLowerCase();if(f?.boardState==='finished'||/finished|full_time|full time|\bft\b|ended/.test(raw))return false;return f?.boardState==='live'||/in_play|in play|live|playing|first|second|\b1h\b|\b2h\b/.test(raw)}
function liveMinute(f){const d=num(f?.minute);if(d!==null)return d;const m=String(f?.statusCode??'').match(/\d+/);return m?Number(m[0]):null}
async function activeSignals(request,env){const [sr,br]=await Promise.all([env.ENGINE.fetch(serviceRequest(request,'engine.internal','/signals')),env.ENGINE.fetch(serviceRequest(request,'engine.internal','/board'))]);const [s,b]=await Promise.all([sr.json().catch(()=>({})),br.json().catch(()=>({}))]);if(s?.ok!==true)return Response.json(s||{ok:false,error:'SIGNALS_NOT_READY'},{status:sr.status||503});if(b?.ok!==true)return Response.json({ok:false,error:'BOARD_NOT_READY',signals:[]},{status:br.status||503});const fixtures=Array.isArray(b.fixtures)?b.fixtures:[],live=fixtures.filter(fixtureIsLive),map=new Map(live.map(f=>[String(f?.fixtureId??''),f])),pending=Array.isArray(s.signals)?s.signals:[];let hidden=0;const signals=pending.filter(x=>{const ok=map.has(String(x?.fixtureId??''));if(!ok)hidden++;return ok}).map(x=>{const f=map.get(String(x.fixtureId));return{...x,mirrorMinute:liveMinute(f),mirrorScore:copy(f?.goals),mirrorState:'LIVE',mirrorSource:'ENGINE_BOARD_LIVE',liveStatistics:copy(f?.statistics),liveCorners:copy(f?.corners),liveCards:copy(f?.cards),liveEvents:Array.isArray(f?.events)?copy(f.events):[],liveStatus:f?.status??null,liveStatusCode:f?.statusCode??null,liveUpdatedAt:b?.hubFetchedAt??null,liveAgeMs:num(b?.hubAgeMs)}}).sort((a,c)=>Number(c?.createdAt||0)-Number(a?.createdAt||0));return Response.json({...s,signals,mirror:{source:'ENGINE_BOARD_LIVE',externalRequestsAdded:0,boardFixtures:fixtures.length,liveFixtures:live.length,activeMatches:new Set(signals.map(x=>String(x.fixtureId))).size,activeSignals:signals.length,hiddenPendingSignals:hidden,hubFetchedAt:b?.hubFetchedAt??null,hubAgeMs:num(b?.hubAgeMs),stale:Boolean(b?.stale)}},{headers:{'cache-control':'no-store'}})}
async function fullMarket(request,env,path){if(!env.FULL_MARKET)return Response.json({ok:false,error:'FULL_MARKET_BINDING_MISSING'},{status:503});return env.FULL_MARKET.fetch(serviceRequest(request,'full-market.internal',path))}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/engine/signals'&&request.method==='GET')return activeSignals(request,env);if(u.pathname.startsWith('/api/engine/'))return env.ENGINE.fetch(serviceRequest(request,'engine.internal',u.pathname.replace('/api/engine','')||'/'));if(u.pathname.startsWith('/api/full-market/'))return fullMarket(request,env,u.pathname.replace('/api/full-market','')||'/');if(request.method==='GET'&&(u.pathname==='/index.html'||u.pathname.startsWith('/expanded-match-343')||u.pathname.startsWith('/full-market-bookmaker-343')||u.pathname==='/statistics.html'||u.pathname==='/statistics.js'||u.pathname==='/statistics-page-343.css'||u.pathname==='/signal.html'||u.pathname==='/signal.js'||u.pathname==='/signal-compact-343.css'||u.pathname==='/signal-bettor-343.css'))return noStoreUiAsset(request,env);if(u.pathname==='/'){const a=new URL(request.url);a.pathname='/index.html';return noStoreUiAsset(new Request(a,request),env)}return env.ASSETS.fetch(request)}};
