export const safe=v=>String(v??'').trim();
export const nk=k=>safe(k).toLowerCase().normalize('NFKD').replace(/[^a-z0-9ก-๙]/g,'');
export const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[,%]/g,''));return Number.isFinite(n)?n:null};
export const first=(...xs)=>xs.find(v=>v!==null&&v!==undefined&&v!=='')??null;
export function pick(o,names){if(!o||typeof o!=='object'||Array.isArray(o))return null;const wanted=new Set(names.map(nk));for(const [k,v] of Object.entries(o)){if(wanted.has(nk(k))&&v!==null&&v!==undefined&&v!=='')return v;}return null;}
export function name(v){if(typeof v==='string'||typeof v==='number')return safe(v);return safe(pick(v,['name','displayName','shortName','teamName','competitorName','label','title','description','value']));}
export function redact(v,depth=0){if(depth>5)return '[depth]';if(Array.isArray(v))return v.slice(0,30).map(x=>redact(x,depth+1));if(!v||typeof v!=='object')return typeof v==='string'&&v.length>300?v.slice(0,300)+'…':v;const out={};let n=0;for(const [k,x] of Object.entries(v)){if(n++>80)break;if(/pass|token|cookie|session|account|balance|wallet|email|phone|auth|credential|profile|username|userid/i.test(k)){out[k]='[redacted]';continue;}out[k]=redact(x,depth+1);}return out;}
export function participants(o){let h=name(pick(o,['home','homeName','homeTeam','homeTeamName','team1','competitor1','participant1','host','local']));let a=name(pick(o,['away','awayName','awayTeam','awayTeamName','team2','competitor2','participant2','guest','visitor']));if(h&&a)return[h,a];for(const k of ['participants','competitors','teams','contestants','opponents']){const arr=pick(o,[k]);if(!Array.isArray(arr)||arr.length<2)continue;let hh='',aa='';for(const item of arr){const nm=name(item),side=safe(pick(item,['side','homeAway','designation','position','type'])).toLowerCase();if(!nm)continue;if(/home|host|team1|^1$/.test(side))hh=nm;else if(/away|guest|team2|^2$/.test(side))aa=nm;}if(hh&&aa)return[hh,aa];const names=arr.map(name).filter(Boolean);if(names.length>=2)return names.slice(0,2);}return['',''];}
export function score(o){const h=num(pick(o,['homeScore','scoreHome','homeGoals','score1','homeTeamScore','hScore']));const a=num(pick(o,['awayScore','scoreAway','awayGoals','score2','awayTeamScore','aScore']));if(h!==null&&a!==null)return[h,a];const s=pick(o,['score','currentScore','liveScore','result','scores']);if(typeof s==='string'){const m=s.match(/(\d+)\s*[-:]\s*(\d+)/);if(m)return[+m[1],+m[2]];}if(s&&typeof s==='object'&&!Array.isArray(s)){const hh=num(pick(s,['home','homeScore','h','score1'])),aa=num(pick(s,['away','awayScore','a','score2']));if(hh!==null&&aa!==null)return[hh,aa];}return[null,null];}
export const normTeam=s=>safe(s).toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9À-žก-๙]+/gi,' ').replace(/\s+/g,' ').trim();
export function parseText(text){const t=safe(text);if(!t)return null;const starts=[t.indexOf('{'),t.indexOf('[')].filter(x=>x>=0).sort((a,b)=>a-b);for(const x of [t,t.replace(/^\d+/,''),starts.length?t.slice(starts[0]):t]){try{return JSON.parse(x)}catch{}}return null;}
