import crypto from 'node:crypto';
import {safe} from './rich-utils.mjs';
const STOP=/^(live|football|soccer|sports|sport|today|tomorrow|all|match|matches|market|markets|odds|more|popular|home|away|draw|over|under|handicap|1x2|my bets|bet slip|login|logout|menu|สด)$/i;
function teamish(s){s=safe(s);return s.length>=2&&s.length<=70&&/[A-Za-zÀ-žก-๙]/.test(s)&&!STOP.test(s)&&!/^[-+]?\d/.test(s)&&!/(cash|balance|wallet|deposit|withdraw|promotion|bonus|account|stake|payout)/i.test(s);}
const LABELS={attacks:/^(attacks?|การบุก)$/i,dangerousAttacks:/^(dangerous attacks?|danger attacks?|การบุกอันตราย)$/i,shots:/^(shots?|total shots?|การยิง|ยิงทั้งหมด)$/i,shotsOnTarget:/^(shots? on target|on target|ยิงเข้ากรอบ)$/i,shotsOffTarget:/^(shots? off target|off target|ยิงออกนอกกรอบ)$/i,corners:/^(corners?|corner kicks?|เตะมุม)$/i,possession:/^(possession|ball possession|การครองบอล)$/i,fouls:/^(fouls?|ฟาวล์)$/i,yellowCards:/^(yellow cards?|ใบเหลือง)$/i,redCards:/^(red cards?|ใบแดง)$/i,offsides:/^(offsides?|ล้ำหน้า)$/i,saves:/^(saves?|เซฟ)$/i};
function parseStats(lines){const result={};for(let i=0;i<lines.length;i++)for(const [key,re] of Object.entries(LABELS)){if(!re.test(lines[i]))continue;const nums=[];for(let j=Math.max(0,i-2);j<=Math.min(lines.length-1,i+2);j++)for(const m of lines[j].matchAll(/\b(\d{1,3})(?:%)?\b/g))nums.push(Number(m[1]));if(nums.length>=2)result[key]=[nums[0],nums[1]];}return result;}
function parseEvents(lines){const out=[];for(const line of lines){if(!/(goal|ประตู|yellow|ใบเหลือง|red card|ใบแดง|corner|เตะมุม|substitut|เปลี่ยนตัว|penalty|จุดโทษ|var)/i.test(line))continue;const mm=line.match(/\b(\d{1,3})\s*['′’]?/);out.push({type:line,minute:mm?Number(mm[1]):null,team:'',side:'',player:'',score:'',raw:{domLine:line}});}return out.slice(0,80);}
export function parseDomBlock(text,frameUrl){const lines=String(text||'').split(/\r?\n/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);if(lines.length<2||lines.length>80)return null;const odds=[...text.matchAll(/\b([1-9]\d?\.\d{2,3})\b/g)].map(m=>Number(m[1])).filter(n=>n>=1.01&&n<=100),scoreIdx=lines.findIndex(x=>/^\d+\s*[-:]\s*\d+$/.test(x));let home='',away='';if(scoreIdx>0){for(let i=scoreIdx-1;i>=0&&!home;i--)if(teamish(lines[i]))home=lines[i];for(let i=scoreIdx+1;i<lines.length&&!away;i++)if(teamish(lines[i]))away=lines[i];}if(!home||!away){const teams=lines.filter(teamish).filter((v,i,a)=>a.indexOf(v)===i);if(teams.length>=2){home=home||teams[0];away=away||teams[1];}}if(!home||!away||home===away)return null;const sm=text.match(/(\d+)\s*[-:]\s*(\d+)/),mm=text.match(/\b(\d{1,3})\s*['′’]/),stats=parseStats(lines),events=parseEvents(lines),id=crypto.createHash('sha1').update(frameUrl+'|'+home+'|'+away).digest('hex').slice(0,16),raw={domFallback:true,frameUrl,text:lines.slice(0,80)};const r={sourceId:`dom-${id}`,sport:'Football',league:'M88 live',home,away,minute:mm?Number(mm[1]):null,period:'',clock:'',homeScore:sm?Number(sm[1]):null,awayScore:sm?Number(sm[2]):null,status:/(สด|live|in.?play)/i.test(text)?'LIVE':'',market:'',selection:'',odds:odds[0]??null,line:null,handicapLine:null,goalLine:null,markets:[],events,extraStats:[],rawSnapshot:raw,raw};for(const [k,pair] of Object.entries(stats)){const cap=k[0].toUpperCase()+k.slice(1);r[`home${cap}`]=pair[0];r[`away${cap}`]=pair[1];}const fields=['homeAttacks','awayAttacks','homeDangerousAttacks','awayDangerousAttacks','homeShots','awayShots','homeShotsOnTarget','awayShotsOnTarget','homeCorners','awayCorners','homePossession','awayPossession'];r.statsCoverage=fields.filter(k=>r[k]!==null&&r[k]!==undefined).length;r.statsCoverageMax=fields.length;r.eventCount=events.length;r.marketCount=0;return r;}
export async function scanDom(context,onRows){const frames=[],samples=[],rows=[];for(const p of context.pages())for(const f of p.frames()){frames.push(f.url());try{const blocks=await f.locator('div,li,tr,section,article').evaluateAll(els=>els.slice(0,7000).map(el=>{const s=getComputedStyle(el);if(s.display==='none'||s.visibility==='hidden')return'';const t=(el.innerText||'').trim();return t.length>=12&&t.length<=2200?t:'';}).filter(Boolean).slice(0,900));for(const text of blocks){const r=parseDomBlock(text,f.url());if(r){rows.push(r);if(samples.length<30)samples.push({frameUrl:f.url(),text:r.rawSnapshot.text,statsCoverage:r.statsCoverage,eventCount:r.eventCount});}}}catch{}}await onRows(rows,frames,samples);}
