(()=>{
'use strict';
const VERSION='343-ai-k-win-only-v1';
const SETTINGS_KEY='NOMAD343_AI_K_SETTINGS_V1';
const SIGNALS_KEY='NOMAD343_AI_K_SIGNALS_V1';
const DEFAULTS=Object.freeze({enabled:false,mode:'WIN_ONLY',confidenceMin:85,patternMin:80,minConfirmations:2,minuteFrom:55,minuteTo:82,oddsMin:1.50,oddsMax:3.50,maxDataAgeSeconds:30,rollingMinutes:5,minWarmSamples:8,oneSignalPerMatch:true,rejectRedCard:true,maxSignals:300});
const history=new Map();
let lastSnapshotKey='',lastSettingsStamp='',lastEvalAt=0,lastSummary={evaluated:0,signals:0,rejected:0,reason:'IDLE'};
const num=v=>v===null||v===undefined||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))?null:Number(v);
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const clone=v=>JSON.parse(JSON.stringify(v));
const norm=v=>String(v??'').toLowerCase().replace(/[\s_-]/g,'');
const now=()=>Date.now();
function readSettings(){try{return {...DEFAULTS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {...DEFAULTS}}}
function writeSettings(next){const clean={...DEFAULTS,...next};localStorage.setItem(SETTINGS_KEY,JSON.stringify(clean));window.dispatchEvent(new CustomEvent('nomad343:ai-k-settings',{detail:clean}));return clean}
function readSignals(){try{const v=JSON.parse(localStorage.getItem(SIGNALS_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function writeSignals(rows){const cfg=readSettings(),next=rows.slice(-Number(cfg.maxSignals||300));localStorage.setItem(SIGNALS_KEY,JSON.stringify(next));return next}
function pair(v){return v&&typeof v==='object'?{home:num(v.home),away:num(v.away)}:{home:null,away:null}}
function delta(a,b){a=num(a);b=num(b);return a===null||b===null||a<b?null:a-b}
function deltaPair(cur,old){return {home:delta(cur?.home,old?.home),away:delta(cur?.away,old?.away)}}
function share(p,side){const h=num(p?.home),a=num(p?.away);if(h===null||a===null||h+a<=0)return null;return (side==='HOME'?h:a)/(h+a)*100}
function sideValue(p,side){return num(side==='HOME'?p?.home:p?.away)}
function fixtureId(f){return String(f?.fixtureId??f?.id??'')}
function minuteOf(f){const m=num(f?.minute);if(m!==null)return m;const hit=String(f?.statusCode??'').match(/\d+/);return hit?Number(hit[0]):null}
function isLive(f){const s=String(f?.boardState??f?.status??f?.statusCode??'').toLowerCase();return f?.boardState==='live'||/live|in_play|in play|playing|first|second|\b1h\b|\b2h\b|half/.test(s)||/^\d+$/.test(String(f?.statusCode??''))}
function hasRedCard(f){const a=num(f?.cards?.home?.red)??0,b=num(f?.cards?.away?.red)??0;if(a>0||b>0)return true;return (Array.isArray(f?.events)?f.events:[]).some(e=>/red/i.test(`${e?.type??''} ${e?.detail??''} ${e?.name??''}`))}
function providerBooks(f){const p=f?.providerOdds;if(!p||typeof p!=='object')return[];const roots=[p?.bookmakers,p?.data?.bookmakers,p?.odds?.bookmakers].filter(Array.isArray);let raw=roots[0]||[];if(!raw.length&&p.bet365&&typeof p.bet365==='object')raw=[{slug:'bet365',name:'Bet365',odds:p.bet365}];if(!raw.length&&p.odds&&typeof p.odds==='object'&&!Array.isArray(p.odds))raw=[{slug:'bet365',name:'Bet365',odds:p.odds}];if(!raw.length&&Object.keys(p).some(k=>/1x2|asian|goal/i.test(k)))raw=[{slug:'bet365',name:'Bet365',odds:p}];return raw}
function bet365Root(f){const row=providerBooks(f).find(x=>{const k=norm(x?.slug??x?.bookmaker?.slug??x?.name??x?.bookmaker?.name);return k==='bet365'||k.includes('bet365')});const root=row?.odds??row?.markets??row?.data?.odds??row?.data?.markets??null;return root&&typeof root==='object'?root:null}
function market(root,aliases){for(const k of aliases){if(root?.[k]&&typeof root[k]==='object')return root[k]}return null}
function liveStage(m){const v=m?.inplay??m?.in_play??m?.live??null;return v&&typeof v==='object'?v:null}
function prices(f){const root=bet365Root(f);if(!root)return null;const ah=liveStage(market(root,['asian_handicap','asian','handicap']));const gl=liveStage(market(root,['goal_line','goalline','total_goals','goals_over_under']));const x12=liveStage(market(root,['1x2','moneyline','match_odds']));return {root,ah,gl,x12}}
function point(f,at){const st=f?.statistics||{};const px=prices(f);return {at,minute:minuteOf(f),score:pair(f?.goals),sot:pair(st?.shotsOnTarget),soff:pair(st?.shotsOffTarget),corners:pair(f?.corners??st?.corners),attacks:pair(st?.attacks),danger:pair(st?.dangerousAttacks),possession:pair(st?.possession),ah:px?.ah?clone(px.ah):null,gl:px?.gl?clone(px.gl):null,x12:px?.x12?clone(px.x12):null}}
function appendHistory(f,at){const id=fixtureId(f);if(!id)return[];const arr=history.get(id)||[],p=point(f,at);if(!arr.length||arr[arr.length-1].at!==at)arr.push(p);else arr[arr.length-1]=p;const keep=arr.filter(x=>at-x.at<=30*60_000).slice(-140);history.set(id,keep);return keep}
function rolling(arr,cfg){if(!Array.isArray(arr)||arr.length<Number(cfg.minWarmSamples||8))return null;const cur=arr[arr.length-1],target=cur.at-Number(cfg.rollingMinutes||5)*60_000;let old=null;for(let i=arr.length-2;i>=0;i--){if(arr[i].at<=target){old=arr[i];break}}if(!old)old=arr[0];if(!old||old===cur)return null;return {fromAt:old.at,toAt:cur.at,minutes:Math.max(.25,(cur.at-old.at)/60_000),sot:deltaPair(cur.sot,old.sot),soff:deltaPair(cur.soff,old.soff),corners:deltaPair(cur.corners,old.corners),attacks:deltaPair(cur.attacks,old.attacks),danger:deltaPair(cur.danger,old.danger),possession:cur.possession,prev:old,current:cur}}
function weightedMomentum(r,side){if(!r)return 0;const rows=[[share(r.attacks,side),15],[share(r.danger,side),25],[share(r.sot,side),25],[share(r.soff,side),10],[share(r.corners,side),15],[sideValue(r.possession,side),10]].filter(x=>x[0]!==null);const w=rows.reduce((s,x)=>s+x[1],0);return w?rows.reduce((s,x)=>s+x[0]*x[1],0)/w:0}
function threat(r,side){if(!r)return 0;const sot=sideValue(r.sot,side)??0,soff=sideValue(r.soff,side)??0,c=sideValue(r.corners,side)??0,da=share(r.danger,side)??50;return clamp(sot*18+soff*6+c*7+(da-50)*.55,0,100)}
function bothThreat(r){if(!r)return 0;const sot=(num(r.sot?.home)??0)+(num(r.sot?.away)??0),soff=(num(r.soff?.home)??0)+(num(r.soff?.away)??0),c=(num(r.corners?.home)??0)+(num(r.corners?.away)??0);return clamp(sot*14+soff*4+c*5,0,100)}
function priceMove(cur,prev){cur=num(cur);prev=num(prev);if(cur===null)return {score:0,veto:true};if(prev===null)return {score:72,veto:false};const ratio=cur/prev;if(ratio>1.10)return {score:30,veto:true};if(ratio<.94)return {score:92,veto:false};return {score:78,veto:false}}
function marketCandidates(f,r,cfg){const px=prices(f);if(!px)return[];const score=pair(f?.goals),h=num(score.home)??0,a=num(score.away)??0,out=[];
  const sideCandidate=(side,kind)=>{const mom=weightedMomentum(r,side),thr=threat(r,side),statsPass=thr>=62,momentumPass=mom>=62;let line=null,odds=null,prevOdds=null,selection=side,marketName=kind;
    if(kind==='FT_AH'&&px.ah){const base=num(px.ah.line??px.ah.hdp??px.ah.handicap);line=base===null?null:(side==='HOME'?base:-base);odds=num(side==='HOME'?(px.ah.home??px.ah.home_odds):(px.ah.away??px.ah.away_odds));const p=r?.prev?.ah;prevOdds=num(side==='HOME'?(p?.home??p?.home_odds):(p?.away??p?.away_odds));}
    if(kind==='FT_1X2'&&px.x12){line=null;odds=num(side==='HOME'?px.x12.home:px.x12.away);const p=r?.prev?.x12;prevOdds=num(side==='HOME'?p?.home:p?.away);}
    if(odds===null||odds<cfg.oddsMin||odds>cfg.oddsMax)return;const pm=priceMove(odds,prevOdds),pricePass=!pm.veto;const confirmations=[statsPass,momentumPass,pricePass].filter(Boolean).length;const pattern=Math.round(clamp(mom*.55+thr*.45,0,100));const confidence=Math.round(clamp(pattern*.70+pm.score*.20+(confirmations/3)*10,0,100));const trailing=side==='HOME'?a-h:h-a;if(trailing>1)return;out.push({market:marketName,selection,line,odds,pattern,confidence,confirmations,priceScore:pm.score,veto:pm.veto,reasons:[`Momentum ${mom.toFixed(0)}`,`Threat ${thr.toFixed(0)}`,`Price ${pm.score.toFixed(0)}`]});};
  sideCandidate('HOME','FT_AH');sideCandidate('AWAY','FT_AH');sideCandidate('HOME','FT_1X2');sideCandidate('AWAY','FT_1X2');
  if(px.gl){const line=num(px.gl.line??px.gl.total),currentGoals=h+a,totalThr=bothThreat(r);for(const selection of ['OVER','UNDER']){const odds=num(selection==='OVER'?(px.gl.over??px.gl.over_odds):(px.gl.under??px.gl.under_odds));if(line===null||odds===null||odds<cfg.oddsMin||odds>cfg.oddsMax)continue;const prev=r?.prev?.gl,prevOdds=num(selection==='OVER'?(prev?.over??prev?.over_odds):(prev?.under??prev?.under_odds)),pm=priceMove(odds,prevOdds);const gap=line-currentGoals;if(gap<=0)continue;let pattern,statsPass,momentumPass;if(selection==='OVER'){pattern=Math.round(clamp(totalThr*.82+Math.min(18,Math.max(0,1.5-gap)*12),0,100));statsPass=totalThr>=68;momentumPass=gap<=1.5;}else{const quiet=100-totalThr;pattern=Math.round(clamp(quiet*.82+Math.min(18,Math.max(0,gap-1)*9),0,100));statsPass=quiet>=70;momentumPass=gap>=1.0;}const pricePass=!pm.veto,confirmations=[statsPass,momentumPass,pricePass].filter(Boolean).length,confidence=Math.round(clamp(pattern*.70+pm.score*.20+(confirmations/3)*10,0,100));out.push({market:`FT_${selection}`,selection,line,odds,pattern,confidence,confirmations,priceScore:pm.score,veto:pm.veto,reasons:[`Pattern ${pattern}`,`Goal gap ${gap.toFixed(2)}`,`Price ${pm.score.toFixed(0)}`]});}}
  return out;
}
function evaluateFixture(f,snapshot,cfg){const id=fixtureId(f),minute=minuteOf(f),at=num(snapshot?.fetchedAt)??now();if(!id||!isLive(f))return {ok:false,reason:'NOT_LIVE'};if(minute===null||minute<cfg.minuteFrom||minute>cfg.minuteTo)return {ok:false,reason:'MINUTE'};const age=Math.max(0,now()-at);if(age>cfg.maxDataAgeSeconds*1000)return {ok:false,reason:'STALE'};if(cfg.rejectRedCard&&hasRedCard(f))return {ok:false,reason:'RED_CARD_VETO'};const st=f?.statistics||{};if(!st?.shotsOnTarget||!st?.dangerousAttacks||!f?.goals)return {ok:false,reason:'CRITICAL_DATA_MISSING'};if(!bet365Root(f))return {ok:false,reason:'NO_BET365'};const arr=appendHistory(f,at),r=rolling(arr,cfg);if(!r)return {ok:false,reason:'WARMING'};const candidates=marketCandidates(f,r,cfg).filter(c=>!c.veto&&c.confirmations>=cfg.minConfirmations&&c.pattern>=cfg.patternMin&&c.confidence>=cfg.confidenceMin).sort((a,b)=>b.confidence-a.confidence||b.pattern-a.pattern);if(!candidates.length)return {ok:false,reason:'NO_EDGE'};return {ok:true,best:candidates[0],rolling:r};}
function signalKey(s){return `${s.fixtureId}|${s.market}|${s.selection}`}
function addSignal(f,result,snapshot,cfg){const rows=readSignals(),id=fixtureId(f);if(cfg.oneSignalPerMatch&&rows.some(x=>String(x.fixtureId)===id))return null;const b=result.best,sig={id:`AIK-${id}-${Date.now().toString(36)}`,source:'AI_K',mode:'WIN_ONLY',fixtureId:id,league:clone(f?.league??null),home:clone(f?.home??null),away:clone(f?.away??null),market:b.market,selection:b.selection,line:b.line,odds:b.odds,bookmaker:'Bet365',confidence:b.confidence,patternStrength:b.pattern,confirmations:b.confirmations,reasons:b.reasons,entryMinute:minuteOf(f),entryScore:clone(f?.goals??null),createdAt:now(),snapshotAt:num(snapshot?.fetchedAt)??now(),status:'PENDING'};if(rows.some(x=>signalKey(x)===signalKey(sig)))return null;writeSignals([...rows,sig]);window.dispatchEvent(new CustomEvent('nomad343:ai-k-signal',{detail:sig}));return sig}
function patchBadges(){const signals=readSignals(),byId=new Map();for(const s of signals)if(s?.status==='PENDING')byId.set(String(s.fixtureId),s);document.querySelectorAll('.match-card[data-match-id]').forEach(card=>{const id=String(card.dataset.matchId||''),host=card.querySelector('.fixture-side');if(!host)return;let badge=host.querySelector('[data-ai-k-badge]');const s=byId.get(id);if(!s){badge?.remove();return}if(!badge){badge=document.createElement('span');badge.dataset.aiKBadge='1';badge.style.cssText='margin-left:6px;padding:3px 6px;border:1px solid #6adf8f;border-radius:999px;font-size:8px;font-weight:900;color:#79efa1;background:#0b2014;white-space:nowrap';host.appendChild(badge)}badge.textContent=`AI K ${s.market} ${s.confidence}%`;});}
function ensureIndicator(){let el=document.querySelector('[data-ai-k-indicator]');if(el)return el;const bar=document.querySelector('.today-toolbar')||document.querySelector('.toolbar');if(!bar)return null;el=document.createElement('span');el.dataset.aiKIndicator='1';el.className='pill';bar.appendChild(el);return el}
function updateIndicator(cfg){const el=ensureIndicator();if(!el)return;const count=readSignals().filter(x=>x.status==='PENDING').length;el.textContent=cfg.enabled?`AI เซียน K · RUN · ${count} signal`:'AI เซียน K · STOP';el.style.borderColor=cfg.enabled?'#2e9265':'';el.style.color=cfg.enabled?'#73f2ac':''}
function evaluate(snapshot){const cfg=readSettings();updateIndicator(cfg);patchBadges();if(!cfg.enabled){lastSummary={evaluated:0,signals:0,rejected:0,reason:'STOPPED'};return lastSummary}const key=String(snapshot?.fetchedAt??snapshot?.lastSuccessAt??'');if(!key||key===lastSnapshotKey)return lastSummary;lastSnapshotKey=key;let evaluated=0,signals=0,rejected=0;for(const f of Array.isArray(snapshot?.fixtures)?snapshot.fixtures:[]){if(!isLive(f))continue;evaluated++;const r=evaluateFixture(f,snapshot,cfg);if(!r.ok){rejected++;continue}if(addSignal(f,r,snapshot,cfg))signals++;}lastEvalAt=now();lastSummary={evaluated,signals,rejected,reason:'OK',at:lastEvalAt,snapshotAt:num(snapshot?.fetchedAt)??null};patchBadges();updateIndicator(cfg);return lastSummary}
function poll(){try{const live=window.NOMAD343_LIVE,snapshot=live?.getSnapshot?.();if(snapshot)evaluate(snapshot)}catch(e){lastSummary={...lastSummary,reason:`ERROR:${e?.message||e}`}}}
window.addEventListener('storage',e=>{if(e.key===SETTINGS_KEY||e.key===SIGNALS_KEY){patchBadges();updateIndicator(readSettings())}});
window.addEventListener('nomad343:ai-k-settings',()=>{patchBadges();updateIndicator(readSettings())});
window.NOMAD343_AI_K={version:VERSION,defaults:{...DEFAULTS},readSettings,writeSettings,readSignals,evaluate,getSummary:()=>clone(lastSummary),getHistory:id=>clone(history.get(String(id))||[]),clearSignals:()=>writeSignals([])};
setInterval(poll,1000);queueMicrotask(poll);
})();
