(()=>{
'use strict';
const VERSION='343-language-id-v1';
const CODE='id';
const STORAGE_KEY='nomad343_language_v1';
const SELECT_ID='nomad343-language-select';

const ID=new Map(Object.entries({
'Live Scores':'Skor Langsung','Signals':'Sinyal','Statistics':'Statistik',"Today's Matches":'Pertandingan Hari Ini',
"Live scores, match statistics and Bet365 markets for today's fixtures.":'Skor langsung, statistik pertandingan, dan pasaran Bet365 untuk pertandingan hari ini.',
'Connecting to Live Data':'Menghubungkan ke data langsung','Search teams or leagues…':'Cari tim atau liga…','Today':'Hari Ini','Local Time':'Waktu Lokal','Bet365 Live Markets':'Pasaran Langsung Bet365',
'Live':'Langsung','Upcoming':'Akan Datang','Finished':'Selesai','Unconfirmed':'Belum Terkonfirmasi','No Live Matches':'Tidak ada pertandingan langsung',"Waiting for Today's Fixtures":'Menunggu pertandingan hari ini','No Finished Matches':'Tidak ada pertandingan selesai','No Unconfirmed Matches':'Tidak ada pertandingan yang belum terkonfirmasi','No More Upcoming Matches':'Tidak ada pertandingan berikutnya',
'Select a match to view match details, statistics, event flow and Bet365 markets.':'Pilih pertandingan untuk melihat detail, statistik, alur pertandingan, dan pasaran Bet365.',
'Latest Match Data':'Data Pertandingan Terbaru','Match Statistics':'Statistik Pertandingan','Shots on Target':'Tembakan Tepat Sasaran','Shots off Target':'Tembakan Melenceng','Corners':'Tendangan Sudut','Attacks':'Serangan','Dangerous Attacks':'Serangan Berbahaya','Possession':'Penguasaan Bola','Attack Percentage':'Persentase Serangan','Dangerous Attack Percentage':'Persentase Serangan Berbahaya','Possession Percentage':'Persentase Penguasaan Bola',
'Building Event History':'Menyusun riwayat kejadian','No Bookmaker Odds Available':'Tidak ada odds bookmaker yang tersedia','Building Odds Movement History':'Menyusun riwayat pergerakan odds','Live Data Unavailable':'Data langsung tidak tersedia','Live Data Delayed':'Data langsung terlambat','Live data':'Data langsung','Waiting for Data':'Menunggu data','Signal Locked':'Sinyal Dikunci','No Signal':'Tidak Ada Sinyal','Signal —':'Sinyal —','Half-Time':'Jeda Babak','Full-Time':'Selesai',
'Event Flow':'Alur Pertandingan','Event Flow · Match History':'Alur Pertandingan · Riwayat Pertandingan','Event Flow · Attack Momentum':'Alur Pertandingan · Momentum Serangan','Attack intensity from recent match data':'Intensitas serangan berdasarkan data pertandingan terbaru','Attack Momentum graph':'Grafik Momentum Serangan','Odds Movement':'Pergerakan Odds','Observed Odds':'Odds Terpantau','Building Attack Momentum History':'Menyusun riwayat momentum serangan','Loading Attack Momentum History…':'Memuat riwayat momentum serangan…','Event Flow Unavailable':'Alur pertandingan tidak tersedia',
'Active Signals':'Sinyal Aktif','Live selections with entry odds, entry score and current match status in one card.':'Pilihan langsung dengan odds saat masuk, skor saat masuk, dan status pertandingan terkini dalam satu kartu.','Connecting to Active Signals':'Menghubungkan ke sinyal aktif','Active Matches':'Pertandingan Bersinyal','One match per card':'Satu pertandingan per kartu','All markets currently being tracked':'Semua pasaran yang sedang dipantau','Live Tracking':'Pemantauan Langsung','Now':'Sekarang','Minute · Score · Match Data':'Menit · Skor · Data Pertandingan','Results':'Hasil','Settled signals move to Statistics':'Sinyal yang sudah diselesaikan dipindahkan ke Statistik',
'System selections, entry odds and current match status. Select a card to view full details.':'Pilihan sistem, odds saat masuk, dan status pertandingan terkini. Pilih kartu untuk melihat detail lengkap.','Active Only':'Hanya Aktif','Waiting for Live Signals':'Menunggu sinyal langsung','When a signal is settled as Win, Loss or Push, it leaves this page and moves to Statistics.':'Saat sinyal diselesaikan sebagai Menang, Kalah, atau Pengembalian, sinyal dipindahkan dari halaman ini ke Statistik.','No Active Signals':'Tidak ada sinyal aktif','There are no active signals right now':'Saat ini tidak ada sinyal aktif','Active Signals Unavailable':'Sinyal aktif tidak tersedia',
'Signal Time':'Waktu Sinyal','Entry Score':'Skor Saat Masuk','Pick':'Pilihan','Line':'Line','Entry Odds':'Odds Saat Masuk','Bookmaker':'Bookmaker','Entry Match Statistics':'Statistik Saat Masuk','Signal Criteria':'Kriteria Sinyal','Match statistics at signal entry':'Statistik pertandingan saat sinyal masuk','Criteria met when the signal was created':'Kriteria yang terpenuhi saat sinyal dibuat','Live Match Statistics':'Statistik Pertandingan Langsung','Signal Tracker':'Pemantau Sinyal','Entry status compared with the current match':'Status saat masuk dibandingkan dengan kondisi pertandingan terkini','Signal Details':'Detail Sinyal','Entry Locked':'Entri Dikunci','Technical Details':'Detail Teknis','Provider Market':'Pasaran Penyedia','Rolling Window':'Jendela Analisis','5USD Raw Line':'Line Mentah 5USD','Feed Age':'Usia Data','Events':'Kejadian','Raw Card Count':'Jumlah Kartu Mentah','Pass':'Lolos','Not Met':'Tidak Terpenuhi','Required':'Wajib',
'Settled Signals':'Sinyal Tuntas','Track active signals above and review settled results below.':'Pantau sinyal aktif di atas dan tinjau hasil yang sudah diselesaikan di bawah.','Connecting to Statistics':'Menghubungkan ke statistik','Live Signal Tracker':'Pemantau Sinyal Langsung','Live minute and score from the Signals page. Select a card to view details for an active match.':'Menit dan skor langsung dari halaman Sinyal. Pilih kartu untuk melihat detail pertandingan aktif.','Waiting for Active Signals':'Menunggu sinyal aktif','Results already settled':'Hasil yang sudah diselesaikan','Wins':'Menang','Full wins':'Menang penuh','Losses':'Kalah','Full losses':'Kalah penuh','Win Rate':'Tingkat Kemenangan','Push excluded · half results weighted':'Pengembalian tidak dihitung · hasil setengah diberi bobot','Average Entry Odds':'Rata-rata Odds Saat Masuk','Average odds when signals were created':'Rata-rata odds ketika sinyal dibuat','Results History':'Riwayat Hasil','Entry odds and settled results by market · Time shown in':'Odds saat masuk dan hasil tuntas berdasarkan pasaran · Waktu ditampilkan dalam','All Market Results':'Hasil Semua Pasaran','Date & Time':'Tanggal & Waktu','League / Match':'Liga / Pertandingan','Market':'Pasaran','Full-Time Score':'Skor Akhir','Result':'Hasil','Waiting for Settled Results':'Menunggu hasil yang sudah diselesaikan',
'Supports Win, Loss, Push, Half Win and Half Loss. If required settlement data is unavailable, the result remains Unresolved.':'Mendukung Menang, Kalah, Pengembalian, Menang Setengah, dan Kalah Setengah. Jika data penyelesaian yang diperlukan tidak tersedia, hasil tetap Belum Terselesaikan.','No Settled Results Yet':'Belum ada hasil yang diselesaikan','Statistics Unavailable':'Statistik tidak tersedia','Win':'Menang','Loss':'Kalah','Push':'Pengembalian','Half Win':'Menang Setengah','Half Loss':'Kalah Setengah','Unresolved':'Belum Terselesaikan','All Markets':'Semua Pasaran','Half Results':'Hasil Setengah',
'BET365 · FULL MARKET ODDS':'BET365 · ODDS SEMUA PASARAN','Match Result · Full Time':'Hasil Pertandingan · Waktu Penuh','Match Result · First Half':'Hasil Pertandingan · Babak Pertama','Asian Handicap · Full Time':'Handicap Asia · Waktu Penuh','Asian Handicap · First Half':'Handicap Asia · Babak Pertama','Goals Over / Under · Full Time':'Gol Lebih / Kurang · Waktu Penuh','Goals Over / Under · First Half':'Gol Lebih / Kurang · Babak Pertama','Goals Over · Full Time':'Gol Lebih · Waktu Penuh','Goals Under · Full Time':'Gol Kurang · Waktu Penuh','Goals Over · First Half':'Gol Lebih · Babak Pertama','Goals Under · First Half':'Gol Kurang · Babak Pertama','Corners Over / Under · Full Time':'Tendangan Sudut Lebih / Kurang · Waktu Penuh','Corners Over / Under · First Half':'Tendangan Sudut Lebih / Kurang · Babak Pertama','Corners Over · Full Time':'Tendangan Sudut Lebih · Waktu Penuh','Corners Under · Full Time':'Tendangan Sudut Kurang · Waktu Penuh','Corners Over · First Half':'Tendangan Sudut Lebih · Babak Pertama','Corners Under · First Half':'Tendangan Sudut Kurang · Babak Pertama','Corners Asian Handicap':'Handicap Asia Tendangan Sudut','Cards Over / Under · Full Time':'Kartu Lebih / Kurang · Waktu Penuh','Cards Over · Full Time':'Kartu Lebih · Waktu Penuh','Cards Under · Full Time':'Kartu Kurang · Waktu Penuh','Cards Asian Handicap':'Handicap Asia Kartu','Both Teams to Score':'Kedua Tim Mencetak Gol','Both Teams to Score · Yes':'Kedua Tim Mencetak Gol · Ya','Both Teams to Score · No':'Kedua Tim Mencetak Gol · Tidak','In-Play Odds':'Odds Langsung','Pre-Match Odds':'Odds Pra-Pertandingan','Opening Odds':'Odds Pembukaan','Home':'Tuan Rumah','Away':'Tandang','HOME':'Tuan Rumah','AWAY':'Tandang','Draw':'Seri','Over':'Lebih','Under':'Kurang','Yes':'Ya','No':'Tidak','Loading':'Memuat','Odds —':'Odds —','Full Market Odds Unavailable':'Odds semua pasaran tidak tersedia','Loading Full Bet365 Lines and Odds':'Memuat line dan odds lengkap Bet365','Full Market Odds Are Unavailable for This Match':'Odds semua pasaran tidak tersedia untuk pertandingan ini'
}));

const RULES=[
[/^(\d+) Active Signal(?:s)? in this match$/i,'$1 sinyal aktif dalam pertandingan ini'],
[/^(\d+) Signal(?:s)? · Details$/i,'$1 sinyal · Detail'],
[/^Active Signals · (\d+) match(?:es)?(?: · (\d+) signal(?:s)?)?(?: · data age (\d+)s)?$/i,(_,m,s,a)=>`Sinyal aktif · ${m} pertandingan${s?` · ${s} sinyal`:''}${a?` · data ${a} dtk`:''}`],
[/^(\d+) Points$/i,'$1 poin'],[/^(\d+) Markets$/i,'$1 pasaran'],[/^Half-Time\s+(.+)$/i,'Jeda Babak $1'],[/^Full Time · (.+)$/i,'Waktu Penuh · $1'],[/^First Half · (.+)$/i,'Babak Pertama · $1'],[/^Revised from (.+?) · /i,'Direvisi dari $1 · '],
[/^Attack trend from recent match data · (\d+)-minute rate · smoothed trend$/i,'Tren serangan dari data terbaru · laju $1 menit · tren diperhalus'],[/^Timeline uses observed match data · both teams measured independently$/i,'Garis waktu menggunakan data pertandingan yang diamati · kedua tim diukur secara terpisah'],[/^Momentum = Dangerous Attacks 30 · Shots on Target 25 · Attacks 20 · Shots off Target 10 · Corners 10 · Possession 5$/i,'Momentum = Serangan Berbahaya 30 · Tembakan Tepat Sasaran 25 · Serangan 20 · Tembakan Melenceng 10 · Tendangan Sudut 10 · Penguasaan Bola 5'],[/^Event Flow uses observed match history · Bookmaker odds show observed data only/i,'Alur pertandingan menggunakan riwayat yang diamati · odds bookmaker hanya menampilkan data yang diamati'],[/ · this match is unconfirmed and cannot be settled$/i,' · pertandingan ini belum terkonfirmasi dan tidak dapat diselesaikan'],
[/\bMatch Statistics\b/g,'Statistik Pertandingan'],[/5USD Full Market Odds/g,'Odds Lengkap 5USD'],[/\s+vs\s+/gi,' vs '],[/→\s*Live$/i,'→ Langsung'],[/\bHalf Win\b/g,'Menang Setengah'],[/\bHalf Loss\b/g,'Kalah Setengah'],[/\bUnresolved\b/g,'Belum Terselesaikan'],[/\bWin\b/g,'Menang'],[/\bLoss\b/g,'Kalah'],[/\bPush\b/g,'Pengembalian'],[/\bNot Met\b/g,'Tidak Terpenuhi'],[/\bRequired\b/g,'Wajib'],[/\bPass\b/g,'Lolos'],[/·\s*Full Time\b/g,'· Waktu Penuh'],[/·\s*First Half\b/g,'· Babak Pertama'],[/·\s*FT\b/g,'· Waktu Penuh'],[/·\s*HT\b/g,'· Babak Pertama'],[/\bAll Markets\b/g,'Semua Pasaran'],[/\bUnresolved (\d+)\b/gi,'Belum Terselesaikan $1'],[/ · Half Results (\d+\/\d+)$/i,' · Hasil Setengah $1']
];

const TITLES={live:'nomadtips3 · Skor Langsung 3.43',signal:'nomadtips3 · Sinyal 3.43',statistics:'nomadtips3 · Statistik 3.43'};
const TEXT_SOURCE=new WeakMap(),ATTR_SOURCE=new WeakMap();
let active=false,observer=null,baseApi=null,baseSet=null,baseCurrent=null;
function translate(text){let next=ID.get(text)??text;for(const [p,r] of RULES)next=next.replace(p,r);return next}
function skip(el){return !el||Boolean(el.closest('[data-language-343],script,style,noscript,textarea,code,pre'))}
function translateTextNode(node){if(!active||!node||node.nodeType!==Node.TEXT_NODE||skip(node.parentElement))return;const current=node.nodeValue||'',prev=TEXT_SOURCE.get(node),source=prev&&current===prev.rendered?prev.source:current,rendered=translate(source);TEXT_SOURCE.set(node,{source,rendered});if(current!==rendered)node.nodeValue=rendered}
function restoreTextNode(node){if(!node||node.nodeType!==Node.TEXT_NODE||skip(node.parentElement))return;const prev=TEXT_SOURCE.get(node);if(prev&&node.nodeValue===prev.rendered)node.nodeValue=prev.source;TEXT_SOURCE.delete(node)}
function translateAttribute(el,attr){if(!active||skip(el)||!el.hasAttribute(attr))return;let rec=ATTR_SOURCE.get(el);if(!rec){rec=new Map();ATTR_SOURCE.set(el,rec)}const current=el.getAttribute(attr)??'',prev=rec.get(attr),source=prev&&current===prev.rendered?prev.source:current,rendered=translate(source);rec.set(attr,{source,rendered});if(current!==rendered)el.setAttribute(attr,rendered)}
function restoreAttribute(el,attr){const rec=ATTR_SOURCE.get(el),prev=rec?.get(attr);if(!prev)return;if(el.getAttribute(attr)===prev.rendered)el.setAttribute(attr,prev.source);rec.delete(attr)}
function visit(root,mode){if(!root)return;const textFn=mode==='restore'?restoreTextNode:translateTextNode,attrFn=mode==='restore'?restoreAttribute:translateAttribute;if(root.nodeType===Node.TEXT_NODE){textFn(root);return}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_FRAGMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE)return;const applyEl=el=>{if(skip(el))return;attrFn(el,'placeholder');attrFn(el,'aria-label');attrFn(el,'title')};if(root.nodeType===Node.ELEMENT_NODE)applyEl(root);root.querySelectorAll?.('*').forEach(applyEl);const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))textFn(node)}
function setTitle(){const page=document.body?.dataset.page||'';if(TITLES[page])document.title=TITLES[page]}
function enableOption(){const select=document.getElementById(SELECT_ID),option=select?.querySelector(`option[value="${CODE}"]`);if(option)option.disabled=false;const language=baseApi?.languages?.find?.(x=>x.code===CODE);if(language)language.ready=true}
function resetCurrentLanguage(){const api=window.NOMAD343_LANGUAGE;if(api&&typeof api.set==='function')api.set('en');else if(baseSet)baseSet('en')}
function activate({persist=true,emit=true}={}){resetCurrentLanguage();active=true;enableOption();document.documentElement.lang=CODE;document.documentElement.dataset.language343=CODE;setTitle();visit(document.body,'translate');const select=document.getElementById(SELECT_ID);if(select)select.value=CODE;if(persist){try{localStorage.setItem(STORAGE_KEY,CODE)}catch{}}if(emit)document.dispatchEvent(new CustomEvent('nomad343:language-change',{detail:{language:CODE}}))}
function deactivate(code,{forward=true}={}){if(active)visit(document.body,'restore');active=false;if(forward&&baseSet)baseSet(code);else if(forward){try{localStorage.setItem(STORAGE_KEY,code)}catch{}}}
function intercept(event){const select=event.target?.id===SELECT_ID?event.target:null;if(!select)return;const code=select.value;if(code===CODE){activate({persist:true,emit:true});event.stopPropagation();return}if(active)deactivate(code,{forward:false})}
function startObserver(){if(observer||!document.body)return;observer=new MutationObserver(records=>{if(!active)return;for(const record of records){if(record.type==='characterData'){translateTextNode(record.target);continue}for(const node of record.addedNodes||[]){try{window.NOMAD343_FOOTBALL_EN?.normalize?.(node)}catch{}visit(node,'translate')}}});observer.observe(document.body,{subtree:true,childList:true,characterData:true})}
function patchApi(){baseApi=window.NOMAD343_LANGUAGE||null;if(!baseApi)return;baseSet=typeof baseApi.set==='function'?baseApi.set.bind(baseApi):null;baseCurrent=typeof baseApi.current==='function'?baseApi.current.bind(baseApi):()=> 'en';enableOption();baseApi.current=()=>active?CODE:baseCurrent();baseApi.set=code=>{if(code===CODE)return activate({persist:true,emit:true});if(active)return deactivate(code,{forward:true});return baseSet?baseSet(code):undefined}}
function mount(){patchApi();enableOption();startObserver();let saved='';try{saved=localStorage.getItem(STORAGE_KEY)||''}catch{}if(saved===CODE)activate({persist:false,emit:false})}
window.addEventListener('change',intercept,true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
window.NOMAD343_LANGUAGE_ID={version:VERSION,code:CODE};
})();
