(()=>{
'use strict';
const VERSION='343-language-ar-v1';
const CODE='ar';
const STORAGE_KEY='nomad343_language_v1';
const SELECT_ID='nomad343-language-select';

const AR=new Map(Object.entries({
'Live Scores':'النتائج المباشرة','Signals':'الإشارات','Statistics':'الإحصائيات',"Today's Matches":'مباريات اليوم',
"Live scores, match statistics and Bet365 markets for today's fixtures.":'نتائج مباشرة وإحصائيات المباراة وأسواق Bet365 لمباريات اليوم.',
'Connecting to Live Data':'جارٍ الاتصال بالبيانات المباشرة','Search teams or leagues…':'ابحث عن فريق أو دوري…','Today':'اليوم','Local Time':'التوقيت المحلي','Bet365 Live Markets':'أسواق Bet365 المباشرة',
'Live':'مباشر','Upcoming':'قادمة','Finished':'انتهت','Unconfirmed':'غير مؤكدة','No Live Matches':'لا توجد مباريات مباشرة',"Waiting for Today's Fixtures":'في انتظار مباريات اليوم','No Finished Matches':'لا توجد مباريات منتهية','No Unconfirmed Matches':'لا توجد مباريات غير مؤكدة','No More Upcoming Matches':'لا توجد مباريات قادمة إضافية',
'Select a match to view match details, statistics, event flow and Bet365 markets.':'اختر مباراة لعرض التفاصيل والإحصائيات وسير المباراة وأسواق Bet365.',
'Latest Match Data':'أحدث بيانات المباراة','Match Statistics':'إحصائيات المباراة','Shots on Target':'تسديدات على المرمى','Shots off Target':'تسديدات خارج المرمى','Corners':'ركلات ركنية','Attacks':'هجمات','Dangerous Attacks':'هجمات خطيرة','Possession':'الاستحواذ','Attack Percentage':'نسبة الهجمات','Dangerous Attack Percentage':'نسبة الهجمات الخطيرة','Possession Percentage':'نسبة الاستحواذ',
'Building Event History':'جارٍ تجميع سجل الأحداث','No Bookmaker Odds Available':'لا توجد احتمالات متاحة من شركة المراهنات','Building Odds Movement History':'جارٍ تجميع سجل حركة الاحتمالات','Live Data Unavailable':'البيانات المباشرة غير متاحة','Live Data Delayed':'البيانات المباشرة متأخرة','Live data':'بيانات مباشرة','Waiting for Data':'في انتظار البيانات','Signal Locked':'تم قفل الإشارة','No Signal':'لا توجد إشارة','Signal —':'إشارة —','Half-Time':'نهاية الشوط الأول','Full-Time':'نهاية المباراة',
'Event Flow':'سير المباراة','Event Flow · Match History':'سير المباراة · سجل المباراة','Event Flow · Attack Momentum':'سير المباراة · زخم الهجوم','Attack intensity from recent match data':'شدة الهجوم وفق أحدث بيانات المباراة','Attack Momentum graph':'رسم زخم الهجوم','Odds Movement':'حركة الاحتمالات','Observed Odds':'الاحتمالات المرصودة','Building Attack Momentum History':'جارٍ تجميع سجل زخم الهجوم','Loading Attack Momentum History…':'جارٍ تحميل سجل زخم الهجوم…','Event Flow Unavailable':'سير المباراة غير متاح',
'Active Signals':'الإشارات النشطة','Live selections with entry odds, entry score and current match status in one card.':'اختيارات مباشرة مع احتمالات الدخول ونتيجة الدخول وحالة المباراة الحالية في بطاقة واحدة.','Connecting to Active Signals':'جارٍ الاتصال بالإشارات النشطة','Active Matches':'المباريات ذات الإشارة','One match per card':'مباراة واحدة لكل بطاقة','All markets currently being tracked':'جميع الأسواق التي تتم متابعتها حاليًا','Live Tracking':'متابعة مباشرة','Now':'الآن','Minute · Score · Match Data':'الدقيقة · النتيجة · بيانات المباراة','Results':'النتائج','Settled signals move to Statistics':'تنتقل الإشارات المحسومة إلى الإحصائيات',
'System selections, entry odds and current match status. Select a card to view full details.':'اختيارات النظام واحتمالات الدخول وحالة المباراة الحالية. اختر بطاقة لعرض التفاصيل كاملة.','Active Only':'النشطة فقط','Waiting for Live Signals':'في انتظار الإشارات المباشرة','When a signal is settled as Win, Loss or Push, it leaves this page and moves to Statistics.':'عند حسم الإشارة كفوز أو خسارة أو رهان مسترد، تنتقل من هذه الصفحة إلى الإحصائيات.','No Active Signals':'لا توجد إشارات نشطة','There are no active signals right now':'لا توجد إشارات نشطة حاليًا','Active Signals Unavailable':'الإشارات النشطة غير متاحة',
'Signal Time':'وقت الإشارة','Entry Score':'النتيجة عند الدخول','Pick':'الاختيار','Line':'الخط','Entry Odds':'احتمالات الدخول','Bookmaker':'شركة المراهنات','Entry Match Statistics':'إحصائيات المباراة عند الدخول','Signal Criteria':'معايير الإشارة','Match statistics at signal entry':'إحصائيات المباراة عند لحظة الدخول','Criteria met when the signal was created':'المعايير التي تحققت عند إنشاء الإشارة','Live Match Statistics':'إحصائيات المباراة المباشرة','Signal Tracker':'متابعة الإشارة','Entry status compared with the current match':'حالة الدخول مقارنةً بالمباراة الحالية','Signal Details':'تفاصيل الإشارة','Entry Locked':'تم قفل الدخول','Technical Details':'التفاصيل الفنية','Provider Market':'سوق مزود البيانات','Rolling Window':'نافذة التحليل','5USD Raw Line':'خط 5USD الخام','Feed Age':'عمر البيانات','Events':'الأحداث','Raw Card Count':'العدد الخام للبطاقات','Pass':'مستوفى','Not Met':'غير مستوفى','Required':'مطلوب',
'Settled Signals':'الإشارات المحسومة','Track active signals above and review settled results below.':'تابع الإشارات النشطة أعلاه وراجع النتائج المحسومة أدناه.','Connecting to Statistics':'جارٍ الاتصال بالإحصائيات','Live Signal Tracker':'متابعة الإشارات المباشرة','Live minute and score from the Signals page. Select a card to view details for an active match.':'الدقيقة والنتيجة المباشرة من صفحة الإشارات. اختر بطاقة لعرض تفاصيل المباراة النشطة.','Waiting for Active Signals':'في انتظار الإشارات النشطة','Results already settled':'نتائج تم حسمها بالفعل','Wins':'فوز','Full wins':'فوز كامل','Losses':'خسارة','Full losses':'خسارة كاملة','Win Rate':'نسبة النجاح','Push excluded · half results weighted':'الرهانات المستردة مستبعدة · النتائج النصفية موزونة','Average Entry Odds':'متوسط احتمالات الدخول','Average odds when signals were created':'متوسط الاحتمالات عند إنشاء الإشارات','Results History':'سجل النتائج','Entry odds and settled results by market · Time shown in':'احتمالات الدخول والنتائج المحسومة حسب السوق · الوقت المعروض حسب','All Market Results':'نتائج جميع الأسواق','Date & Time':'التاريخ والوقت','League / Match':'الدوري / المباراة','Market':'السوق','Full-Time Score':'النتيجة النهائية','Result':'النتيجة','Waiting for Settled Results':'في انتظار النتائج المحسومة',
'Supports Win, Loss, Push, Half Win and Half Loss. If required settlement data is unavailable, the result remains Unresolved.':'يدعم الفوز والخسارة والرهان المسترد ونصف الفوز ونصف الخسارة. إذا لم تتوفر بيانات الحسم المطلوبة تبقى النتيجة معلقة.','No Settled Results Yet':'لا توجد نتائج محسومة حتى الآن','Statistics Unavailable':'الإحصائيات غير متاحة','Win':'فوز','Loss':'خسارة','Push':'مسترد','Half Win':'نصف فوز','Half Loss':'نصف خسارة','Unresolved':'معلق','All Markets':'جميع الأسواق','Half Results':'نتائج نصفية',
'BET365 · FULL MARKET ODDS':'BET365 · احتمالات جميع الأسواق','Match Result · Full Time':'نتيجة المباراة · المباراة كاملة','Match Result · First Half':'نتيجة المباراة · الشوط الأول','Asian Handicap · Full Time':'الهانديكاب الآسيوي · المباراة كاملة','Asian Handicap · First Half':'الهانديكاب الآسيوي · الشوط الأول','Goals Over / Under · Full Time':'الأهداف أكثر / أقل · المباراة كاملة','Goals Over / Under · First Half':'الأهداف أكثر / أقل · الشوط الأول','Goals Over · Full Time':'الأهداف أكثر · المباراة كاملة','Goals Under · Full Time':'الأهداف أقل · المباراة كاملة','Goals Over · First Half':'الأهداف أكثر · الشوط الأول','Goals Under · First Half':'الأهداف أقل · الشوط الأول','Corners Over / Under · Full Time':'الركنيات أكثر / أقل · المباراة كاملة','Corners Over / Under · First Half':'الركنيات أكثر / أقل · الشوط الأول','Corners Over · Full Time':'الركنيات أكثر · المباراة كاملة','Corners Under · Full Time':'الركنيات أقل · المباراة كاملة','Corners Over · First Half':'الركنيات أكثر · الشوط الأول','Corners Under · First Half':'الركنيات أقل · الشوط الأول','Corners Asian Handicap':'الهانديكاب الآسيوي للركنيات','Cards Over / Under · Full Time':'البطاقات أكثر / أقل · المباراة كاملة','Cards Over · Full Time':'البطاقات أكثر · المباراة كاملة','Cards Under · Full Time':'البطاقات أقل · المباراة كاملة','Cards Asian Handicap':'الهانديكاب الآسيوي للبطاقات','Both Teams to Score':'كلا الفريقين يسجلان','Both Teams to Score · Yes':'كلا الفريقين يسجلان · نعم','Both Teams to Score · No':'كلا الفريقين يسجلان · لا','In-Play Odds':'الاحتمالات المباشرة','Pre-Match Odds':'احتمالات ما قبل المباراة','Opening Odds':'الاحتمالات الافتتاحية','Home':'صاحب الأرض','Away':'الضيف','HOME':'صاحب الأرض','AWAY':'الضيف','Draw':'تعادل','Over':'أكثر','Under':'أقل','Yes':'نعم','No':'لا','Loading':'جارٍ التحميل','Odds —':'الاحتمالات —','Full Market Odds Unavailable':'احتمالات جميع الأسواق غير متاحة','Loading Full Bet365 Lines and Odds':'جارٍ تحميل خطوط واحتمالات Bet365 كاملة','Full Market Odds Are Unavailable for This Match':'احتمالات جميع الأسواق غير متاحة لهذه المباراة'
}));

function countSignals(n){const x=Number(n);if(x===1)return'إشارة واحدة';if(x===2)return'إشارتان';if(x>=3&&x<=10)return`${n} إشارات`;return`${n} إشارة`}
function countMatches(n){const x=Number(n);if(x===1)return'مباراة واحدة';if(x===2)return'مباراتان';if(x>=3&&x<=10)return`${n} مباريات`;return`${n} مباراة`}
const RULES=[
[/^(\d+) Active Signal(?:s)? in this match$/i,(_,n)=>`${countSignals(n)} في هذه المباراة`],
[/^(\d+) Signal(?:s)? · Details$/i,(_,n)=>`${countSignals(n)} · التفاصيل`],
[/^Active Signals · (\d+) match(?:es)?(?: · (\d+) signal(?:s)?)?(?: · data age (\d+)s)?$/i,(_,m,s,a)=>`إشارات نشطة · ${countMatches(m)}${s?` · ${countSignals(s)}`:''}${a?` · عمر البيانات ${a} ث`:''}`],
[/^(\d+) Points$/i,'$1 نقاط'],[/^(\d+) Markets$/i,'$1 أسواق'],[/^Half-Time\s+(.+)$/i,'نهاية الشوط الأول $1'],[/^Full Time · (.+)$/i,'المباراة كاملة · $1'],[/^First Half · (.+)$/i,'الشوط الأول · $1'],[/^Revised from (.+?) · /i,'تمت المراجعة من $1 · '],
[/^Attack trend from recent match data · (\d+)-minute rate · smoothed trend$/i,'اتجاه الهجوم من أحدث البيانات · معدل $1 دقائق · اتجاه سلس'],[/^Timeline uses observed match data · both teams measured independently$/i,'الخط الزمني يستخدم بيانات المباراة المرصودة · يتم قياس الفريقين بشكل مستقل'],[/^Momentum = Dangerous Attacks 30 · Shots on Target 25 · Attacks 20 · Shots off Target 10 · Corners 10 · Possession 5$/i,'الزخم = هجمات خطيرة 30 · تسديدات على المرمى 25 · هجمات 20 · تسديدات خارج المرمى 10 · ركنيات 10 · استحواذ 5'],[/^Event Flow uses observed match history · Bookmaker odds show observed data only/i,'سير المباراة يستخدم السجل المرصود · احتمالات شركة المراهنات تعرض البيانات المرصودة فقط'],[/ · this match is unconfirmed and cannot be settled$/i,' · هذه المباراة غير مؤكدة ولا يمكن حسمها'],
[/\bMatch Statistics\b/g,'إحصائيات المباراة'],[/5USD Full Market Odds/g,'احتمالات 5USD الكاملة'],[/\s+vs\s+/gi,' ضد '],[/→\s*Live$/i,'→ مباشر'],[/\bHalf Win\b/g,'نصف فوز'],[/\bHalf Loss\b/g,'نصف خسارة'],[/\bUnresolved\b/g,'معلق'],[/\bWin\b/g,'فوز'],[/\bLoss\b/g,'خسارة'],[/\bPush\b/g,'مسترد'],[/\bNot Met\b/g,'غير مستوفى'],[/\bRequired\b/g,'مطلوب'],[/\bPass\b/g,'مستوفى'],[/·\s*Full Time\b/g,'· المباراة كاملة'],[/·\s*First Half\b/g,'· الشوط الأول'],[/·\s*FT\b/g,'· المباراة كاملة'],[/·\s*HT\b/g,'· الشوط الأول'],[/\bAll Markets\b/g,'جميع الأسواق'],[/\bUnresolved (\d+)\b/gi,'معلق $1'],[/ · Half Results (\d+\/\d+)$/i,' · نتائج نصفية $1']
];

const TITLES={live:'nomadtips3 · النتائج المباشرة 3.43',signal:'nomadtips3 · الإشارات 3.43',statistics:'nomadtips3 · الإحصائيات 3.43'};
const TEXT_SOURCE=new WeakMap(),ATTR_SOURCE=new WeakMap();
let active=false,observer=null,baseApi=null,baseSet=null,baseCurrent=null;
function translate(text){let next=AR.get(text)??text;for(const [p,r] of RULES)next=next.replace(p,r);return next}
function skip(el){return !el||Boolean(el.closest('[data-language-343],script,style,noscript,textarea,code,pre'))}
function translateTextNode(node){if(!active||!node||node.nodeType!==Node.TEXT_NODE||skip(node.parentElement))return;const current=node.nodeValue||'',prev=TEXT_SOURCE.get(node),source=prev&&current===prev.rendered?prev.source:current,rendered=translate(source);TEXT_SOURCE.set(node,{source,rendered});if(current!==rendered)node.nodeValue=rendered}
function restoreTextNode(node){if(!node||node.nodeType!==Node.TEXT_NODE||skip(node.parentElement))return;const prev=TEXT_SOURCE.get(node);if(prev&&node.nodeValue===prev.rendered)node.nodeValue=prev.source;TEXT_SOURCE.delete(node)}
function translateAttribute(el,attr){if(!active||skip(el)||!el.hasAttribute(attr))return;let rec=ATTR_SOURCE.get(el);if(!rec){rec=new Map();ATTR_SOURCE.set(el,rec)}const current=el.getAttribute(attr)??'',prev=rec.get(attr),source=prev&&current===prev.rendered?prev.source:current,rendered=translate(source);rec.set(attr,{source,rendered});if(current!==rendered)el.setAttribute(attr,rendered)}
function restoreAttribute(el,attr){const rec=ATTR_SOURCE.get(el),prev=rec?.get(attr);if(!prev)return;if(el.getAttribute(attr)===prev.rendered)el.setAttribute(attr,prev.source);rec.delete(attr)}
function visit(root,mode){if(!root)return;const textFn=mode==='restore'?restoreTextNode:translateTextNode,attrFn=mode==='restore'?restoreAttribute:translateAttribute;if(root.nodeType===Node.TEXT_NODE){textFn(root);return}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_FRAGMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE)return;const applyEl=el=>{if(skip(el))return;attrFn(el,'placeholder');attrFn(el,'aria-label');attrFn(el,'title')};if(root.nodeType===Node.ELEMENT_NODE)applyEl(root);root.querySelectorAll?.('*').forEach(applyEl);const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode()))textFn(node)}
function setTitle(){const page=document.body?.dataset.page||'';if(TITLES[page])document.title=TITLES[page]}
function enableOption(){const select=document.getElementById(SELECT_ID),option=select?.querySelector(`option[value="${CODE}"]`);if(option)option.disabled=false;const language=baseApi?.languages?.find?.(x=>x.code===CODE);if(language)language.ready=true}
function resetCurrentLanguage(){const api=window.NOMAD343_LANGUAGE;if(api&&typeof api.set==='function')api.set('en');else if(baseSet)baseSet('en')}
function activate({persist=true,emit=true}={}){resetCurrentLanguage();active=true;enableOption();document.documentElement.lang=CODE;document.documentElement.dataset.language343=CODE;setTitle();visit(document.body,'translate');const select=document.getElementById(SELECT_ID);if(select)select.value=CODE;if(persist){try{localStorage.setItem(STORAGE_KEY,CODE)}catch{}}if(emit)document.dispatchEvent(new CustomEvent('nomad343:language-change',{detail:{language:CODE}}))}
function deactivate(code,{forward=true}={}){if(active)visit(document.body,'restore');active=false;if(forward&&baseSet)baseSet(code);else if(forward){try{localStorage.setItem(STORAGE_KEY,code)}catch{}}}
function intercept(event){const select=event.target?.id===SELECT_ID?event.target:null;if(!select)return;const code=select.value;if(code===CODE){activate({persist:true,emit:true});event.stopPropagation();return}if(active)deactivate(code,{forward:false})}
function startObserver(){if(observer||!document.body)return;observer=new MutationObserver(records=>{if(!active)return;for(const record of records){if(record.type==='characterData'){translateTextNode(record.target);continue}for(const node of record.addedNodes||[]){try{window.NOMAD343_FOOTBALL_EN?.normalize?.(node)}catch{}visit(node,'translate')}}});observer.observe(document.body,{subtree:true,childList:true,characterData:true})}
function patchApi(){baseApi=window.NOMAD343_LANGUAGE||null;if(!baseApi)return;baseSet=typeof baseApi.set==='function'?baseApi.set.bind(baseApi):null;baseCurrent=typeof baseApi.current==='function'?baseApi.current.bind(baseApi):()=> 'en';enableOption();baseApi.current=()=>active?CODE:baseCurrent();baseApi.set=code=>{if(code===CODE)return activate({persist:true,emit:true});if(active)return deactivate(code,{forward:true});return baseSet?baseSet(code):undefined}}
function mount(){patchApi();enableOption();startObserver();let saved='';try{saved=localStorage.getItem(STORAGE_KEY)||''}catch{}if(saved===CODE)activate({persist:false,emit:false})}
window.addEventListener('change',intercept,true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
window.NOMAD343_LANGUAGE_AR={version:VERSION,code:CODE};
})();
