(()=>{
'use strict';
const VERSION='343-settings-allmarkets-v2-fullmarket';
const API='/api/engine/settings';
const FULL_MARKET_API='/api/full-market/settings';
let settings={},runState={},markets={};
let fullMarket=null,fullMarketDefaults={refreshSeconds:30,workerCacheSeconds:30,eventTrigger:true,softLimitPerMinute:24};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v===null||v===undefined||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))?null:Number(v);
const clone=v=>JSON.parse(JSON.stringify(v));
const lowRule=k=>/_under$|_btts_no$/.test(k);
const basisLabel=d=>d?.basis==='corners'?'เตะมุม':d?.basis==='cards'?'การ์ด':'ประตู';
function state(text,type='live'){const el=document.querySelector('[data-engine-state]');if(el)el.innerHTML=`<i class="dot ${type}"></i>${esc(text)}`}
function fullState(text,type='live'){const el=document.querySelector('[data-full-market-state]');if(el)el.innerHTML=`<i class="dot ${type}"></i>${esc(text)}`}
function statusCard(key,def){return `<article class="status-item" data-status="${esc(key)}"><span>${esc(def.label)}</span><b>${runState[key]?'RUN':'STOP'}</b></article>`}
function evidenceFields(key){const word=lowRule(key)?'ไม่เกิน':'ตั้งแต่';return `
  <section class="group"><div class="group-head"><b>หลักฐานใน Rolling Window</b><small>${lowRule(key)?'LOW pressure gate':'HIGH pressure gate'} · ไม่มีข้อมูล = ไม่ผ่าน</small></div><div class="grid">
    <label><span>ยิงเข้ากรอบ ${word}</span><div class="unit"><input name="shotOnTarget" type="number" min="0" max="50"><em>ครั้ง</em></div></label>
    <label><span>ยิงไม่เข้ากรอบ ${word}</span><div class="unit"><input name="shotOff" type="number" min="0" max="50"><em>ครั้ง</em></div></label>
    <label><span>เตะมุม ${word}</span><div class="unit"><input name="corner" type="number" min="0" max="50"><em>ครั้ง</em></div></label>
    <label><span>การบุก ${word}</span><div class="unit"><input name="attackPct" type="number" min="0" max="100"><em>%</em></div></label>
    <label><span>การบุกอันตราย ${word}</span><div class="unit"><input name="dangerousAttackPct" type="number" min="0" max="100"><em>%</em></div></label>
    <label><span>ครองบอล ${word}</span><div class="unit"><input name="possessionPct" type="number" min="0" max="100"><em>%</em></div></label>
    <label class="wide"><span>ต้องการหลักฐาน</span><select name="evidenceRequired">${[1,2,3,4,5,6].map(x=>`<option value="${x}">${x}</option>`).join('')}</select><small>จำนวนข้อจากทั้งหมด 6 ข้อ</small></label>
  </div></section>`}
function sideFields(def){if(!def.sideMode)return'';if(def.kind==='1X2')return `<section class="group"><div class="group-head"><b>ตัวเลือก Signal</b></div><div class="choice"><label><input type="radio" name="sideMode" value="HOME">Home</label><label><input type="radio" name="sideMode" value="AWAY">Away</label><label><input type="radio" name="sideMode" value="DRAW">Draw</label><label><input type="radio" name="sideMode" value="BOTH">Home + Away</label><label><input type="radio" name="sideMode" value="ALL">All 1X2</label></div></section>`;return `<section class="group"><div class="group-head"><b>เลือกฝั่ง</b></div><div class="choice"><label><input type="radio" name="sideMode" value="HOME">Home</label><label><input type="radio" name="sideMode" value="AWAY">Away</label><label><input type="radio" name="sideMode" value="BOTH">Both</label></div></section>`}
function priceFields(key,def,cfg){let extra='';if(def.kind==='AH')extra=`<label><span>Line ตั้งแต่</span><input name="lineMin" type="number" step="0.25"></label><label><span>Line ไม่เกิน</span><input name="lineMax" type="number" step="0.25"></label>`;else if(def.kind==='OU'&&def.gap)extra=`<label><span>Line ตั้งแต่</span><input name="lineMin" type="number" step="0.25"></label><label><span>ระยะห่าง Line จาก${basisLabel(def)}ปัจจุบัน ไม่เกิน</span><select name="lineGapMax">${[0.5,1,1.5,2,2.5,999].map(x=>`<option value="${x}">${x===999?'ไม่จำกัด':x.toFixed(1)}</option>`).join('')}</select></label>`;else if(def.kind==='OU')extra=`<label><span>Line ตั้งแต่</span><input name="lineMin" type="number" step="0.25"></label><label><span>Line ไม่เกิน</span><input name="lineMax" type="number" step="0.25"></label>`;const score=def.kind==='1X2'?`<label><span>ตามหลังได้ไม่เกิน</span><input name="scoreTrailingMax" type="number" min="0" max="10" step="1"></label>`:'';return `<section class="group"><div class="group-head"><b>ราคา Bet365 · IN-PLAY</b><small>${esc(def.provider)} · ไม่ใช้ Closing แทน Live</small></div><div class="grid">${extra}<label><span>ราคา ตั้งแต่</span><input name="oddsMin" type="number" min="1.01" step="0.01"></label><label><span>ราคา ไม่เกิน</span><input name="oddsMax" type="number" min="1.01" step="0.01"></label>${score}</div></section>`}
function timeFields(){return `<section class="group"><div class="group-head"><b>ช่วงเวลาทำงาน</b></div><div class="grid"><label><span>นาทีเริ่ม</span><input name="minuteFrom" type="number" min="0" max="120"></label><label><span>นาทีจบ</span><input name="minuteTo" type="number" min="0" max="120"></label><label><span>Rolling Window</span><div class="unit"><input name="rollingWindowMinutes" type="number" min="2" max="30"><em>นาที</em></div></label></div></section>`}
function ruleCard(key,def){const cfg=settings[key]||{};return `<article class="settings-card rule-card" data-rule="${esc(key)}"><form data-form="${esc(key)}"><header class="settings-title"><div><small>${esc(def.group)} · ${esc(def.provider)}</small><h2>${esc(def.label)}</h2></div><p>${def.period==='HT'?'FIRST-HALF GUARD เปิดใช้งาน':'FULL-TIME MARKET'} · ${def.selection?`Selection ${esc(def.selection)}`:'เลือกฝั่งได้'}</p></header>${sideFields(def)}${evidenceFields(key)}${priceFields(key,def,cfg)}${timeFields()}<footer class="actions"><div class="message" data-message>พร้อมตั้งค่า</div><div class="buttons"><button type="button" class="stop" data-stop>STOP</button><button type="submit" class="save">บันทึก</button><button type="button" class="run" data-run>RUN</button></div></footer></form></article>`}
function fill(form,cfg){for(const el of form.elements){if(!el.name)continue;if(el.type==='radio')el.checked=String(el.value).toUpperCase()===String(cfg[el.name]??'').toUpperCase();else if(cfg[el.name]!==undefined)el.value=String(cfg[el.name])}}
function read(form,key){const out=clone(settings[key]||{});for(const el of form.elements){if(!el.name)continue;if(el.type==='radio'){if(el.checked)out[el.name]=el.value;continue}out[el.name]=Number(el.value)}return out}
function validate(key,cfg){const e=[];for(const k of ['shotOnTarget','shotOff','corner'])if(num(cfg[k])===null||cfg[k]<0||cfg[k]>50)e.push('ค่าจำนวนครั้งต้องอยู่ระหว่าง 0–50');for(const k of ['attackPct','dangerousAttackPct','possessionPct'])if(num(cfg[k])===null||cfg[k]<0||cfg[k]>100)e.push('เปอร์เซ็นต์ต้องอยู่ระหว่าง 0–100');if(num(cfg.evidenceRequired)===null||cfg.evidenceRequired<1||cfg.evidenceRequired>6)e.push('Evidence ต้องอยู่ระหว่าง 1–6');if(num(cfg.minuteFrom)===null||num(cfg.minuteTo)===null||cfg.minuteFrom>cfg.minuteTo)e.push('ช่วงนาทีไม่ถูกต้อง');if(num(cfg.rollingWindowMinutes)===null||cfg.rollingWindowMinutes<2||cfg.rollingWindowMinutes>30)e.push('Rolling Window ต้อง 2–30 นาที');if(num(cfg.oddsMin)===null||cfg.oddsMin<1.01||num(cfg.oddsMax)===null||cfg.oddsMax<cfg.oddsMin)e.push('ช่วงราคาไม่ถูกต้อง');const lmin=num(cfg.lineMin),lmax=num(cfg.lineMax);if(lmin!==null&&Math.abs(lmin*4-Math.round(lmin*4))>1e-8)e.push('Line ตั้งแต่ ต้องเป็นขั้น 0.25');if(lmax!==null&&Math.abs(lmax*4-Math.round(lmax*4))>1e-8)e.push('Line ไม่เกิน ต้องเป็นขั้น 0.25');if(lmin!==null&&lmax!==null&&lmin>lmax)e.push('ช่วง Line ไม่ถูกต้อง: ค่าตั้งแต่ต้องไม่มากกว่าค่าไม่เกิน');if('lineGapMax'in cfg&&![0.5,1,1.5,2,2.5,999].includes(Number(cfg.lineGapMax)))e.push('Gap ต้องเป็น 0.5 / 1 / 1.5 / 2 / 2.5 / ไม่จำกัด');return e}
function note(form,msg){const el=form.querySelector('[data-message]');if(el)el.textContent=msg}
function syncStatus(){const board=document.querySelector('[data-status-board]');if(board)board.innerHTML=Object.entries(markets).map(([k,d])=>statusCard(k,d)).join('');document.querySelectorAll('[data-status]').forEach(el=>el.classList.toggle('run',!!runState[el.dataset.status]))}
async function push(){const r=await fetch(API,{method:'PUT',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify({settings,runState})});const j=await r.json().catch(()=>null);if(!r.ok||j?.ok!==true)throw new Error(j?.error||`HTTP_${r.status}`);settings=j.settings;runState=j.runState;markets=j.markets||markets;syncStatus();return j}
async function loadEngine(){const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'});const j=await r.json();if(!r.ok||j?.ok!==true)throw new Error(j?.error||`HTTP_${r.status}`);settings=j.settings||{};runState=j.runState||{};markets=j.markets||{};return j}
function bindForms(){for(const [key] of Object.entries(markets)){const form=document.querySelector(`[data-form="${CSS.escape(key)}"]`);if(!form)continue;fill(form,settings[key]||{});form.addEventListener('submit',async e=>{e.preventDefault();const cfg=read(form,key),err=validate(key,cfg);if(err.length){note(form,err[0]);return}const before=clone(settings[key]||{});settings[key]=cfg;note(form,'กำลังบันทึก…');try{await push();fill(form,settings[key]);note(form,'บันทึกเข้า Engine แล้ว')}catch(error){settings[key]=before;fill(form,before);note(form,`บันทึกไม่สำเร็จ · ${error.message}`)}});form.querySelector('[data-run]')?.addEventListener('click',async()=>{const cfg=read(form,key),err=validate(key,cfg);if(err.length){note(form,err[0]);return}const beforeRun=!!runState[key],beforeCfg=clone(settings[key]||{});settings[key]=cfg;runState[key]=true;syncStatus();note(form,'กำลัง RUN…');try{await push();note(form,'RUN แล้ว · ใช้ Price Referee จริง')}catch(error){runState[key]=beforeRun;settings[key]=beforeCfg;fill(form,beforeCfg);syncStatus();note(form,`RUN ไม่สำเร็จ · ${error.message}`)}});form.querySelector('[data-stop]')?.addEventListener('click',async()=>{const beforeRun=!!runState[key];runState[key]=false;syncStatus();note(form,'กำลัง STOP…');try{await push();note(form,'STOP แล้ว')}catch(error){runState[key]=beforeRun;syncStatus();note(form,`STOP ไม่สำเร็จ · ${error.message}`)}})}}
function render(){for(const group of ['FULL TIME','FIRST HALF','CORNERS','CARDS & BTTS']){const el=document.querySelector(`[data-group-panel="${group}"]`);if(el)el.innerHTML=Object.entries(markets).filter(([,d])=>d.group===group).map(([k,d])=>ruleCard(k,d)).join('')}syncStatus();bindForms();document.querySelectorAll('[data-group-tab]').forEach(btn=>btn.addEventListener('click',()=>{const g=btn.dataset.groupTab;document.querySelectorAll('[data-group-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('[data-group-panel]').forEach(p=>p.hidden=p.dataset.groupPanel!==g)}))}
async function bootEngine(){try{await loadEngine();render();state(`Engine ONLINE · ${Object.keys(markets).length} กฎตรวจจับ`,'live')}catch(error){state(`Engine OFFLINE · ${error.message}`,'warn')}}

function fullMessage(text){const el=document.querySelector('[data-full-market-message]');if(el)el.textContent=text}
function fillFullMarket(control){const form=document.querySelector('[data-full-market-form]');if(!form||!control)return;for(const key of ['refreshSeconds','workerCacheSeconds','softLimitPerMinute']){const el=form.elements.namedItem(key);if(el)el.value=String(control[key])}const ev=form.elements.namedItem('eventTrigger');if(ev)ev.checked=Boolean(control.eventTrigger)}
function readFullMarket(){const form=document.querySelector('[data-full-market-form]');return {refreshSeconds:Number(form?.elements.namedItem('refreshSeconds')?.value),workerCacheSeconds:Number(form?.elements.namedItem('workerCacheSeconds')?.value),eventTrigger:Boolean(form?.elements.namedItem('eventTrigger')?.checked),softLimitPerMinute:Number(form?.elements.namedItem('softLimitPerMinute')?.value)}}
function validateFullMarket(cfg){if(!Number.isFinite(cfg.refreshSeconds)||cfg.refreshSeconds<10||cfg.refreshSeconds>120)return'Refresh ต้องอยู่ 10–120 วินาที';if(!Number.isFinite(cfg.workerCacheSeconds)||cfg.workerCacheSeconds<10||cfg.workerCacheSeconds>120)return'Worker Cache ต้องอยู่ 10–120 วินาที';if(!Number.isFinite(cfg.softLimitPerMinute)||cfg.softLimitPerMinute<1||cfg.softLimitPerMinute>36)return'Soft Limit ต้องอยู่ 1–36 requests/min';return''}
function paintFullMarketMeter(j){const used=Number(j?.usedInWindow??j?.rate?.usedInWindow??0),soft=Number(j?.control?.softLimitPerMinute??24),account=Number(j?.accountLimitPerMinute??j?.rate?.accountLimitPerMinute??40);const u=document.querySelector('[data-full-market-used]'),s=document.querySelector('[data-full-market-soft]'),a=document.querySelector('[data-account-limit]'),r=document.querySelector('[data-full-market-rate-state]');if(u)u.textContent=String(used);if(s)s.textContent=String(soft);if(a)a.value=String(account);if(r){const ratio=soft>0?used/soft:0;r.textContent=ratio>=1?'LIMIT':ratio>=.8?'WATCH':'CLEAR';r.className=ratio>=1?'rate-red':ratio>=.8?'rate-yellow':'rate-green'}}
async function loadFullMarket(){const r=await fetch(`${FULL_MARKET_API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json().catch(()=>null);if(!r.ok||j?.ok!==true)throw new Error(j?.error||`HTTP_${r.status}`);fullMarket=j.control||clone(fullMarketDefaults);fullMarketDefaults=j.defaults||fullMarketDefaults;fillFullMarket(fullMarket);paintFullMarketMeter(j);fullState(`FULL MARKET ONLINE · ${fullMarket.refreshSeconds}s`,'live');return j}
async function saveFullMarket(control){const r=await fetch(FULL_MARKET_API,{method:'PUT',headers:{'content-type':'application/json'},cache:'no-store',body:JSON.stringify({control})}),j=await r.json().catch(()=>null);if(!r.ok||j?.ok!==true)throw new Error(j?.error||`HTTP_${r.status}`);fullMarket=j.control;fillFullMarket(fullMarket);paintFullMarketMeter(j);fullState(`FULL MARKET ONLINE · ${fullMarket.refreshSeconds}s`,'live');return j}
function bindFullMarket(){const form=document.querySelector('[data-full-market-form]');if(!form||form.dataset.bound==='1')return;form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();const cfg=readFullMarket(),err=validateFullMarket(cfg);if(err){fullMessage(err);return}fullMessage('กำลังบันทึก Full Market…');try{await saveFullMarket(cfg);fullMessage(`บันทึกแล้ว · Refresh ${fullMarket.refreshSeconds}s · Cache ${fullMarket.workerCacheSeconds}s · Soft ${fullMarket.softLimitPerMinute}/min`)}catch(error){fullMessage(`บันทึกไม่สำเร็จ · ${error.message}`)}});form.querySelector('[data-full-market-reset]')?.addEventListener('click',async()=>{fullMessage('กำลังคืนค่า Default…');try{await saveFullMarket(clone(fullMarketDefaults));fullMessage('คืน Default แล้ว · 30s / 30s / Event ON / 24 per min')}catch(error){fullMessage(`RESET ไม่สำเร็จ · ${error.message}`)}})}
async function bootFullMarket(){bindFullMarket();try{await loadFullMarket();fullMessage('พร้อมตั้งค่า Full Market')}catch(error){fullState(`FULL MARKET OFFLINE · ${error.message}`,'warn');fullMessage(`อ่านค่าไม่สำเร็จ · ${error.message}`)}}
function boot(){bootEngine();bootFullMarket();setInterval(()=>loadFullMarket().catch(()=>{}),30_000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.NOMAD343_SETTINGS={version:VERSION,reload:boot,get settings(){return settings},get runState(){return runState},get markets(){return markets},get fullMarket(){return fullMarket}};
})();
