(()=>{'use strict';
const API='/api/engine/signals',POLL=30000;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const show=v=>v===null||v===undefined||v===''?'—':String(v);
function time(ms){try{return new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms))}catch{return'—'}}
function score(s){const v=s.entryScore??s.scoreAt;if(typeof v==='string')return v;if(v&&typeof v==='object')return`${show(v.home)}-${show(v.away)}`;return'—'}
function state(type,text){const el=document.querySelector('[data-signal-state]');if(el)el.innerHTML=`<span class="pill"><i class="dot ${type}"></i>${esc(text)}</span>`}
function evidenceText(s){const e=s?.evidence;if(!e)return'—';return `${show(e.count)}/${show(e.required)} · ${show(e.mode||e.side)}`}
function renderMarketSummary(rows){const el=document.querySelector('[data-signal-market-summary]');if(!el)return;const map=new Map();for(const s of rows){const key=s.providerMarket||s.market,label=s.marketLabel||s.market||'—';const rec=map.get(key)||{count:0,labels:new Set()};rec.count++;rec.labels.add(label);map.set(key,rec)}el.innerHTML=map.size?[...map].map(([key,v])=>`<article class="metric"><span>${esc(key)}</span><strong>${v.count}</strong><small>${esc([...v.labels].join(' · '))}</small></article>`).join(''):'<article class="metric"><span>MARKETS</span><strong>0</strong><small>ยังไม่มีตลาดที่ล็อกสัญญาณ</small></article>'}
function render(j){const rows=Array.isArray(j.signals)?j.signals:[];document.querySelector('[data-active]')?.replaceChildren(document.createTextNode(rows.length));renderMarketSummary(rows);const tbody=document.querySelector('[data-signal-body]');if(!tbody)return;if(!rows.length){tbody.innerHTML='<tr><td colspan="11" class="empty">ยังไม่มีสัญญาณที่ยืนยันแล้ว</td></tr>';state('live','พร้อมรับข้อมูลสัญญาณทุกตลาด');return}tbody.innerHTML=rows.map(s=>{const league=[s.league?.country,s.league?.name].filter(Boolean).join(' · '),min=s.entryMinute??s.minute;return`<tr><td>${esc(time(s.createdAt))}</td><td><span class="match-name">${esc(s.home?.name||'—')} - ${esc(s.away?.name||'—')}</span><span class="sub">${esc(league||'—')}</span></td><td class="live-minute-343">${esc(show(min))}${min==null?'':"'"}</td><td class="score">${esc(score(s))}</td><td><span class="match-name">${esc(s.marketLabel||s.market||'—')}</span><span class="sub">${esc(s.providerMarket||'—')} · ${esc(s.period||'—')}</span></td><td>${esc(show(s.selection))}</td><td>${esc(show(s.line))}</td><td class="odds">${esc(show(s.odds))}</td><td>${esc(s.bookmaker||'Bet365')}<span class="sub">${esc(s.priceStage||'inplay')}</span></td><td>${esc(evidenceText(s))}</td><td><span class="tag signal">LOCKED</span></td></tr>`}).join('');state('live','Live signals · All Markets')}
async function load(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j?.ok!==true)throw new Error();render(j)}catch{state('warn','ข้อมูลสัญญาณไม่พร้อม')}}load();setInterval(load,POLL)})();
