(()=>{
'use strict';
const API='/api/engine/signals';
const POLL=30000;
const UI_REVISION='343-signal-ceo-detail-v1';
const openIds=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const show=v=>v===null||v===undefined||v===''?'—':String(v);
const num=v=>{if(v===null||v===undefined||v===''||typeof v==='boolean')return null;const n=Number(String(v).replace('%','').trim());return Number.isFinite(n)?n:null};
const score=v=>{if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v))return`${show(v[0])}-${show(v[1])}`;if(v&&typeof v==='object')return`${show(v.home??v.h)}-${show(v.away??v.a)}`;return'—'};
const entryMinute=s=>s?.entryMinute??s?.minute;
const entryScore=s=>score(s?.entryScore??s?.scoreAt);
const liveMinute=s=>s?.mirrorMinute===null||s?.mirrorMinute===undefined?'—':`${show(s.mirrorMinute)}'`;
const liveScore=s=>s?.mirrorScore===null||s?.mirrorScore===undefined?'—':score(s.mirrorScore);
const team=(s,side)=>s?.[side]?.name||side.toUpperCase();
const isCeo=s=>String(s?.strategy||'').toUpperCase()==='CEO';
const ceoRows=g=>(Array.isArray(g?.signals)?g.signals:[]).filter(isCeo);
const ownerRows=g=>(Array.isArray(g?.signals)?g.signals:[]).filter(s=>!isCeo(s));
function ceoSignal(g){return ceoRows(g).slice().sort((a,b)=>Number(b?.createdAt||0)-Number(a?.createdAt||0))[0]||null}
function ownerSignal(g){return ownerRows(g).slice().sort((a,b)=>Number(b?.createdAt||0)-Number(a?.createdAt||0))[0]||null}
const CEO_REASON_LABELS={PRESSURE_EDGE:'Pressure Edge',EVENT_EVIDENCE:'Event Evidence',TREND_SUPPORT:'Trend Support',SHORT_PRESSURE:'Short Pressure',TEMPO_ACTIVE:'Active Tempo',PRIMARY_EVENT:'Primary Event',TREND_STABLE:'Trend Stable',TREND_SHIFT:'Trend Shift',LOW_TEMPO:'Low Tempo',LOW_EVENT_RATE:'Low Event Rate',TREND_CONTROL:'Trend Control',BOTH_SIDES_ACTIVE:'Both Sides Active',BOTH_SIDES_SOT:'Both Sides SOT',BALANCED_THREAT:'Balanced Threat',ONE_SIDE_SUPPRESSED:'One Side Suppressed',NO_RECENT_SOT:'No Recent SOT',PRESSURE_IMBALANCE:'Pressure Imbalance',CARD_RATE_EDGE:'Card Rate Edge',CARD_IMBALANCE:'Card Imbalance'};
function ceoReasonLabel(v){const k=String(v||'').toUpperCase();return CEO_REASON_LABELS[k]||k.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function fmtMetric(v,suffix=''){const n=num(v);return n===null?'—':`${Math.round(n*10)/10}${suffix}`}
function strategyBadge(g){const rows=ceoRows(g);if(!rows.length)return'';const v=rows[0]?.strategyVersion||'1.0',dual=ownerRows(g).length>0,count=rows.length>1?` · ${rows.length} CEO`:'';return`<div class="ceo-strategy-row"><span class="ceo-strategy-badge">CEO · ADD K${esc(count)}</span><span class="ceo-version">v${esc(v)}</span>${dual?'<span class="ceo-dual">OWNER + CEO</span>':''}</div>`}
function ceoDecision(g){
  const s=ceoSignal(g);if(!s)return'';
  const r=s?.referee||{},gate=s?.ceoPriceGate||{},scoreVal=num(s?.ceoScore),need=num(gate?.scoreNeed),valid=num(r?.validOffers),consensus=num(r?.consensusOffers),available=num(r?.availableBookmakers),agree=num(r?.agreementPct),median=num(gate?.medianOdds),best=num(r?.selectedOdds??s?.odds),version=s?.strategyVersion||'1.0';
  const raw=[...(Array.isArray(s?.ceoReasonCodes)?s.ceoReasonCodes:[]),...(Array.isArray(s?.evidence?.reasonCodes)?s.evidence.reasonCodes:[])];
  if(String(gate?.reason||'').toUpperCase()==='CEO_PASS')raw.push('REFEREE_CONSENSUS','PRICE_SCORE_FIT','NO_PRICE_OUTLIER');
  const extra={REFEREE_CONSENSUS:'Referee Consensus',PRICE_SCORE_FIT:'Price / Score Fit',NO_PRICE_OUTLIER:'No Price Outlier'};
  const reasons=[...new Set(raw.filter(Boolean))].map(x=>extra[String(x).toUpperCase()]||ceoReasonLabel(x));
  const minute=entryMinute(s),book=s?.bookmaker||r?.selectedBookmaker||'—';
  return`<div class="ceo-decision"><div class="ceo-decision-head"><span>CEO AUTO · ADD K</span><strong>v${esc(version)} · Official Signal</strong></div><div class="ceo-score-wrap"><div class="ceo-score-box"><small>CEO SCORE</small><strong>${esc(scoreVal===null?'—':Math.round(scoreVal*10)/10)}</strong><em>Decision score · not win probability</em></div><div class="ceo-gate"><div class="ceo-metric pass"><span>STATUS</span><strong>PASS</strong></div><div class="ceo-metric"><span>REQUIRED AT PRICE</span><strong>${esc(need===null?'—':Math.round(need*10)/10)}</strong></div><div class="ceo-metric"><span>MARKET</span><strong>${esc(s?.marketLabel||s?.market||'—')}</strong></div><div class="ceo-metric"><span>LINE</span><strong>${esc(lineText(s))}</strong></div></div></div><div class="ceo-referee"><div class="ceo-metric"><span>BOOKS AVAILABLE</span><strong>${esc(show(available))}</strong></div><div class="ceo-metric"><span>REFEREE</span><strong>${esc(show(consensus))}/${esc(show(valid))}</strong></div><div class="ceo-metric"><span>AGREEMENT</span><strong>${esc(agree===null?'—':`${Math.round(agree*10)/10}%`)}</strong></div><div class="ceo-metric"><span>MARKET MEDIAN</span><strong>${esc(median===null?'—':Math.round(median*100)/100)}</strong></div><div class="ceo-metric pass"><span>BEST PRICE</span><strong>@ ${esc(best===null?show(s?.odds):Math.round(best*1000)/1000)}</strong></div><div class="ceo-metric"><span>BOOKMAKER</span><strong>${esc(book)}</strong></div></div><div class="ceo-reasons">${reasons.length?reasons.map(x=>`<span class="ceo-reason">${esc(x)}</span>`).join(''):'<span class="ceo-reason">CEO Auto Gate Passed</span>'}</div><div class="ceo-lock">Signal locked at ${esc(show(minute))}${minute==null?'':"'"} · Score ${esc(entryScore(s))} · Strategy CEO v${esc(version)}</div></div>`
}
function isAsian(s){const k=String(s?.market||s?.providerMarket||'').toLowerCase();return /(^|_)(ah|asian)(_|$)/.test(k)||k.includes('handicap')||k.includes('corner_asian')||k.includes('card_asian')||k.includes('cards_asian')}
function lineText(s){const n=num(s?.line);if(n===null)return'—';const t=Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000);return isAsian(s)&&n>0?`+${t}`:t}
function selection(s){const x=String(s?.selection||'').toUpperCase();if(x==='HOME')return team(s,'home');if(x==='AWAY')return team(s,'away');if(x==='DRAW')return'DRAW';return show(s?.selection).toUpperCase()}
function pickText(s){const line=num(s?.line);return line===null?selection(s):`${selection(s)} ${lineText(s)}`}
function state(type,text){const el=document.querySelector('[data-next-signal-state]');if(el)el.innerHTML=`<span class="next-dot ${type}"></span>${esc(text)}`}
function group(rows){const map=new Map();for(const s of rows){const id=String(s?.fixtureId??s?.id??'unknown');let g=map.get(id);if(!g){g={id,signals:[],sample:s,createdAt:Number(s?.createdAt||0)};map.set(id,g)}g.signals.push(s);if(Number(s?.createdAt||0)>g.createdAt){g.sample=s;g.createdAt=Number(s.createdAt||0)}}return[...map.values()].sort((a,b)=>b.createdAt-a.createdAt)}
function renderKpis(groups,rows){const set=(q,v)=>{const el=document.querySelector(q);if(el)el.textContent=show(v)};set('[data-next-active-matches]',groups.length);set('[data-next-active-signals]',rows.length);set('[data-next-markets]',new Set(rows.map(s=>s?.market||s?.providerMarket||'—')).size);set('[data-next-tracking]',rows.length?'Live':'—')}
function renderMarkets(rows){const el=document.querySelector('[data-next-market-summary]');if(!el)return;const map=new Map();for(const s of rows){const label=s?.marketLabel||s?.market||'Signal';const key=s?.market||s?.providerMarket||label;const r=map.get(key)||{label,count:0,books:new Set()};r.count++;if(s?.bookmaker)r.books.add(s.bookmaker);map.set(key,r)}el.innerHTML=[...map.values()].map(r=>`<div class="next-market-item"><span>${esc(r.label)}</span><strong>${r.count}</strong><small>${esc([...r.books].join(' · ')||'Live market')}</small></div>`).join('')}
const METRICS=[['ATTACKS',['attacks','attack']],['DANGEROUS',['dangerousAttacks','dangerous_attacks','dangerousAttack','dangerous']],['SOT',['shotsOnTarget','shots_on_target','shotOnTarget','sot']],['SHOT OFF',['shotsOffTarget','shots_off_target','shotOff','off']],['CORNERS',['corners','corner']],['POSSESSION',['possession','possessionPct','possession_percent'],true]];
function pair(src,keys){if(!src)return[null,null];for(const k of keys){const v=src[k];if(Array.isArray(v))return[num(v[0]),num(v[1])];if(v&&typeof v==='object'){const h=num(v.home??v.h??v[0]),a=num(v.away??v.a??v[1]);if(h!==null||a!==null)return[h,a]}}return[null,null]}
function liveStats(s){const base=s?.liveStatistics&&typeof s.liveStatistics==='object'?{...s.liveStatistics}:{};if(s?.liveCorners!==undefined&&s?.liveCorners!==null)base.corners=s.liveCorners;return base}
function statRows(s){const src=liveStats(s);if(!src||!Object.keys(src).length)return'<div class="next-empty">Live match statistics are not available from the current feed.</div>';return METRICS.map(([label,keys,pct])=>{const[h,a]=pair(src,keys),max=pct?100:Math.max(1,h||0,a||0),hw=h===null?0:Math.max(0,Math.min(100,(h/max)*100)),aw=a===null?0:Math.max(0,Math.min(100,(a/max)*100)),fmt=v=>v===null?'—':`${Number.isInteger(v)?v:v.toFixed(1)}${pct?'%':''}`;return`<div class="next-stat-row"><b>${esc(fmt(h))}</b><div class="next-bar home"><i style="width:${hw}%"></i></div><span>${esc(label)}</span><div class="next-bar away"><i style="width:${aw}%"></i></div><b>${esc(fmt(a))}</b></div>`}).join('')}
function flowCard(g){const s=g.sample;return`<div class="next-flow-wrap"><h4>Event Flow · Attack Momentum</h4><section class="nomad-event-flow-card" data-event-flow-fixture="${esc(g.id)}" data-home="${esc(team(s,'home'))}" data-away="${esc(team(s,'away'))}"><div class="nomad-flow-loading">Loading Event Flow…</div></section></div>`}
function evidence(s){const e=s?.evidence,items=Array.isArray(e?.items)?e.items:[];if(!e)return'<div class="next-empty">No evidence detail is available for this signal.</div>';const cards=items.map(x=>`<div class="next-rule ${x?.pass?'pass':''}"><span>${esc(String(x?.key||'RULE').replace(/([a-z])([A-Z])/g,'$1 $2').toUpperCase())}</span><strong>${esc(show(x?.value))}</strong><small>${x?.pass?'PASS':'NOT MET'} · required ${esc(show(x?.threshold))}</small></div>`).join('');return`<div class="next-evidence">${cards||`<div class="next-rule pass"><span>EVIDENCE</span><strong>${esc(show(e?.count))}/${esc(show(e?.required))}</strong><small>${esc(String(e?.side||e?.mode||'').toUpperCase())}</small></div>`}</div>`}
function detail(g){const s=g.sample,m=entryMinute(s),league=[s?.league?.country,s?.league?.name].filter(Boolean).join(' · '),ceo=ceoSignal(g),owner=ownerSignal(g);const right=ceo?`${ceoDecision(g)}${owner?`<div class="ceo-owner-block"><h4>OWNER CONDITIONS · SAME MATCH</h4>${evidence(owner)}</div>`:''}`:evidence(s),title=ceo?'CEO Decision · Add K':'Why this signal';return`<div class="next-signal-detail"><div class="next-detail-grid"><section class="next-detail-card"><h3>Live match statistics</h3>${statRows(s)}${flowCard(g)}</section><section class="next-detail-card"><h3>${title}</h3>${right}</section></div><div class="next-detail-meta"><div class="next-meta"><span>SIGNAL AT</span><strong>${esc(show(m))}${m==null?'':"'"} · ${esc(entryScore(s))}</strong></div><div class="next-meta"><span>LIVE NOW</span><strong>${esc(liveMinute(s))} · ${esc(liveScore(s))}</strong></div><div class="next-meta"><span>LEAGUE</span><strong>${esc(league||'—')}</strong></div><div class="next-meta"><span>ACTIVE SIGNALS</span><strong>${g.signals.length}</strong></div></div></div>`}
function marketPrimary(g){const s=g.signals[0];const extra=g.signals.length>1?` +${g.signals.length-1}`:'';return`<div class="next-market"><small>PRIMARY SIGNAL${extra}</small><div class="next-market-line"><span class="next-market-name">${esc(s?.marketLabel||s?.market||'—')}</span><span class="next-pick">${esc(pickText(s))}</span><span class="next-price">@ ${esc(show(s?.odds))}</span></div><div class="next-book">${esc(s?.bookmaker||'Bet365')}${extra?` · ${esc(extra)} more active signal${g.signals.length>2?'s':''}`:''}</div>${strategyBadge(g)}</div>`}
function card(g){const s=g.sample,open=openIds.has(g.id),m=entryMinute(s),league=[s?.league?.country,s?.league?.name].filter(Boolean).join(' · ');return`<article class="next-signal-card${open?' open':''}" data-next-card="${esc(g.id)}"><div class="next-signal-main"><div class="next-match-id"><div class="next-league"><span class="live-badge">LIVE</span><span>${esc(league||'Live match')}</span></div><div class="next-teams">${esc(team(s,'home'))} — ${esc(team(s,'away'))}</div></div><div class="next-score"><strong>${esc(liveScore(s))}</strong><small>${esc(liveMinute(s))}</small></div><div class="next-entry"><small>SIGNAL AT</small><strong>${esc(show(m))}${m==null?'':"'"} · ${esc(entryScore(s))}</strong></div>${marketPrimary(g)}<button type="button" class="next-expand" data-next-toggle="${esc(g.id)}" aria-expanded="${open?'true':'false'}" aria-label="Toggle signal details">${open?'−':'+'}</button></div>${open?detail(g):''}</article>`}
function render(rows){const groups=group(rows);renderKpis(groups,rows);renderMarkets(rows);const el=document.querySelector('[data-next-signal-list]');if(el)el.innerHTML=groups.length?groups.map(card).join(''):'<div class="next-empty">No active live signals right now.</div>';window.NOMAD_EVENT_FLOW_343?.hydrate(el);state('live',`${rows.length} active signal${rows.length===1?'':'s'} · ${groups.length} match${groups.length===1?'':'es'}`)}
async function load(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(`HTTP ${r.status}`);render(Array.isArray(j?.signals)?j.signals:[])}catch(err){console.warn('Signal NEXT preview load failed',err);state('warn','Signal feed unavailable');const el=document.querySelector('[data-next-signal-list]');if(el&&!el.children.length)el.innerHTML='<div class="next-empty">Unable to load active signals.</div>'}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-next-toggle]');if(!b)return;const id=b.getAttribute('data-next-toggle');if(openIds.has(id))openIds.delete(id);else openIds.add(id);load()});
load();setInterval(load,POLL);
})();
