(()=>{'use strict';
const API='/api/engine/signals',POLL=30000;
const expanded=new Set();
const METRICS=[
  {label:'ATTACKS',keys:['attacks','attack']},
  {label:'DANGEROUS',keys:['dangerousAttacks','dangerous_attacks','dangerousAttack','dangerous']},
  {label:'SOT',keys:['shotsOnTarget','shots_on_target','shotOnTarget','sot']},
  {label:'SHOT OFF',keys:['shotsOffTarget','shots_off_target','shotOff','off']},
  {label:'CORNERS',keys:['corners','corner']},
  {label:'POSSESSION',keys:['possession','possessionPct','possession_percent'],pct:true}
];
const EVIDENCE_LABELS={shotOnTarget:'SOT',shotOff:'SHOT OFF',corner:'CORNERS',attackPct:'ATTACK %',dangerousAttackPct:'DANGEROUS %',possessionPct:'POSSESSION %'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const show=v=>v===null||v===undefined||v===''?'—':String(v);
const num=v=>{if(v===null||v===undefined||v===''||typeof v==='boolean')return null;const n=Number(String(v).replace('%','').trim());return Number.isFinite(n)?n:null};
function time(ms){try{return new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms))}catch{return'—'}}
function scoreValue(v){if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v))return`${show(v[0])}-${show(v[1])}`;if(v&&typeof v==='object')return`${show(v.home??v.h)}-${show(v.away??v.a)}`;return'—'}
function entryScore(s){return scoreValue(s.entryScore??s.scoreAt)}
function isFt(s){return String(s.mirrorState||'').toUpperCase()==='FT'||String(s.status||'').toUpperCase()==='SETTLED'}
function currentScore(s){return scoreValue(isFt(s)?(s.finalScore??s.mirrorScore):(s.mirrorScore??s.entryScore??s.scoreAt))}
function entryMinute(s){return s.entryMinute??s.minute}
function mirrorMinute(s){if(isFt(s))return'FT';const v=s.mirrorMinute;if(v===null||v===undefined||v==='')return'—';return`${show(v)}'`}
function state(type,text){const el=document.querySelector('[data-signal-state]');if(el)el.innerHTML=`<span class="pill"><i class="dot ${type}"></i>${esc(text)}</span>`}
function evidenceText(s){const e=s?.evidence;if(!e)return'—';const side=String(e.side||e.mode||'').toUpperCase();return`${show(e.count)}/${show(e.required)}${side?` · ${side}`:''}`}
function renderMarketSummary(rows){const el=document.querySelector('[data-signal-market-summary]');if(!el)return;const map=new Map();for(const s of rows){const key=s.providerMarket||s.market,label=s.marketLabel||s.market||'—';const rec=map.get(key)||{count:0,labels:new Set()};rec.count++;rec.labels.add(label);map.set(key,rec)}el.innerHTML=map.size?[...map].map(([key,v])=>`<article class="metric"><span>${esc(key)}</span><strong>${v.count}</strong><small>${esc([...v.labels].join(' · '))}</small></article>`).join(''):'<article class="metric"><span>MARKETS</span><strong>0</strong><small>ยังไม่มีสัญญาณที่กำลังติดตาม</small></article>'}
function stateTag(s){const ft=isFt(s);return`<span class="signal-state-tag${ft?' ft':''}">${ft?'FT':'LOCKED'}</span>`}
function statSource(s){return s?.entryStats??s?.statisticsAtEntry??s?.statistics??null}
function metricPair(src,keys){if(!src)return[null,null];for(const k of keys){const v=src[k];if(Array.isArray(v))return[num(v[0]),num(v[1])];if(v&&typeof v==='object'){const h=num(v.home??v.h??v[0]),a=num(v.away??v.a??v[1]);if(h!==null||a!==null)return[h,a]}}return[null,null]}
function formatMetric(v,pct=false){if(v===null)return'—';return`${Number.isInteger(v)?v:v.toFixed(1)}${pct?'%':''}`}
function evidenceBars(s){const src=statSource(s);if(!src)return'<div class="signal-evidence-empty">ไม่มี Snapshot สถิติ ณ จุดเข้า</div>';const rows=METRICS.map((m,i)=>{const[h,a]=metricPair(src,m.keys),max=m.pct?100:Math.max(1,h||0,a||0),hw=h===null?0:Math.max(0,Math.min(100,h/max*100)),aw=a===null?0:Math.max(0,Math.min(100,a/max*100));return`<div class="signal-mirror-row" data-metric="${i}"><strong>${esc(formatMetric(h,m.pct))}</strong><div class="signal-mirror-half home"><i style="width:${hw}%"></i></div><span>${esc(m.label)}</span><div class="signal-mirror-half away"><i style="width:${aw}%"></i></div><strong>${esc(formatMetric(a,m.pct))}</strong></div>`});return rows.join('')}
function evidenceRules(s){const e=s?.evidence,items=Array.isArray(e?.items)?e.items:[];if(!e)return'<div class="signal-evidence-empty">ไม่มีข้อมูลกฎ Evidence</div>';const head=`<div class="signal-evidence-rule-head"><b>${esc(show(e.count))}/${esc(show(e.required))}</b><span>${esc(String(e.mode||'').toUpperCase())} · ${esc(String(e.side||'').toUpperCase()||'—')}</span></div>`;if(!items.length)return head+'<div class="signal-evidence-empty compact">ไม่มีรายละเอียดเงื่อนไขรายข้อ</div>';return head+`<div class="signal-rule-list">${items.map(x=>{const key=EVIDENCE_LABELS[x.key]||String(x.key||'RULE').toUpperCase(),value=x.value===null||x.value===undefined?'—':x.value,threshold=x.threshold===null||x.threshold===undefined?'—':x.threshold;return`<div class="signal-rule-item ${x.pass?'pass':'fail'}"><span>${esc(key)}</span><b>${esc(show(value))}</b><small>${x.pass?'PASS':'MISS'} · TARGET ${esc(show(threshold))}</small></div>`}).join('')}</div>`}
function snapshotCards(s){const evCount=Array.isArray(s?.eventHistory)?s.eventHistory.length:0,book=Array.isArray(s?.bookmakerHistory)&&s.bookmakerHistory.length?s.bookmakerHistory[s.bookmakerHistory.length-1]:null,roll=s?.rolling;const range=roll&&roll.fromMinute!=null&&roll.toMinute!=null?`${roll.fromMinute}' → ${roll.toMinute}'`:'—';return`<div class="signal-snapshot-strip"><article><span>ROLLING WINDOW</span><strong>${esc(range)}</strong><small>หลักฐานก่อน Entry</small></article><article><span>EVENTS CAPTURED</span><strong>${esc(evCount)}</strong><small>Snapshot ณ Entry</small></article><article><span>PRICE SNAPSHOT</span><strong>${esc(book?.odds??s.odds??'—')}</strong><small>${esc(book?.bookmaker||s.bookmaker||'Bet365')} · ${book?.minute!=null?`${esc(book.minute)}'`:'Entry'}</small></article></div>`}
function evidencePanel(s){const m=entryMinute(s),market=s.marketLabel||s.market||'—';return`<div class="signal-evidence-panel"><header class="signal-evidence-head"><div><p>MATCH EVIDENCE</p><h3>${esc(s.home?.name||'—')} - ${esc(s.away?.name||'—')}</h3><small>${esc([s.league?.country,s.league?.name].filter(Boolean).join(' · ')||'—')}</small></div><span class="signal-entry-badge">ENTRY SNAPSHOT</span></header><div class="signal-entry-grid"><article><span>ENTRY MIN</span><strong>${esc(show(m))}${m==null?'':"'"}</strong></article><article><span>ENTRY SCORE</span><strong>${esc(entryScore(s))}</strong></article><article><span>MARKET</span><strong>${esc(market)}</strong></article><article><span>LINE</span><strong>${esc(show(s.line))}</strong></article><article><span>ODDS</span><strong>${esc(show(s.odds))}</strong></article><article><span>BOOKMAKER</span><strong>${esc(s.bookmaker||'Bet365')}</strong></article></div><div class="signal-evidence-grid"><section class="signal-evidence-card"><header><b>MATCH STATISTICS</b><small>HOME ← 6 EVENTS → AWAY · ณ จุดเข้า</small></header><div class="signal-mirror-bars">${evidenceBars(s)}</div></section><section class="signal-evidence-card"><header><b>RULE EVIDENCE</b><small>เงื่อนไขที่ทำให้ Signal ผ่าน</small></header><div class="signal-rule-wrap">${evidenceRules(s)}</div></section></div>${snapshotCards(s)}<div class="signal-evidence-foot">ข้อมูลส่วนนี้ใช้ Snapshot ที่ระบบบันทึกจริงตอนเข้า Signal เท่านั้น · Current minute/score ดูจากการ์ดด้านบน</div></div>`}
function signalRows(rows){return rows.map(s=>{const league=[s.league?.country,s.league?.name].filter(Boolean).join(' · '),entryMin=entryMinute(s),line=show(s.line),stage=show(s.priceStage||'inplay'),id=String(s.id||`${s.fixtureId}-${s.market}`),open=expanded.has(id);return`<tr class="signal-main-row${open?' expanded':''}" data-signal-toggle data-signal-id="${esc(id)}" tabindex="0" aria-expanded="${open?'true':'false'}"><td class="sig-time">${esc(time(s.createdAt))}</td><td class="sig-match"><span class="match-name">${esc(s.home?.name||'—')} - ${esc(s.away?.name||'—')}</span><span class="sub">${esc(league||'—')}</span></td><td class="sig-live"><span class="signal-live-main"><span class="live-minute-343">${esc(mirrorMinute(s))}</span><b class="signal-live-score">${esc(currentScore(s))}</b></span><span class="signal-entry">ENTRY <b>${esc(show(entryMin))}${entryMin==null?'':"'"}</b> · ${esc(entryScore(s))}</span></td><td class="sig-market"><span class="signal-market-name">${esc(s.marketLabel||s.market||'—')}</span><span class="sub">${esc(s.providerMarket||'—')} · ${esc(s.period||'—')}</span></td><td class="sig-pick"><span class="signal-pick-main">${esc(show(s.selection))}</span><span class="sub">LINE ${esc(line)}</span></td><td class="sig-odds odds">${esc(show(s.odds))}</td><td class="sig-book"><span class="signal-book-name">${esc(s.bookmaker||'Bet365')}</span><span class="sub">${esc(stage)}</span></td><td class="sig-evidence"><span class="signal-evidence-summary">${esc(evidenceText(s))}</span><span class="signal-expand-cue">${open?'▲':'▼'} MATCH EVIDENCE</span></td><td class="sig-state">${stateTag(s)}</td></tr><tr class="signal-evidence-row" data-signal-detail="${esc(id)}"${open?'':' hidden'}><td colspan="9">${evidencePanel(s)}</td></tr>`}).join('')}
function render(j){const rows=Array.isArray(j.signals)?j.signals:[],active=rows.filter(s=>!isFt(s));document.querySelector('[data-active]')?.replaceChildren(document.createTextNode(active.length));renderMarketSummary(active);const tbody=document.querySelector('[data-signal-body]');if(!tbody)return;if(!rows.length){tbody.innerHTML='<tr><td colspan="9" class="empty">ยังไม่มีสัญญาณที่ยืนยันแล้ว</td></tr>';state('live','พร้อมรับข้อมูลสัญญาณทุกตลาด');return}const ids=new Set(rows.map(s=>String(s.id||`${s.fixtureId}-${s.market}`)));for(const id of [...expanded])if(!ids.has(id))expanded.delete(id);tbody.innerHTML=signalRows(rows);state('live',`Signal mirror · ${active.length} LOCKED · ${rows.length-active.length} FT`)}
function toggle(id){if(expanded.has(id))expanded.delete(id);else expanded.add(id);document.querySelectorAll('[data-signal-toggle]').forEach(row=>{if(row.dataset.signalId!==id)return;const open=expanded.has(id);row.classList.toggle('expanded',open);row.setAttribute('aria-expanded',open?'true':'false');const cue=row.querySelector('.signal-expand-cue');if(cue)cue.textContent=`${open?'▲':'▼'} MATCH EVIDENCE`});document.querySelectorAll('[data-signal-detail]').forEach(row=>{if(row.dataset.signalDetail===id)row.hidden=!expanded.has(id)})}
async function load(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j?.ok!==true)throw new Error();render(j)}catch{state('warn','ข้อมูลสัญญาณไม่พร้อม')}}
document.addEventListener('click',e=>{const row=e.target.closest('[data-signal-toggle]');if(row)toggle(row.dataset.signalId)});
document.addEventListener('keydown',e=>{const row=e.target.closest('[data-signal-toggle]');if(row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();toggle(row.dataset.signalId)}});
load();setInterval(load,POLL)})();
