(()=>{'use strict';
const API='/api/engine/signals',POLL=30000;
const expanded=new Set();
const METRICS=[
  {label:'ATTACKS',keys:['attacks','attack']},{label:'DANGEROUS',keys:['dangerousAttacks','dangerous_attacks','dangerousAttack','dangerous']},{label:'SOT',keys:['shotsOnTarget','shots_on_target','shotOnTarget','sot']},{label:'SHOT OFF',keys:['shotsOffTarget','shots_off_target','shotOff','off']},{label:'CORNERS',keys:['corners','corner']},{label:'POSSESSION',keys:['possession','possessionPct','possession_percent'],pct:true}
];
const EVIDENCE_LABELS={shotOnTarget:'SOT',shotOff:'SHOT OFF',corner:'CORNERS',attackPct:'ATTACK %',dangerousAttackPct:'DANGEROUS %',possessionPct:'POSSESSION %'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const show=v=>v===null||v===undefined||v===''?'—':String(v);
const num=v=>{if(v===null||v===undefined||v===''||typeof v==='boolean')return null;const n=Number(String(v).replace('%','').trim());return Number.isFinite(n)?n:null};
function numberText(v){const n=num(v);if(n===null)return'—';return Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000)}
function signedLineText(v){const n=num(v);if(n===null)return'—';const t=numberText(n);return n>0?`+${t}`:t}
function marketKey(s){return String(s?.market||s?.providerMarket||'').toLowerCase()}
function isAsianMarket(s){const k=marketKey(s);return /(^|_)(ah|asian)(_|$)/.test(k)||k.includes('handicap')||k.includes('corner_asian')||k.includes('card_asian')||k.includes('cards_asian')}
function isTotalMarket(s){const k=marketKey(s),sel=String(s?.selection||'').toUpperCase();return sel==='OVER'||sel==='UNDER'||k.includes('over')||k.includes('under')||k.includes('goal_line')||k.includes('corner_line')||k.includes('card_line')}
function publicLineText(s){const n=num(s?.line);if(n===null)return'—';return isAsianMarket(s)?signedLineText(n):numberText(n)}
function scoreValue(v){if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v))return`${show(v[0])}-${show(v[1])}`;if(v&&typeof v==='object')return`${show(v.home??v.h)}-${show(v.away??v.a)}`;return'—'}
function entryMinute(s){return s?.entryMinute??s?.minute}
function entryScore(s){return scoreValue(s?.entryScore??s?.scoreAt)}
function liveMinute(s){const v=s?.mirrorMinute;return v===null||v===undefined||v===''?'—':`${show(v)}'`}
function liveScore(s){return s?.mirrorScore===null||s?.mirrorScore===undefined?'—':scoreValue(s.mirrorScore)}
function teamName(s,side){return s?.[String(side).toLowerCase()]?.name||side}
function selectionLabel(s){const sel=String(s?.selection||'').toUpperCase();if(sel==='HOME')return teamName(s,'HOME');if(sel==='AWAY')return teamName(s,'AWAY');if(sel==='DRAW')return'DRAW';return show(s?.selection).toUpperCase()}
function betText(s){const pick=selectionLabel(s),line=num(s?.line);if(line===null)return pick;if(isAsianMarket(s)||isTotalMarket(s))return`${pick} ${publicLineText(s)}`;return pick}
function rawLineText(s){const n=num(s?.providerLine);if(n===null)return'—';const raw=isAsianMarket(s)?signedLineText(n):numberText(n);return`${raw}${s?.providerLineSide?` · ${s.providerLineSide}`:''}`}
function state(type,text){const el=document.querySelector('[data-signal-state]');if(el)el.innerHTML=`<span class="pill"><i class="dot ${type}"></i>${esc(text)}</span>`}
function evidenceText(s){const e=s?.evidence;if(!e)return'—';const side=String(e.side||e.mode||'').toUpperCase();return`${show(e.count)}/${show(e.required)}${side?` · ${side}`:''}`}
function metricPair(src,keys){if(!src)return[null,null];for(const k of keys){const v=src[k];if(Array.isArray(v))return[num(v[0]),num(v[1])];if(v&&typeof v==='object'){const h=num(v.home??v.h??v[0]),a=num(v.away??v.a??v[1]);if(h!==null||a!==null)return[h,a]}}return[null,null]}
function formatMetric(v,pct=false){if(v===null)return'—';return`${Number.isInteger(v)?v:v.toFixed(1)}${pct?'%':''}`}
function liveStatSource(s){const base=s?.liveStatistics&&typeof s.liveStatistics==='object'?{...s.liveStatistics}:{};if(s?.liveCorners!==undefined&&s?.liveCorners!==null)base.corners=s.liveCorners;return base}
function entryStatSource(s){const base=s?.entryStats??s?.statisticsAtEntry??s?.statistics??null;if(!base)return null;const out={...base};if(s?.entryCorners!==undefined&&s?.entryCorners!==null)out.corners=s.entryCorners;return out}
function bars(src,mode='live'){if(!src||!Object.keys(src).length)return`<div class="signal-evidence-empty">ไม่มี${mode==='live'?' Live Statistics':'สถิติตอนออก Signal'}จาก feed</div>`;return METRICS.map((m,i)=>{const[h,a]=metricPair(src,m.keys),max=m.pct?100:Math.max(1,h||0,a||0),hw=h===null?0:Math.max(0,Math.min(100,h/max*100)),aw=a===null?0:Math.max(0,Math.min(100,a/max*100));return`<div class="signal-mirror-row" data-metric="${i}"><strong>${esc(formatMetric(h,m.pct))}</strong><div class="signal-mirror-half home"><i style="width:${hw}%"></i></div><span>${esc(m.label)}</span><div class="signal-mirror-half away"><i style="width:${aw}%"></i></div><strong>${esc(formatMetric(a,m.pct))}</strong></div>`}).join('')}
function cardTotal(cards){const side=v=>{if(!v||typeof v!=='object')return null;const y=num(v.yellow),r=num(v.red);return y===null&&r===null?null:(y??0)+(r??0)};return{home:side(cards?.home),away:side(cards?.away)}}
function groupMatches(rows){const map=new Map();for(const s of rows){const id=String(s.fixtureId||s.id||'unknown');let g=map.get(id);if(!g){g={id,fixtureId:id,sample:s,signals:[],createdAt:Number(s.createdAt||0)};map.set(id,g)}g.signals.push(s);if(Number(s.createdAt||0)>g.createdAt){g.createdAt=Number(s.createdAt||0);g.sample=s}}return[...map.values()].sort((a,b)=>b.createdAt-a.createdAt)}
function renderMarketSummary(rows){const el=document.querySelector('[data-signal-market-summary]');if(!el)return;const map=new Map();for(const s of rows){const key=s.market||s.providerMarket||'—',label=s.marketLabel||s.market||'—';const rec=map.get(key)||{count:0,labels:new Set()};rec.count++;rec.labels.add(label);map.set(key,rec)}if(!map.size){el.innerHTML='';return}el.innerHTML=[...map].map(([,v])=>`<article class="metric"><span>${esc([...v.labels][0]||'SIGNAL')}</span><strong>${v.count}</strong><small>${esc([...v.labels].join(' · '))}</small></article>`).join('')}
function marketChip(s){return`<span class="signal-market-chip"><b>${esc(s.marketLabel||s.market||'—')}</b><span><strong>${esc(betText(s))}</strong> @ ${esc(show(s.odds))} · ${esc(s.bookmaker||'Bet365')}</span></span>`}
function signalAtQuick(s){const m=entryMinute(s);return`<div class="signal-entry-quick"><span><small>SIGNAL AT</small><b>${esc(show(m))}${m==null?'':"'"}</b></span><span><small>SCORE</small><b>${esc(entryScore(s))}</b></span></div>`}
function evidenceRules(s){const e=s?.evidence,items=Array.isArray(e?.items)?e.items:[];if(!e)return'<div class="signal-evidence-empty compact">ไม่มีข้อมูลเหตุผลของ Signal</div>';const head=`<div class="signal-evidence-rule-head"><b>${esc(show(e.count))}/${esc(show(e.required))}</b><span>${esc(String(e.mode||'').toUpperCase())} · ${esc(String(e.side||'').toUpperCase()||'—')}</span></div>`;if(!items.length)return head+'<div class="signal-evidence-empty compact">ไม่มีรายละเอียดเงื่อนไขรายข้อ</div>';return head+`<div class="signal-rule-list">${items.map(x=>{const key=EVIDENCE_LABELS[x.key]||String(x.key||'RULE').toUpperCase(),value=x.value===null||x.value===undefined?'—':x.value,threshold=x.threshold===null||x.threshold===undefined?'—':x.threshold;return`<div class="signal-rule-item ${x.pass?'pass':'fail'}"><span>${esc(key)}</span><b>${esc(show(value))}</b><small>${x.pass?'PASS':'NOT MET'} · REQUIRED ${esc(show(threshold))}</small></div>`}).join('')}</div>`}
function technicalDetails(s){const roll=s?.rolling,range=roll&&roll.fromMinute!=null&&roll.toMinute!=null?`${roll.fromMinute}' → ${roll.toMinute}'`:'—',cards=cardTotal(s?.liveCards),events=Array.isArray(s?.liveEvents)?s.liveEvents.length:0,age=num(s?.liveAgeMs),hasRaw=num(s?.providerLine)!==null;return`<details class="signal-technical"><summary>Source / technical details</summary><div class="signal-technical-grid"><span><small>PROVIDER MARKET</small><b>${esc(s.providerMarket||s.market||'—')}</b></span><span><small>ROLLING WINDOW</small><b>${esc(range)}</b></span>${hasRaw?`<span><small>5USD RAW LINE</small><b>${esc(rawLineText(s))}</b></span>`:''}<span><small>FEED AGE</small><b>${age===null?'—':`${Math.round(age/1000)}s`}</b></span><span><small>EVENTS</small><b>${esc(events)}</b></span><span><small>CARDS RAW COUNT</small><b>${esc(`${show(cards.home)}-${show(cards.away)}`)}</b></span></div></details>`}
function entryBlock(s){const m=entryMinute(s);return`<article class="signal-entry-block"><header><div><b>${esc(s.marketLabel||s.market||'—')}</b><small>${esc(betText(s))} @ ${esc(show(s.odds))} · ${esc(s.bookmaker||'Bet365')}</small></div><span>${esc(evidenceText(s))}</span></header><div class="signal-entry-grid"><div><span>SIGNAL AT</span><strong>${esc(show(m))}${m==null?'':"'"}</strong></div><div><span>SCORE AT SIGNAL</span><strong>${esc(entryScore(s))}</strong></div><div><span>PICK</span><strong>${esc(selectionLabel(s))}</strong></div><div><span>LINE</span><strong>${esc(publicLineText(s))}</strong></div><div><span>ODDS AT SIGNAL</span><strong>${esc(show(s.odds))}</strong></div><div><span>BOOKMAKER</span><strong>${esc(s.bookmaker||'Bet365')}</strong></div></div><div class="signal-entry-detail-grid"><section><header><b>MATCH STATS AT SIGNAL</b><small>สถิติตอนระบบออก Signal</small></header><div class="signal-mirror-bars">${bars(entryStatSource(s),'entry')}</div></section><section><header><b>WHY THIS SIGNAL</b><small>เงื่อนไขที่ผ่านตอนออก Signal</small></header><div class="signal-rule-wrap">${evidenceRules(s)}</div></section></div>${technicalDetails(s)}</article>`}
function signalTracker(s){const m=entryMinute(s);return`<div class="signal-live-meta signal-tracker"><span><small>SIGNAL AT</small><b>${esc(show(m))}${m==null?'':"'"} · ${esc(entryScore(s))}</b></span><span><small>LIVE NOW</small><b>${esc(liveMinute(s))} · ${esc(liveScore(s))}</b></span><span><small>ODDS AT SIGNAL</small><b>${esc(show(s.odds))} · ${esc(s.bookmaker||'Bet365')}</b></span></div>`}
function flowCard(g){const s=g.sample;return`<section class="nomad-event-flow-card" data-event-flow-fixture="${esc(g.fixtureId)}" data-home="${esc(s.home?.name||'HOME')}" data-away="${esc(s.away?.name||'AWAY')}"><div class="nomad-flow-loading">Event Flow</div></section>`}
function matchDetail(g){const s=g.sample,h=teamName(s,'HOME'),a=teamName(s,'AWAY');return`<div class="signal-match-detail"><section class="signal-live-section"><header><div><p>LIVE NOW</p><h3>${esc(h)} - ${esc(a)}</h3><small>${esc([s.league?.country,s.league?.name].filter(Boolean).join(' · ')||'—')}</small></div><span class="signal-live-badge">${esc(liveMinute(s))} · ${esc(liveScore(s))}</span></header><div class="signal-live-grid"><section class="signal-evidence-card"><header><b>LIVE MATCH STATISTICS</b><small>${esc(h)} ← MATCH STATISTICS → ${esc(a)}</small></header><div class="signal-mirror-bars">${bars(liveStatSource(s),'live')}</div></section><section class="signal-evidence-card"><header><b>SIGNAL TRACKER</b><small>ตอนออก Signal เทียบกับสถานะปัจจุบัน</small></header>${signalTracker(s)}</section></div>${flowCard(g)}</section><section class="signal-entries-section"><header><div><p>SIGNAL DETAILS</p><h3>${g.signals.length} Active Signal${g.signals.length===1?'':'s'} ในแมตช์นี้</h3></div><span class="signal-entry-badge">ENTRY LOCKED</span></header><div class="signal-entry-blocks">${g.signals.sort((a,b)=>Number(a.createdAt||0)-Number(b.createdAt||0)).map(entryBlock).join('')}</div></section></div>`}
function matchCard(g){const s=g.sample,open=expanded.has(g.id),league=[s.league?.country,s.league?.name].filter(Boolean).join(' · ');return`<article class="active-signal-card${open?' expanded':''}" data-match-toggle data-match-id="${esc(g.id)}" tabindex="0" aria-expanded="${open?'true':'false'}"><div class="active-signal-card-main"><div class="active-signal-title"><span class="active-signal-live-dot">LIVE</span><div><small>${esc(league||'—')}</small><h3>${esc(s.home?.name||'—')} - ${esc(s.away?.name||'—')}</h3></div></div><div class="active-signal-score"><span class="live-minute-343">${esc(liveMinute(s))}</span><b>${esc(liveScore(s))}</b></div>${signalAtQuick(s)}<div class="active-signal-markets">${g.signals.map(marketChip).join('')}</div><div class="active-signal-cue">${open?'▲':'▼'} ${g.signals.length} SIGNAL${g.signals.length===1?'':'S'} · DETAILS</div></div><div class="active-signal-detail" data-match-detail="${esc(g.id)}"${open?'':' hidden'}>${matchDetail(g)}</div></article>`}
function toggle(id){if(expanded.has(id))expanded.delete(id);else expanded.add(id);const card=document.querySelector(`[data-match-id="${CSS.escape(id)}"]`);if(!card)return;const open=expanded.has(id);card.classList.toggle('expanded',open);card.setAttribute('aria-expanded',open?'true':'false');const detail=card.querySelector('[data-match-detail]');if(detail)detail.hidden=!open;const cue=card.querySelector('.active-signal-cue');if(cue)cue.textContent=`${open?'▲':'▼'} ${card.querySelectorAll('.signal-market-chip').length} SIGNAL${card.querySelectorAll('.signal-market-chip').length===1?'':'S'} · DETAILS`;if(open)window.NOMAD_EVENT_FLOW_343?.hydrate(card)}
function render(j){const rows=Array.isArray(j.signals)?j.signals:[],groups=groupMatches(rows);document.querySelector('[data-active-matches]')?.replaceChildren(document.createTextNode(groups.length));document.querySelector('[data-active-signals]')?.replaceChildren(document.createTextNode(rows.length));renderMarketSummary(rows);const board=document.querySelector('[data-signal-body]');if(!board)return;const ids=new Set(groups.map(g=>g.id));for(const id of [...expanded])if(!ids.has(id))expanded.delete(id);if(!groups.length){board.innerHTML='<div class="active-signal-empty"><b>NO ACTIVE SIGNAL</b><span>ยังไม่มี Signal ที่กำลังแข่งขันอยู่</span></div>';const age=num(j?.mirror?.hubAgeMs);state('live',`Active Signal Board · 0 match${age===null?'':` · feed age ${Math.round(age/1000)}s`}`);return}board.innerHTML=groups.map(matchCard).join('');window.NOMAD_EVENT_FLOW_343?.hydrate(board);const age=num(j?.mirror?.hubAgeMs);state('live',`Active Signal Board · ${groups.length} match · ${rows.length} signal${age===null?'':` · feed age ${Math.round(age/1000)}s`}`)}
async function load(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j?.ok!==true)throw new Error();render(j)}catch{state('warn','Active Signal Board ไม่พร้อม')}}
document.addEventListener('click',e=>{if(e.target.closest('.signal-technical'))return;const card=e.target.closest('[data-match-toggle]');if(card)toggle(card.dataset.matchId)});
document.addEventListener('keydown',e=>{if(e.target.closest('.signal-technical'))return;const card=e.target.closest('[data-match-toggle]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();toggle(card.dataset.matchId)}});
load();setInterval(load,POLL)})();
