(()=>{
'use strict';
const STAT_API='/api/engine/statistics';
const SIGNAL_API='/api/engine/signals';
const POLL=45000;
const liveOpenIds=new Set();
const TZ=(()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}catch{return'UTC'}})();
const LOCALE=(()=>{try{return navigator.language||'en-GB'}catch{return'en-GB'}})();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const show=v=>v===null||v===undefined||v===''?'—':String(v);
const num=v=>v===null||v===undefined||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))?null:Number(v);
const score=v=>{if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v))return`${show(v[0])}-${show(v[1])}`;if(v&&typeof v==='object')return`${show(v.home??v.h)}-${show(v.away??v.a)}`;return'—'};
const when=ms=>{try{return new Intl.DateTimeFormat(LOCALE,{timeZone:TZ,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms))}catch{return'—'}};
function isAsian(s){const k=String(s?.market||s?.providerMarket||'').toLowerCase();return /(^|_)(ah|asian)(_|$)/.test(k)||k.includes('handicap')||k.includes('corner_asian')||k.includes('card_asian')||k.includes('cards_asian')}
function lineText(s){const n=num(s?.line);if(n===null)return'—';const t=Number.isInteger(n)?String(n):String(Math.round(n*1000)/1000);return isAsian(s)&&n>0?`+${t}`:t}
function selection(s){const x=String(s?.selection||'').toUpperCase();if(x==='HOME')return s?.home?.name||'HOME';if(x==='AWAY')return s?.away?.name||'AWAY';if(x==='DRAW')return'DRAW';return show(s?.selection).toUpperCase()}
function status(type,text){const el=document.querySelector('[data-next-stat-state]');if(el)el.innerHTML=`<span class="next-dot ${type}"></span>${esc(text)}`}
function set(q,v){const el=document.querySelector(q);if(el)el.textContent=show(v)}
function resultTag(r){const x=String(r||'').toUpperCase(),cls=x==='WIN'||x==='HALF_WIN'?'win':x==='LOSS'||x==='HALF_LOSS'?'loss':'push';return`<span class="result-tag ${cls}">${esc(x||'—')}</span>`}
function avgOdds(rows){const vals=rows.map(r=>num(r?.odds)).filter(v=>v!==null&&v>1);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function renderMarkets(j){const el=document.querySelector('[data-next-stat-markets]');if(!el)return;const defs=j?.markets||{},counts=j?.byMarket||{};el.innerHTML=Object.entries(defs).map(([k,d])=>`<div class="next-market-item"><span>${esc(d?.label||k)}</span><strong>${esc(counts[k]||0)}</strong><small>${esc(d?.provider||'Bet365')} · ${esc(d?.period||'FT')}</small></div>`).join('')}
function renderStats(j){const rows=Array.isArray(j?.rows)?j.rows:[],avg=avgOdds(rows);set('[data-next-total]',j?.total);set('[data-next-win]',j?.win);set('[data-next-loss]',j?.loss);set('[data-next-win-rate]',j?.winRate===null||j?.winRate===undefined?'—':`${j.winRate}%`);set('[data-next-avg-odds]',avg===null?'—':avg.toFixed(2));renderMarkets(j);const body=document.querySelector('[data-next-stat-body]');if(body)body.innerHTML=rows.length?rows.map(s=>{const league=[s?.league?.country,s?.league?.name].filter(Boolean).join(' · '),m=s?.entryMinute??s?.minute;return`<tr><td>${esc(when(s?.createdAt))}</td><td><span class="match-primary">${esc(s?.home?.name||'—')} — ${esc(s?.away?.name||'—')}</span><span class="sub">${esc(league||'—')}</span></td><td>${esc(show(m))}${m==null?'':"'"}</td><td><span class="match-primary">${esc(s?.marketLabel||s?.market||'—')}</span><span class="sub">${esc(s?.period||'—')}</span></td><td>${esc(selection(s))}</td><td>${esc(lineText(s))}</td><td class="odds-readonly">${esc(show(s?.odds))}</td><td>${esc(s?.bookmaker||'Bet365')}</td><td>${esc(score(s?.entryScore??s?.scoreAt))}</td><td>${esc(score(s?.finalScore))}</td><td>${resultTag(s?.result)}</td></tr>`}).join(''):'<tr><td colspan="11"><div class="next-empty">No settled results yet.</div></td></tr>';status('live',`Results online · ${esc(j?.settlementRevision||'current rules')}`)}
function groupSignals(rows){const map=new Map();for(const s of rows){const id=String(s?.fixtureId??s?.id??'unknown');let g=map.get(id);if(!g){g={id,sample:s,signals:[],createdAt:Number(s?.createdAt||0)};map.set(id,g)}g.signals.push(s);if(Number(s?.createdAt||0)>g.createdAt){g.sample=s;g.createdAt=Number(s.createdAt||0)}}return[...map.values()].sort((a,b)=>b.createdAt-a.createdAt).slice(0,8)}
function liveMinute(s){return s?.mirrorMinute===null||s?.mirrorMinute===undefined?'—':`${show(s.mirrorMinute)}'`}
function liveScore(s){return s?.mirrorScore===null||s?.mirrorScore===undefined?'—':score(s.mirrorScore)}
const LIVE_METRICS=[['ATTACKS',['attacks','attack']],['DANGEROUS',['dangerousAttacks','dangerous_attacks','dangerousAttack','dangerous']],['SOT',['shotsOnTarget','shots_on_target','shotOnTarget','sot']],['SHOT OFF',['shotsOffTarget','shots_offTarget','shots_off_target','shotOff','off']],['CORNERS',['corners','corner']],['POSSESSION',['possession','possessionPct','possession_percent'],true]];
function livePair(src,keys){if(!src)return[null,null];for(const k of keys){const v=src[k];if(Array.isArray(v))return[num(v[0]),num(v[1])];if(v&&typeof v==='object'){const h=num(v.home??v.h??v[0]),a=num(v.away??v.a??v[1]);if(h!==null||a!==null)return[h,a]}}return[null,null]}
function liveStatSource(s){const base=s?.liveStatistics&&typeof s.liveStatistics==='object'?{...s.liveStatistics}:{};if(s?.liveCorners!==undefined&&s?.liveCorners!==null)base.corners=s.liveCorners;return base}
function liveStatRows(s){const src=liveStatSource(s);if(!src||!Object.keys(src).length)return'<div class="next-empty">Live match statistics are not available from the current feed.</div>';return LIVE_METRICS.map(([label,keys,pct])=>{const[h,a]=livePair(src,keys),max=pct?100:Math.max(1,h||0,a||0),hw=h===null?0:Math.max(0,Math.min(100,(h/max)*100)),aw=a===null?0:Math.max(0,Math.min(100,(a/max)*100)),fmt=v=>v===null?'—':`${Number.isInteger(v)?v:v.toFixed(1)}${pct?'%':''}`;return`<div class="next-stat-row"><b>${esc(fmt(h))}</b><div class="next-bar home"><i style="width:${hw}%"></i></div><span>${esc(label)}</span><div class="next-bar away"><i style="width:${aw}%"></i></div><b>${esc(fmt(a))}</b></div>`}).join('')}
function liveFlowCard(g){const s=g.sample;return`<div class="next-flow-wrap"><h4>Event Flow · Attack Momentum</h4><section class="nomad-event-flow-card" data-event-flow-fixture="${esc(g.id)}" data-home="${esc(s?.home?.name||'HOME')}" data-away="${esc(s?.away?.name||'AWAY')}"><div class="nomad-flow-loading">Loading Event Flow…</div></section></div>`}
function renderLive(rows){const el=document.querySelector('[data-next-live-tracker]');if(!el)return;const groups=groupSignals(rows),ids=new Set(groups.map(g=>g.id));for(const id of [...liveOpenIds])if(!ids.has(id))liveOpenIds.delete(id);el.innerHTML=groups.length?groups.map(g=>{const s=g.sample,open=liveOpenIds.has(g.id),league=[s?.league?.country,s?.league?.name].filter(Boolean).join(' · '),picks=g.signals.map(x=>`<span class="next-live-pick"><b>${esc(x?.marketLabel||x?.market||'—')}</b> · ${esc(selection(x))} ${esc(lineText(x))} @ <span class="odds-readonly">${esc(show(x?.odds))}</span></span>`).join('');return`<article class="next-live-track-card${open?' open':''}"><div class="next-live-row with-toggle"><div class="teams">${esc(s?.home?.name||'—')} — ${esc(s?.away?.name||'—')}<small>${esc(league||'Live match')}</small></div><div class="score">${esc(liveScore(s))}<small style="display:block;color:var(--green);font-size:9px;margin-top:3px">${esc(liveMinute(s))}</small></div><div class="picks">${picks}</div><button type="button" class="next-live-toggle" data-next-live-toggle="${esc(g.id)}" aria-expanded="${open?'true':'false'}" aria-label="Toggle live evidence">${open?'−':'+'}</button></div>${open?`<div class="next-live-track-detail"><section class="next-detail-card"><h3>Live match statistics</h3>${liveStatRows(s)}${liveFlowCard(g)}</section></div>`:''}</article>`}).join(''):'<div class="next-empty">No active signals to track right now.</div>';window.NOMAD_EVENT_FLOW_343?.hydrate(el)}
async function load(){try{const [sr,lr]=await Promise.all([fetch(`${STAT_API}?_=${Date.now()}`,{cache:'no-store'}),fetch(`${SIGNAL_API}?_=${Date.now()}`,{cache:'no-store'})]);const sj=await sr.json();if(!sr.ok||sj?.ok!==true)throw new Error('statistics unavailable');renderStats(sj);if(lr.ok){const lj=await lr.json();renderLive(Array.isArray(lj?.signals)?lj.signals:[])}}catch(err){console.warn('Statistics NEXT preview load failed',err);status('warn','Statistics feed unavailable')}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-next-live-toggle]');if(!b)return;const id=b.getAttribute('data-next-live-toggle');if(liveOpenIds.has(id))liveOpenIds.delete(id);else liveOpenIds.add(id);load()});
const tz=document.querySelector('[data-next-timezone]');if(tz)tz.textContent=TZ;
load();setInterval(load,POLL);
})();
