(()=>{
'use strict';
const API='/api/engine/statistics',POLL=45000,NS='http://www.w3.org/2000/svg';
const COLORS=['#f0c95b','#dc8c62','#9f8ce7','#62c9bf','#d979a4','#9fc967','#76a7e8','#d09b68'];
const METRICS=[{label:'ATTACKS',keys:['attacks','attack']},{label:'DANGEROUS',keys:['dangerousAttacks','dangerous_attacks','dangerousAttack','dangerous']},{label:'SOT',keys:['shotsOnTarget','shots_on_target','shotOnTarget','sot']},{label:'SHOT OFF',keys:['shotsOffTarget','shots_off_target','shotOff','off']},{label:'CORNERS',keys:['corners','corner']},{label:'POSSESSION',keys:['possession','possessionPct','possession_percent'],pct:true}];
let rows=[],selected=0,marketDefs={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{if(v===null||v===undefined||v===''||typeof v==='boolean')return null;const n=Number(String(v).replace('%','').trim());return Number.isFinite(n)?n:null};
const show=v=>v===null||v===undefined||v===''?'—':String(v);
function label(s){return s?.marketLabel||marketDefs[s?.market]?.label||s?.market||'—'}
function dt(ms){try{return new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms))}catch{return'—'}}
function resultTag(r){const cls=r==='WIN'||r==='HALF_WIN'?'win':r==='LOSS'||r==='HALF_LOSS'?'loss':'push';return`<span class="tag ${cls}">${esc(r||'—')}</span>`}
function set(q,v){const el=document.querySelector(q);if(el)el.textContent=show(v)}
function score(v){if(typeof v==='string'&&v.trim())return v;if(Array.isArray(v))return`${show(v[0])}-${show(v[1])}`;if(v&&typeof v==='object')return`${show(v.home??v.h)}-${show(v.away??v.a)}`;return'—'}
function entryMinute(s){return s?.entryMinute??s?.minute}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function clear(el){while(el?.firstChild)el.removeChild(el.firstChild)}
function sourceStats(s){return s?.entryStats??s?.statisticsAtEntry??s?.statistics??null}
function metricPair(src,keys){if(!src)return[null,null];for(const k of keys){const v=src[k];if(Array.isArray(v))return[num(v[0]),num(v[1])];if(v&&typeof v==='object'){const h=num(v.home??v.h??v[0]),a=num(v.away??v.a??v[1]);if(h!==null||a!==null)return[h,a]}}return[null,null]}
function renderBars(s){const el=document.querySelector('[data-mirror-bars]');if(!el)return;const src=sourceStats(s),pairs=METRICS.map(m=>({m,p:metricPair(src,m.keys)}));if(!src||!pairs.some(x=>x.p[0]!==null||x.p[1]!==null)){el.innerHTML='<div class="visual-empty">ไม่มี Snapshot สถิติ ณ จุดเข้า</div>';return}el.innerHTML=pairs.map(({m,p})=>{const[h,a]=p,max=m.pct?100:Math.max(1,h||0,a||0),hw=h===null?0:Math.max(0,Math.min(100,h/max*100)),aw=a===null?0:Math.max(0,Math.min(100,a/max*100)),fmt=v=>v===null?'—':`${Number.isInteger(v)?v:v.toFixed(1)}${m.pct?'%':''}`;return`<div class="mirror-row"><strong>${fmt(h)}</strong><div class="mirror-half home"><i style="width:${hw}%"></i></div><span>${m.label}</span><div class="mirror-half away"><i style="width:${aw}%"></i></div><strong>${fmt(a)}</strong></div>`}).join('')}
function chartFrame(el,w,h,minX,maxX,minY,maxY,yFmt){const p={l:48,r:16,t:18,b:30},plot={x:p.l,y:p.t,w:w-p.l-p.r,h:h-p.t-p.b};for(let i=0;i<=5;i++){const y=plot.y+plot.h*i/5;el.appendChild(svg('line',{x1:plot.x,y1:y,x2:plot.x+plot.w,y2:y,class:'public-grid'}));const t=svg('text',{x:plot.x-7,y:y+3,'text-anchor':'end',class:'public-axis'});t.textContent=yFmt(maxY-(maxY-minY)*i/5);el.appendChild(t)}for(let i=0;i<=6;i++){const x=plot.x+plot.w*i/6;el.appendChild(svg('line',{x1:x,y1:plot.y,x2:x,y2:plot.y+plot.h,class:'public-grid'}));const t=svg('text',{x,y:plot.y+plot.h+18,'text-anchor':'middle',class:'public-axis'});t.textContent=`${Math.round(minX+(maxX-minX)*i/6)}'`;el.appendChild(t)}return{plot,x:v=>plot.x+(v-minX)/Math.max(.0001,maxX-minX)*plot.w,y:v=>plot.y+plot.h-(v-minY)/Math.max(.0001,maxY-minY)*plot.h}}
function eventRows(s){const raw=s?.eventHistory;if(!Array.isArray(raw))return[];const direct=raw.map(r=>({minute:num(r?.minute??r?.min??r?.time),home:num(r?.home??r?.homeValue??r?.h),away:num(r?.away??r?.awayValue??r?.a)})).filter(r=>r.minute!==null&&r.home!==null&&r.away!==null);if(direct.length)return direct.sort((a,b)=>a.minute-b.minute);let home=0,away=0;return raw.map(r=>{const minute=num(r?.minute??r?.min??r?.time);if(minute===null)return null;const side=String(r?.side??r?.teamSide??'').toLowerCase();if(side==='home'||side==='h')home++;else if(side==='away'||side==='a')away++;else return null;return{minute,home,away}}).filter(Boolean).sort((a,b)=>a.minute-b.minute)}
function renderEvent(s){const el=document.querySelector('[data-event-chart]'),empty=document.querySelector('[data-event-empty]');if(!el)return;clear(el);const r=eventRows(s);if(r.length<2){if(empty)empty.hidden=false;return}if(empty)empty.hidden=true;let minX=Math.min(...r.map(x=>x.minute)),maxX=Math.max(...r.map(x=>x.minute));if(minX===maxX)maxX=minX+1;const maxY=Math.max(1,...r.flatMap(x=>[x.home,x.away])),f=chartFrame(el,720,260,minX,maxX,0,maxY,v=>Math.round(v));for(const[k,cls]of[['home','home'],['away','away']])el.appendChild(svg('polyline',{points:r.map(x=>`${f.x(x.minute)},${f.y(x[k])}`).join(' '),class:`event-line ${cls}`}))}
function bookSeries(s){const raw=s?.bookmakerHistory;if(!Array.isArray(raw)||!raw.length)return[];const map=new Map();for(const p of raw){const name=String(p.bookmaker||'Bet365'),minute=num(p.minute),odds=num(p.odds);if(minute===null||odds===null)continue;if(!map.has(name))map.set(name,[]);map.get(name).push({minute,odds})}return[...map].map(([name,points])=>({name,points:points.sort((a,b)=>a.minute-b.minute)}))}
function renderBooks(s){const el=document.querySelector('[data-book-chart]'),empty=document.querySelector('[data-book-empty]'),legend=document.querySelector('[data-book-legend]');if(!el)return;clear(el);if(legend)legend.innerHTML='';const books=bookSeries(s);if(!books.length){if(empty)empty.hidden=false;return}if(empty)empty.hidden=true;if(legend)legend.innerHTML=books.map((b,i)=>`<span><i style="background:${COLORS[i%COLORS.length]}"></i>${esc(b.name)}</span>`).join('');const all=books.flatMap(b=>b.points);let minX=Math.min(...all.map(x=>x.minute)),maxX=Math.max(...all.map(x=>x.minute));if(minX===maxX){minX-=1;maxX+=1}let minY=Math.min(...all.map(x=>x.odds)),maxY=Math.max(...all.map(x=>x.odds));if(minY===maxY){minY=Math.max(1,minY-.05);maxY+=.05}const f=chartFrame(el,1040,320,minX,maxX,minY,maxY,v=>Number(v).toFixed(2));books.forEach((b,i)=>{const color=COLORS[i%COLORS.length];if(b.points.length>1)el.appendChild(svg('polyline',{points:b.points.map(r=>`${f.x(r.minute)},${f.y(r.odds)}`).join(' '),class:'book-line',stroke:color}));b.points.forEach(r=>el.appendChild(svg('circle',{cx:f.x(r.minute),cy:f.y(r.odds),r:3,class:'book-dot',fill:color})))} )}
function renderMarketSummary(j){const el=document.querySelector('[data-market-summary]');if(!el)return;const defs=j.markets||marketDefs,counts=j.byMarket||{};el.innerHTML=Object.entries(defs).map(([k,d])=>`<article class="metric"><span>${esc(d.label||k)}</span><strong>${counts[k]||0}</strong><small>${esc(d.provider||'Bet365')} · ${esc(d.period||'FT')}</small></article>`).join('')}
function selectRow(index){selected=Math.max(0,Math.min(index,rows.length-1));document.querySelectorAll('[data-stat-index]').forEach((tr,i)=>tr.classList.toggle('selected',i===selected));const s=rows[selected],box=document.querySelector('[data-visual-evidence]');if(!s){if(box)box.hidden=true;return}if(box)box.hidden=false;set('[data-visual-match]',`${s.home?.name||'—'} - ${s.away?.name||'—'}`);set('[data-visual-meta]',([s.league?.country,s.league?.name].filter(Boolean).join(' · ')||'—')+` · ${s.bookmaker||'Bet365'} · ${s.providerMarket||'—'} · ${s.period||'—'}`);const m=entryMinute(s);set('[data-visual-minute]',m==null?'—':`${m}'`);set('[data-visual-score]',score(s.entryScore??s.scoreAt));set('[data-visual-market]',label(s));set('[data-visual-line]',s.line);set('[data-visual-odds]',s.odds);renderBars(s);renderEvent(s);renderBooks(s)}
function render(j){marketDefs=j.markets||{};set('[data-total]',j.total);set('[data-win]',j.win);set('[data-loss]',j.loss);set('[data-win-rate]',j.winRate===null?'—':`${j.winRate}%`);renderMarketSummary(j);rows=Array.isArray(j.rows)?j.rows:[];const tbody=document.querySelector('[data-stat-body]');if(tbody)tbody.innerHTML=rows.length?rows.map((s,i)=>{const league=[s.league?.country,s.league?.name].filter(Boolean).join(' · '),m=entryMinute(s);return`<tr data-stat-index="${i}" tabindex="0"><td>${esc(dt(s.createdAt))}</td><td><span class="match-name">${esc(s.home?.name||'—')} - ${esc(s.away?.name||'—')}</span><span class="sub">${esc(league||'—')}</span></td><td>${esc(show(m))}${m==null?'':"'"}</td><td><span class="match-name">${esc(label(s))}</span><span class="sub">${esc(s.providerMarket||'—')} · ${esc(s.period||'—')}</span></td><td>${esc(show(s.selection))}</td><td>${esc(show(s.line))}</td><td class="odds">${esc(show(s.odds))}</td><td>${esc(s.bookmaker||'Bet365')}</td><td>${esc(score(s.entryScore??s.scoreAt))}</td><td>${esc(score(s.finalScore))}</td><td>${resultTag(s.result)}</td></tr>`}).join(''):'<tr><td colspan="11" class="empty">ยังไม่มีสัญญาณที่จบการแข่งขันและตัดสินผลแล้ว</td></tr>';if(rows.length)selectRow(Math.min(selected,rows.length-1));else selectRow(0);const st=document.querySelector('[data-stat-state]');if(st)st.innerHTML=`<span class="pill"><i class="dot live"></i>Results · ALL MARKETS${j.halfWin||j.halfLoss?` · HALF ${j.halfWin||0}/${j.halfLoss||0}`:''}</span>`}
async function load(){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j?.ok!==true)throw new Error();render(j)}catch{const st=document.querySelector('[data-stat-state]');if(st)st.innerHTML='<span class="pill"><i class="dot warn"></i>ข้อมูลสถิติไม่พร้อม</span>'}}
document.addEventListener('click',e=>{const tr=e.target.closest('[data-stat-index]');if(tr)selectRow(Number(tr.dataset.statIndex))});document.addEventListener('keydown',e=>{const tr=e.target.closest('[data-stat-index]');if(tr&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectRow(Number(tr.dataset.statIndex))}});load();setInterval(load,POLL);
})();
