(()=>{
'use strict';
const config=window.NOMAD342_CONFIG;
if(!config?.defaults)throw new Error('NOMAD342_CONFIG missing');
const SETTINGS_KEY=config.settingsKey;
const DEFAULTS=config.defaults;
const LEDGER_KEY='nomadLedger342';
const runtime=window.NOMAD342_RUNTIME||{};
function settings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return {...DEFAULTS,...saved,allowedSelectionLines:Array.isArray(saved.allowedSelectionLines)?saved.allowedSelectionLines:[...(DEFAULTS.allowedSelectionLines||[])]};}catch{return {...DEFAULTS,allowedSelectionLines:[...(DEFAULTS.allowedSelectionLines||[])]};}}
function saveSettings(v){localStorage.setItem(SETTINGS_KEY,JSON.stringify(v));}
function fmtLine(n){if(n===null||n===undefined||!Number.isFinite(Number(n)))return '—';const x=Number(Number(n).toFixed(2));return `${x>0?'+':''}${x}`;}
function fillLineOptions(select){if(!select||select.options.length)return;for(let v=-5;v<=5.0001;v+=.25){const n=Number(v.toFixed(2)),op=document.createElement('option');op.value=String(n);op.textContent=fmtLine(n);select.appendChild(op);}}
function readForm(form,base={}){const v={...base};for(const [k,d] of Object.entries(DEFAULTS)){const x=form.elements[k];if(!x)continue;if(k==='allowedSelectionLines'){v[k]=[...x.selectedOptions].map(o=>Number(o.value));continue;}if(typeof d==='boolean')v[k]=x.checked;else if(typeof d==='number')v[k]=Number(x.value);else v[k]=x.value;}return v;}
function validateSettings(v){const errors=[];if(!Number.isFinite(v.minuteFrom)||!Number.isFinite(v.minuteTo)||v.minuteFrom>v.minuteTo)errors.push('Minute From must not be later than Minute To');if(!Number.isFinite(v.rollingWindowMinutes)||v.rollingWindowMinutes<1||v.rollingWindowMinutes>15)errors.push('Rolling Window must be 1–15 minutes');if(Number(v.attackWeight)===0&&Number(v.dangerousAttackWeight)===0)errors.push('Attack and Dangerous Attack weights cannot both be zero');if(v.homeEventRequired&&!v.sotEvidenceEnabled&&!v.shotOffEvidenceEnabled&&!v.cornerEvidenceEnabled)errors.push('Enable at least one evidence type while fresh HOME event is required');if(v.allowedLinesMode==='SELECTED'&&!(v.allowedSelectionLines||[]).length)errors.push('Select at least one AH line or use ANY');if(v.oddsMaximumEnabled){if(!Number.isFinite(v.oddsMaximum))errors.push('Maximum Odds is required when enabled');else if(Number(v.oddsMinimum)>Number(v.oddsMaximum))errors.push('Minimum Odds must not exceed Maximum Odds');}return errors;}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function summaryItems(v){const evidence=[v.sotEvidenceEnabled?`SOT +${v.sotDeltaMinimum}`:null,v.shotOffEvidenceEnabled?`OFF +${v.shotOffDeltaMinimum}`:null,v.cornerEvidenceEnabled?`CORNER +${v.cornerDeltaMinimum}`:null].filter(Boolean);const oddsMax=v.oddsMaximumEnabled&&Number.isFinite(v.oddsMaximum)?Number(v.oddsMaximum).toFixed(2):'OFF';return [`${v.minuteFrom}–${v.minuteTo}'`,`${v.rollingWindowMinutes}m rolling`,v.scoreDifferenceFilterEnabled?`score gap ≤${v.maxScoreDifference}`:'score filter OFF',`ATK×${v.attackWeight}`,`DANGER×${v.dangerousAttackWeight}`,`pressure ≥${v.homePressureShareMinimum}%`,`trend ${v.trendConditionsRequired}/3`,v.homeEventRequired?`evidence ${v.evidenceMode}`:'event gate OFF',...evidence,`odds ${Number(v.oddsMinimum).toFixed(2)}–${oddsMax}`,`age ≤${v.maximumPriceAgeSeconds}s`,v.oneSignalPerMatch?'1 signal/match':'repeat signals allowed'];}
function renderSummary(form,base){const host=document.getElementById('settingsSummary');if(!host)return;const v=readForm(form,base),errors=validateSettings(v);host.innerHTML=summaryItems(v).map(text=>`<span>${esc(text)}</span>`).join('')+errors.map(text=>`<span class="warn">${esc(text)}</span>`).join('');}
function bindSettings(){const form=document.getElementById('settingsForm');if(!form)return;const lines=form.elements.allowedSelectionLines;fillLineOptions(lines);let c=settings();Object.entries(c).forEach(([k,v])=>{const e=form.elements[k];if(!e)return;if(k==='allowedSelectionLines'){[...e.options].forEach(op=>op.selected=(v||[]).map(Number).includes(Number(op.value)));return;}if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v;});const refresh=()=>renderSummary(form,c);form.addEventListener('input',refresh);form.addEventListener('change',refresh);refresh();form.addEventListener('submit',event=>{event.preventDefault();const v=readForm(form,c),errors=validateSettings(v),status=document.getElementById('saveStatus');if(errors.length){if(status){status.textContent=`Not saved · ${errors[0]}`;status.className='waittxt';}renderSummary(form,c);return;}saveSettings(v);c={...v,allowedSelectionLines:[...(v.allowedSelectionLines||[])]};if(status){status.textContent='Saved · 3.42 will use these values on this browser';status.className='oktxt';}renderSummary(form,c);document.dispatchEvent(new CustomEvent('nomad342:settingssaved',{detail:{settings:c}}));});document.getElementById('defaultsButton')?.addEventListener('click',()=>{saveSettings({...DEFAULTS,allowedSelectionLines:[...(DEFAULTS.allowedSelectionLines||[])]});location.reload();});}
async function fetchJson(url,timeoutMs=6000){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),timeoutMs);try{const response=await fetch(url,{cache:'no-store',signal:ac.signal});if(!response.ok)throw new Error(`http_${response.status}`);return await response.json();}finally{clearTimeout(timer);}}
async function renderHealth(){const grid=document.getElementById('healthGrid');if(!grid)return;const c=settings();const priceBase=String(runtime.priceBase||'').replace(/\/$/,'');let adapter=null,adapterError=null;try{if(priceBase)adapter=await fetchJson(`${priceBase}${runtime.priceHealthPath||'/health'}`,Number(runtime.priceTimeoutMs)||8000);}catch(error){adapterError=String(error?.message||error);}const ready=Boolean(adapter?.ok),adapterState=ready?'READY':adapter?'WAIT':'ERROR';const source=adapter?.source||{};const items=[['Event Engine',runtime.engineBase?'READY':'WAIT',runtime.engineBase?'3.42 live-score/event feed is configured.':'3.42 event endpoint is not configured.'],['Bookmaker Price Feed',adapterState,ready?`${source.source||'Market worker'} price reference is reachable.`:adapterError?`Price health request failed: ${adapterError}`:'Price reference is not ready.'],['Fixture Mapping','READY','Team/league mapping is fail-closed; low-confidence or ambiguous matches do not receive a price.'],['AH Validator','READY','Only valid quarter-goal HOME AH lines with two-sided decimal odds above 1.00 enter the price gate.'],['Freshness Gate','READY',`Configured maximum price age is ${c.maximumPriceAgeSeconds}s.`],['Final Judge','ARMED','Event Gate plus configured bookmaker price limits determine whether a signal can lock; final score settlement remains separate.']];grid.innerHTML=items.map(i=>`<article class="health-item"><header><span>${i[0]}</span><b class="${['LIVE','READY','VALID','ARMED'].includes(i[1])?'oktxt':'waittxt'}">${i[1]}</b></header><div class="note">${i[2]}</div></article>`).join('');}
function renderLegacyStats(){const tbody=document.getElementById('statsBody');if(!tbody)return;let rows=[];try{rows=JSON.parse(localStorage.getItem(LEDGER_KEY)||'[]');}catch{}tbody.innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.ts).toLocaleString()}</td><td>${r.match}</td><td>${r.minute}'</td><td>${r.score}</td><td>HOME ${r.line}</td><td>${r.odds}</td><td>${r.source||'Bookmaker'}</td><td>${r.result||'PENDING'}</td><td>${r.reason||''}</td></tr>`).join(''):'<tr><td colspan="9">No signal snapshot yet.</td></tr>';}
document.addEventListener('DOMContentLoaded',()=>{const page=document.body?.dataset?.page;if(page==='settings')bindSettings();if(page==='health')renderHealth();if(page==='statistics')renderLegacyStats();});
})();
