(()=>{
'use strict';
const SETTINGS_KEY='nomadSettings342';
const DEFAULTS={minuteFrom:55,minuteTo:88,rollingWindowMinutes:5,scoreDifferenceFilterEnabled:true,maxScoreDifference:1,attackWeight:1,dangerousAttackWeight:2,homePressureShareMinimum:55,trendConditionsRequired:2,homeEventRequired:true,sotEvidenceEnabled:true,sotDeltaMinimum:1,shotOffEvidenceEnabled:true,shotOffDeltaMinimum:1,cornerEvidenceEnabled:true,cornerDeltaMinimum:1,evidenceMode:'ANY',allowedLinesMode:'ANY',allowedSelectionLines:[],oddsMinimum:1.80,oddsMaximumEnabled:false,oddsMaximum:2.40,maximumPriceAgeSeconds:30,oneSignalPerMatch:true};
const runtime=window.NOMAD342_RUNTIME||{};
function settings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return {...DEFAULTS,...saved,allowedSelectionLines:Array.isArray(saved.allowedSelectionLines)?saved.allowedSelectionLines:[]};}catch{return {...DEFAULTS,allowedSelectionLines:[]};}}
function saveSettings(v){localStorage.setItem(SETTINGS_KEY,JSON.stringify(v));}
function fmtLine(n){if(n===null||n===undefined||!Number.isFinite(Number(n)))return '—';const x=Number(Number(n).toFixed(2));return `${x>0?'+':''}${x}`;}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function fillLineOptions(select){if(!select||select.options.length)return;for(let v=-5;v<=5.0001;v+=.25){const n=Number(v.toFixed(2)),op=document.createElement('option');op.value=String(n);op.textContent=fmtLine(n);select.appendChild(op);}}
function bindSettings(){const form=document.getElementById('settingsForm');if(!form)return;const lines=form.elements.allowedSelectionLines;fillLineOptions(lines);const c=settings();Object.entries(c).forEach(([k,v])=>{const e=form.elements[k];if(!e)return;if(k==='allowedSelectionLines'){[...e.options].forEach(op=>op.selected=(v||[]).map(Number).includes(Number(op.value)));return;}if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v;});form.addEventListener('submit',e=>{e.preventDefault();const v={...c};for(const [k,d] of Object.entries(DEFAULTS)){const x=form.elements[k];if(!x)continue;if(k==='allowedSelectionLines'){v[k]=[...x.selectedOptions].map(o=>Number(o.value));continue;}if(typeof d==='boolean')v[k]=x.checked;else if(typeof d==='number')v[k]=Number(x.value);else v[k]=x.value;}saveSettings(v);const s=document.getElementById('saveStatus');if(s)s.textContent='Saved';});document.getElementById('defaultsButton')?.addEventListener('click',()=>{saveSettings(DEFAULTS);location.reload();});}
async function getJson(path){if(!runtime.engineBase)throw new Error('engine_not_configured');const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),Number(runtime.requestTimeoutMs)||9000);try{const r=await fetch(`${runtime.engineBase}${path}`,{cache:'no-store',signal:ac.signal});if(!r.ok)throw new Error(`http_${r.status}`);return await r.json();}finally{clearTimeout(timer);}}
async function renderHealth(){const grid=document.getElementById('healthGrid');if(!grid)return;let engine=null,judge=null;try{[engine,judge]=await Promise.all([getJson('/health'),getJson(runtime.judgeStatusPath||'/judge/thscore/status')]);}catch(error){const msg=String(error?.message||error);grid.innerHTML=`<article class="health-item"><header><span>3.42 Engine</span><b class="waittxt">WAIT</b></header><div class="note">${esc(msg)}</div></article>`;return;}const configured=Boolean(judge?.configured);const sourceOk=engine?.version==='3.42'&&!engine?.lastError;const items=[['TotalCorner Event Inlet',sourceOk?'LIVE':'WAIT',sourceOk?`Cycle ${engine.cycle??'—'} · ${engine.liveMatches??0} live matches`:(engine?.lastError||'Event inlet waiting')],['THScore Price Judge',configured?'READY':'FAIL CLOSED',configured?'Server-side API secret is configured.':'THScore API key is not configured; candidates remain WAIT.'],['Match Mapper','READY','HOME/AWAY names, league, kickoff and live score are cross-checked; ambiguous matches wait.'],['Asian Handicap Decode','READY','THScore handicap sign is normalized to NOMAD HOME AH and quarter-line checked.'],['Odds Normalizer',judge?.oddsFormat==='AUTO'?'CAUTIOUS':'READY',judge?.oddsFormat==='AUTO'?'Unclear odds formats remain UNKNOWN and wait.':`Forced format: ${judge?.oddsFormat}`],['Freshness Gate','READY',`Frontend maximum price age: ${settings().maximumPriceAgeSeconds}s.`],['Final Judge',configured?'READY':'WAIT','Signal requires Event PASS + mapped match + fresh valid THScore HOME AH price inside configured gates.']];grid.innerHTML=items.map(i=>`<article class="health-item"><header><span>${esc(i[0])}</span><b class="${['LIVE','READY'].includes(i[1])?'oktxt':'waittxt'}">${esc(i[1])}</b></header><div class="note">${esc(i[2])}</div></article>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{const p=document.body.dataset.page;if(p==='settings')bindSettings();if(p==='health')renderHealth();});
})();
