(()=>{
'use strict';
const SETTINGS_KEY='nomadSettings342';
const LEDGER_KEY='nomadLedger342';
const DEFAULTS={minuteFrom:55,minuteTo:88,rollingWindowMinutes:5,scoreDifferenceFilterEnabled:true,maxScoreDifference:1,attackWeight:1,dangerousAttackWeight:2,homePressureShareMinimum:55,trendConditionsRequired:2,homeEventRequired:true,sotEvidenceEnabled:true,sotDeltaMinimum:1,shotOffEvidenceEnabled:true,shotOffDeltaMinimum:1,cornerEvidenceEnabled:true,cornerDeltaMinimum:1,evidenceMode:'ANY',allowedLinesMode:'ANY',allowedSelectionLines:[],oddsMinimum:1.80,oddsMaximumEnabled:false,oddsMaximum:2.40,maximumPriceAgeSeconds:30,oneSignalPerMatch:true};
const TEST_FIXTURES=[
 {id:'342-m88-zero',league:'NOMAD Test League',home:'River City',away:'North United',minute:67,score:[1,1],event:{snapshots:[{minute:62,attacks:[50,38],dangerous:[28,18],sot:[4,3],off:[6,3],corner:[3,2]},{minute:67,attacks:[61,42],dangerous:[38,21],sot:[5,3],off:[8,4],corner:[4,2]}]},m88:{status:'VALID',rawHomeLine:'0',rawAwayLine:'',homeOddsRaw:0.85,awayOddsRaw:1.05,oddsFormat:'HK',transport:'DOM'}},
 {id:'342-m88-unsigned',league:'NOMAD Test League',home:'East Athletic',away:'Blue Town',minute:74,score:[0,0],event:{snapshots:[{minute:69,attacks:[44,42],dangerous:[21,20],sot:[2,2],off:[4,4],corner:[2,2]},{minute:74,attacks:[56,47],dangerous:[31,24],sot:[3,2],off:[6,5],corner:[3,2]}]},m88:{status:'VALID',rawHomeLine:'0.5',rawAwayLine:'',homeOddsRaw:0.84,awayOddsRaw:1.06,oddsFormat:'HK',transport:'DOM'}},
 {id:'342-m88-too-early',league:'NOMAD Test League',home:'Green FC',away:'Capital Stars',minute:49,score:[0,1],event:{snapshots:[{minute:44,attacks:[48,31],dangerous:[24,14],sot:[3,1],off:[5,2],corner:[2,1]},{minute:49,attacks:[64,35],dangerous:[37,16],sot:[5,1],off:[7,3],corner:[4,1]}]},m88:{status:'VALID',rawHomeLine:'0',rawAwayLine:'',homeOddsRaw:0.88,awayOddsRaw:1.02,oddsFormat:'HK',transport:'DOM'}}
];
function settings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return {...DEFAULTS,...saved,allowedSelectionLines:Array.isArray(saved.allowedSelectionLines)?saved.allowedSelectionLines:[]}}catch{return {...DEFAULTS,allowedSelectionLines:[]}}}
function saveSettings(v){localStorage.setItem(SETTINGS_KEY,JSON.stringify(v));}
function fmtLine(n){if(n===null||n===undefined||!Number.isFinite(Number(n)))return '—';const x=Number(Number(n).toFixed(2));return `${x>0?'+':''}${x}`}
function delta(a,b,i){return Number(b?.[i]||0)-Number(a?.[i]||0)}
function eventMetrics(m,c){const snaps=[...(m.event?.snapshots||[])].sort((a,b)=>a.minute-b.minute);const eligible=snaps.filter(s=>s.minute>=m.minute-c.rollingWindowMinutes&&s.minute<=m.minute);const first=eligible[0]||snaps[0],last=eligible[eligible.length-1]||snaps[snaps.length-1];if(!first||!last)return null;const hA=delta(first.attacks,last.attacks,0),aA=delta(first.attacks,last.attacks,1);const hD=delta(first.dangerous,last.dangerous,0),aD=delta(first.dangerous,last.dangerous,1);const hWeighted=hA*c.attackWeight+hD*c.dangerousAttackWeight;const aWeighted=aA*c.attackWeight+aD*c.dangerousAttackWeight;const total=Math.max(0,hWeighted)+Math.max(0,aWeighted);const pressureShare=total>0?(Math.max(0,hWeighted)/total)*100:0;const sotDelta=delta(first.sot,last.sot,0),awaySotDelta=delta(first.sot,last.sot,1);const offDelta=delta(first.off,last.off,0),awayOffDelta=delta(first.off,last.off,1);const cornerDelta=delta(first.corner,last.corner,0),awayCornerDelta=delta(first.corner,last.corner,1);const trend=[hWeighted>aWeighted,hD>aD,(sotDelta+offDelta)>(awaySotDelta+awayOffDelta)];return {from:first.minute,to:last.minute,pressureShare:Number(pressureShare.toFixed(1)),trendPass:trend.filter(Boolean).length,sotDelta,offDelta,cornerDelta,attacks:`+${hA} / +${aA}`,dangerous:`+${hD} / +${aD}`};}
function eventCheck(m,c){const reasons=[];let pass=true;const metrics=eventMetrics(m,c);if(m.minute<c.minuteFrom||m.minute>c.minuteTo){pass=false;reasons.push(`minute ${m.minute} outside ${c.minuteFrom}–${c.minuteTo}`)}else reasons.push(`minute ${m.minute} in window`);if(c.scoreDifferenceFilterEnabled&&Math.abs(m.score[0]-m.score[1])>c.maxScoreDifference){pass=false;reasons.push('score gap rejected')}else reasons.push('score gate pass');if(!metrics){pass=false;reasons.push('rolling event window unavailable');return {pass,reasons,metrics:null}}if(metrics.pressureShare<c.homePressureShareMinimum){pass=false;reasons.push(`HOME pressure ${metrics.pressureShare}% < ${c.homePressureShareMinimum}%`)}else reasons.push(`HOME pressure ${metrics.pressureShare}% pass`);if(metrics.trendPass<c.trendConditionsRequired){pass=false;reasons.push(`trend ${metrics.trendPass}/3 < ${c.trendConditionsRequired}/3`)}else reasons.push(`trend ${metrics.trendPass}/3 pass`);const ev=[];if(c.sotEvidenceEnabled)ev.push(metrics.sotDelta>=c.sotDeltaMinimum);if(c.shotOffEvidenceEnabled)ev.push(metrics.offDelta>=c.shotOffDeltaMinimum);if(c.cornerEvidenceEnabled)ev.push(metrics.cornerDelta>=c.cornerDeltaMinimum);if(c.homeEventRequired){const ep=c.evidenceMode==='ALL'?ev.length>0&&ev.every(Boolean):ev.some(Boolean);if(!ep){pass=false;reasons.push(`new HOME event ${c.evidenceMode} rejected`)}else reasons.push(`new HOME event ${c.evidenceMode} pass`)}return {pass,reasons,metrics};}
function makeTestObservation(m){return {...m.m88,matchId:m.id,home:m.home,away:m.away,minute:m.minute,score:m.score,observedAt:Date.now()-5000}}
function lineAllowed(line,c){if(c.allowedLinesMode!=='SELECTED')return true;const selected=(c.allowedSelectionLines||[]).map(Number).filter(Number.isFinite);return selected.some(v=>Math.abs(v-line)<0.001)}
function m88Check(m,c){const api=window.NOMADM88;if(!api)return {pass:false,obs:null,reason:'M88 OBSERVER MODULE MISSING'};const obs=api.normalizeObservation(makeTestObservation(m),c.maximumPriceAgeSeconds);if(obs.status!=='VALID')return {pass:false,obs,reason:obs.status==='UNKNOWN'?'M88 HDP SIGN UNKNOWN — WAIT':`M88 ${obs.status} — WAIT`};if(!lineAllowed(obs.decodedHomeLine,c))return {pass:false,obs,reason:`HOME AH ${fmtLine(obs.decodedHomeLine)} NOT SELECTED`};if(obs.homeOddsDecimal<c.oddsMinimum)return {pass:false,obs,reason:`M88 PRICE ${obs.homeOddsDecimal.toFixed(2)} BELOW ${c.oddsMinimum.toFixed(2)}`};if(c.oddsMaximumEnabled&&obs.homeOddsDecimal>c.oddsMaximum)return {pass:false,obs,reason:`M88 PRICE ${obs.homeOddsDecimal.toFixed(2)} ABOVE ${c.oddsMaximum.toFixed(2)}`};return {pass:true,obs,reason:'M88 PRICE CONFIRMED'};}
function evaluate(m,c=settings()){const event=eventCheck(m,c);const candidate=event.pass;const price=candidate?m88Check(m,c):{pass:false,obs:null,reason:'EVENT GATE NOT PASSED'};const signal=candidate&&price.pass;return {m,event,candidate,price,signal,decision:signal?'SIGNAL':candidate?'WAIT':'WATCH'};}
function saveLedger(r,c=settings()){if(!r.signal)return;let rows=[];try{rows=JSON.parse(localStorage.getItem(LEDGER_KEY)||'[]')}catch{}if(c.oneSignalPerMatch&&rows.some(x=>x.id===r.m.id))return;const o=r.price.obs;rows.unshift({id:r.m.id,ts:new Date().toISOString(),match:`${r.m.home} — ${r.m.away}`,minute:r.m.minute,score:r.m.score.join('–'),line:fmtLine(o.decodedHomeLine),rawLine:o.rawHomeLine,odds:o.homeOddsDecimal,rawOdds:o.homeOddsRaw,oddsFormat:o.oddsFormat,source:'M88',result:'PENDING',reason:'EVENT PASS + M88 PRICE CONFIRMED'});localStorage.setItem(LEDGER_KEY,JSON.stringify(rows.slice(0,100)));}
function statusClass(r){return r.signal?'signal-card-pass':r.candidate?'signal-card-wait':'signal-card-watch'}
function pickValue(r){return r.signal?r.m.home:r.candidate?'WAIT':'WATCH'}
function m88Detail(r){if(!r.price.obs)return `<div class="kv"><span>Status</span><b>NOT CHECKED</b></div>`;const o=r.price.obs;return `<div class="kv"><span>Status</span><b>${o.status}</b></div><div class="kv"><span>RAW HOME HDP</span><b>${o.rawHomeLine||'—'}</b></div><div class="kv"><span>RAW HK odds</span><b>${o.homeOddsRaw??'—'} / ${o.awayOddsRaw??'—'}</b></div><div class="kv"><span>Decimal odds</span><b>${o.homeOddsDecimal??'—'} / ${o.awayOddsDecimal??'—'}</b></div><div class="kv"><span>Price age</span><b>${o.ageSeconds??'—'}s</b></div>`}
function matchCard(r){const m=r.m,em=r.event.metrics,o=r.price.obs;const line=o?.decodedHomeLine;const odds=o?.homeOddsDecimal;const summary=r.signal?`${m.home} · HOME AH ${fmtLine(line)} @ ${odds.toFixed(2)} · M88`:r.candidate?r.price.reason:'Waiting for event conditions';return `<article class="signal-card ${statusClass(r)}"><div class="card-topline"><span>${m.league}</span><span class="live-minute">${m.minute}'</span><span class="live-score">${m.score.join('–')}</span><span class="badge ${r.signal?'signal':'wait'}">${r.decision}</span></div><div class="teams-line"><strong>${m.home}</strong><span>vs</span><strong>${m.away}</strong></div><div class="pick-strip"><div><span>PICK</span><strong>${pickValue(r)}</strong></div><div><span>AH</span><strong>${line===null||line===undefined?(o?.rawHomeLine?`RAW ${o.rawHomeLine}`:'—'):fmtLine(line)}</strong></div><div><span>ODDS</span><strong>${odds?odds.toFixed(2):'—'}</strong></div><div><span>ENTRY</span><strong>${m.minute}' · ${m.score.join('–')}</strong></div></div><div class="signal-summary">${summary}</div><div class="details"><div class="box"><h3>EVENT</h3><div class="kv"><span>Window</span><b>${em?`${em.from}'–${em.to}'`:'—'}</b></div><div class="kv"><span>Pressure</span><b>${em?em.pressureShare+'%':'—'}</b></div><div class="kv"><span>Attack Δ H/A</span><b>${em?.attacks||'—'}</b></div><div class="kv"><span>Dangerous Δ H/A</span><b>${em?.dangerous||'—'}</b></div><div class="kv"><span>SOT / OFF / COR</span><b>${em?`+${em.sotDelta} / +${em.offDelta} / +${em.cornerDelta}`:'—'}</b></div><div class="kv"><span>Gate</span><b class="${r.event.pass?'oktxt':'redtxt'}">${r.event.pass?'PASS':'WAIT'}</b></div></div><div class="box"><h3>M88 PRICE</h3>${m88Detail(r)}</div><div class="box"><h3>DECISION</h3><div class="kv"><span>Candidate</span><b>${r.candidate?'YES':'NO'}</b></div><div class="kv"><span>HOME AH</span><b>${fmtLine(line)}</b></div><div class="kv"><span>HOME odds</span><b>${odds??'—'}</b></div><div class="kv"><span>Verdict</span><b>${r.price.reason}</b></div><div class="kv"><span>Final</span><b class="${r.signal?'oktxt':'waittxt'}">${r.signal?'SIGNAL':'NO SIGNAL'}</b></div></div></div><div class="reason-line">${r.event.reasons.join(' · ')}</div></article>`;}
function renderExternalObserver(c){const host=document.getElementById('observerCard');if(!host||!window.NOMADM88)return;const raw=window.NOMADM88.read();const status=document.getElementById('m88ObserverStatus');if(!raw){host.innerHTML='<div class="note">Waiting for an M88 observation.</div>';if(status)status.textContent='READY';return}const o=window.NOMADM88.normalizeObservation(raw,c.maximumPriceAgeSeconds);host.innerHTML=`<div class="kv"><span>Match</span><b>${o.home||'—'} — ${o.away||'—'}</b></div><div class="kv"><span>RAW HOME HDP</span><b>${o.rawHomeLine||'—'}</b></div><div class="kv"><span>RAW HK odds</span><b>${o.homeOddsRaw??'—'} / ${o.awayOddsRaw??'—'}</b></div><div class="kv"><span>Decimal odds</span><b>${o.homeOddsDecimal??'—'} / ${o.awayOddsDecimal??'—'}</b></div><div class="kv"><span>Status</span><b>${o.status}</b></div>`;if(status)status.textContent=o.status;}
function renderLive(){const c=settings(),results=TEST_FIXTURES.map(m=>evaluate(m,c));const list=document.getElementById('matchList');if(list)list.innerHTML=results.map(matchCard).join('');const ids={liveCount:results.length,watchCount:results.filter(x=>!x.candidate).length,candidateCount:results.filter(x=>x.candidate).length,signalCount:results.filter(x=>x.signal).length};Object.entries(ids).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});document.querySelectorAll('[data-pipe]').forEach(x=>x.classList.add('ok'));window.__nomad342Results=results;renderExternalObserver(c);}
function runCheck(){const c=settings(),results=TEST_FIXTURES.map(m=>evaluate(m,c));results.forEach(r=>saveLedger(r,c));renderLive();const el=document.getElementById('runStatus');if(el)el.textContent=`Cycle complete · ${results.filter(r=>r.signal).length} signal · ${new Date().toLocaleTimeString()}`;}
function renderStats(){let rows=[];try{rows=JSON.parse(localStorage.getItem(LEDGER_KEY)||'[]')}catch{}const tbody=document.getElementById('statsBody');if(tbody)tbody.innerHTML=rows.length?rows.map(r=>`<tr><td>${new Date(r.ts).toLocaleString()}</td><td>${r.match}</td><td>${r.minute}'</td><td>${r.score}</td><td>HOME ${r.line}<br><small>RAW ${r.rawLine}</small></td><td>${r.odds}<br><small>${r.rawOdds} ${r.oddsFormat}</small></td><td>${r.source}</td><td class="waittxt">${r.result}</td><td>${r.reason}</td></tr>`).join(''):`<tr><td colspan="9">No signal snapshot yet.</td></tr>`;}
function renderHealth(){const grid=document.getElementById('healthGrid');if(!grid)return;const hasLive=Boolean(window.NOMADM88?.read());const items=[['Event Engine','TEST INPUT','Rolling-window pressure and event gates are active.'],['M88 Price Observer','VERIFIED','HOME/AWAY, FT HDP and changing Hong Kong odds are readable from the M88 live page.'],['M88 Observation',hasLive?'LIVE SNAPSHOT':'READY',hasLive?'Current observation is available to the adapter.':'Adapter is waiting for an observation.'],['HDP Decode','CAUTIOUS','Zero or explicitly signed lines are accepted. Unsigned non-zero lines wait for a proven side-sign rule.'],['Odds Normalizer','READY','Hong Kong odds are preserved and converted to decimal for the price gate.'],['Freshness Gate','READY','Old observations become STALE at the configured age.'],['Final Judge','READY','Signal requires Event PASS and a valid M88 price inside the configured line and odds gates.']];grid.innerHTML=items.map(i=>`<article class="health-item"><header><span>${i[0]}</span><b class="${['READY','VERIFIED','LIVE SNAPSHOT'].includes(i[1])?'oktxt':'waittxt'}">${i[1]}</b></header><div class="note">${i[2]}</div></article>`).join('');}
function fillLineOptions(select){if(!select||select.options.length)return;for(let v=-5;v<=5.0001;v+=.25){const n=Number(v.toFixed(2)),op=document.createElement('option');op.value=String(n);op.textContent=fmtLine(n);select.appendChild(op)}}
function bindSettings(){const form=document.getElementById('settingsForm');if(!form)return;const lines=form.elements.allowedSelectionLines;fillLineOptions(lines);const c=settings();Object.entries(c).forEach(([k,v])=>{const e=form.elements[k];if(!e)return;if(k==='allowedSelectionLines'){[...e.options].forEach(op=>op.selected=(v||[]).map(Number).includes(Number(op.value)));return}if(e.type==='checkbox')e.checked=Boolean(v);else e.value=v});form.addEventListener('submit',e=>{e.preventDefault();const v={...c};for(const [k,d] of Object.entries(DEFAULTS)){const x=form.elements[k];if(!x)continue;if(k==='allowedSelectionLines'){v[k]=[...x.selectedOptions].map(o=>Number(o.value));continue}if(typeof d==='boolean')v[k]=x.checked;else if(typeof d==='number')v[k]=Number(x.value);else v[k]=x.value}saveSettings(v);document.getElementById('saveStatus').textContent='Saved';});document.getElementById('defaultsButton')?.addEventListener('click',()=>{saveSettings(DEFAULTS);location.reload()});}
document.addEventListener('DOMContentLoaded',()=>{const p=document.body.dataset.page;if(p==='live'){renderLive();document.getElementById('runCheck')?.addEventListener('click',runCheck);document.getElementById('resetLedger')?.addEventListener('click',()=>{localStorage.removeItem(LEDGER_KEY);document.getElementById('runStatus').textContent='Ledger cleared'})}if(p==='statistics')renderStats();if(p==='health')renderHealth();if(p==='settings')bindSettings();});
})();