(()=>{
'use strict';
const SETTINGS_KEY='nomad342.condition2.settings.v1';
const TELEMETRY_KEY='nomad342.condition2.telemetry.v1';
const DEFAULTS={targetMode:'BOTH',minuteFrom:55,minuteTo:88,rollingWindowMinutes:5,attackWeight:1,dangerousAttackWeight:1,pressureShareMinimum:55,evidenceMode:'ANY',sotEvidenceEnabled:true,sotDeltaMinimum:1,shotOffEvidenceEnabled:true,shotOffDeltaMinimum:1,cornerEvidenceEnabled:true,cornerDeltaMinimum:1,priceGateEnabled:false,oddsMinimum:1.80,oddsMaximumEnabled:false,oddsMaximum:2.40,observeOnly:true};
const FIELDS=Object.keys(DEFAULTS);
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function load(){try{return {...DEFAULTS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {...DEFAULTS}}}
function telemetry(){try{const v=JSON.parse(localStorage.getItem(TELEMETRY_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function applyForm(c){const form=document.getElementById('c2Form');if(!form)return;FIELDS.forEach(k=>{const el=form.elements[k];if(!el)return;if(el.type==='checkbox')el.checked=Boolean(c[k]);else el.value=String(c[k])})}
function readForm(){const form=document.getElementById('c2Form');const out={};FIELDS.forEach(k=>{const el=form.elements[k];if(!el)return;if(el.type==='checkbox')out[k]=el.checked;else if(el.type==='number')out[k]=Number(el.value);else out[k]=el.value});out.observeOnly=true;out.priceGateEnabled=false;return out}
function save(){const c=readForm();localStorage.setItem(SETTINGS_KEY,JSON.stringify(c));const s=document.getElementById('saveStatus');if(s)s.textContent=`Saved · ${new Date().toLocaleTimeString()} · observer only`;render()}
function reset(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(DEFAULTS));applyForm(DEFAULTS);render();const s=document.getElementById('saveStatus');if(s)s.textContent='Condition 2 defaults restored'}
function latestGroups(rows){const map=new Map();for(const x of rows){const key=`${x.matchId}|${x.side}`;if(!map.has(key))map.set(key,x)}return [...map.values()]}
function metric(v,d=2){const n=finite(v);return n===null?'—':n.toFixed(d)}
function selectedKey(){return document.getElementById('telemetrySelect')?.value||''}
function refreshSelect(rows){const sel=document.getElementById('telemetrySelect');if(!sel)return;const current=sel.value;const latest=latestGroups(rows);sel.innerHTML=latest.length?latest.map(x=>`<option value="${esc(x.matchId+'|'+x.side)}">${esc(x.side)} · ${esc(x.match||x.targetTeam||x.matchId)}</option>`).join(''):'<option value="">No C2 telemetry yet</option>';if([...sel.options].some(o=>o.value===current))sel.value=current}
function drawAxes(ctx,w,h,maxY,label){ctx.clearRect(0,0,w,h);ctx.font='11px Arial';ctx.fillStyle='#98a091';ctx.strokeStyle='rgba(150,158,151,.18)';ctx.lineWidth=1;const l=44,r=12,t=14,b=30;for(let i=0;i<=4;i++){const y=t+(h-t-b)*i/4;const val=maxY*(1-i/4);ctx.beginPath();ctx.moveTo(l,y);ctx.lineTo(w-r,y);ctx.stroke();ctx.fillText(String(Math.round(val*100)/100),4,y+4)}ctx.fillText(label,l,h-8);return {l,r,t,b,pw:w-l-r,ph:h-t-b}}
function setupCanvas(canvas){const ratio=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();const w=Math.max(320,Math.floor(rect.width));const h=Math.max(220,Math.floor(rect.height));canvas.width=w*ratio;canvas.height=h*ratio;const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return {ctx,w,h}}
function barChart(sample){const canvas=document.getElementById('rawChart');if(!canvas)return;const {ctx,w,h}=setupCanvas(canvas);const labels=['Attack','Danger','SOT','SOFF','Corner'];const keys=['attacks','dangerous','sot','off','corner'];const vals=keys.flatMap(k=>[Math.max(0,finite(sample?.raw?.[k]?.target)||0),Math.max(0,finite(sample?.raw?.[k]?.opponent)||0)]);const max=Math.max(1,...vals);const axis=drawAxes(ctx,w,h,Math.ceil(max),'events / rolling window');const groupW=axis.pw/labels.length;const bw=Math.max(8,Math.min(22,groupW*.28));ctx.font='10px Arial';for(let i=0;i<labels.length;i++){const a=vals[i*2],b=vals[i*2+1];const x=axis.l+i*groupW+groupW/2;for(const [j,v] of [[0,a],[1,b]]){const bh=axis.ph*(v/Math.ceil(max));const bx=x+(j===0?-bw-2:2);const by=axis.t+axis.ph-bh;ctx.fillStyle=j===0?'rgba(131,223,137,.72)':'rgba(242,210,27,.62)';ctx.fillRect(bx,by,bw,bh);ctx.fillStyle='#f2f4ef';ctx.fillText(String(v),bx,Math.max(axis.t+10,by-3))}ctx.fillStyle='#98a091';ctx.textAlign='center';ctx.fillText(labels[i],x,h-12);ctx.textAlign='left'}}
function pressureChart(series,c){const canvas=document.getElementById('pressureChart');if(!canvas)return;const {ctx,w,h}=setupCanvas(canvas);const axis=drawAxes(ctx,w,h,100,'pressure share %');const rows=[...series].reverse().slice(-40);ctx.strokeStyle='rgba(242,210,27,.75)';const thresholdY=axis.t+axis.ph*(1-c.pressureShareMinimum/100);ctx.beginPath();ctx.moveTo(axis.l,thresholdY);ctx.lineTo(w-axis.r,thresholdY);ctx.stroke();ctx.fillStyle='#f2d21b';ctx.fillText(`threshold ${c.pressureShareMinimum}%`,axis.l+4,thresholdY-4);if(rows.length<2)return;ctx.strokeStyle='#83df89';ctx.lineWidth=2;ctx.beginPath();rows.forEach((x,i)=>{const px=axis.l+axis.pw*(i/(rows.length-1));const py=axis.t+axis.ph*(1-Math.max(0,Math.min(100,finite(x?.pressure?.share)||0))/100);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)});ctx.stroke()}
function rateChart(series){const canvas=document.getElementById('rateChart');if(!canvas)return;const {ctx,w,h}=setupCanvas(canvas);const rows=[...series].reverse().slice(-40);const vals=rows.flatMap(x=>[Math.max(0,finite(x?.rates?.dangerousPerMinTarget)||0),Math.max(0,finite(x?.rates?.dangerousPerMinOpponent)||0)]);const max=Math.max(1,...vals);const axis=drawAxes(ctx,w,h,Math.ceil(max*10)/10,'dangerous attacks / min');if(rows.length<2)return;for(const [key,stroke] of [['dangerousPerMinTarget','#83df89'],['dangerousPerMinOpponent','#f2d21b']]){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.beginPath();rows.forEach((x,i)=>{const v=Math.max(0,finite(x?.rates?.[key])||0);const px=axis.l+axis.pw*(i/(rows.length-1));const py=axis.t+axis.ph*(1-v/(Math.ceil(max*10)/10));if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)});ctx.stroke()}}
function renderTelemetry(rows,c){refreshSelect(rows);const key=selectedKey();const series=rows.filter(x=>`${x.matchId}|${x.side}`===key);const x=series[0];const host=document.getElementById('telemetryDetail');if(!host)return;if(!x){host.innerHTML='<div class="note">Open Live once to collect Condition 2 telemetry. C1 remains untouched.</div>';barChart(null);pressureChart([],c);rateChart([]);return}host.innerHTML=`<div class="c2-kpi"><span>TARGET</span><b>${esc(x.side)} · ${esc(x.targetTeam)}</b></div><div class="c2-kpi"><span>WINDOW</span><b>${esc(x.window?.from)}′–${esc(x.window?.to)}′</b></div><div class="c2-kpi"><span>PRESSURE SHARE</span><b>${metric(x.pressure?.share,1)}%</b></div><div class="c2-kpi"><span>DA RATE</span><b>${metric(x.rates?.dangerousPerMinTarget,2)} / min</b></div><div class="c2-kpi"><span>ACCELERATION</span><b>${metric(x.acceleration?.dangerousPerMin,2)} Δ/min</b></div><div class="c2-kpi"><span>FIELD GATE</span><b class="${x.gates?.field?'oktxt':'waittxt'}">${x.gates?.field?'READY':'WATCH'}</b></div><div class="c2-kpi"><span>NORMALIZED</span><b>CALIBRATION PENDING</b></div><div class="c2-kpi"><span>PRICE GATE</span><b class="waittxt">BLOCKED / OBSERVE</b></div>`;barChart(x);pressureChart(series,c);rateChart(series)}
function render(){const c=load();const rows=telemetry();renderTelemetry(rows,c)}
function start(){if(document.body?.dataset?.page!=='condition2')return;applyForm(load());document.getElementById('c2Form')?.addEventListener('submit',e=>{e.preventDefault();save()});document.getElementById('defaultsButton')?.addEventListener('click',reset);document.getElementById('telemetrySelect')?.addEventListener('change',render);document.getElementById('refreshTelemetry')?.addEventListener('click',render);render();setInterval(render,5000);window.addEventListener('resize',()=>requestAnimationFrame(render))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();