const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let runtime=null,liveRows=[],records=[],activeSignals=[],selectedSignalId=null;

function n(v){const x=Number(v);return Number.isFinite(x)?x:null;}
function fmtOdds(v){const x=n(v);return x===null?'—':x.toFixed(2);}
function fmtLine(v){const x=n(v);return x===null?'—':`${x>0?'+':''}${Number.isInteger(x)?x.toFixed(1):String(x)}`;}
function fmtElapsed(seconds){const x=n(seconds);if(x===null||x<0)return null;const whole=Math.round(x),m=Math.floor(whole/60),s=whole%60;return `${m}:${String(s).padStart(2,'0')}`;}
function liveClock(row){const status=String(row?.status||'LIVE').toUpperCase();if(status==='FT'||status.includes('FINISH'))return'FT';if(status==='HT'||status.includes('HALF'))return'HT';if(row?.goalooClock?.verified===true){const t=fmtElapsed(row.goalooElapsedSeconds);if(t)return t;}const m=n(row?.minute);return m===null?'LIVE':`${Math.max(0,Math.round(m))}'`;}
function selectedLine(record){const explicit=n(record?.selectedLine);if(explicit!==null)return explicit;return n(record?.line);}
function pickText(record){const market=String(record?.market||'').toUpperCase(),team=record?.selectedTeam||record?.selectedSide||'SELECTED';if(market==='AH')return `${team} ${fmtLine(selectedLine(record))} @ ${fmtOdds(record?.odds)}`;if(market==='OU')return `${String(record?.ouDirection||'OVER').toUpperCase()} ${fmtLine(record?.line)} @ ${fmtOdds(record?.odds)}`;return `${team} · WIN @ ${fmtOdds(record?.odds)}`;}
function currentMarket(record,row){if(!row)return'—';const market=String(record?.market||'').toUpperCase(),side=String(record?.selectedSide||'HOME').toUpperCase(),away=side==='AWAY';if(market==='AH'){const raw=n(row.odds?.asianHandicap?.line),line=raw===null?null:(away?-raw:raw),odds=row.odds?.asianHandicap?.[away?'away':'home'];return `${record.selectedTeam||side} ${fmtLine(line)} @ ${fmtOdds(odds)}`;}if(market==='OU'){const ou=row.odds?.overUnder||{},dir=String(record?.ouDirection||'OVER').toUpperCase();return `${dir} ${fmtLine(ou.line)} @ ${fmtOdds(ou[dir==='UNDER'?'under':'over'])}`;}const one=row.odds?.oneXtwo||{};return `${record.selectedTeam||side} · WIN @ ${fmtOdds(one[away?'away':'home'])}`;}
function selectedScore(record,row){if(!row)return'—';const away=String(record?.selectedSide||'HOME').toUpperCase()==='AWAY';const s=away?row.score?.away:row.score?.home,o=away?row.score?.home:row.score?.away;return `${s??0}–${o??0}`;}
function entryScore(record){const away=String(record?.selectedSide||'HOME').toUpperCase()==='AWAY';const s=away?record?.entryScore?.away:record?.entryScore?.home,o=away?record?.entryScore?.home:record?.entryScore?.away;return `${s??'—'}–${o??'—'}`;}
function reasonChips(record){const ev=record?.evidence||{},out=[];if(n(record?.momentum)!==null)out.push(`Momentum <strong>${Math.round(n(record.momentum))}%</strong>`);if(n(ev.dangerous)!==null)out.push(`Dangerous Attack <strong>+${n(ev.dangerous)}</strong>`);if(n(ev.shots)!==null)out.push(`Shots <strong>+${n(ev.shots)}</strong>`);if(n(ev.sot)!==null)out.push(`SOT <strong>+${n(ev.sot)}</strong>`);if(n(ev.corners)!==null)out.push(`Corners <strong>+${n(ev.corners)}</strong>`);return out;}
function byId(id){return liveRows.find(x=>String(x.sourceMatchId)===String(id));}
function recordById(id){return records.find(x=>String(x.id)===String(id));}
function isNew(record){const t=Date.parse(record?.selectedAt||'');return Number.isFinite(t)&&Date.now()-t<45000;}

function renderScorebar(){const bar=$('#car32Scorebar'),count=$('#car32SignalCount');if(!bar||!count)return;count.textContent=`${activeSignals.length} ACTIVE`;if(!activeSignals.length){bar.innerHTML='<div class="car32-empty">Waiting for confirmed live signals…</div>';return;}bar.innerHTML=activeSignals.map(({record,row})=>`<button class="car32-scorecard ${String(record.id)===String(selectedSignalId)?'active':''} ${isNew(record)?'is-new':''}" data-signal-id="${esc(record.id)}"><div class="car32-score-top"><small>⚡ SIGNAL ${esc(record.entryMinute??'—')}'</small><b>LIVE ${esc(liveClock(row))}</b></div><strong class="car32-pick">${esc(pickText(record))}</strong><div class="car32-score-bottom"><span>ENTRY ${esc(entryScore(record))}</span><span class="car32-live-now">NOW ${esc(selectedScore(record,row))}</span></div></button>`).join('');bar.querySelectorAll('[data-signal-id]').forEach(btn=>btn.addEventListener('click',()=>focusSignal(btn.dataset.signalId,true)));}

function clickExistingCandidate(record,row){const cards=[...document.querySelectorAll('.candidate')];const names=[String(row?.home||record?.home||''),String(row?.away||record?.away||'')].filter(Boolean);const hit=cards.find(card=>names.every(name=>card.textContent.includes(name)))||cards.find(card=>card.textContent.includes(String(record?.selectedTeam||'')));if(hit&&!hit.classList.contains('active'))hit.click();}

function renderSummary(record,row){const box=$('#car32SignalSummary');if(!box)return;if(!record||!row){box.className='car32-signal-summary waiting';box.innerHTML='<div class="car32-summary-status"><span class="car32-live-dot"></span><b>MONITORING</b><small>Click an active signal above to follow it live.</small></div>';return;}const current=currentMarket(record,row),locked=pickText(record),moved=current!==locked;box.className='car32-signal-summary confirmed';box.innerHTML=`<div class="car32-summary-status"><span class="car32-live-dot"></span><b>CONFIRMED SIGNAL</b><small>Locked at detection · live match continues below</small></div><div class="car32-summary-main"><div class="car32-summary-cell primary"><small>DETECTED SELECTION</small><b>${esc(locked)}</b></div><div class="car32-summary-cell signal"><small>SIGNAL / ENTRY</small><b>${esc(record.entryMinute??'—')}' · ${esc(entryScore(record))}</b></div><div class="car32-summary-cell live"><small>LIVE NOW</small><b>${esc(liveClock(row))} · ${esc(selectedScore(record,row))}</b></div><div class="car32-summary-cell"><small>CURRENT MARKET</small><b class="${moved?'car32-market-moved':''}">${esc(current)}</b></div></div><div class="car32-summary-reason">${reasonChips(record).map(x=>`<span class="car32-reason-chip">${x}</span>`).join('')}</div>`;

  const signal=$('#signalMinute'),clock=$('#liveClock');if(signal)signal.textContent=n(record.entryMinute)===null?'—':`${record.entryMinute}'`;if(clock)clock.textContent=liveClock(row);
  const evidence=$('#evidenceGrid');if(evidence){const ev=record.evidence||{};evidence.innerHTML=[['Dangerous Attacks',ev.dangerous],['Shots',ev.shots],['Shots on Target',ev.sot],['Corners',ev.corners]].map(([k,v])=>`<div class="evidence-card"><small>${esc(k)} AT SIGNAL</small><b>${n(v)===null?'—':`${n(v)>=0?'+':''}${n(v)}`}</b></div>`).join('');}
}

function focusSignal(id,userInitiated=false){const record=recordById(id),row=byId(id);if(!record||!row)return;selectedSignalId=String(id);if(userInitiated)clickExistingCandidate(record,row);renderScorebar();renderSummary(record,row);}

async function refresh(){runtime=runtime||await fetch('./runtime.json',{cache:'no-store'}).then(r=>r.json());const [live,history]=await Promise.all([fetch(`${runtime.workerUrl}/live?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()).catch(()=>({matches:[]})),fetch(`${runtime.workerUrl}/history?page=1&limit=100&t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()).catch(()=>({records:[]}))]);liveRows=live.matches||[];records=history.records||[];const liveIds=new Set(liveRows.map(r=>String(r.sourceMatchId)));activeSignals=records.filter(r=>liveIds.has(String(r.id))).map(record=>({record,row:byId(record.id)})).sort((a,b)=>Date.parse(b.record.selectedAt||0)-Date.parse(a.record.selectedAt||0));if(selectedSignalId&&!liveIds.has(String(selectedSignalId)))selectedSignalId=null;if(!selectedSignalId&&activeSignals.length)selectedSignalId=String(activeSignals[0].record.id);renderScorebar();if(selectedSignalId){const r=recordById(selectedSignalId),row=byId(selectedSignalId);renderSummary(r,row);}else renderSummary(null,null);}

setTimeout(()=>refresh().catch(()=>{}),500);setInterval(()=>refresh().catch(()=>{}),5000);document.addEventListener('click',e=>{if(e.target.closest('.candidate'))setTimeout(()=>{const active=e.target.closest('.candidate'),text=active?.textContent||'';const pair=activeSignals.find(({record,row})=>[row?.home,row?.away,record?.selectedTeam].filter(Boolean).some(name=>text.includes(String(name))));if(pair){selectedSignalId=String(pair.record.id);renderScorebar();renderSummary(pair.record,pair.row);}},80);});
