(()=>{
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const score=s=>s?`${s.home??0}–${s.away??0}`:'—';
  const line=v=>{const n=Number(v);return Number.isFinite(n)?`${n>=0?'+':''}${Number(n.toFixed(2))}`:'—';};
  const cls=v=>String(v||'').toLowerCase()==='win'?'win':String(v||'').toLowerCase()==='loss'?'loss':String(v||'').toLowerCase()==='draw'?'draw':'pending';
  async function getJson(url,timeout=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal}),d=await r.json().catch(()=>null);if(!r.ok||!d)throw new Error(`${r.status}`);return d;}finally{clearTimeout(timer);}}
  function metrics(s={}){const map={historyTotal:s.total||0,historyPending:s.pending||0,historyWin:s.win||0,historyLoss:s.loss||0,historyDraw:s.draw||0,historyAvg:Number(s.averageOdds||0).toFixed(2)};for(const[id,v]of Object.entries(map))if($(id))$(id).textContent=v;}
  function chart(records=[]){const el=$('historyChart');if(!el)return;const settled=[...records].filter(r=>r.resultGroup&&r.resultGroup!=='PENDING'&&r.resultGroup!=='VOID').reverse();let w=0,l=0,d=0;const points=settled.map(r=>{if(r.resultGroup==='WIN')w++;else if(r.resultGroup==='LOSS')l++;else d++;return{w,l,d};});if(!points.length){el.innerHTML='<div class="empty">No settled signals yet.</div>';return;}const max=Math.max(1,...points.flatMap(p=>[p.w,p.l,p.d]));el.innerHTML=points.map(p=>`<div class="history-point" title="W ${p.w} · L ${p.l} · D ${p.d}"><span class="bar win" style="height:${Math.max(4,p.w/max*100)}%"></span><span class="bar loss" style="height:${Math.max(4,p.l/max*100)}%"></span><span class="bar draw" style="height:${Math.max(4,p.d/max*100)}%"></span></div>`).join('');}
  function rows(records=[]){const body=$('historyBody');if(!body)return;body.innerHTML=records.length?records.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.selectedAt||'')}</td><td>${esc(`${r.home||''} vs ${r.away||''}`)}</td><td class="pick">${esc(r.selectedTeam||'')}</td><td>${r.entryMinute??'—'}′ / ${score(r.entryScore)}</td><td>AH ${line(r.selectedLine??r.line)} @ ${r.odds??'—'}</td><td>${r.momentum??'—'}%</td><td>${esc(r.kickoff||'—')}</td><td>${esc(r.settledAt||'—')}</td><td>${score(r.finalScore)}</td><td><span class="status ${cls(r.resultGroup)}">${esc(r.resultGroup||'PENDING')}</span></td><td>${r.settlementNetUnits??'—'}</td></tr>`).join(''):'<tr><td colspan="12" class="muted">No locked signals yet.</td></tr>';}
  async function load(page=1){try{const rt=await getJson('./runtime.json',4000),p=await getJson(`${rt.engineWorkerUrl}/history?page=${page}&limit=25`);metrics(p.summary);rows(p.records||[]);chart(p.records||[]);const ribbon=document.querySelector('.preview-ribbon');if(ribbon)ribbon.textContent='FULL ENGINE HISTORY · BET365_V4 settlement';if($('pageInfo'))$('pageInfo').textContent=`Page ${p.page} / ${p.pages} · 25 rows/page`;if($('prevPage')){$('prevPage').disabled=p.page<=1;$('prevPage').onclick=()=>load(p.page-1);}if($('nextPage')){$('nextPage').disabled=p.page>=p.pages;$('nextPage').onclick=()=>load(p.page+1);}}catch{metrics({});rows([]);chart([]);const ribbon=document.querySelector('.preview-ribbon');if(ribbon)ribbon.textContent='HISTORY OFFLINE · engine unavailable';}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>load()):load();
})();
