const DEMO_MATCHES=[
  {state:'SIGNAL',league:'Demo Premier League',home:'Riverside FC',away:'North City',score:'1–1',minute:72,pressure:67,ah:'+1.00',odds:'1.58',event:'Shot on target · Riverside FC',ball:'a',evidence:['Dangerous +6','Shots +3','SOT +2','Corners +1'],details:{attacks:'74–68',dangerous:'39–31',shots:'12–9',sot:'5–3',corners:'6–4',possession:'54–46'}},
  {state:'CLOSE',league:'Demo Continental Cup',home:'Harbor United',away:'Metro Athletic',score:'0–1',minute:61,pressure:57,ah:'+1.25',odds:'1.46',event:'Corner · Harbor United',ball:'b',evidence:['Dangerous +3','Shots +1','Corners +2'],details:{attacks:'61–57',dangerous:'28–24',shots:'8–6',sot:'2–2',corners:'5–3',possession:'52–48'}},
  {state:'WATCHING',league:'Demo National League',home:'Westfield',away:'Union Stars',score:'0–0',minute:54,pressure:49,ah:'+0.75',odds:'1.51',event:'Attack building · Westfield',ball:'a',evidence:['Dangerous +1'],details:{attacks:'45–47',dangerous:'19–20',shots:'5–6',sot:'1–2',corners:'2–3',possession:'51–49'}}
];
const DEMO_SIGNALS=[
  {time:'20 Aug · 07:42',match:'Riverside FC vs North City',team:'Riverside FC',ah:'+1.00',odds:'1.58',entry:'1–1 · 72′',status:'PENDING',source:'1xBet'},
  {time:'19 Aug · 21:18',match:'Old Town vs Portside',team:'Old Town',ah:'+1.25',odds:'1.62',entry:'0–1 · 68′',status:'WIN',source:'1xBet'},
  {time:'19 Aug · 19:54',match:'Green County vs Academy XI',team:'Green County',ah:'+1.00',odds:'1.49',entry:'0–1 · 64′',status:'PUSH',source:'1xBet'}
];
const DEMO_RESULTS=[
  {detected:'20 Aug 07:42',match:'Riverside FC vs North City',pick:'Riverside FC',ah:'+1.00',odds:'1.58',entry:'1–1',final:'—',result:'PENDING',source:'1xBet'},
  {detected:'19 Aug 21:18',match:'Old Town vs Portside',pick:'Old Town',ah:'+1.25',odds:'1.62',entry:'0–1',final:'1–1',result:'WIN',source:'1xBet'},
  {detected:'19 Aug 19:54',match:'Green County vs Academy XI',pick:'Green County',ah:'+1.00',odds:'1.49',entry:'0–1',final:'0–1',result:'PUSH',source:'1xBet'},
  {detected:'19 Aug 18:21',match:'Lake City vs Redbridge',pick:'Lake City',ah:'+1.00',odds:'1.55',entry:'0–1',final:'1–2',result:'PUSH',source:'1xBet'},
  {detected:'18 Aug 22:10',match:'Central FC vs East Gate',pick:'Central FC',ah:'+1.25',odds:'1.61',entry:'0–2',final:'1–2',result:'WIN',source:'1xBet'},
  {detected:'18 Aug 20:04',match:'River Plate Demo vs South Club',pick:'South Club',ah:'+1.00',odds:'1.44',entry:'1–2',final:'3–2',result:'LOSS',source:'1xBet'}
];

const q=(s)=>document.querySelector(s);const qa=(s)=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function clsResult(v){v=String(v).toLowerCase();if(v==='win')return'win';if(v==='loss')return'loss';if(v==='push'||v==='draw')return'draw';return'pending'}

function renderLive(){
  const grid=q('#candidateCards'); if(!grid)return;
  grid.innerHTML=DEMO_MATCHES.map((m,i)=>`<article class="match-card ${m.state.toLowerCase()}"><div class="match-top"><span class="match-league">${esc(m.league)}</span><span class="state-badge ${m.state.toLowerCase()}">${m.state[0]+m.state.slice(1).toLowerCase()}</span></div><div class="score-line"><div class="team">${esc(m.home)}</div><div class="score-box"><strong>${m.score}</strong><span class="minute">${m.minute}′</span></div><div class="team away">${esc(m.away)}</div></div><div class="match-pitch"><span class="pitch-ball ball-${m.ball}"></span></div><div class="match-sub"><div class="pressure"><small>Pressure</small><strong>${m.pressure}%</strong></div><div class="market-box"><small>Real AH market</small><div class="market-pick">${m.ah} <span class="odds-value">@ ${m.odds}</span></div></div></div><div class="evidence-row">${m.evidence.map(x=>`<span class="evidence-chip hot">${esc(x)}</span>`).join('')}</div><div class="last-event"><b>Latest:</b> ${esc(m.event)}</div><details class="match-details"><summary>View live evidence</summary><div class="detail-grid">${Object.entries(m.details).map(([k,v])=>`<div class="detail-stat"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('')}</div></details></article>`).join('');
  q('#signals').innerHTML=DEMO_SIGNALS.map(s=>`<article class="signal-card"><div><small>${s.time}</small><strong>${esc(s.match)}</strong><div class="signal-meta">Entry ${s.entry}</div></div><div><small>Selected</small><strong class="signal-team">${esc(s.team)}</strong></div><div><small>AH / odds</small><strong class="signal-market">${s.ah} <span class="signal-price">@ ${s.odds}</span></strong></div><div><small>Result</small><span class="status ${clsResult(s.status)}">${s.status}</span></div></article>`).join('');
  q('#liveCount').textContent='12';q('#watching').textContent='3';q('#nearSignal').textContent='1';q('#lockedToday').textContent='1';q('#freshness').textContent='Mock snapshot · UI only';
}
function renderStats(){
  if(!q('#statsRows'))return;const settled=DEMO_RESULTS.filter(x=>x.result!=='PENDING');const wins=settled.filter(x=>x.result==='WIN').length;const losses=settled.filter(x=>x.result==='LOSS').length;const pushes=settled.filter(x=>x.result==='PUSH').length;const wr=(wins+losses)?wins/(wins+losses)*100:0;const avg=DEMO_RESULTS.reduce((a,x)=>a+Number(x.odds),0)/DEMO_RESULTS.length;
  q('#winRate').textContent=`${wr.toFixed(1)}%`;q('#win').textContent=wins;q('#loss').textContent=losses;q('#draw').textContent=pushes;q('#avgOdds').textContent=avg.toFixed(2);q('#total').textContent=DEMO_RESULTS.length;q('#settled').textContent=settled.length;q('#netUnits').textContent='+1.04';
  q('#statsRows').innerHTML=DEMO_RESULTS.map(r=>`<tr><td>${r.detected}</td><td>${esc(r.match)}</td><td class="pick">${esc(r.pick)}</td><td>${r.ah}</td><td><b>${r.odds}</b></td><td>${r.entry}</td><td>${r.final}</td><td><span class="status ${clsResult(r.result)}">${r.result}</span></td><td>${r.source}</td></tr>`).join('');
  q('#statsCards').innerHTML=DEMO_RESULTS.map(r=>`<article class="stats-card"><div class="stats-card-head"><small>${r.detected}</small><span class="status ${clsResult(r.result)}">${r.result}</span></div><h3>${esc(r.match)}</h3><div class="pick-line">${esc(r.pick)} ${r.ah} @ ${r.odds}</div><div class="stats-card-meta"><div><small>Entry</small><strong>${r.entry}</strong></div><div><small>Final</small><strong>${r.final}</strong></div><div><small>Source</small><strong>${r.source}</strong></div></div></article>`).join('');
  const p=q('#statsPager');if(p)p.innerHTML='<button class="active">1</button>';
}
const CONFIG={engineEnabled:true,side:'HOME',confirmationRounds:1,minuteMin:54,minuteMax:89,realMarketMaxAgeSeconds:120,oddsMin:1.4,oddsMax:'',ahMin:1,ahMax:'',momentumMin:54,weightAttacks:.16,weightDangerousAttacks:.52,weightShots:2,weightShotsOnTarget:4,weightCorners:1.25,weightPossession:.07,attackEvidenceEnabled:true,attackEvidenceRequirement:'1',attackEvidenceDangerousAttacksEnabled:true,attackEvidenceDangerousAttacksMin:1,attackEvidenceShotsEnabled:true,attackEvidenceShotsMin:1,attackEvidenceShotsOnTargetEnabled:true,attackEvidenceShotsOnTargetMin:1,attackEvidenceCornersEnabled:true,attackEvidenceCornersMin:1,goalGapLimited:false,maxGoalGap:1,redCardPolicy:'ALLOW',requireCoreStats:true,matchConfidenceMin:85,sourceFreshnessMaxSeconds:90,signalLimitEnabled:false,maxSignalsPerDay:10};
function applyConfig(c){Object.entries(c).forEach(([id,v])=>{const el=document.getElementById(id);if(!el)return;if(el.type==='checkbox')el.checked=Boolean(v);else el.value=v??''});const t=q('#configUpdated');if(t)t.textContent='Local mock';}
function collectConfig(){const out={};Object.keys(CONFIG).forEach(id=>{const el=document.getElementById(id);if(!el)return;if(el.type==='checkbox')out[id]=el.checked;else if(el.type==='number')out[id]=el.value===''?'':Number(el.value);else out[id]=el.value});return out}
function initSettings(){const f=q('#settingsForm');if(!f)return;let saved;try{saved=JSON.parse(localStorage.getItem('car341-mock-config')||'null')}catch{}applyConfig({...CONFIG,...saved});f.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('car341-mock-config',JSON.stringify(collectConfig()));const s=q('#saveState');s.textContent='Saved locally · UI shell only';setTimeout(()=>s.textContent='',2400)});q('#copy31')?.addEventListener('click',()=>{localStorage.removeItem('car341-mock-config');applyConfig(CONFIG);const s=q('#saveState');s.textContent='Reloaded CAR 3.4.1 mock defaults';setTimeout(()=>s.textContent='',2400)});}
function renderHistory(){const body=q('#historyBody');if(!body)return;body.innerHTML=DEMO_RESULTS.map((r,i)=>`<tr><td>${i+1}</td><td>${r.detected}</td><td>${esc(r.match)}</td><td class="pick">${esc(r.pick)}</td><td>${r.entry}</td><td>AH ${r.ah} @ ${r.odds}</td><td>${i%2?57:64}%</td><td>Demo</td><td>${r.result==='PENDING'?'—':'Demo settled'}</td><td>${r.final}</td><td><span class="status ${clsResult(r.result)}">${r.result}</span></td><td>${r.result==='WIN'?'+0.62':r.result==='LOSS'?'-1.00':'0.00'}</td></tr>`).join('')}
function init(){renderLive();renderStats();initSettings();renderHistory();qa('[data-mock-clock]').forEach(el=>{const tick=()=>el.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});tick();setInterval(tick,1000)});}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
