const DEMO_MATCHES=[
  {state:'SIGNAL',league:'Demo Premier League',home:'Riverside FC',away:'North City',score:'1–1',minute:72,pressure:67,ah:'+1.00',odds:'1.58',evidence:['Dangerous +6','Shots +3','SOT +2','Corners +1'],details:{attacks:'74–68',dangerous:'39–31',shots:'12–9',sot:'5–3',corners:'6–4',possession:'54–46'}},
  {state:'CLOSE',league:'Demo Continental Cup',home:'Harbor United',away:'Metro Athletic',score:'0–1',minute:61,pressure:57,ah:'+1.25',odds:'1.46',evidence:['Dangerous +3','Shots +1','Corners +2'],details:{attacks:'61–57',dangerous:'28–24',shots:'8–6',sot:'2–2',corners:'5–3',possession:'52–48'}}
];
const DEMO_RESULTS=[
  {detected:'20 Aug 07:42',match:'Riverside FC vs North City',pick:'Riverside FC',ah:'+1.00',odds:'1.58',entry:'1–1',final:'—',result:'PENDING',source:'1xBet'},
  {detected:'19 Aug 21:18',match:'Old Town vs Portside',pick:'Old Town',ah:'+1.25',odds:'1.62',entry:'0–1',final:'1–1',result:'WIN',source:'1xBet'},
  {detected:'18 Aug 20:04',match:'River Plate Demo vs South Club',pick:'South Club',ah:'+1.00',odds:'1.44',entry:'1–2',final:'3–2',result:'LOSS',source:'1xBet'}
];
const DEFAULT_CONFIG={engineEnabled:true,side:'HOME',confirmationRounds:1,minuteMin:54,minuteMax:89,realMarketMaxAgeSeconds:120,oddsMin:1.4,oddsMax:'',ahMin:1,ahMax:'',momentumMin:54,weightAttacks:.16,weightDangerousAttacks:.52,weightShots:2,weightShotsOnTarget:4,weightCorners:1.25,weightPossession:.07,attackEvidenceEnabled:true,attackEvidenceRequirement:'1',attackEvidenceDangerousAttacksEnabled:true,attackEvidenceDangerousAttacksMin:1,attackEvidenceShotsEnabled:true,attackEvidenceShotsMin:1,attackEvidenceShotsOnTargetEnabled:true,attackEvidenceShotsOnTargetMin:1,attackEvidenceCornersEnabled:true,attackEvidenceCornersMin:1,goalGapLimited:false,maxGoalGap:1,redCardPolicy:'ALLOW',requireCoreStats:true,matchConfidenceMin:85,sourceFreshnessMaxSeconds:90,signalLimitEnabled:false,maxSignalsPerDay:10};
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;};
function clsResult(v){v=String(v||'').toLowerCase();if(v==='win')return'win';if(v==='loss')return'loss';if(v==='draw'||v==='push')return'draw';return'pending';}
function fmtLine(v){const x=n(v);return x===null?'—':`${x>=0?'+':''}${Number(x.toFixed(2))}`;}
function scoreText(score){return`${score?.home??0}–${score?.away??0}`;}
function pairText(pair){return`${pair?.home??'—'}–${pair?.away??'—'}`;}
function setRibbon(text){const el=q('.preview-ribbon');if(el)el.textContent=text;}
function setSystem(text,mode='running'){const el=q('#systemText');if(el)el.textContent=text;const box=el?.closest('.live-system');if(box){box.classList.remove('offline','paused');if(mode==='offline')box.classList.add('offline');if(mode==='paused')box.classList.add('paused');}}
async function fetchJson(url,options={},timeout=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',...options,signal:c.signal});const data=await r.json().catch(()=>null);if(!r.ok||!data)throw new Error(`${r.status}:${data?.error||'INVALID_RESPONSE'}`);return data;}finally{clearTimeout(timer);}}
async function runtime(){try{return await fetchJson('./runtime.json',{},4000);}catch{return{version:'3.4.1',engineWorkerUrl:'',sourceWorkerUrl:'',refreshSeconds:15};}}

function liveCard(m){const e=m.engine||{},state=e.decision==='SIGNAL'?'SIGNAL':e.decision==='CLOSE'?'CLOSE':'WATCHING',details={attacks:pairText(m.stats?.attacks),dangerous:pairText(m.stats?.dangerousAttacks),shots:pairText(m.stats?.shots),sot:pairText(m.stats?.shotsOnTarget),corners:pairText(m.stats?.corners),possession:pairText(m.stats?.possession)},ev=e.evidence||{},chips=[['Dangerous',ev.dangerous],['Shots',ev.shots],['SOT',ev.sot],['Corners',ev.corners]].filter(x=>n(x[1])!==null).map(([k,v])=>`${k} ${v>=0?'+':''}${v}`),market=e.odds?`${fmtLine(e.selectedLine)} @ ${e.odds}`:'Waiting 1xBet';return`<article class="match-card ${state.toLowerCase()}"><div class="match-top"><span class="match-league">${esc(m.match?.league)}</span><span class="state-badge ${state.toLowerCase()}">${state[0]+state.slice(1).toLowerCase()}</span></div><div class="score-line"><div class="team">${esc(m.match?.home)}</div><div class="score-box"><strong>${scoreText(m.score)}</strong><span class="minute">${m.state?.minute??'—'}′</span></div><div class="team away">${esc(m.match?.away)}</div></div><div class="match-pitch"><span class="pitch-ball ball-a"></span></div><div class="match-sub"><div class="pressure"><small>Pressure</small><strong>${e.momentum??'—'}%</strong></div><div class="market-box"><small>${m.realMarket?.status==='MATCH'?'Real AH market':'Market status'}</small><div class="market-pick">${market}</div></div></div><div class="evidence-row">${chips.map(x=>`<span class="evidence-chip hot">${esc(x)}</span>`).join('')}</div><div class="last-event"><b>Source:</b> Goaloo stats · ${m.realMarket?.status==='MATCH'?'1xBet price locked for evaluation':esc(m.realMarket?.status||'waiting')}</div><details class="match-details"><summary>View live evidence</summary><div class="detail-grid">${Object.entries(details).map(([k,v])=>`<div class="detail-stat"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('')}</div></details></article>`;}
function sourceCard(m){const details={attacks:pairText(m.stats?.attacks),dangerous:pairText(m.stats?.dangerousAttacks),shots:pairText(m.stats?.shots),sot:pairText(m.stats?.shotsOnTarget),corners:pairText(m.stats?.corners),possession:pairText(m.stats?.possession)};return`<article class="match-card watching"><div class="match-top"><span class="match-league">${esc(m.match?.league)}</span><span class="state-badge watching">Source</span></div><div class="score-line"><div class="team">${esc(m.match?.home)}</div><div class="score-box"><strong>${scoreText(m.score)}</strong><span class="minute">${m.state?.minute??'—'}′</span></div><div class="team away">${esc(m.match?.away)}</div></div><div class="match-pitch"><span class="pitch-ball ball-b"></span></div><div class="match-sub"><div class="pressure"><small>Data quality</small><strong>${m.quality?.coreStatsComplete?'100':'70'}%</strong></div><div class="market-box"><small>Real AH market</small><div class="market-pick">Engine connecting</div></div></div><details class="match-details"><summary>View live evidence</summary><div class="detail-grid">${Object.entries(details).map(([k,v])=>`<div class="detail-stat"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('')}</div></details></article>`;}
function signalCard(s){return`<article class="signal-card"><div><small>${esc(s.selectedAt||'')}</small><strong>${esc(`${s.home} vs ${s.away}`)}</strong><div class="signal-meta">Entry ${scoreText(s.entryScore)} · ${s.entryMinute??'—'}′</div></div><div><small>Selected</small><strong class="signal-team">${esc(s.selectedTeam)}</strong></div><div><small>AH / odds</small><strong class="signal-market">${fmtLine(s.selectedLine)} <span class="signal-price">@ ${s.odds??'—'}</span></strong></div><div><small>Result</small><span class="status ${clsResult(s.resultGroup||s.result)}">${esc(s.resultGroup||s.result||'PENDING')}</span></div></article>`;}
function renderFullLive(payload){const matches=payload.matches||[],signals=payload.signalsToday||[];q('#candidateCards').innerHTML=matches.length?matches.map(liveCard).join(''):'<div class="empty">No live matches from Goaloo right now.</div>';q('#signals').innerHTML=signals.length?signals.map(signalCard).join(''):'<div class="empty">No locked signals today.</div>';q('#liveCount').textContent=matches.length;q('#watching').textContent=matches.filter(m=>!['SIGNAL','CLOSE'].includes(m.engine?.decision)).length;q('#nearSignal').textContent=matches.filter(m=>m.engine?.decision==='CLOSE').length;q('#lockedToday').textContent=signals.length;q('#freshness').textContent=`Engine · ${payload.generatedAt?new Date(payload.generatedAt).toLocaleTimeString(): '—'}`;setRibbon(payload.pricingError?`FULL ENGINE · pricing warning: ${payload.pricingError}`:'FULL ENGINE · Goaloo + 1xBet · live');setSystem('CAR 3.4.1 · RUNNING');}
function renderSourceLive(payload){const matches=payload.matches||[];q('#candidateCards').innerHTML=matches.length?matches.map(sourceCard).join(''):'<div class="empty">No live matches from Goaloo right now.</div>';q('#signals').innerHTML='<div class="empty">Source layer online. Waiting for full engine.</div>';q('#liveCount').textContent=matches.length;q('#watching').textContent=matches.length;q('#nearSignal').textContent='0';q('#lockedToday').textContent='0';q('#freshness').textContent=`Source · ${payload.generatedAt?new Date(payload.generatedAt).toLocaleTimeString():'—'}`;setRibbon('SOURCE ONLY · Goaloo live · detector/pricing not yet available');setSystem('CAR 3.4.1 · SOURCE ONLY','paused');}
function renderMockLive(){q('#candidateCards').innerHTML=DEMO_MATCHES.map(m=>`<article class="match-card ${m.state.toLowerCase()}"><div class="match-top"><span class="match-league">${m.league}</span><span class="state-badge ${m.state.toLowerCase()}">${m.state}</span></div><div class="score-line"><div class="team">${m.home}</div><div class="score-box"><strong>${m.score}</strong><span class="minute">${m.minute}′</span></div><div class="team away">${m.away}</div></div><div class="match-pitch"></div><div class="match-sub"><div class="pressure"><small>Pressure</small><strong>${m.pressure}%</strong></div><div class="market-box"><small>Demo AH</small><div class="market-pick">${m.ah} @ ${m.odds}</div></div></div></article>`).join('');q('#signals').innerHTML='<div class="empty">Mock fallback only · no real signal shown.</div>';q('#liveCount').textContent='—';q('#watching').textContent='—';q('#nearSignal').textContent='—';q('#lockedToday').textContent='—';q('#freshness').textContent='Offline fallback';setRibbon('MOCK FALLBACK · engine/source unavailable · not live data');setSystem('CAR 3.4.1 · OFFLINE','offline');}
async function refreshLive(rt){if(!q('#candidateCards'))return;try{if(rt.engineWorkerUrl){const data=await fetchJson(`${rt.engineWorkerUrl}/live`);if(data.generatedAt){renderFullLive(data);return;}}}catch{}try{if(rt.sourceWorkerUrl){const data=await fetchJson(`${rt.sourceWorkerUrl}/live`);renderSourceLive(data);return;}}catch{}renderMockLive();}

function resultRow(r){return{detected:r.selectedAt||'',match:`${r.home||''} vs ${r.away||''}`,pick:r.selectedTeam||'',ah:fmtLine(r.selectedLine??r.line),odds:r.odds??'—',entry:scoreText(r.entryScore),final:r.finalScore?scoreText(r.finalScore):'—',result:r.resultGroup||r.result||'PENDING',source:r.bookmaker||'1xBet'};}
function renderStatsPayload(payload){const s=payload.summary||{},rows=(payload.records||[]).map(resultRow);q('#winRate').textContent=`${Number(s.winRate||0).toFixed(1)}%`;q('#win').textContent=s.win||0;q('#loss').textContent=s.loss||0;q('#draw').textContent=s.draw||0;q('#avgOdds').textContent=Number(s.averageOdds||0).toFixed(2);q('#total').textContent=s.total||0;q('#settled').textContent=s.settled||0;q('#netUnits').textContent=Number(s.netUnits||0).toFixed(2);q('#statsRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.detected)}</td><td>${esc(r.match)}</td><td class="pick">${esc(r.pick)}</td><td>${r.ah}</td><td><b>${r.odds}</b></td><td>${r.entry}</td><td>${r.final}</td><td><span class="status ${clsResult(r.result)}">${r.result}</span></td><td>${r.source}</td></tr>`).join(''):'<tr><td colspan="9" class="muted">No locked signals yet.</td></tr>';q('#statsCards').innerHTML=rows.map(r=>`<article class="stats-card"><div class="stats-card-head"><small>${esc(r.detected)}</small><span class="status ${clsResult(r.result)}">${r.result}</span></div><h3>${esc(r.match)}</h3><div class="pick-line">${esc(r.pick)} ${r.ah} @ ${r.odds}</div><div class="stats-card-meta"><div><small>Entry</small><strong>${r.entry}</strong></div><div><small>Final</small><strong>${r.final}</strong></div><div><small>Source</small><strong>${r.source}</strong></div></div></article>`).join('');if(q('#statsPager'))q('#statsPager').innerHTML=`<button class="active">${payload.page||1}</button>`;setRibbon('FULL ENGINE HISTORY · BET365_V4 settlement');}
function renderMockStats(){const rows=DEMO_RESULTS;const wins=rows.filter(x=>x.result==='WIN').length,losses=rows.filter(x=>x.result==='LOSS').length;q('#winRate').textContent=`${(wins+losses?wins/(wins+losses)*100:0).toFixed(1)}%`;q('#win').textContent=wins;q('#loss').textContent=losses;q('#draw').textContent=0;q('#avgOdds').textContent='1.55';q('#total').textContent=rows.length;q('#settled').textContent=wins+losses;q('#netUnits').textContent='-0.42';q('#statsRows').innerHTML=rows.map(r=>`<tr><td>${r.detected}</td><td>${r.match}</td><td>${r.pick}</td><td>${r.ah}</td><td>${r.odds}</td><td>${r.entry}</td><td>${r.final}</td><td><span class="status ${clsResult(r.result)}">${r.result}</span></td><td>${r.source}</td></tr>`).join('');setRibbon('MOCK FALLBACK · engine history unavailable');}
async function initStats(rt){if(!q('#statsRows'))return;try{const p=await fetchJson(`${rt.engineWorkerUrl}/history?limit=25`);renderStatsPayload(p);}catch{renderMockStats();}}

function flattenConfig(c){return{...c,weightAttacks:c.momentumWeights?.attacks??c.weightAttacks,weightDangerousAttacks:c.momentumWeights?.dangerousAttacks??c.weightDangerousAttacks,weightShots:c.momentumWeights?.shots??c.weightShots,weightShotsOnTarget:c.momentumWeights?.shotsOnTarget??c.weightShotsOnTarget,weightCorners:c.momentumWeights?.corners??c.weightCorners,weightPossession:c.momentumWeights?.possession??c.weightPossession};}
function applyConfig(c,label='—'){Object.entries(flattenConfig(c)).forEach(([id,v])=>{const el=document.getElementById(id);if(!el)return;if(el.type==='checkbox')el.checked=Boolean(v);else el.value=v??'';});if(q('#configUpdated'))q('#configUpdated').textContent=label;}
function collectConfig(){const out={};Object.keys(DEFAULT_CONFIG).forEach(id=>{const el=document.getElementById(id);if(!el)return;if(el.type==='checkbox')out[id]=el.checked;else if(el.type==='number')out[id]=el.value===''?null:Number(el.value);else out[id]=el.value;});out.momentumWeights={attacks:out.weightAttacks,dangerousAttacks:out.weightDangerousAttacks,shots:out.weightShots,shotsOnTarget:out.weightShotsOnTarget,corners:out.weightCorners,possession:out.weightPossession};return out;}
async function initSettings(rt){const form=q('#settingsForm');if(!form)return;let remote=false;try{const data=await fetchJson(`${rt.engineWorkerUrl}/config`);applyConfig(data.config,data.updatedAt?new Date(data.updatedAt).toLocaleString():'Engine defaults');remote=true;setRibbon('FULL ENGINE CONFIG · changes apply to next scan');}catch{let saved=null;try{saved=JSON.parse(localStorage.getItem('car341-mock-config')||'null');}catch{}applyConfig({...DEFAULT_CONFIG,...saved},'Local fallback');setRibbon('LOCAL FALLBACK · engine config unavailable');}
  form.addEventListener('submit',async e=>{e.preventDefault();const state=q('#saveState'),payload=collectConfig();if(remote){try{const data=await fetchJson(`${rt.engineWorkerUrl}/config`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});applyConfig(data.config,new Date(data.updatedAt).toLocaleString());state.textContent='Saved to CAR 3.4.1 engine';return;}catch{remote=false;}}
    localStorage.setItem('car341-mock-config',JSON.stringify(payload));state.textContent='Engine unavailable · saved locally only';});
  q('#copy31')?.addEventListener('click',async()=>{if(remote){try{const data=await fetchJson(`${rt.engineWorkerUrl}/config`);applyConfig(data.config,data.updatedAt?new Date(data.updatedAt).toLocaleString():'Engine defaults');q('#saveState').textContent='Reloaded current engine config';return;}catch{}}localStorage.removeItem('car341-mock-config');applyConfig(DEFAULT_CONFIG,'Local defaults');q('#saveState').textContent='Reloaded local defaults';});
}

async function initHistory(rt){const body=q('#historyBody');if(!body)return;try{const p=await fetchJson(`${rt.engineWorkerUrl}/history?limit=25`);const rows=p.records||[];body.innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.selectedAt)}</td><td>${esc(`${r.home} vs ${r.away}`)}</td><td class="pick">${esc(r.selectedTeam)}</td><td>${r.entryMinute??'—'}′ / ${scoreText(r.entryScore)}</td><td>AH ${fmtLine(r.selectedLine)} @ ${r.odds??'—'}</td><td>${r.momentum??'—'}%</td><td>${esc(r.kickoff||'—')}</td><td>${esc(r.settledAt||'—')}</td><td>${r.finalScore?scoreText(r.finalScore):'—'}</td><td><span class="status ${clsResult(r.resultGroup)}">${r.resultGroup||'PENDING'}</span></td><td>${r.settlementNetUnits??'—'}</td></tr>`).join(''):'<tr><td colspan="12" class="muted">No locked signals yet.</td></tr>';setRibbon('FULL ENGINE HISTORY · live records');}catch{body.innerHTML='<tr><td colspan="12" class="muted">Engine history unavailable.</td></tr>';setRibbon('HISTORY OFFLINE · engine unavailable');}}

async function init(){const rt=await runtime();await Promise.all([refreshLive(rt),initStats(rt),initSettings(rt),initHistory(rt)]);if(q('#candidateCards'))setInterval(()=>refreshLive(rt),Math.max(10,Number(rt.refreshSeconds)||15)*1000);qa('[data-mock-clock]').forEach(el=>{const tick=()=>el.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});tick();setInterval(tick,1000);});}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
