(()=>{
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const score=s=>s?`${s.home??0}–${s.away??0}`:'—';
  const line=v=>{const n=Number(v);return Number.isFinite(n)?`${n>=0?'+':''}${Number(n.toFixed(2))}`:'—';};
  const cls=v=>String(v||'').toLowerCase()==='win'?'win':String(v||'').toLowerCase()==='loss'?'loss':String(v||'').toLowerCase()==='draw'?'draw':'pending';
  async function getJson(url,timeout=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal}),d=await r.json().catch(()=>null);if(!r.ok||!d)throw new Error(`${r.status}`);return d;}finally{clearTimeout(timer);}}
  function summary(s={}){if($('winRate'))$('winRate').textContent=`${Number(s.winRate||0).toFixed(1)}%`;if($('win'))$('win').textContent=s.win||0;if($('loss'))$('loss').textContent=s.loss||0;if($('draw'))$('draw').textContent=s.draw||0;if($('avgOdds'))$('avgOdds').textContent=Number(s.averageOdds||0).toFixed(2);if($('total'))$('total').textContent=s.total||0;if($('settled'))$('settled').textContent=s.settled||0;if($('netUnits'))$('netUnits').textContent=Number(s.netUnits||0).toFixed(2);}
  function normalize(r){return{detected:r.selectedAt||'',match:`${r.home||''} vs ${r.away||''}`,pick:r.selectedTeam||'',ah:line(r.selectedLine??r.line),odds:r.odds??'—',entry:score(r.entryScore),final:r.finalScore?score(r.finalScore):'—',result:r.resultGroup||r.result||'PENDING',source:r.bookmaker||'1xBet'};}
  function render(records=[]){const rows=records.map(normalize);if($('statsRows'))$('statsRows').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.detected)}</td><td>${esc(r.match)}</td><td class="pick">${esc(r.pick)}</td><td>${r.ah}</td><td><b>${r.odds}</b></td><td>${r.entry}</td><td>${r.final}</td><td><span class="status ${cls(r.result)}">${esc(r.result)}</span></td><td>${esc(r.source)}</td></tr>`).join(''):'<tr><td colspan="9" class="muted">No locked signals yet.</td></tr>';if($('statsCards'))$('statsCards').innerHTML=rows.map(r=>`<article class="stats-card"><div class="stats-card-head"><small>${esc(r.detected)}</small><span class="status ${cls(r.result)}">${esc(r.result)}</span></div><h3>${esc(r.match)}</h3><div class="pick-line">${esc(r.pick)} ${r.ah} @ ${r.odds}</div><div class="stats-card-meta"><div><small>Entry</small><strong>${r.entry}</strong></div><div><small>Final</small><strong>${r.final}</strong></div><div><small>Source</small><strong>${esc(r.source)}</strong></div></div></article>`).join('');}
  function pager(p){const el=$('statsPager');if(!el)return;const current=Number(p.page)||1,pages=Number(p.pages)||1;el.innerHTML=`<button data-page="${Math.max(1,current-1)}" ${current<=1?'disabled':''}>←</button><button class="active" disabled>${current} / ${pages}</button><button data-page="${Math.min(pages,current+1)}" ${current>=pages?'disabled':''}>→</button>`;el.querySelectorAll('button[data-page]').forEach(b=>b.addEventListener('click',()=>load(Number(b.dataset.page))));}
  async function load(page=1){try{const rt=await getJson('./runtime.json',4000),p=await getJson(`${rt.engineWorkerUrl}/history?page=${page}&limit=25`);summary(p.summary);render(p.records||[]);pager(p);const ribbon=document.querySelector('.preview-ribbon');if(ribbon)ribbon.textContent='FULL ENGINE HISTORY · BET365_V4 settlement';}catch{summary({});render([]);pager({page:1,pages:1});const ribbon=document.querySelector('.preview-ribbon');if(ribbon)ribbon.textContent='STATISTICS OFFLINE · engine unavailable';}}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>load()):load();
})();
