name = "nomadtips3-nowgoal-probe-342"
main = "src/index.js"
compatibility_date = "2026-08-27"
workers_dev = true

[observability]
enabled = true

[env.test]
name = "nomadtips3-nowgoal-probe-342-test"
workers_dev = true
