const VERSION='nomad343-engine-v1';
const MARKETS=['ah','oneXtwo','over','under'];
const DEFAULTS={ah:{sideMode:'BOTH',shotOnTarget:1,shotOff:1,corner:1,attackPct:55,dangerousAttackPct:55,possessionPct:50,evidenceRequired:3,lineMin:0,oddsMin:1.50,oddsMax:3.00,minuteFrom:55,minuteTo:88,rollingWindowMinutes:10},oneXtwo:{sideMode:'BOTH',shotOnTarget:1,shotOff:1,corner:1,attackPct:55,dangerousAttackPct:55,possessionPct:50,evidenceRequired:3,scoreTrailingMax:1,oddsMin:1.50,oddsMax:4.00,minuteFrom:55,minuteTo:88,rollingWindowMinutes:10},over:{shotOnTarget:1,shotOff:1,corner:1,attackPct:55,dangerousAttackPct:55,possessionPct:50,evidenceRequired:3,lineMin:0.5,lineMax:5.5,oddsMin:1.50,minuteFrom:55,minuteTo:88,rollingWindowMinutes:10},under:{sideMode:'BOTH',shotOnTarget:1,shotOff:1,corner:1,attackPct:45,dangerousAttackPct:45,possessionPct:50,evidenceRequired:3,lineMin:0.5,lineMax:5.5,oddsMin:1.50,minuteFrom:55,minuteTo:88,rollingWindowMinutes:10}};
const now=()=>Date.now();
const num=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
const clone=v=>JSON.parse(JSON.stringify(v));
const pair=v=>v&&typeof v==='object'?{home:num(v.home),away:num(v.away)}:null;
const sideValue=(p,s)=>p?num(p[s]):null;
const delta=(a,b)=>{a=num(a);b=num(b);if(a===null||b===null)return null;const d=a-b;return d>=0?d:null};
function sanitizeSettings(input={}){const out={};for(const m of MARKETS){const d=DEFAULTS[m],src=input[m]||{};out[m]={...d};for(const k of Object.keys(d)){if(k==='sideMode'){const v=String(src[k]??d[k]).toUpperCase();out[m][k]=['HOME','AWAY','BOTH'].includes(v)?v:d[k]}else{const v=num(src[k]);if(v!==null)out[m][k]=v}}}return out}
function normalizeRun(input={}){return Object.fromEntries(MARKETS.map(m=>[m,Boolean(input[m])]))}
function sampleOf(f,at){return{at,minute:num(f.minute),shotsOnTarget:pair(f.statistics?.shotsOnTarget),shotsOffTarget:pair(f.statistics?.shotsOffTarget),corners:pair(f.corners),attacks:pair(f.statistics?.attacks),dangerousAttacks:pair(f.statistics?.dangerousAttacks),possession:pair(f.statistics?.possession),goals:pair(f.goals)}}
function deltaPair(cur,old){if(!cur||!old)return null;return{home:delta(cur.home,old.home),away:delta(cur.away,old.away)}}
function sharePair(p){if(!p)return null;const h=num(p.home),a=num(p.away);if(h===null||a===null||h+a<=0)return null;return{home:h/(h+a)*100,away:a/(h+a)*100}}
function rolling(history,minutes){if(!Array.isArray(history)||history.length<2)return{ready:false,reason:'WARMING'};const cur=history[history.length-1],target=cur.at-minutes*60000;let old=null;for(let i=history.length-2;i>=0;i--){if(history[i].at<=target){old=history[i];break}}if(!old)return{ready:false,reason:'WARMING'};const attacksDelta=deltaPair(cur.attacks,old.attacks),dangerousDelta=deltaPair(cur.dangerousAttacks,old.dangerousAttacks);return{ready:true,windowMinutes:minutes,fromAt:old.at,toAt:cur.at,shotsOnTarget:deltaPair(cur.shotsOnTarget,old.shotsOnTarget),shotsOffTarget:deltaPair(cur.shotsOffTarget,old.shotsOffTarget),corners:deltaPair(cur.corners,old.corners),attackPct:sharePair(attacksDelta),dangerousAttackPct:sharePair(dangerousDelta),possession:cur.possession}}
const EVIDENCE=[['shotOnTarget','shotsOnTarget'],['shotOff','shotsOffTarget'],['corner','corners'],['attackPct','attackPct'],['dangerousAttackPct','dangerousAttackPct'],['possessionPct','possession']];
function evidenceFor(r,cfg,side,isUnder){const items=EVIDENCE.map(([cfgKey,metricKey])=>{const value=sideValue(r[metricKey],side),threshold=num(cfg[cfgKey]),pass=value!==null&&threshold!==null&&(isUnder?value<=threshold:value>=threshold);return{key:cfgKey,value,threshold,pass}});return{side,items,passCount:items.filter(x=>x.pass).length,required:Number(cfg.evidenceRequired||0)}}
function allowedSides(cfg,market){if(market==='over')return['home','away'];const mode=String(cfg.sideMode||'BOTH').toUpperCase();if(mode==='HOME')return['home'];if(mode==='AWAY')return['away'];return['home','away']}
function oddsRoot(raw){if(!raw||typeof raw!=='object')return null;if(Array.isArray(raw.bookmakers)){const b=raw.bookmakers.find(x=>String(x?.slug||x?.name||'').toLowerCase().replace(/\s/g,'').includes('bet365'))||raw.bookmakers[0];return b?.odds||null}if(raw.data?.bookmakers)return oddsRoot(raw.data);if(raw.odds&&typeof raw.odds==='object'&&(raw.odds['1x2']||raw.odds.asian_handicap||raw.odds.goal_line))return raw.odds;return raw}
function inplay(root,key,alt){const m=root?.[key]??(alt?root?.[alt]:null);const v=m?.inplay??m?.in_play??null;return v&&typeof v==='object'?v:null}
function priceFor(f,market,side){const root=oddsRoot(f.providerOdds);if(!root)return null;if(market==='oneXtwo'){const p=inplay(root,'1x2');const odds=num(p?.[side]);return odds===null?null:{selection:side==='home'?'HOME':'AWAY',line:null,odds}}
if(market==='ah'){const p=inplay(root,'asian_handicap','asian');if(!p)return null;const homeLine=num(p.line),odds=num(p[side]);if(homeLine===null||odds===null)return null;return{selection:side==='home'?'HOME':'AWAY',line:side==='home'?homeLine:-homeLine,odds}}
const p=inplay(root,'goal_line','goalline');if(!p)return null;const line=num(p.line),odds=num(p[market==='over'?'over':'under']);if(line===null||odds===null)return null;return{selection:market==='over'?'OVER':'UNDER',line,odds}}
function pricePass(p,cfg,market){if(!p)return false;if(num(cfg.oddsMin)!==null&&p.odds<num(cfg.oddsMin))return false;if(num(cfg.oddsMax)!==null&&p.odds>num(cfg.oddsMax))return false;if(market==='ah'&&num(cfg.lineMin)!==null&&Math.abs(p.line)<Math.abs(num(cfg.lineMin)))return false;if((market==='over'||market==='under')){if(num(cfg.lineMin)!==null&&p.line<num(cfg.lineMin))return false;if(num(cfg.lineMax)!==null&&p.line>num(cfg.lineMax))return false}return true}
function trailingPass(f,side,max){const h=num(f.goals?.home),a=num(f.goals?.away);if(h===null||a===null)return false;const deficit=side==='home'?a-h:h-a;return deficit<=Number(max||0)}
function evaluateMarket(f,history,cfg,market,run){const minute=num(f.minute);if(!run)return{state:'STOP'};if(minute===null||minute<cfg.minuteFrom||minute>cfg.minuteTo)return{state:'TIME'};const r=rolling(history,cfg.rollingWindowMinutes);if(!r.ready)return{state:r.reason};const candidates=[];for(const side of allowedSides(cfg,market)){const e=evidenceFor(r,cfg,side,market==='under');if(e.passCount<e.required)continue;if(market==='oneXtwo'&&!trailingPass(f,side,cfg.scoreTrailingMax))continue;const p=priceFor(f,market,side);if(!pricePass(p,cfg,market))continue;candidates.push({side,evidence:e,price:p})}if(!candidates.length)return{state:'NO_PASS',rolling:r};candidates.sort((a,b)=>b.evidence.passCount-a.evidence.passCount);return{state:'PASS',rolling:r,...candidates[0]}}
function splitLine(line){const q=Math.round(Number(line)*4)/4;if(Math.abs(q*2-Math.round(q*2))<1e-8)return[q];return[Math.floor(q*2)/2,Math.ceil(q*2)/2]}
function combine(parts){if(parts.every(x=>x==='WIN'))return'WIN';if(parts.every(x=>x==='LOSS'))return'LOSS';if(parts.every(x=>x==='PUSH'))return'PUSH';if(parts.includes('WIN')&&parts.includes('PUSH')&&!parts.includes('LOSS'))return'HALF_WIN';if(parts.includes('LOSS')&&parts.includes('PUSH')&&!parts.includes('WIN'))return'HALF_LOSS';return parts.includes('WIN')?'HALF_WIN':'HALF_LOSS'}
function settle(signal,f){const h=num(f.goals?.home),a=num(f.goals?.away);if(h===null||a===null)return null;if(signal.market==='oneXtwo'){const win=signal.selection==='HOME'?h>a:a>h;return win?'WIN':'LOSS'}if(signal.market==='ah'){const base=signal.selection==='HOME'?h-a:a-h;return combine(splitLine(signal.line).map(l=>base+l>0?'WIN':base+l<0?'LOSS':'PUSH'))}const total=h+a;return combine(splitLine(signal.line).map(l=>signal.market==='over'?(total>l?'WIN':total<l?'LOSS':'PUSH'):(total<l?'WIN':total>l?'LOSS':'PUSH')))}
function statsFrom(signals){const rows=signals.filter(s=>s.status==='SETTLED');const count=r=>rows.filter(x=>x.result===r).length;const win=count('WIN'),loss=count('LOSS'),push=count('PUSH'),halfWin=count('HALF_WIN'),halfLoss=count('HALF_LOSS');const denom=win+loss+halfWin+halfLoss;return{total:rows.length,win,loss,push,halfWin,halfLoss,winRate:denom?Math.round(((win+.5*halfWin)/denom)*1000)/10:null,byMarket:Object.fromEntries(MARKETS.map(m=>[m,rows.filter(x=>x.market===m).length])),rows:rows.slice().sort((a,b)=>b.createdAt-a.createdAt)}}
export class Nomad343Engine{constructor(ctx,env){this.ctx=ctx;this.env=env;this.scanPromise=null}
async settings(){return sanitizeSettings(await this.ctx.storage.get('settings')||DEFAULTS)}async runState(){return normalizeRun(await this.ctx.storage.get('runState')||{})}
async scanIfDue(){const meta=await this.ctx.storage.get('lastScan');if(meta?.finishedAt&&now()-meta.finishedAt<45000)return meta;if(this.scanPromise)return this.scanPromise;this.scanPromise=this.scan().finally(()=>this.scanPromise=null);return this.scanPromise}
async scan(){const startedAt=now();try{const hr=await this.env.HUB.fetch('https://hub.internal/snapshot');const hub=await hr.json();if(!hub?.ok)throw new Error(hub?.error||'HUB_NOT_READY');const settings=await this.settings(),run=await this.runState();const oldHist=await this.ctx.storage.get('histories')||{},signals=await this.ctx.storage.get('signals')||[];const histories={},board=[];const seenSignal=new Set(signals.map(s=>`${s.fixtureId}:${s.market}`));const live=hub.fixtures.filter(f=>String(f.status||f.boardState).toLowerCase().includes('in_play')||f.boardState==='live');for(const f of live){const id=String(f.fixtureId);const arr=Array.isArray(oldHist[id])?oldHist[id].slice():[];const at=Number(hub.fetchedAt||now());const s=sampleOf(f,at);if(arr.length&&arr[arr.length-1].at===at)arr[arr.length-1]=s;else arr.push(s);histories[id]=arr.filter(x=>at-x.at<=45*60000).slice(-60)}for(const f of hub.fixtures){const analysis={};if(f.boardState==='live'){const id=String(f.fixtureId),history=histories[id]||[];for(const m of MARKETS){const ev=evaluateMarket(f,history,settings[m],m,run[m]);analysis[m]=ev;if(ev.state==='PASS'&&!seenSignal.has(`${id}:${m}`)){const sig={id:`${id}-${m}-${now().toString(36)}`,fixtureId:id,league:f.league,home:f.home,away:f.away,market:m,selection:ev.price.selection,line:ev.price.line,odds:ev.price.odds,createdAt:now(),minute:num(f.minute),scoreAt:pair(f.goals),evidence:ev.evidence,rolling:ev.rolling,status:'PENDING',result:null,finalScore:null};signals.push(sig);seenSignal.add(`${id}:${m}`)}}}board.push({...f,analysis})}
const finished=new Map(hub.fixtures.filter(f=>String(f.status||'').toLowerCase()==='finished').map(f=>[String(f.fixtureId),f]));for(const s of signals){if(s.status!=='PENDING')continue;const f=finished.get(String(s.fixtureId));if(!f)continue;const result=settle(s,f);if(!result)continue;s.status='SETTLED';s.result=result;s.finalScore=pair(f.goals);s.settledAt=now()}
await this.ctx.storage.put('histories',histories);await this.ctx.storage.put('signals',signals.slice(-1200));await this.ctx.storage.put('board',{ok:true,version:VERSION,hubFetchedAt:hub.fetchedAt,hubAgeMs:hub.ageMs,stale:hub.stale,counts:hub.counts,fixtures:board,runState:run});const meta={ok:true,startedAt,finishedAt:now(),fixtureCount:board.length,liveCount:live.length,signalCount:signals.filter(s=>s.status==='PENDING').length,lastError:null};await this.ctx.storage.put('lastScan',meta);return meta}catch(e){const meta={ok:false,startedAt,finishedAt:now(),lastError:String(e?.message||e)};await this.ctx.storage.put('lastScan',meta);return meta}}
async fetch(request){const u=new URL(request.url);if(u.pathname!=='/settings')await this.scanIfDue();if(u.pathname==='/health'){const m=await this.ctx.storage.get('lastScan');return Response.json({ok:Boolean(m?.ok),component:'NOMAD343_ENGINE',version:VERSION,...m})}if(u.pathname==='/settings'&&request.method==='GET')return Response.json({ok:true,version:VERSION,settings:await this.settings(),runState:await this.runState()});if(u.pathname==='/settings'&&request.method==='PUT'){const body=await request.json().catch(()=>({}));const settings=sanitizeSettings(body.settings||{}),run=normalizeRun(body.runState||{});await this.ctx.storage.put('settings',settings);await this.ctx.storage.put('runState',run);return Response.json({ok:true,settings,runState:run})}if(u.pathname==='/scan'&&request.method==='POST')return Response.json(await this.scan());if(u.pathname==='/board'){return Response.json(await this.ctx.storage.get('board')||{ok:false,version:VERSION,error:'NO_BOARD'})}if(u.pathname==='/signals'){const s=await this.ctx.storage.get('signals')||[];return Response.json({ok:true,version:VERSION,signals:s.filter(x=>x.status==='PENDING').sort((a,b)=>b.createdAt-a.createdAt),allCount:s.length})}if(u.pathname==='/statistics'){const s=await this.ctx.storage.get('signals')||[];return Response.json({ok:true,version:VERSION,...statsFrom(s)})}return new Response('Not found',{status:404})}}
function stub(env){return env.ENGINE.get(env.ENGINE.idFromName('global'))}
function cors(request,response){const h=new Headers(response.headers);const o=request.headers.get('origin')||'*';h.set('access-control-allow-origin',o);h.set('access-control-allow-methods','GET,PUT,POST,OPTIONS');h.set('access-control-allow-headers','content-type');h.set('cache-control','no-store');return new Response(response.body,{status:response.status,headers:h})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return cors(request,new Response(null,{status:204}));const u=new URL(request.url);if(!['/health','/settings','/scan','/board','/signals','/statistics'].includes(u.pathname))return cors(request,Response.json({ok:false,error:'NOT_FOUND'},{status:404}));const r=await stub(env).fetch(new Request(`https://engine.internal${u.pathname}${u.search}`,request));return cors(request,r)},async scheduled(_e,env,ctx){ctx.waitUntil(stub(env).fetch('https://engine.internal/scan',{method:'POST'}))}};
