import{DEFAULT_CONFIG,normalizeConfig,schedule,evaluate}from'./rules.js';
import{fetchNowgoal1xBetMarkets}from'../../../nomad-live-engine/src/nowgoal.js';
const API='https://v3.football.api-sports.io';
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|sc|afc|club)\b/g,'').replace(/[^a-z0-9]/g,'');
const pair=(a,b)=>({home:a??null,away:b??null});
function cors(){return{'content-type':'application/json;charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-owner-key'}}
const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:cors()});
async function api(path,key){const r=await fetch(API+path,{headers:{'x-apisports-key':key}});const j=await r.json();if(!r.ok||j.errors&&Object.keys(j.errors).length)throw new Error('API-Football: '+JSON.stringify(j.errors||r.status));return j.response||[]}
function stats(rows){const out={sot:{},shotOff:{},corners:{}};for(const team of rows){const side=team.team?.winner===true?'winner':null;void side;const map=Object.fromEntries((team.statistics||[]).map(x=>[String(x.type).toLowerCase(),x.value]));team._parsed={sot:map['shots on goal'],shotOff:map['shots off goal'],corners:map['corner kicks']}}return rows}
function nearest(feed,f){const h=norm(f.teams.home.name),a=norm(f.teams.away.name);return(feed.matches||[]).find(m=>norm(m.home)===h&&norm(m.away)===a)||null}
function merged(f,rows,m){const home=rows.find(x=>norm(x.team?.name)===norm(f.teams.home.name))?._parsed||{},away=rows.find(x=>norm(x.team?.name)===norm(f.teams.away.name))?._parsed||{};const st=m?.stats||{};return{stats:{sot:pair(home.sot,away.sot),shotOff:pair(home.shotOff,away.shotOff),corners:st.corners||pair(home.corners,away.corners),attacks:st.attacks,dangerous:st.dangerousAttack||st.dangerous},market:m?.market||m?.selectedMarket||null}}
export class DetectorState{
 constructor(state,env){this.state=state;this.env=env}
 async cfg(){return normalizeConfig(await this.state.storage.get('config')||DEFAULT_CONFIG)}
 async cycle(){
  const c=await this.cfg();if(!c.enabled)return{ok:true,skipped:'disabled'};if(!this.env.API_FOOTBALL_KEY)throw new Error('ยังไม่ได้ตั้ง API_FOOTBALL_KEY');
  const [live,feed]=await Promise.all([api('/fixtures?live=all',this.env.API_FOOTBALL_KEY),fetch(this.env.NOMAD_FEED_URL).then(r=>r.json())]);const jobs=[];
  for(const f of live){const id=String(f.fixture.id),minute=Number(f.fixture.status?.elapsed);if(!Number.isFinite(minute)||minute<c.minuteFrom||minute>c.minuteTo+3)continue;const key='match:'+id,rec=await this.state.storage.get(key)||{fixtureId:id,completed:[],locked:false};if(rec.locked||rec.completed.length>=4)continue;const times=schedule(c),index=times.findIndex((x,i)=>minute>=x&&!rec.completed.includes(i));if(index<0)continue;const match=nearest(feed,f);if(match)jobs.push({f,id,minute,key,rec,index,match})}
  let markets=new Map();if(jobs.length){const n=await fetchNowgoal1xBetMarkets(jobs.map(j=>({id:j.match.id,home:j.match.home,away:j.match.away,score:j.match.score})),{requestTimeoutMs:9000,maximumPriceAgeSeconds:c.sourceMaxAgeSeconds},Date.now(),await this.state.storage.get('nowgoalUpdates')||{});markets=new Map(n.results.map(x=>[String(x.matchId),x.market]));await this.state.storage.put('nowgoalUpdates',n.priceUpdates||{})}
  let checked=0,locked=0;for(const j of jobs){const rows=stats(await api('/fixtures/statistics?fixture='+j.id,this.env.API_FOOTBALL_KEY)),base=merged(j.f,rows,j.match);base.market=markets.get(String(j.match.id))||null;j.rec.completed.push(j.index);j.rec.lastMinute=j.minute;j.rec.updatedAt=Date.now();j.rec.snapshots=[...(j.rec.snapshots||[]),{index:j.index,minute:j.minute,data:base}];for(const side of(c.side==='BOTH'?['HOME','AWAY']:[c.side])){const result=evaluate({side,...base},c);if(result.passed){const signal={id:j.id+':'+side,fixtureId:j.id,side,league:j.f.league?.name,home:j.f.teams.home.name,away:j.f.teams.away.name,minute:j.minute,score:pair(j.f.goals.home,j.f.goals.away),...result,stats:base.stats,market:base.market,lockedAt:Date.now()};await this.state.storage.put('signal:'+signal.id,signal);j.rec.locked=true;locked++;break}}await this.state.storage.put(j.key,j.rec);checked++}await this.state.storage.put('status',{updatedAt:Date.now(),live:live.length,eligible:jobs.length,checked,locked});return{ok:true,live:live.length,checked,locked}}
 async fetch(req){if(req.method==='OPTIONS')return new Response('',{status:204,headers:cors()});const u=new URL(req.url);if(u.pathname==='/config'){if(req.method==='POST'){if(this.env.OWNER_KEY&&req.headers.get('x-owner-key')!==this.env.OWNER_KEY)return json({ok:false,error:'รหัสเจ้าของไม่ถูกต้อง'},401);try{const c=normalizeConfig(await req.json());await this.state.storage.put('config',c);return json({ok:true,config:c,schedule:schedule(c)})}catch(e){return json({ok:false,error:e.message},400)}}const c=await this.cfg();return json({ok:true,config:c,schedule:schedule(c)})}if(u.pathname==='/signals'){const list=[];for(const[,v]of await this.state.storage.list({prefix:'signal:'}))list.push(v);return json({ok:true,signals:list.sort((a,b)=>b.lockedAt-a.lockedAt)})}if(u.pathname==='/status')return json({ok:true,status:await this.state.storage.get('status')||null});if(u.pathname==='/cycle'&&req.method==='POST'){if(this.env.OWNER_KEY&&req.headers.get('x-owner-key')!==this.env.OWNER_KEY)return json({ok:false},401);try{return json(await this.cycle())}catch(e){return json({ok:false,error:e.message},500)}}return json({ok:true,service:'ADD K AH Detector',version:'1.0.0'})}}
export default{fetch(req,env){return env.DETECTOR.get(env.DETECTOR.idFromName('main')).fetch(req)},scheduled(_,env,ctx){ctx.waitUntil(env.DETECTOR.get(env.DETECTOR.idFromName('main')).fetch('https://internal/cycle',{method:'POST',headers:{'x-owner-key':env.OWNER_KEY||''}}))}};


