export const DEFAULT_CONFIG = Object.freeze({
  scanUrl: 'https://www.totalcorner.com/match/today/',
  endedUrl: 'https://www.totalcorner.com/match/today/ended',
  sourceHost: 'https://www.totalcorner.com',
  minuteFrom: 55,
  minuteTo: 80,
  watchMinuteFrom: 45,
  watchMinuteTo: 88,
  maxScoreDifference: 1,
  attackDifference: 15,
  dangerousAttackDifference: 10,
  dangerousAttackRatio: 1.30,
  shotsOnTargetMinimum: 4,
  shotsOnTargetDifference: 2,
  cornersMinimum: 4,
  momentumMinimum: 70,
  allowedSelectionLines: [0, -0.25, -0.5, -0.75, -1],
  oddsMinimum: 1.70,
  oddsMaximum: 2.10,
  staleAfterMs: 90000,
  cycleEveryMs: 55000,
  maxWatchMatches: 24,
  maxNearOddsMatches: 12,
  requestTimeoutMs: 10000,
  oneSignalPerMatch: true,
});
