const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const FSIGN='SW9D1eZo';
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'*/*','accept-language':'en-GB,en;q=0.9','referer':'https://www.flashscore.com/','origin':'https://www.flashscore.com','x-fsign':FSIGN,'cache-control':'no-cache','pragma':'no-cache'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function grab(url,headers=HEADERS){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),12000);try{const r=await fetch(url,{headers,redirect:'follow',signal:ac.signal}),text=await r.text();return{url,finalUrl:r.url,status:r.status,ok:r.ok,contentType:r.headers.get('content-type')||'',bytes:text.length,text,error:null};}catch(e){return{url,finalUrl:null,status:null,ok:false,contentType:'',bytes:0,text:'',error:String(e?.message||e)}}finally{clearTimeout(timer)}}
function parseRecords(text=''){const out=[];let cur=null;for(const raw of text.split('¬')){if(!raw)continue;const ix=raw.indexOf('÷');if(ix<0)continue;let key=raw.slice(0,ix),value=raw.slice(ix+1);const fresh=key.startsWith('~');if(fresh)key=key.slice(1);if(fresh||!cur){if(cur&&Object.keys(cur).length)out.push(cur);cur={};}cur[key]=value;}if(cur&&Object.keys(cur).length)out.push(cur);return out;}
function eventsFromFeed(text=''){return parseRecords(text).filter(x=>x.AA).map(x=>({id:x.AA,status:x.AB??null,start:x.AD??null,home:x.AE??null,away:x.AF??null,homeScore:x.AG??null,awayScore:x.AH??null,homeSlug:x.WU??null,awaySlug:x.WV??null,urlHomeId:x.PX??null,urlAwayId:x.PY??null,participantHomeId:x.JA??null,participantAwayId:x.JB??null,raw:x}));}
function statRows(text=''){let section='Match';const rows=[];for(const r of parseRecords(text)){if(r.SE!=null){section=r.SE;continue;}if(r.SG!=null)rows.push({section,name:r.SG,home:r.SH??null,away:r.SI??null});}return rows;}
function general(text=''){const r=parseRecords(text)[0]||{};let minute=null;if(r.DA==='2'){if(r.DB==='38')minute=45;else if((r.DB==='12'||r.DB==='13')&&Number.isFinite(Number(r.DD))){const elapsed=Math.floor((Date.now()/1000-Number(r.DD))/60);minute=r.DB==='13'?elapsed+45:elapsed;}}return{status:r.DA??null,stage:r.DB??null,phaseStartedAt:r.DD??null,start:r.DC??null,minute,homeScore:r.DE??null,awayScore:r.DF??null,raw:Object.fromEntries(Object.entries(r).filter(([,v])=>String(v).length<100))};}
function jsonAfter(text,marker){const i=text.indexOf(marker);if(i<0)return null;const start=text.indexOf('{',i+marker.length);if(start<0)return null;let depth=0,str=false,esc=false;for(let p=start;p<text.length;p++){const ch=text[p];if(str){if(esc)esc=false;else if(ch==='\\')esc=true;else if(ch==='"')str=false;continue;}if(ch==='"'){str=true;continue;}if(ch==='{')depth++;else if(ch==='}'){depth--;if(depth===0){try{return JSON.parse(text.slice(start,p+1));}catch{return null;}}}}return null;}
function keyScan(obj){const out=[];function walk(v,path='',d=0){if(d>7||v==null||out.length>120)return;if(Array.isArray(v)){for(let i=0;i<Math.min(v.length,8);i++)walk(v[i],`${path}[${i}]`,d+1);return;}if(typeof v!=='object')return;for(const[k,val]of Object.entries(v)){const p=path?`${path}.${k}`:k;if(/id$|Id$|ID$|tournament|season|stage|participant|team|country|category/i.test(k)&&(typeof val==='string'||typeof val==='number'||typeof val==='boolean'))out.push({path:p,value:val});walk(val,p,d+1);}}walk(obj);return out.slice(0,120);}
function envSummary(text){const env=jsonAfter(text,'window.environment =');if(!env)return null;return{keys:Object.keys(env),scan:keyScan(env),header:env.header?{keys:Object.keys(env.header),scan:keyScan(env.header)}:null,participants:env.participantsData?keyScan(env.participantsData):null};}
function canonicalTeams(url='',sample={}){const m=String(url).match(/\/match\/football\/([^/?]+)-([A-Za-z0-9]+)\/([^/?]+)-([A-Za-z0-9]+)\//i);if(!m)return{};const parts=[{slug:m[1],id:m[2]},{slug:m[3],id:m[4]}];const bySlug=s=>parts.find(p=>s&&(p.slug===s||p.slug.includes(s)||s.includes(p.slug)));return{parts,home:bySlug(sample.homeSlug)||null,away:bySlug(sample.awaySlug)||null};}
async function gql(url){const r=await grab(url,{...HEADERS,accept:'application/json,text/plain,*/*'});let json=null;try{json=JSON.parse(r.text)}catch{}return{status:r.status,ok:r.ok,bytes:r.bytes,hasData:!!json?.data,scan:json?keyScan(json.data).slice(0,80):[]};}
async function inspectEvent(e,feedBase){const statsR=await grab(`${feedBase}/df_st_1_${e.id}`);await sleep(120);const generalR=await grab(`${feedBase}/dc_1_${e.id}`);await sleep(120);const matchR=await grab(`https://www.flashscore.com/match/${e.id}/`);const teams=canonicalTeams(matchR.finalUrl,e);return{id:e.id,status:e.status,home:e.home,away:e.away,feedIds:{PX:e.urlHomeId,PY:e.urlAwayId,JA:e.participantHomeId,JB:e.participantAwayId},canonical:matchR.finalUrl,canonicalTeams:teams,stats:{status:statsR.status,rows:statRows(statsR.text).filter(x=>x.section==='Match'),hasAttack:statRows(statsR.text).some(x=>/^attacks?$/i.test(x.name)),hasDangerous:statRows(statsR.text).some(x=>/dangerous/i.test(x.name))},general:{status:generalR.status,...general(generalR.text)},environment:envSummary(matchR.text)};}
async function probe(){
  const feedUrl='https://www.flashscore.com/x/feed/f_1_0_3_en-gb_1',feedR=await grab(feedUrl),events=feedR.ok?eventsFromFeed(feedR.text):[];if(!events.length)return{checkedAt:new Date().toISOString(),error:'no_feed_events',feedStatus:feedR.status};const feedBase='https://www.flashscore.com/x/feed';
  const live=events.filter(e=>e.status==='2'),finished=events.filter(e=>e.status==='3');const chosen=[...live.slice(0,5),...finished.slice(0,5)];if(!chosen.some(x=>x.id==='dpt0n9Ca'))chosen.push({id:'dpt0n9Ca',status:'3',home:'Racing Club',away:'Belgrano',homeSlug:'racing-club',awaySlug:'ca-belgrano-de-cordoba'});
  const samples=[];for(const e of chosen){samples.push(await inspectEvent(e,feedBase));await sleep(180);}
  const anchor=samples.find(x=>x.environment?.header)||samples[0];const matchId=anchor.id;
  const extras={summary:(await grab(`${feedBase}/df_sui_1_${matchId}`)).status,h2h:(await grab(`${feedBase}/df_hh_1_${matchId}`)).status,lineups:await gql(`https://2.ds.lsapp.eu/pq_graphql?_hash=dlie2&eventId=${encodeURIComponent(matchId)}&projectId=2`),playerStats:await gql(`https://2.ds.lsapp.eu/pq_graphql?_hash=epmsd&eventId=${encodeURIComponent(matchId)}&providerId=7`),oddsReference:await gql(`https://global.ds.lsapp.eu/odds/pq_graphql?_hash=oce&eventId=${encodeURIComponent(matchId)}&projectId=2&geoIpCode=TH&geoIpSubdivisionCode=TH10`)};
  const teamPages={};for(const side of ['home','away']){const p=anchor.canonicalTeams?.[side];if(!p)continue;const r=await grab(`https://www.flashscore.com/team/${p.slug}/${p.id}/`);teamPages[side]={status:r.status,bytes:r.bytes,environment:envSummary(r.text)};}
  return{checkedAt:new Date().toISOString(),feed:{status:feedR.status,bytes:feedR.bytes,eventCount:events.length,liveCount:live.length,finishedCount:finished.length},samples,anchor:{matchId,canonical:anchor.canonical,teams:anchor.canonicalTeams},extras,teamPages,note:'Flashscore odds is reference-only and is not a lock source.'};
}
export default{async fetch(request){const u=new URL(request.url);if(u.pathname!=='/probe')return new Response(JSON.stringify({ok:true,endpoint:'/probe'}),{headers:JSON_HEADERS});return new Response(JSON.stringify(await probe()),{headers:JSON_HEADERS});}};
