const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const FSIGN='SW9D1eZo';
const HEADERS={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'*/*','accept-language':'en-GB,en;q=0.9','referer':'https://www.flashscore.com/','origin':'https://www.flashscore.com','x-fsign':FSIGN,'cache-control':'no-cache','pragma':'no-cache'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function grab(url,headers=HEADERS){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),12000);try{const r=await fetch(url,{headers,redirect:'follow',signal:ac.signal}),text=await r.text();return{url,finalUrl:r.url,status:r.status,ok:r.ok,contentType:r.headers.get('content-type')||'',bytes:text.length,text,error:null};}catch(e){return{url,finalUrl:null,status:null,ok:false,contentType:'',bytes:0,text:'',error:String(e?.message||e)}}finally{clearTimeout(timer)}}
function parseRecords(text=''){const out=[];let cur=null;for(const raw of text.split('¬')){if(!raw)continue;const ix=raw.indexOf('÷');if(ix<0)continue;let key=raw.slice(0,ix),value=raw.slice(ix+1);const fresh=key.startsWith('~');if(fresh)key=key.slice(1);if(fresh||!cur){if(cur&&Object.keys(cur).length)out.push(cur);cur={};}cur[key]=value;}if(cur&&Object.keys(cur).length)out.push(cur);return out;}
function contextualEvents(text=''){let league={};const out=[];for(const r of parseRecords(text)){if(r.ZA){league={name:r.ZA,country:r.ZY??null,countryId:r.ZB??null,tournamentKey:r.ZEE??null,seasonKey:r.ZC??null,stageKey:r.ZE??null,path:r.ZL??null,seasonLabel:r.ZS??null,kind:r.ZD??null};continue;}if(!r.AA)continue;out.push({id:r.AA,status:r.AB??null,start:r.AD??null,home:r.AE??null,away:r.AF??null,homeScore:r.AG??null,awayScore:r.AH??null,homeSlug:r.WU??null,awaySlug:r.WV??null,urlHomeId:r.PX??null,urlAwayId:r.PY??null,participantHomeId:r.JA??null,participantAwayId:r.JB??null,league:{...league},raw:r});}return out;}
function statRows(text=''){let section='Match';const rows=[];for(const r of parseRecords(text)){if(r.SE!=null){section=r.SE;continue;}if(r.SG!=null)rows.push({section,name:r.SG,home:r.SH??null,away:r.SI??null});}return rows;}
function general(text=''){const r=parseRecords(text)[0]||{};let minute=null;if(r.DA==='2'){if(r.DB==='38')minute=45;else if((r.DB==='12'||r.DB==='13')&&Number.isFinite(Number(r.DD))){const elapsed=Math.floor((Date.now()/1000-Number(r.DD))/60);minute=r.DB==='13'?elapsed+45:elapsed;}}return{status:r.DA??null,stage:r.DB??null,phaseStartedAt:r.DD??null,start:r.DC??null,minute,homeScore:r.DE??null,awayScore:r.DF??null};}
function jsonAfter(text,marker){const i=text.indexOf(marker);if(i<0)return null;const start=text.indexOf('{',i+marker.length);if(start<0)return null;let depth=0,str=false,esc=false;for(let p=start;p<text.length;p++){const ch=text[p];if(str){if(esc)esc=false;else if(ch==='\\')esc=true;else if(ch==='"')str=false;continue;}if(ch==='"'){str=true;continue;}if(ch==='{')depth++;else if(ch==='}'){depth--;if(depth===0){try{return JSON.parse(text.slice(start,p+1));}catch{return null;}}}}return null;}
function keyScan(obj,max=160){const out=[];function walk(v,path='',d=0){if(d>8||v==null||out.length>=max)return;if(Array.isArray(v)){for(let i=0;i<Math.min(v.length,12);i++)walk(v[i],`${path}[${i}]`,d+1);return;}if(typeof v!=='object')return;for(const[k,val]of Object.entries(v)){const p=path?`${path}.${k}`:k;if(/id$|Id$|ID$|tournament|season|stage|participant|team|country|category|league/i.test(k)&&(typeof val==='string'||typeof val==='number'||typeof val==='boolean'))out.push({path:p,value:val});walk(val,p,d+1);}}walk(obj);return out;}
function envSummary(text){const env=jsonAfter(text,'window.environment =');if(!env)return null;return{keys:Object.keys(env),scan:keyScan(env),header:env.header?keyScan(env.header):null,participantHeader:env.participantHeader?keyScan(env.participantHeader):null};}
function canonicalTeams(url='',sample={}){const m=String(url).match(/\/match\/football\/([^/?]+)-([A-Za-z0-9]+)\/([^/?]+)-([A-Za-z0-9]+)\//i);if(!m)return{};const parts=[{slug:m[1],id:m[2]},{slug:m[3],id:m[4]}];const bySlug=s=>parts.find(p=>s&&(p.slug===s||p.slug.includes(s)||s.includes(p.slug)));return{parts,home:bySlug(sample.homeSlug)||null,away:bySlug(sample.awaySlug)||null};}
function teamLinks(text=''){const out=[];const re=/href=["'](?:https:\/\/www\.flashscore\.com)?\/team\/([^/"']+)\/([A-Za-z0-9]+)\/?[^"']*["']/gi;let m;while((m=re.exec(text))&&out.length<80){const x={slug:m[1],id:m[2]};if(!out.some(v=>v.id===x.id))out.push(x);}return out;}
function playerLinks(text=''){const out=[];const re=/href=["'](?:https:\/\/www\.flashscore\.com)?\/player\/([^/"']+)\/([A-Za-z0-9]+)\/?[^"']*["']/gi;let m;while((m=re.exec(text))&&out.length<120){const x={slug:m[1],id:m[2]};if(!out.some(v=>v.id===x.id))out.push(x);}return out;}
function markerCounts(text=''){const count=re=>(text.match(re)||[]).length;return{standings:count(/standings/gi),overall:count(/overall/gi),home:count(/home/gi),away:count(/away/gi),form:count(/form/gi),squad:count(/squad/gi),goalkeepers:count(/goalkeepers/gi),defenders:count(/defenders/gi),midfielders:count(/midfielders/gi),forwards:count(/forwards/gi),playerLinks:playerLinks(text).length,teamLinks:teamLinks(text).length};}
async function gql(url){const r=await grab(url,{...HEADERS,accept:'application/json,text/plain,*/*'});let json=null;try{json=JSON.parse(r.text)}catch{}return{status:r.status,ok:r.ok,bytes:r.bytes,hasData:!!json?.data,scan:json?keyScan(json.data,80):[]};}
async function inspectEvent(e,feedBase){const statsR=await grab(`${feedBase}/df_st_1_${e.id}`);await sleep(100);const generalR=await grab(`${feedBase}/dc_1_${e.id}`);await sleep(100);const matchR=await grab(`https://www.flashscore.com/match/${e.id}/`);const teams=canonicalTeams(matchR.finalUrl,e),rows=statRows(statsR.text).filter(x=>x.section==='Match');return{id:e.id,status:e.status,home:e.home,away:e.away,league:e.league,feedIds:{PX:e.urlHomeId,PY:e.urlAwayId,JA:e.participantHomeId,JB:e.participantAwayId},canonical:matchR.finalUrl,canonicalTeams:teams,stats:{status:statsR.status,rows,hasAttack:rows.some(x=>/^attacks?$/i.test(x.name)),hasDangerous:rows.some(x=>/dangerous/i.test(x.name))},general:{status:generalR.status,...general(generalR.text)},environment:envSummary(matchR.text)};}
async function probe(){
  const feedUrl='https://www.flashscore.com/x/feed/f_1_0_3_en-gb_1',feedR=await grab(feedUrl),events=feedR.ok?contextualEvents(feedR.text):[];if(!events.length)return{checkedAt:new Date().toISOString(),error:'no_feed_events',feedStatus:feedR.status};const feedBase='https://www.flashscore.com/x/feed';
  const real=e=>!/esoccer|e-soccer|virtual|simulated/i.test(e.league?.name||'');const live=events.filter(e=>e.status==='2'&&real(e)),finished=events.filter(e=>e.status==='3'&&real(e));const chosen=[...live.slice(0,4),...finished.slice(0,4)];const samples=[];for(const e of chosen){samples.push(await inspectEvent(e,feedBase));await sleep(150);}
  const anchor=samples.find(x=>x.league?.path&&x.canonicalTeams?.home)||samples[0];const matchId=anchor.id;
  const extras={summary:(await grab(`${feedBase}/df_sui_1_${matchId}`)).status,h2h:(await grab(`${feedBase}/df_hh_1_${matchId}`)).status,lineups:await gql(`https://2.ds.lsapp.eu/pq_graphql?_hash=dlie2&eventId=${encodeURIComponent(matchId)}&projectId=2`),playerStats:await gql(`https://2.ds.lsapp.eu/pq_graphql?_hash=epmsd&eventId=${encodeURIComponent(matchId)}&providerId=7`),oddsReference:await gql(`https://global.ds.lsapp.eu/odds/pq_graphql?_hash=oce&eventId=${encodeURIComponent(matchId)}&projectId=2&geoIpCode=TH&geoIpSubdivisionCode=TH10`)};
  const teamPages={};for(const side of ['home','away']){const p=anchor.canonicalTeams?.[side];if(!p)continue;const r=await grab(`https://www.flashscore.com/team/${p.slug}/${p.id}/`);teamPages[side]={status:r.status,bytes:r.bytes,markers:markerCounts(r.text),players:playerLinks(r.text).slice(0,35),teams:teamLinks(r.text).slice(0,10),environment:envSummary(r.text)};await sleep(150);}
  let standings=null;if(anchor.league?.path){const p=anchor.league.path.startsWith('/')?anchor.league.path:`/${anchor.league.path}`;const r=await grab(`https://www.flashscore.com${p.replace(/\/$/,'')}/standings/`);standings={status:r.status,bytes:r.bytes,finalUrl:r.finalUrl,markers:markerCounts(r.text),teams:teamLinks(r.text).slice(0,30),environment:envSummary(r.text),embeddedResults:/tournament-page-data-results/i.test(r.text),embeddedStandings:/tournament-page-data-standings/i.test(r.text)};}
  const premierR=await grab('https://www.flashscore.com/football/england/premier-league/standings/');const premier={status:premierR.status,bytes:premierR.bytes,markers:markerCounts(premierR.text),teams:teamLinks(premierR.text).slice(0,30),environment:envSummary(premierR.text),embeddedResults:/tournament-page-data-results/i.test(premierR.text),embeddedStandings:/tournament-page-data-standings/i.test(premierR.text)};
  const chelseaR=await grab('https://www.flashscore.com/team/chelsea/4fGZN2oK/');const chelsea={status:chelseaR.status,bytes:chelseaR.bytes,markers:markerCounts(chelseaR.text),players:playerLinks(chelseaR.text).slice(0,50),environment:envSummary(chelseaR.text)};
  return{checkedAt:new Date().toISOString(),feed:{status:feedR.status,bytes:feedR.bytes,eventCount:events.length,liveReal:live.length,finishedReal:finished.length},samples,anchor:{matchId,league:anchor.league,canonical:anchor.canonical,teams:anchor.canonicalTeams},extras,teamPages,standings,premier,chelsea,note:'Odds is reference-only; no lock semantics.'};
}
export default{async fetch(request){const u=new URL(request.url);if(u.pathname!=='/probe')return new Response(JSON.stringify({ok:true,endpoint:'/probe'}),{headers:JSON_HEADERS});return new Response(JSON.stringify(await probe()),{headers:JSON_HEADERS});}};
