/* B46_DAILY_PERFORMANCE_20261005
 * Presentation-only Daily Performance card. Old scorebar and engine stay untouched.
 */
(()=>{'use strict';
const ID='ball46-daily-performance',TZ='Europe/London',CUT=6,REFRESH=300000;
let lastGood=null,busy=false;
const $=(s,r=document)=>r.querySelector(s);
function ensure(){let r=document.getElementById(ID);if(r)return r;const t=$('.main-board .board-toolbar');if(!t)return null;r=document.createElement('section');r.id=ID;r.setAttribute('aria-label','Daily performance');r.innerHTML=`<div class="b46-perf-grid"><section class="b46-perf-side today"><div class="b46-perf-head"><div class="b46-perf-title"><span class="b46-perf-kicker">TODAY'S PERFORMANCE</span><span class="b46-perf-sub" data-b46-label="today">Live Summary</span></div><div class="b46-perf-rate"><span>WIN RATE</span><strong data-b46-rate="today">—</strong></div></div><div class="b46-perf-stats"><div class="b46-perf-stat win"><span>WIN</span><strong data-b46-stat="today-win">—</strong></div><div class="b46-perf-stat loss"><span>LOSS</span><strong data-b46-stat="today-loss">—</strong></div><div class="b46-perf-stat push"><span>PUSH</span><strong data-b46-stat="today-push">—</strong></div><div class="b46-perf-stat pending"><span>PENDING</span><strong data-b46-stat="today-pending">—</strong></div></div><div class="b46-perf-foot"><span class="b46-perf-total">TOTAL PICKS <b data-b46-total="today">—</b></span><div class="b46-market-row" data-b46-markets="today"></div></div><span class="b46-perf-state">LONDON DAY · 06:00</span></section><section class="b46-perf-side yesterday"><div class="b46-perf-head"><div class="b46-perf-title"><span class="b46-perf-kicker">YESTERDAY'S PERFORMANCE</span><span class="b46-perf-sub" data-b46-label="yesterday">Final Summary</span></div><div class="b46-perf-rate"><span>WIN RATE</span><strong data-b46-rate="yesterday">—</strong></div></div><div class="b46-perf-stats"><div class="b46-perf-stat win"><span>WIN</span><strong data-b46-stat="yesterday-win">—</strong></div><div class="b46-perf-stat loss"><span>LOSS</span><strong data-b46-stat="yesterday-loss">—</strong></div><div class="b46-perf-stat push"><span>PUSH</span><strong data-b46-stat="yesterday-push">—</strong></div></div><div class="b46-perf-foot"><span class="b46-perf-total">TOTAL PICKS <b data-b46-total="yesterday">—</b></span><div class="b46-market-row" data-b46-markets="yesterday"></div></div><span class="b46-perf-state">FINAL · SETTLED ONLY</span></section></div>`;t.insertAdjacentElement('afterend',r);return r}
function parts(ms){const o={};for(const p of new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms)))if(p.type!=='literal')o[p.type]=p.value;return o}
function prev(k){const [y,m,d]=k.split('-').map(Number);return new Date(Date.UTC(y,m-1,d)-86400000).toISOString().slice(0,10)}
function sportDay(ms){const p=parts(ms);let k=`${p.year}-${p.month}-${p.day}`;if(Number(p.hour)<CUT)k=prev(k);return k}
function ms(v){if(v==null||v==='')return null;if(typeof v==='number'||/^\d+(?:\.\d+)?$/.test(String(v))){const n=Number(v);return Number.isFinite(n)?(n>1e12?n:n>1e9?n*1000:null):null}const n=Date.parse(String(v));return Number.isFinite(n)?n:null}
function stamp(r){for(const k of ['settledAt','settled_at','resolvedAt','resolved_at','updatedAt','updated_at','createdAt','created_at','timestamp','time','detectedAt','lockedAt','entryAt']){const n=ms(r?.[k]);if(n!==null)return n}return null}
function outcome(r){const x=String(r?.result??r?.settlement??r?.outcome??r?.status??'').trim().toLowerCase();if(/\bwin(?:ner|ning)?\b/.test(x))return'win';if(/\b(?:loss|lose|lost)\b/.test(x))return'loss';if(/\b(?:push|draw|refund|void|neutral|cancel(?:led)?)\b/.test(x))return'push';return null}
function market(r){const x=String(r?.marketLabel??r?.market??r?.marketType??'').toLowerCase().replace(/[_-]+/g,' ');if(/asian|handicap|\bah\b/.test(x))return'AH';if(/over\s*\/?\s*under|o\s*\/?\s*u|goal line|total/.test(x))return'O/U';if(/1x2|match result|moneyline/.test(x))return'1X2';return null}
function rowId(r){const fallback=[r?.fixtureId,r?.market,r?.selection].filter(Boolean).join('|');return String(r?.signalId??r?.id??fallback??'')}
function bucket(){return{win:0,loss:0,push:0,pending:0,markets:{AH:{win:0,loss:0,push:0},'O/U':{win:0,loss:0,push:0},'1X2':{win:0,loss:0,push:0}}}}
function add(b,r){const o=outcome(r);if(!o)return false;b[o]++;const m=market(r);if(m)b.markets[m][o]++;return true}
function final(r){return Boolean(outcome(r))||/settled|finished|final|closed|resolved/i.test(String(r?.status??''))}
function aggregate(stats,signals){const tk=sportDay(Date.now()),yk=prev(tk),today=bucket(),yesterday=bucket(),settled=new Set();for(const r of stats){const t=stamp(r);if(t===null)continue;const k=sportDay(t);if(k!==tk&&k!==yk)continue;if(add(k===tk?today:yesterday,r)){const id=rowId(r);if(id)settled.add(id)}}const seen=new Set();for(const s of signals){const id=rowId(s);if(id&&(settled.has(id)||seen.has(id)))continue;if(id)seen.add(id);if(final(s))continue;const t=stamp(s);if(t!==null&&sportDay(t)!==tk)continue;today.pending++}return{today,yesterday,tk,yk}}
function rate(b){const n=b.win+b.loss;return n?`${(b.win/n*100).toFixed(1).replace(/\.0$/,'')}%`:'—'}
function dateLabel(k){const [y,m,d]=k.split('-').map(Number);return new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'2-digit',month:'short'}).format(new Date(Date.UTC(y,m-1,d))).toUpperCase()}
function marketHtml(b){return['AH','O/U','1X2'].map(m=>`<span class="b46-market"><b>${m}</b><span>W ${b.markets[m].win} · L ${b.markets[m].loss} · P ${b.markets[m].push}</span></span>`).join('')}
function text(r,s,v){const e=$(s,r);if(e&&e.textContent!==String(v))e.textContent=String(v)}
function render(d){const r=ensure();if(!r)return;for(const [day,b] of [['today',d.today],['yesterday',d.yesterday]]){for(const o of ['win','loss','push'])text(r,`[data-b46-stat="${day}-${o}"]`,b[o]);if(day==='today')text(r,'[data-b46-stat="today-pending"]',b.pending);text(r,`[data-b46-rate="${day}"]`,rate(b));text(r,`[data-b46-total="${day}"]`,b.win+b.loss+b.push+(day==='today'?b.pending:0));const box=$(`[data-b46-markets="${day}"]`,r),h=marketHtml(b);if(box&&box.innerHTML!==h)box.innerHTML=h}text(r,'[data-b46-label="today"]',`Live Summary · ${dateLabel(d.tk)}`);text(r,'[data-b46-label="yesterday"]',`Final Summary · ${dateLabel(d.yk)}`)}
async function json(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw Error(`${url}:${r.status}`);return r.json()}
async function refresh(){if(busy)return;busy=true;try{const [st,sg]=await Promise.all([json('/api/engine/statistics'),json('/api/engine/signals')]);if(st?.ok!==true||!Array.isArray(st?.rows))throw Error('STATISTICS_SHAPE');if(!Array.isArray(sg?.signals))throw Error('SIGNALS_SHAPE');lastGood=aggregate(st.rows,sg.signals);render(lastGood)}catch(e){if(lastGood)render(lastGood);console.warn('B46 Daily Performance refresh skipped:',e?.message||e)}finally{busy=false}}
function boot(){ensure();refresh();setInterval(refresh,REFRESH);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
