import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { inspect,activeVersion,getVersion,api,script,sha,canonical,publicFile,backend,directOrigin,literals } from './production.mjs';
import { schedules,stageCurrentRail,verifyRailBase,wrangler } from './rail.mjs';

const BRANCH='work/ball46-daily-performance-20261005',TARGET='index.html',MARK='B46_DAILY_PERFORMANCE_20261005';
const deploy=process.env.DEPLOY_ENABLED==='true';
mkdirSync('audit',{recursive:true});
const report={run:process.env.GITHUB_RUN_ID,commit:process.env.GITHUB_SHA,branch:process.env.GITHUB_REF_NAME,startedAt:new Date().toISOString(),scope:'Add Daily Performance card immediately after .main-board .board-toolbar. Inline CSS/JS only. Old scorebar, engine, APIs, settlement and all unrelated static assets remain unchanged.'};
const save=()=>writeFileSync('audit/daily-performance-report.json',JSON.stringify(report,null,2));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const nodeCheck=path=>{const r=spawnSync(process.execPath,['--check',path],{encoding:'utf8'});if(r.stdout)process.stdout.write(r.stdout);if(r.stderr)process.stderr.write(r.stderr);assert(!r.error&&r.status===0,`NODE_CHECK_FAILED:${path}:${r.error?.message||r.status}`)};
let current=null,candidate=null;
async function rollback(){if(!current)return;const active=await activeVersion();if(active===current.restore.version){report.rollback={status:'base-still-active',version:active};save();return}if(candidate&&active!==candidate){report.rollback={status:'skipped-foreign-active',version:active};save();return}await api(`/scripts/${script}/deployments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({strategy:'percentage',versions:[{version_id:current.restore.version,percentage:100}],annotations:{'workers/message':`Rollback Daily Performance ${report.run}`}})});assert.equal(await activeVersion(),current.restore.version,'ROLLBACK_NOT_CONFIRMED');report.rollback={status:'confirmed',version:current.restore.version};save()}
function inject(before,css,js){assert(before.includes('<div class="board-toolbar">'),'SEARCH_TOOLBAR_ANCHOR_MISSING');assert(before.includes('data-board-sections'),'BOARD_SECTIONS_ANCHOR_MISSING');assert(!before.includes(MARK),'DAILY_PERFORMANCE_ALREADY_LIVE_STOP');assert.equal((before.match(/<\/head>/g)||[]).length,1,'HEAD_CLOSE_COUNT_BAD');assert.equal((before.match(/<\/body>/g)||[]).length,1,'BODY_CLOSE_COUNT_BAD');const style=`\n<!-- ${MARK} STYLE START -->\n<style id="b46-daily-performance-style">\n${css}\n</style>\n<!-- ${MARK} STYLE END -->\n`,scriptBlock=`\n<!-- ${MARK} SCRIPT START -->\n<script id="b46-daily-performance-runtime">\n${js}\n</script>\n<!-- ${MARK} SCRIPT END -->\n`;const after=before.replace('</head>',style+'</head>').replace('</body>',scriptBlock+'</body>');assert(after.includes(MARK)&&after.includes('ball46-daily-performance'),'INJECTION_MARKER_MISSING');const restored=after.replace(style,'').replace(scriptBlock,'');assert.equal(restored,before,'INJECTION_NOT_REVERSIBLE');return after}
try{
  assert.equal(process.env.GITHUB_REF_NAME,BRANCH,'UNCONFIRMED_BRANCH_STOP');
  const css=readFileSync('card.css','utf8'),js=readFileSync('card.js','utf8');assert(css.includes(MARK),'CSS_MARKER_MISSING');assert(js.includes(MARK),'JS_MARKER_MISSING');writeFileSync('audit/card.js',js);nodeCheck('audit/card.js');
  current=await inspect();const base=current.restore.version;report.baseVersion=base;report.backendBefore=current.restore.backend;
  const settingsBefore=await api(`/scripts/${script}/settings`),settingsSha=sha(canonical(settingsBefore)),cronsBefore=await schedules();
  const beforeBytes=await publicFile('/index.html','html'),before=beforeBytes.toString('utf8'),beforeSha=sha(beforeBytes);writeFileSync('audit/index-before.html',beforeBytes);report.indexBeforeSha=beforeSha;
  const beforeLiterals=literals(current.source),owners=[...beforeLiterals].filter(([,lit])=>sha(Buffer.from(lit.value))===beforeSha);assert.equal(owners.length,1,`INDEX_OWNER_MATCH_COUNT:${owners.length}`);const [ownerName,owner]=owners[0];report.indexOwnerLiteral=ownerName;
  const after=inject(before,css,js),afterBytes=Buffer.from(after),afterSha=sha(afterBytes);writeFileSync('audit/index-after.html',afterBytes);report.indexAfterSha=afterSha;
  const patchedSource=current.source.slice(0,owner.start)+JSON.stringify(after)+current.source.slice(owner.end);writeFileSync('audit/worker-after.js',patchedSource);nodeCheck('audit/worker-after.js');
  const patchedLiterals=literals(patchedSource),patchedOwner=patchedLiterals.get(ownerName);assert(patchedOwner,'PATCHED_INDEX_OWNER_MISSING');assert.equal(sha(Buffer.from(patchedOwner.value)),afterSha,'PATCHED_INDEX_OWNER_SHA_BAD');for(const [name,lit] of beforeLiterals){if(name===ownerName)continue;const next=patchedLiterals.get(name);assert(next,`LITERAL_REMOVED:${name}`);assert.equal(sha(Buffer.from(next.value)),sha(Buffer.from(lit.value)),`UNRELATED_LITERAL_CHANGED:${name}`)}
  const staged=await stageCurrentRail(current.version,settingsBefore,cronsBefore,patchedSource);await verifyRailBase(staged);assert.equal(staged.hashes[TARGET],beforeSha,'STAGED_INDEX_NOT_CURRENT');const protectedAssets={...staged.hashes};delete protectedAssets[TARGET];writeFileSync(resolve(staged.runtime,'assets',TARGET),afterBytes);assert.equal(sha(readFileSync(resolve(staged.runtime,'assets',TARGET))),afterSha,'STAGED_INDEX_SHA_BAD');report.protectedAssetCount=Object.keys(protectedAssets).length;save();
  wrangler(staged,true);assert.equal(await activeVersion(),base,'PRODUCTION_MOVED_AFTER_DRY_RUN');assert.equal(sha(canonical(await api(`/scripts/${script}/settings`))),settingsSha,'SETTINGS_MOVED_BEFORE_DEPLOY');assert.equal(canonical(await backend()),canonical(report.backendBefore),'BACKEND_MOVED_BEFORE_DEPLOY');await verifyRailBase(staged);
  if(!deploy){report.result='PREVIEW_SUCCESS_NO_DEPLOY';report.finalVersion=base;report.completedAt=new Date().toISOString();save();console.log('BALL46_DAILY_PERFORMANCE_PREVIEW_PASS');process.exit(0)}
  try{
    wrangler(staged);for(let i=0;i<30;i++){const a=await activeVersion();if(a!==base){candidate=a;break}await delay(1200)}assert(candidate,'NO_NEW_PRODUCTION_VERSION');report.candidateVersion=candidate;save();
    let directOk=false;for(let i=0;i<36;i++){assert.equal(await activeVersion(),candidate,'PRODUCTION_MOVED_DURING_DIRECT_VERIFY');try{const b=await publicFile('/index.html','html',directOrigin);if(sha(b)===afterSha&&b.toString('utf8').includes(MARK)){directOk=true;break}}catch{}await delay(1250)}assert(directOk,'DAILY_PERFORMANCE_NOT_DIRECT_PRODUCTION');
    let publicOk=false,lastPublicSha=null;for(let i=0;i<35;i++){assert.equal(await activeVersion(),candidate,'PRODUCTION_MOVED_DURING_PUBLIC_VERIFY');try{const b=await publicFile('/index.html','html');lastPublicSha=sha(b);if(lastPublicSha===afterSha&&b.toString('utf8').includes(MARK)){publicOk=true;break}}catch{}await delay(1500)}assert(publicOk,'DAILY_PERFORMANCE_NOT_PUBLIC');report.publicSha=lastPublicSha;
    const diff={};for(const [p,h] of Object.entries(protectedAssets)){const got=sha(await publicFile('/'+p));if(got!==h)diff[p]={expected:h,got}}assert.equal(Object.keys(diff).length,0,`UNRELATED_ASSETS_CHANGED:${JSON.stringify(diff)}`);
    const [boardJson,signalsJson,statsJson]=await Promise.all(['/api/engine/board','/api/engine/signals','/api/engine/statistics'].map(async p=>JSON.parse(await publicFile(p,'json'))));assert(boardJson?.ok===true&&Array.isArray(boardJson.fixtures),'BOARD_API_UNHEALTHY');assert(Array.isArray(signalsJson?.signals),'SIGNALS_API_UNHEALTHY');assert(statsJson?.ok===true&&Array.isArray(statsJson.rows),'STATISTICS_API_UNHEALTHY');report.apiCounts={fixtures:boardJson.fixtures.length,signals:signalsJson.signals.length,settled:statsJson.rows.length};
    assert.equal(canonical(await backend()),canonical(report.backendBefore),'BACKEND_CHANGED');assert.equal(sha(canonical(await api(`/scripts/${script}/settings`))),settingsSha,'SETTINGS_CHANGED');assert.equal(canonical(await schedules()),canonical(cronsBefore),'CRONS_CHANGED');
    const cv=await getVersion(candidate),cm=cv.modules.find(m=>m.name===cv.main_module);assert(cm,'FINAL_MAIN_MISSING');const finalSource=Buffer.from(cm.content_base64,'base64').toString('utf8'),finalLiterals=literals(finalSource),finalOwner=finalLiterals.get(ownerName);assert(finalOwner,'FINAL_INDEX_OWNER_MISSING');assert.equal(sha(Buffer.from(finalOwner.value)),afterSha,'FINAL_INDEX_OWNER_SHA_BAD');for(const [name,lit] of beforeLiterals){if(name===ownerName)continue;const next=finalLiterals.get(name);assert(next,`FINAL_LITERAL_REMOVED:${name}`);assert.equal(sha(Buffer.from(next.value)),sha(Buffer.from(lit.value)),`FINAL_UNRELATED_LITERAL_CHANGED:${name}`)}
    assert.equal(await activeVersion(),candidate,'FINAL_PRODUCTION_MOVED');report.finalVersion=candidate;report.result='SUCCESS';report.backendUntouched=true;report.oldScorebarAssetsUntouched=true;report.unrelatedStaticAssetsUntouched=true;report.completedAt=new Date().toISOString();save();console.log(`FINAL_PRODUCTION=${candidate}`);console.log(`INDEX_SHA=${afterSha}`);console.log('BALL46_DAILY_PERFORMANCE_SUCCESS');
  }catch(e){report.error=e.message;try{await rollback()}catch(rb){report.rollbackError=rb.message;save()}throw e}
}catch(e){report.result='FAIL_STOPPED';report.error=e.message;report.completedAt=new Date().toISOString();save();console.error(e.stack);process.exitCode=1}
