import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { inspect,activeVersion,getVersion,api,script,sha,canonical,publicFile,backend,directOrigin,literals } from './production.mjs';
import { schedules,stageCurrentRail,verifyRailBase,wrangler } from './rail.mjs';
const BRANCH='work/ball46-daily-performance-20261005',TARGET='index.html',MARK='B46_DAILY_PERFORMANCE_20261005',BG_PLACEHOLDER='__B46_PERFORMANCE_BG_DATA__';
const deploy=process.env.DEPLOY_ENABLED==='true';mkdirSync('audit',{recursive:true});
const report={run:process.env.GITHUB_RUN_ID,commit:process.env.GITHUB_SHA,branch:process.env.GITHUB_REF_NAME,startedAt:new Date().toISOString(),scope:'Asset-only index.html refresh: Daily Performance visual fix using approved mockup-derived embedded WebP, light-mode contrast hardening, centered/fitted background, and ~40% larger/heavier market breakdown. Worker source, old scorebar, engine, APIs, settlement and all other public assets remain unchanged.'};
const save=()=>writeFileSync('audit/daily-performance-report.json',JSON.stringify(report,null,2)),delay=ms=>new Promise(r=>setTimeout(r,ms));
const nodeCheck=p=>{const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.stdout)process.stdout.write(r.stdout);if(r.stderr)process.stderr.write(r.stderr);assert(!r.error&&r.status===0,`NODE_CHECK_FAILED:${p}:${r.error?.message||r.status}`)};
let current=null,candidate=null;
async function rollback(){if(!current)return;const a=await activeVersion();if(a===current.restore.version){report.rollback={status:'base-still-active',version:a};save();return}if(candidate&&a!==candidate){report.rollback={status:'skipped-foreign-active',version:a};save();return}await api(`/scripts/${script}/deployments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({strategy:'percentage',versions:[{version_id:current.restore.version,percentage:100}],annotations:{'workers/message':`Rollback Daily Performance ${report.run}`}})});assert.equal(await activeVersion(),current.restore.version,'ROLLBACK_NOT_CONFIRMED');report.rollback={status:'confirmed',version:current.restore.version};save()}
function blocks(css,js){return{style:`\n<!-- ${MARK} STYLE START -->\n<style id="b46-daily-performance-style">\n${css}\n</style>\n<!-- ${MARK} STYLE END -->\n`,scriptBlock:`\n<!-- ${MARK} SCRIPT START -->\n<script id="b46-daily-performance-runtime">\n${js}\n</script>\n<!-- ${MARK} SCRIPT END -->\n`}}
function refreshInjection(before,css,js){
 assert(before.includes('<div class="board-toolbar">'),'SEARCH_TOOLBAR_ANCHOR_MISSING');assert(before.includes('data-board-sections'),'BOARD_SECTIONS_ANCHOR_MISSING');assert.equal((before.match(/<\/head>/g)||[]).length,1,'HEAD_CLOSE_COUNT_BAD');assert.equal((before.match(/<\/body>/g)||[]).length,1,'BODY_CLOSE_COUNT_BAD');
 const styleRe=new RegExp(`\\n?<!-- ${MARK} STYLE START -->[\\s\\S]*?<!-- ${MARK} STYLE END -->\\n?`),scriptRe=new RegExp(`\\n?<!-- ${MARK} SCRIPT START -->[\\s\\S]*?<!-- ${MARK} SCRIPT END -->\\n?`);const hasStyle=styleRe.test(before),hasScript=scriptRe.test(before);assert.equal(hasStyle,hasScript,'PARTIAL_EXISTING_PERFORMANCE_BLOCK');
 const clean=before.replace(styleRe,'').replace(scriptRe,'');const {style,scriptBlock}=blocks(css,js);const after=clean.replace('</head>',style+'</head>').replace('</body>',scriptBlock+'</body>');
 assert(after.includes(MARK)&&after.includes('ball46-daily-performance'),'INJECTION_MARKER_MISSING');assert.equal((after.match(new RegExp(`${MARK} STYLE START`,'g'))||[]).length,1,'STYLE_BLOCK_COUNT_BAD');assert.equal((after.match(new RegExp(`${MARK} SCRIPT START`,'g'))||[]).length,1,'SCRIPT_BLOCK_COUNT_BAD');return{after,mode:hasStyle?'replace':'insert'}
}
try{
 assert.equal(process.env.GITHUB_REF_NAME,BRANCH,'UNCONFIRMED_BRANCH_STOP');
 const bg64=readFileSync('ball46-daily-performance-bg-20261005.webp.b64','utf8').trim();assert(/^[A-Za-z0-9+/=]+$/.test(bg64)&&bg64.length>5000,'BACKGROUND_B64_INVALID');const bg=Buffer.from(bg64,'base64');assert.equal(bg.subarray(0,4).toString('ascii'),'RIFF','BACKGROUND_RIFF_MISSING');assert.equal(bg.subarray(8,12).toString('ascii'),'WEBP','BACKGROUND_WEBP_MISSING');report.backgroundBytes=bg.length;report.backgroundSha=sha(bg);
 const cssTemplate=readFileSync('card.css','utf8'),js=readFileSync('card.js','utf8');assert(cssTemplate.includes(MARK),'CSS_MARKER_MISSING');assert(js.includes(MARK),'JS_MARKER_MISSING');assert.equal((cssTemplate.match(new RegExp(BG_PLACEHOLDER,'g'))||[]).length,1,'BACKGROUND_PLACEHOLDER_COUNT_BAD');const css=cssTemplate.replace(BG_PLACEHOLDER,`data:image/webp;base64,${bg64}`);assert(css.includes('VISUAL_FIX_20261005'),'VISUAL_FIX_MARKER_MISSING');assert(css.includes('font-size:8.4px')&&css.includes('font-weight:850'),'MARKET_40_PERCENT_RULE_MISSING');assert(css.includes('html[data-theme="light"]'),'LIGHT_MODE_OVERRIDE_MISSING');writeFileSync('audit/card.js',js);writeFileSync('audit/card.css',css);nodeCheck('audit/card.js');
 current=await inspect();const base=current.restore.version;report.baseVersion=base;report.backendBefore=current.restore.backend;const workerBeforeSha=sha(Buffer.from(current.source)),beforeLiterals=literals(current.source);report.workerBeforeSha=workerBeforeSha;
 const settingsBefore=await api(`/scripts/${script}/settings`),settingsSha=sha(canonical(settingsBefore)),cronsBefore=await schedules();
 const beforeBytes=await publicFile('/index.html','html'),before=beforeBytes.toString('utf8'),beforeSha=sha(beforeBytes);writeFileSync('audit/index-before.html',beforeBytes);report.indexBeforeSha=beforeSha;
 const patched=refreshInjection(before,css,js);report.injectionMode=patched.mode;const afterBytes=Buffer.from(patched.after),afterSha=sha(afterBytes);writeFileSync('audit/index-after.html',afterBytes);report.indexAfterSha=afterSha;
 const staged=await stageCurrentRail(current.version,settingsBefore,cronsBefore,current.source);await verifyRailBase(staged);assert.equal(staged.hashes[TARGET],beforeSha,'STAGED_INDEX_NOT_CURRENT');const protectedAssets={...staged.hashes};delete protectedAssets[TARGET];writeFileSync(resolve(staged.runtime,'assets',TARGET),afterBytes);assert.equal(sha(readFileSync(resolve(staged.runtime,'assets',TARGET))),afterSha,'STAGED_INDEX_SHA_BAD');report.protectedAssetCount=Object.keys(protectedAssets).length;save();
 wrangler(staged,true);assert.equal(await activeVersion(),base,'PRODUCTION_MOVED_AFTER_DRY_RUN');assert.equal(sha(canonical(await api(`/scripts/${script}/settings`))),settingsSha,'SETTINGS_MOVED_BEFORE_DEPLOY');assert.equal(canonical(await backend()),canonical(report.backendBefore),'BACKEND_MOVED_BEFORE_DEPLOY');await verifyRailBase(staged);
 if(!deploy){report.result='PREVIEW_SUCCESS_NO_DEPLOY';report.finalVersion=base;report.completedAt=new Date().toISOString();save();console.log('BALL46_DAILY_PERFORMANCE_PREVIEW_PASS');process.exit(0)}
 try{
  wrangler(staged);for(let i=0;i<30;i++){const a=await activeVersion();if(a!==base){candidate=a;break}await delay(1200)}assert(candidate,'NO_NEW_PRODUCTION_VERSION');report.candidateVersion=candidate;save();
  let directOk=false;for(let i=0;i<36;i++){assert.equal(await activeVersion(),candidate,'PRODUCTION_MOVED_DURING_DIRECT_VERIFY');try{const b=await publicFile('/index.html','html',directOrigin);const t=b.toString('utf8');if(sha(b)===afterSha&&t.includes('VISUAL_FIX_20261005')&&t.includes('data:image/webp;base64,')){directOk=true;break}}catch{}await delay(1250)}assert(directOk,'DAILY_PERFORMANCE_VISUAL_FIX_NOT_DIRECT_PRODUCTION');
  let publicOk=false,lastPublicSha=null;for(let i=0;i<35;i++){assert.equal(await activeVersion(),candidate,'PRODUCTION_MOVED_DURING_PUBLIC_VERIFY');try{const b=await publicFile('/index.html','html');const t=b.toString('utf8');lastPublicSha=sha(b);if(lastPublicSha===afterSha&&t.includes('VISUAL_FIX_20261005')&&t.includes('font-size:8.4px')&&t.includes('html[data-theme="light"]')){publicOk=true;break}}catch{}await delay(1500)}assert(publicOk,'DAILY_PERFORMANCE_VISUAL_FIX_NOT_PUBLIC');report.publicSha=lastPublicSha;
  const diff={};for(const [p,h] of Object.entries(protectedAssets)){const got=sha(await publicFile('/'+p));if(got!==h)diff[p]={expected:h,got}}assert.equal(Object.keys(diff).length,0,`UNRELATED_ASSETS_CHANGED:${JSON.stringify(diff)}`);
  const [boardJson,signalsJson,statsJson]=await Promise.all(['/api/engine/board','/api/engine/signals','/api/engine/statistics'].map(async p=>JSON.parse(await publicFile(p,'json'))));assert(boardJson?.ok===true&&Array.isArray(boardJson.fixtures),'BOARD_API_UNHEALTHY');assert(Array.isArray(signalsJson?.signals),'SIGNALS_API_UNHEALTHY');assert(statsJson?.ok===true&&Array.isArray(statsJson.rows),'STATISTICS_API_UNHEALTHY');report.apiCounts={fixtures:boardJson.fixtures.length,signals:signalsJson.signals.length,settled:statsJson.rows.length};
  assert.equal(canonical(await backend()),canonical(report.backendBefore),'BACKEND_CHANGED');assert.equal(sha(canonical(await api(`/scripts/${script}/settings`))),settingsSha,'SETTINGS_CHANGED');assert.equal(canonical(await schedules()),canonical(cronsBefore),'CRONS_CHANGED');
  const cv=await getVersion(candidate),cm=cv.modules.find(m=>m.name===cv.main_module);assert(cm,'FINAL_MAIN_MISSING');const finalSource=Buffer.from(cm.content_base64,'base64').toString('utf8');assert.equal(sha(Buffer.from(finalSource)),workerBeforeSha,'WORKER_SOURCE_CHANGED');const finalLiterals=literals(finalSource);for(const [name,lit] of beforeLiterals){const next=finalLiterals.get(name);assert(next,`FINAL_LITERAL_REMOVED:${name}`);assert.equal(sha(Buffer.from(next.value)),sha(Buffer.from(lit.value)),`FINAL_LITERAL_CHANGED:${name}`)}
  assert.equal(await activeVersion(),candidate,'FINAL_PRODUCTION_MOVED');report.finalVersion=candidate;report.result='SUCCESS';report.workerSourceUntouched=true;report.backendUntouched=true;report.oldScorebarAssetsUntouched=true;report.unrelatedStaticAssetsUntouched=true;report.completedAt=new Date().toISOString();save();console.log(`FINAL_PRODUCTION=${candidate}`);console.log(`INDEX_SHA=${afterSha}`);console.log(`BACKGROUND_SHA=${report.backgroundSha}`);console.log('BALL46_DAILY_PERFORMANCE_VISUAL_FIX_SUCCESS');
 }catch(e){report.error=e.message;try{await rollback()}catch(rb){report.rollbackError=rb.message;save()}throw e}
}catch(e){report.result='FAIL_STOPPED';report.error=e.message;report.completedAt=new Date().toISOString();save();console.error(e.stack);process.exitCode=1}
