(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pair=p=>`${p?.home??'—'}–${p?.away??'—'}`;
  const fmtLine=v=>v==null?'—':`${Number(v)>0?'+':''}${Number(v).toFixed(2)}`;
  const fmtOdds=v=>v==null?'—':Number(v).toFixed(2);
  const sideKey=v=>String(v||'home').toLowerCase()==='away'?'away':'home';
  const sideLabel=v=>sideKey(v).toUpperCase();
  const sidePressureKey=v=>sideKey(v)==='away'?'awayPressure':'homePressure';
  const compactAge=s=>s?.priceAgeSeconds!=null?`${Number(s.priceAgeSeconds).toFixed(0)}s`:'—';
  const signalLock=m=>m?.signalStatus==='LOCKED'&&m?.signalLock?.status==='LOCKED'?m.signalLock:null;
  const when=s=>{try{return new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});}catch{return '—';}};
  const sourceValue=s=>s?.status==='PASS'||s?.line!=null||s?.odds!=null?`${s.status||'WAIT'} · ${s.bookmaker||'—'} · ${fmtLine(s.line)} @ ${fmtOdds(s.odds)} · ${compactAge(s)}`:'N/A';
  const compactSourceRow=s=>`<span class="price-source-row ${s?.status==='PASS'?'is-pass':'is-wait'}"><span class="price-source-name">S${s?.position||1} · ${esc(s?.source||'5USD')}</span><span class="price-source-value">${esc(sourceValue(s))}</span></span>`;
  const compactSelectedRow=(s,side)=>`<span class="price-selected-row ${s?'has-price':'is-na'}"><span class="price-selected-name">PRICE REFERENCE</span><span class="price-selected-value">${s?esc(`${s.source||'5USD'} · ${s.bookmaker||'—'} · ${sideLabel(s.side||side)} ${fmtLine(s.line)} @ ${fmtOdds(s.odds)} · ${compactAge(s)}`):'N/A'}</span></span>`;
  const pill=(ok,text)=>`<b class="${ok?'ok':'wait'}">${esc(text)}</b>`;
  function renderChecks(checks={},evidence={},side='home'){
    const label=sideLabel(side); const labels={homeOnly:'HOME selected',awayOnly:'AWAY selected',minute:'Minute window',score:'Score filter',hunger:`${label} hunger trend`,evidence:evidence.required===false?`New ${label} event (optional)`:`New ${label} event`,market:'Full Match Live AH'};
    return Object.entries(checks).map(([k,v])=>`<div class="check"><span>${esc(labels[k]||k)}</span>${pill(Boolean(v),v?'PASS':'WAIT')}</div>`).join('');
  }
  function detail(m){
    const side=sideKey(m.side),label=sideLabel(side),pressureKey=sidePressureKey(side),s=m.stats||{},rolling=m.rolling||{},recent=rolling.recent||{},previous=rolling.previous||{},eventDelta=recent.delta||{};
    const sources=Array.isArray(m.priceSources)?m.priceSources:[],selected=m.selectedPrice||sources.find(x=>x.status==='PASS')||null,locked=signalLock(m),share=rolling.sides?.[side]?.pressureShare;
    const lock=locked?`<section class="detail-card"><h3>SIGNAL LOCK · LOCKED</h3><div class="check"><span>Entry minute / score</span><b>${locked.minute??'—'}′ · ${pair(locked.entryScore)}</b></div><div class="check"><span>Locked ${sideLabel(locked.selection)} AH / odds</span><b>${fmtLine(locked.line)} @ ${fmtOdds(locked.odds)}</b></div><div class="check"><span>Price reference</span><b>${esc(locked.oddsSource||'—')} · ${esc(locked.bookmaker||'—')}</b></div></section>`:'';
    return `<div class="match-detail">${lock}<section class="detail-card"><h3>${label} ROLLING DELTA · ${rolling.windowMinutes??'—'} MIN</h3><div class="evidence"><div><span>ATTACK</span><b>${pair(s.attacks)}</b></div><div><span>DANGER</span><b>${pair(s.dangerousAttack)}</b></div><div><span>SHOT OFF</span><b>${pair(s.shotsOff)}</b></div><div><span>SHOT ON</span><b>${pair(s.shotsOn)}</b></div><div><span>CORNERS</span><b>${pair(s.corners)}</b></div><div><span>POSSESSION</span><b>${pair(s.possession)}</b></div><div><span>Δ SOT / OFF / COR</span><b>${eventDelta.shotsOn?.[side]??'—'} / ${eventDelta.shotsOff?.[side]??'—'} / ${eventDelta.corners?.[side]??'—'}</b></div><div><span>HUNGER</span><b>${m.hunger?.passedCount??0} / ${m.hunger?.total??3}</b></div></div></section><section class="detail-card"><h3>PRESSURE TREND</h3><div class="check"><span>${label} pressure · recent / previous</span><b>${recent[pressureKey]??'—'} / ${previous[pressureKey]??'—'}</b></div><div class="check"><span>${label} pressure share</span><b>${share!=null?Number(share).toFixed(1)+'%':'—'}</b></div><div class="check"><span>Match tempo · recent / previous</span><b>${recent.tempo??'—'} / ${previous.tempo??'—'}</b></div></section><section class="detail-card"><h3>DETECTOR CHECK</h3>${renderChecks(m.checks,m.evidence,side)}</section><section class="detail-card"><h3>PRICE CHECK</h3>${sources.map(x=>`<div class="check"><span>SOURCE ${x.position||1} · ${esc(x.source||'5USD')}</span><b class="${x.status==='PASS'?'ok':'wait'}">${esc(sourceValue(x))}</b></div>`).join('')}<div class="check"><span>PRICE REFERENCE · ${label}</span><b class="${selected?'ok':'wait'}">${selected?esc(sourceValue(selected)):'N/A'}</b></div></section></div>`;
  }
  function row(m){
    const side=sideKey(m.side),state=m.state||'WATCHING',locked=Boolean(signalLock(m)),detectorStyle=state==='SIGNAL'?'signal':state==='NEAR SIGNAL'?'near':'',rowStyle=locked||state==='SIGNAL'?'signal':detectorStyle,sources=Array.isArray(m.priceSources)?m.priceSources:[],selected=m.selectedPrice||sources.find(x=>x.status==='PASS')||null;
    const pressure=m.rolling?.recent?.[sidePressureKey(side)]??'—',sot=m.rolling?.recent?.delta?.shotsOn?.[side]??0;
    return `<details class="match-wrap ${rowStyle}" data-state="${esc(state)}" data-search="${esc(`${m.home} ${m.away} ${m.league}`.toLowerCase())}"><summary class="match-row"><div class="statebox"><span class="state ${detectorStyle}">● ${esc(state)}</span>${locked?'<span class="state signal">◆ LOCKED</span>':''}<span class="minute">${m.minute??'—'}′</span></div><div class="match-main"><span class="league">${esc(m.league||'—')}</span><span class="teams">${esc(m.home||'Home')} — ${esc(m.away||'Away')}</span></div><div class="score">${pair(m.score)}</div><div class="quick"><div class="q"><span>${sideLabel(side)} PRESS</span><b>${pressure}</b></div><div class="q"><span>SOT</span><b>+${sot}</b></div><div class="q"><span>HUNGER</span><b>${m.hunger?.passedCount??0}/3</b></div></div><div class="market"><span class="price-stack">${sources.map(compactSourceRow).join('')}${compactSelectedRow(selected,side)}</span></div><div class="cond"><span>CHECKS</span><strong class="${m.passed===m.total?'pass':m.passed>=5?'warn':''}">${m.passed??0}/${m.total??6}</strong></div></summary>${detail(m)}</details>`;
  }
  function filters(){
    const tabs=[...document.querySelectorAll('.tabs .tab')],search=document.querySelector('.search input');
    const apply=()=>{const active=tabs.find(x=>x.dataset.active==='1')?.textContent.trim().toUpperCase()||'ALL',q=(search?.value||'').trim().toLowerCase();document.querySelectorAll('.match-wrap').forEach(el=>{const st=el.dataset.state||'';const stateOk=active==='ALL'||(active==='SIGNAL'?st==='SIGNAL':active==='NEAR'?st==='NEAR SIGNAL':st===active);el.style.display=stateOk&&(!q||el.dataset.search.includes(q))?'':'none';});};
    tabs.forEach((b,i)=>{b.dataset.active=i===0?'1':'0';b.addEventListener('click',()=>{tabs.forEach(x=>x.dataset.active='0');b.dataset.active='1';apply();});}); if(search)search.addEventListener('input',apply);
  }
  async function start(){
    filters(); const list=document.querySelector('.match-list'),metric=[...document.querySelectorAll('.status-grid .metric strong')],pill=document.querySelector('.source-pill');
    try{const d=await window.NOMAD341Clone.getFeed(); metric[0].textContent=d.counts?.live??0;metric[1].textContent=d.counts?.watching??0;metric[2].textContent=d.counts?.near??0;metric[3].textContent=d.counts?.signal??0; list.innerHTML=(d.matches||[]).map(row).join('')||'<div class="note">No matches.</div>'; const muted=document.querySelector('.panel-head .muted');if(muted)muted.textContent=`updated ${when(d.updatedAt)}`; if(pill)pill.innerHTML=`<span class="dot"></span>${window.NOMAD341Clone.mode()==='5USD'?'5USD DATA · READY':'UI CLONE · MOCK DATA'}`; const note=document.querySelector('[data-clone-note]');if(note)note.textContent='Clean UI clone is running without the legacy 3.41 engine. Data is supplied through the normalized adapter contract.';}catch(e){if(list)list.innerHTML=`<div class="note">UI data adapter unavailable: ${esc(e.message)}</div>`;}
  }
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
