(()=>{'use strict';
const WORKER='https://nomadtips3-test-api.mccarey-supon.workers.dev',PATH='/production-live-config',KEY='nomadtips3.car1.owner-key';
const ids=['side','minuteMin','minuteMax','market','oddsMin','oddsMax','ahMin','ahMax','momentumMin','gapMode','maxGoalGap','confirmationRounds','limitMode','maxSignalsPerDay'];const $=id=>document.getElementById(id);let state=null;
const key=()=>sessionStorage.getItem(KEY)||'';const optional=id=>$(id).value.trim()===''?null:Number($(id).value);const line=v=>v===null?'ไม่จำกัด':`${Number(v)>=0?'+':''}${v}`;
function read(){const a=Number($('minuteMin').value),b=Number($('minuteMax').value);if(!Number.isFinite(a)||!Number.isFinite(b)||a>=b)throw Error('นาทีเริ่มต้องน้อยกว่านาทีสิ้นสุด');return{side:$('side').value,minuteMin:a,minuteMax:b,market:$('market').value,oddsMin:Number($('oddsMin').value),oddsMax:optional('oddsMax'),ahMin:Number($('ahMin').value),ahMax:optional('ahMax'),momentumMin:Number($('momentumMin').value),goalGapLimited:$('gapMode').value==='LIMITED',maxGoalGap:Number($('maxGoalGap').value),confirmationRounds:Number($('confirmationRounds').value),signalLimitEnabled:$('limitMode').value==='LIMITED',maxSignalsPerDay:Number($('maxSignalsPerDay').value)}}
function summary(c){if(!c)return'—';const side=c.side==='BOTH'?'ทั้งสองทีม':c.side==='AWAY'?'ทีมเยือน':'ทีมเจ้าบ้าน',market=c.market==='AH'?'Asian Handicap':'ชนะตรง',gap=c.goalGapLimited?`ผลต่าง ≤ ${c.maxGoalGap} ลูก`:'ทุกสกอร์',limit=c.signalLimitEnabled?`สูงสุด ${c.maxSignalsPerDay} สัญญาณ/วัน`:'สัญญาณไม่จำกัด';return`${side} · นาที ${c.minuteMin}–${c.minuteMax} · ${market} · Odds ${Number(c.oddsMin).toFixed(2)}–${c.oddsMax===null?'ไม่จำกัด':Number(c.oddsMax).toFixed(2)} · AH ${line(c.ahMin)}–${line(c.ahMax)} · บุก ≥ ${c.momentumMin}% · ${gap} · ยืนยัน ${c.confirmationRounds} รอบ · ${limit}`}
function disabled(){ $('maxGoalGap').disabled=$('gapMode').value!=='LIMITED';$('maxSignalsPerDay').disabled=$('limitMode').value!=='LIMITED'}
function fill(c){if(!c)return;$('side').value=c.side;$('minuteMin').value=c.minuteMin;$('minuteMax').value=c.minuteMax;$('market').value=c.market;$('oddsMin').value=c.oddsMin;$('oddsMax').value=c.oddsMax??'';$('ahMin').value=c.ahMin;$('ahMax').value=c.ahMax??'';$('momentumMin').value=c.momentumMin;$('gapMode').value=c.goalGapLimited?'LIMITED':'UNLIMITED';$('maxGoalGap').value=c.maxGoalGap;$('confirmationRounds').value=c.confirmationRounds;$('limitMode').value=c.signalLimitEnabled?'LIMITED':'UNLIMITED';$('maxSignalsPerDay').value=c.maxSignalsPerDay;disabled();draft()}
function draft(){try{$('draftSummary').textContent=summary(read())}catch(e){$('draftSummary').textContent=e.message}}function msg(t,g=false){$('message').textContent=t;$('message').className=`message ${g?'good':'bad'}`}function busy(v){['reloadButton','defaultsButton','saveButton','runButton'].forEach(i=>$(i).disabled=v)}
async function api(method='GET',body){const r=await fetch(WORKER+PATH,{method,cache:'no-store',headers:{'Content-Type':'application/json','X-NOMAD-OWNER-KEY':key()},body:body?JSON.stringify(body):undefined}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw Error(p?.error||`HTTP ${r.status}`);return p}
function render(p){state=p;fill(p.draft||p.active||p.defaults);$('activeSummary').textContent=summary(p.active);$('dashboard').hidden=false;$('loginPanel').hidden=true}
async function load(){try{busy(true);render(await api());msg('เชื่อมเครื่องยนต์เว็บไซต์หลักแล้ว',true)}catch(e){sessionStorage.removeItem(KEY);$('dashboard').hidden=true;$('loginPanel').hidden=false;alert(`เชื่อมต่อไม่ได้: ${e.message}`)}finally{busy(false)}}
async function submit(action){try{const config=read();if(action==='run'&&!confirm('ยืนยันใช้เงื่อนไขนี้กับเครื่องยนต์เว็บไซต์หลัก nomadtips3.com/live ?'))return;busy(true);render(await api('POST',{action,config}));msg(action==='run'?'รันเงื่อนไขใหม่บนเว็บไซต์หลักแล้ว':'เซฟร่างแล้ว เครื่องยนต์ยังใช้ค่าเดิม',true)}catch(e){msg(e.message)}finally{busy(false)}}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();sessionStorage.setItem(KEY,$('ownerKey').value);load()});ids.forEach(i=>$(i).addEventListener('input',draft));$('gapMode').addEventListener('change',()=>{disabled();draft()});$('limitMode').addEventListener('change',()=>{disabled();draft()});$('reloadButton').onclick=load;$('defaultsButton').onclick=()=>fill(state?.defaults);$('saveButton').onclick=()=>submit('save');$('runButton').onclick=()=>submit('run');if(key())load();
})();
