import { DurableObject } from 'cloudflare:workers';

const VERSION='nomad343-central-market-cache-v1';
const API_BASE='https://api.5dollarfootballapi.com/v1';
const DEFAULT_HUB='https://nomadtips3-5usd-hub-343.mccarey-supon.workers.dev/snapshot';
const BOOKS=['bet365','pinnacle','crown','1xbet','12bet','interwetten','macauslot','18bet','vcbet','easybets'];
const BOOK_QUERY=BOOKS.join(',');
const MAX_PROVIDER_PER_60S=18;
const WINDOW_MS=60_000;
const LIVE_TTL_MS=180_000;
const UPCOMING_TTL_MS=30*60_000;
const MAX_FIXTURES=512;
const PROVIDER_TIMEOUT_MS=12_000;

const now=()=>Date.now();
const text=v=>String(v??'').trim();
const lower=v=>text(v).toLowerCase();
const clone=v=>v===undefined?null:JSON.parse(JSON.stringify(v));
function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0',...headers}})}
function fixtureId(f){return text(f?.fixtureId??f?.id??f?.fixture_id??f?.fixture?.id)}
function stateOf(f){const s=lower(f?.boardState??f?.status??f?.statusCode??f?.status_code);if(/finished|full[_ ]?time|ended|\bft\b|aet|penalties|\bpen\b/.test(s))return'finished';if(/live|in[_ ]?play|inplay|playing|first|second|half|\b1h\b|\b2h\b/.test(s)||/^\d+$/.test(text(f?.statusCode??f?.status_code)))return'live';return'upcoming'}
function kickoffMs(f){const raw=f?.kickoffAt??f?.kickoffUtc??f?.startAt??f?.start_time??f?.date??f?.timestamp??null;if(raw===null||raw===undefined||raw==='')return Number.MAX_SAFE_INTEGER;const n=Number(raw);if(Number.isFinite(n))return n<10_000_000_000?n*1000:n;const ms=Date.parse(String(raw));return Number.isFinite(ms)?ms:Number.MAX_SAFE_INTEGER}
function norm(v){return lower(v).replace(/[\s_-]/g,'')}
function bookmakerRows(payload){const roots=[payload?.data,payload,payload?.data?.odds,payload?.odds].filter(Boolean);for(const root of roots){if(Array.isArray(root?.bookmakers))return root.bookmakers;if(Array.isArray(root))return root}return[]}
function availableBookmakers(payload){const found=new Set();for(const row of bookmakerRows(payload)){const key=norm(row?.slug??row?.bookmaker?.slug??row?.name??row?.bookmaker?.name);if(!key)continue;for(const book of BOOKS){const target=norm(book);if(key===target||key.includes(target)||target.includes(key))found.add(book)}}return BOOKS.filter(x=>found.has(x))}
function authorizedTick(request,env){const expected=text(env.FIVEDOLLAR_API_KEY);if(!expected)return false;const auth=text(request.headers.get('authorization'));return auth===`Bearer ${expected}`}

async function hubSnapshot(env){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),PROVIDER_TIMEOUT_MS);try{const r=await fetch(text(env.HUB_SNAPSHOT_URL)||DEFAULT_HUB,{cache:'no-store',headers:{accept:'application/json'},signal:controller.signal});const j=await r.json().catch(()=>null);if(!r.ok||j?.ok!==true)throw new Error(`HUB_HTTP_${r.status}`);return j}finally{clearTimeout(timer)}}

export class CentralMarketHub extends DurableObject{
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.tickPromise=null}
  async requestTimes(at=now()){const raw=await this.ctx.storage.get('providerTimes')||[];const times=raw.filter(x=>Number.isFinite(Number(x))&&at-Number(x)<WINDOW_MS);if(times.length!==raw.length)await this.ctx.storage.put('providerTimes',times);return times}
  async reserveProvider(at=now()){const times=await this.requestTimes(at);if(times.length>=MAX_PROVIDER_PER_60S)return{ok:false,used:times.length};times.push(at);await this.ctx.storage.put('providerTimes',times);return{ok:true,used:times.length}}
  async recentIds(){return await this.ctx.storage.get('recentFixtures')||[]}
  async remember(id){const key=text(id);let ids=(await this.recentIds()).filter(x=>text(x)!==key);ids.push(key);const evicted=ids.length>MAX_FIXTURES?ids.splice(0,ids.length-MAX_FIXTURES):[];if(evicted.length)await this.ctx.storage.delete(evicted.map(x=>`fixture:${x}`));await this.ctx.storage.put('recentFixtures',ids)}
  async records(ids){const clean=[...new Set((ids||[]).map(text).filter(Boolean))];if(!clean.length)return new Map();const keys=clean.map(id=>`fixture:${id}`),raw=await this.ctx.storage.get(keys),out=new Map();for(const id of clean){const row=raw instanceof Map?raw.get(`fixture:${id}`):null;if(row)out.set(id,row)}return out}
  async providerFetch(id){if(!this.env.FIVEDOLLAR_API_KEY)throw Object.assign(new Error('FIVEDOLLAR_API_KEY_MISSING'),{status:500});const budget=await this.reserveProvider();if(!budget.ok)throw Object.assign(new Error('CENTRAL_RATE_GUARD'),{status:429});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),PROVIDER_TIMEOUT_MS);try{const url=`${API_BASE}/fixtures/${encodeURIComponent(id)}/odds?bookmakers=${encodeURIComponent(BOOK_QUERY)}`;const r=await fetch(url,{cache:'no-store',headers:{accept:'application/json',authorization:`Bearer ${this.env.FIVEDOLLAR_API_KEY}`},signal:controller.signal});const body=await r.text();let j=null;try{j=JSON.parse(body)}catch{}if(!r.ok)throw Object.assign(new Error(`5USD_HTTP_${r.status}`),{status:r.status,retryAfter:r.headers.get('retry-after')});if(!j||typeof j!=='object')throw Object.assign(new Error('5USD_INVALID_JSON'),{status:502});return j}finally{clearTimeout(timer)}}
  async refreshOne(id){const fullOdds=await this.providerFetch(id),fetchedAt=now(),record={fullOdds:clone(fullOdds),fetchedAt,availableBookmakers:availableBookmakers(fullOdds)};await this.ctx.storage.put(`fixture:${id}`,record);await this.remember(id);return record}
  async cacheOnly(id){const key=text(id);if(!key)return{ok:false,version:VERSION,error:'FIXTURE_ID_REQUIRED'};const row=await this.ctx.storage.get(`fixture:${key}`);if(!row?.fullOdds)return{ok:true,version:VERSION,fixtureId:key,available:false,cached:false,source:'CENTRAL_CACHE_MISS',fullOdds:null,fetchedAt:null,availableBookmakers:[]};return{ok:true,version:VERSION,fixtureId:key,available:true,cached:true,source:'CENTRAL_CACHE_ONLY',fullOdds:clone(row.fullOdds),fetchedAt:row.fetchedAt??null,availableBookmakers:Array.isArray(row.availableBookmakers)?row.availableBookmakers:[]}}
  async snapshot(){const ids=await this.recentIds(),rows=await this.records(ids),fixtures=[];for(const id of ids){const row=rows.get(text(id));if(!row?.fullOdds)continue;fixtures.push({fixtureId:text(id),fullOdds:clone(row.fullOdds),fetchedAt:row.fetchedAt??null,availableBookmakers:Array.isArray(row.availableBookmakers)?row.availableBookmakers:[]})}return{ok:true,component:'NOMAD343_CENTRAL_MARKET_CACHE',version:VERSION,generatedAt:now(),fixtureCount:fixtures.length,providerCallsTriggeredByViewer:0,schedulerMaxProviderCallsPer60s:MAX_PROVIDER_PER_60S,liveTtlMs:LIVE_TTL_MS,upcomingTtlMs:UPCOMING_TTL_MS,lastTick:await this.ctx.storage.get('lastTick')||null,fixtures}}
  async tick(){if(this.tickPromise)return this.tickPromise;this.tickPromise=this.runTick().finally(()=>{this.tickPromise=null});return this.tickPromise}
  async runTick(){const startedAt=now();let hub;try{hub=await hubSnapshot(this.env)}catch(error){const out={ok:false,version:VERSION,startedAt,finishedAt:now(),providerCalls:0,error:String(error?.message||error)};await this.ctx.storage.put('lastTick',out);return out}const fixtures=Array.isArray(hub.fixtures)?hub.fixtures:[],active=fixtures.map(f=>({id:fixtureId(f),state:stateOf(f),kickoff:kickoffMs(f)})).filter(x=>x.id&&x.state!=='finished'),rows=await this.records(active.map(x=>x.id)),at=now(),due=active.filter(x=>{const row=rows.get(x.id),age=row?.fetchedAt?Math.max(0,at-Number(row.fetchedAt)):Infinity;return age>=(x.state==='live'?LIVE_TTL_MS:UPCOMING_TTL_MS)});due.sort((a,b)=>{if(a.state!==b.state)return a.state==='live'?-1:1;const aa=Number(rows.get(a.id)?.fetchedAt||0),ba=Number(rows.get(b.id)?.fetchedAt||0);if(a.state==='live'&&aa!==ba)return aa-ba;if(a.kickoff!==b.kickoff)return a.kickoff-b.kickoff;return aa-ba});const used=(await this.requestTimes(at)).length,allowance=Math.max(0,Math.min(MAX_PROVIDER_PER_60S-used,due.length)),selected=due.slice(0,allowance),results=[];for(const item of selected){try{const row=await this.refreshOne(item.id);results.push({fixtureId:item.id,state:item.state,ok:true,fetchedAt:row.fetchedAt})}catch(error){const status=Number(error?.status)||null;results.push({fixtureId:item.id,state:item.state,ok:false,status,error:String(error?.message||error)});if(status===429)break}}const providerCalls=results.length;const out={ok:true,version:VERSION,startedAt,finishedAt:now(),hubVersion:hub.version??null,catalogFixtures:fixtures.length,activeFixtures:active.length,dueFixtures:due.length,selectedFixtures:selected.length,providerCalls,usedBeforeTick:used,maxProviderCallsPer60s:MAX_PROVIDER_PER_60S,results};await this.ctx.storage.put('lastTick',out);return out}
  async health(){const times=await this.requestTimes();return{ok:true,component:'NOMAD343_CENTRAL_MARKET_CACHE',version:VERSION,fixtureCount:(await this.recentIds()).length,providerCalls60s:times.length,maxProviderCalls60s:MAX_PROVIDER_PER_60S,viewerProviderCalls:0,lastTick:await this.ctx.storage.get('lastTick')||null}}
  async fetch(request){const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/health')return json(await this.health());if(request.method==='GET'&&url.pathname==='/cache-snapshot')return json(await this.snapshot());if(request.method==='GET'&&url.pathname==='/fixture-odds-cache')return json(await this.cacheOnly(url.searchParams.get('fixtureId')));if(request.method==='POST'&&url.pathname==='/scheduler-tick')return json(await this.tick());return json({ok:false,version:VERSION,error:'NOT_FOUND'},404)}
}

function stub(env){const id=env.CENTRAL_MARKET.idFromName('global');return env.CENTRAL_MARKET.get(id)}
export default{
  async fetch(request,env){const url=new URL(request.url),s=stub(env);if(request.method==='GET'&&url.pathname==='/health')return s.fetch('https://central.internal/health');if(request.method==='GET'&&url.pathname==='/cache-snapshot')return s.fetch('https://central.internal/cache-snapshot');if(request.method==='GET'&&url.pathname==='/fixture-odds-cache'){const u=new URL('https://central.internal/fixture-odds-cache');u.search=url.search;return s.fetch(u)}if(request.method==='POST'&&url.pathname==='/scheduler-tick'){if(!authorizedTick(request,env))return json({ok:false,version:VERSION,error:'FORBIDDEN'},403);return s.fetch('https://central.internal/scheduler-tick',{method:'POST'})}return json({ok:false,version:VERSION,error:'NOT_FOUND'},404)},
  async scheduled(_controller,env,ctx){ctx.waitUntil(stub(env).fetch('https://central.internal/scheduler-tick',{method:'POST'}))}
};
