import test from 'node:test';
import assert from 'node:assert/strict';
import {CAR31_DEFAULT_CONFIG,CAR31_SOURCE_MODE,ENGINE3_BASE_DEFAULTS,configSummary,normalizeCar31Config,validateCar31Config} from '../src/config.js';
test('CAR 3.1 keeps Engine 3 core defaults as baseline',()=>{for(const key of ['side','minuteMin','minuteMax','oddsMin','ahMin','momentumMin','attackEvidenceEnabled','goalGapLimited','maxGoalGap','confirmationRounds'])assert.equal(CAR31_DEFAULT_CONFIG[key],ENGINE3_BASE_DEFAULTS[key]);});
test('normalizer supports expanded OU options',()=>{const c=normalizeCar31Config({market:'ou',ouDirection:'under',ouLine:'3.25',sourceRefreshSeconds:5,matchConfidenceMin:101});assert.equal(c.market,'OU');assert.equal(c.ouDirection,'UNDER');assert.equal(c.ouLine,3.25);assert.equal(c.sourceRefreshSeconds,10);assert.equal(c.matchConfidenceMin,100);});
test('NOMADTIPS3-only branding pins API and backup paths off',()=>{assert.equal(CAR31_SOURCE_MODE.locked,true);const c=normalizeCar31Config({sourcePrimary:'API_FOOTBALL',sourceFallback:'API_FOOTBALL',sourceBackup:'ALERTS_BET',apiVerifyPolicy:'ALWAYS',dataConflictPolicy:'USE_API'});assert.equal(c.sourcePrimary,'NOMADTIPS3');assert.equal(c.sourceFallback,'OFF');assert.equal(c.sourceBackup,'OFF');assert.equal(c.apiVerifyPolicy,'OFF');assert.equal(c.dataConflictPolicy,'PASS');});
test('strict evidence rejects impossible requirement',()=>{const r=validateCar31Config({attackEvidenceEnabled:true,attackEvidenceDangerousAttacksEnabled:true,attackEvidenceShotsEnabled:false,attackEvidenceShotsOnTargetEnabled:false,attackEvidenceCornersEnabled:false,attackEvidenceRequirement:'3'});assert.equal(r.ok,false);assert.match(r.errors.join(' '),/เปิดอยู่เพียง 1/);});
test('strict evidence rejects all sub-rules off',()=>{const r=validateCar31Config({attackEvidenceEnabled:true,attackEvidenceDangerousAttacksEnabled:false,attackEvidenceShotsEnabled:false,attackEvidenceShotsOnTargetEnabled:false,attackEvidenceCornersEnabled:false});assert.equal(r.ok,false);assert.match(r.errors.join(' '),/ไม่มี Evidence/);});
test('summary exposes core runtime choices',()=>{const s=configSummary({side:'BOTH',minuteMin:55,minuteMax:88,market:'AH',momentumMin:67});assert.match(s,/BOTH/);assert.match(s,/55-88/);assert.match(s,/AH/);assert.match(s,/67%/);});
